# -*- coding: utf-8 -*-
# batch10.py - explanations for smle2026/data/slices/batch10.json

TOPICS = {
    1022: "Pediatrics",
    1024: "Respiratory Medicine",
    1025: "Medical Ethics & Communication",
    1026: "Endocrinology",
    1027: "Rheumatology",
    1028: "Pediatrics",
    1029: "Medical Ethics & Communication",
    1030: "Cardiology",
    1031: "Medical Ethics & Communication",
    1032: "Respiratory Medicine",
    1033: "Nephrology",
    1034: "Respiratory Medicine",
    1035: "Respiratory Medicine",
    1036: "Endocrinology",
    1037: "Nephrology",
    1038: "Medical Ethics & Communication",
    1039: "General Surgery",
    1040: "Medical Ethics & Communication",
    1041: "Biostatistics & Research Methods",
    1042: "Obstetrics & Gynecology",
    1043: "Obstetrics & Gynecology",
    1044: "Obstetrics & Gynecology",
    1045: "General Surgery",
    1046: "Oncology",
    1047: "Cardiology",
    1048: "Medical Ethics & Communication",
    1049: "Clinical Pharmacology & Toxicology",
    1050: "Pediatrics",
    1051: "Nephrology",
    1052: "Obstetrics & Gynecology",
    1053: "General Surgery",
    1054: "Rheumatology",
    1055: "Endocrinology",
    1056: "Obstetrics & Gynecology",
    1057: "Urology",
    1058: "Cardiology",
    1059: "Oncology",
    1060: "Preventive & Community Medicine",
    1061: "Preventive & Community Medicine",
    1062: "General Surgery",
    1063: "Cardiology",
    1064: "Obstetrics & Gynecology",
    1065: "Obstetrics & Gynecology",
    1066: "Medical Ethics & Communication",
    1067: "Emergency & Critical Care",
    1068: "Preventive & Community Medicine",
    1069: "Dermatology",
    1070: "Nephrology",
    1074: "Respiratory Medicine",
    1077: "Cardiology",
    1078: "Hematology",
    1079: "Obstetrics & Gynecology",
    1087: "Preventive & Community Medicine",
    1088: "Obstetrics & Gynecology",
    1089: "Preventive & Community Medicine",
    1090: "Preventive & Community Medicine",
    1092: "Gastroenterology",
    1093: "Emergency & Critical Care",
    1094: "Medical Ethics & Communication",
    1095: "Gastroenterology",
    1096: "Obstetrics & Gynecology",
    1097: "Preventive & Community Medicine",
    1098: "Rheumatology",
    1099: "Obstetrics & Gynecology",
    1100: "Obstetrics & Gynecology",
    1101: "Respiratory Medicine",
    1102: "Preventive & Community Medicine",
    1103: "Respiratory Medicine",
    1104: "Gastroenterology",
    1105: "Obstetrics & Gynecology",
    1106: "Medical Ethics & Communication",
    1107: "Obstetrics & Gynecology",
    1108: "Obstetrics & Gynecology",
    1109: "ENT",
    1110: "Respiratory Medicine",
    1111: "Obstetrics & Gynecology",
    1112: "Obstetrics & Gynecology",
    1113: "Obstetrics & Gynecology",
    1114: "Pediatrics",
    1115: "Rheumatology",
    1116: "Hematology",
    1117: "Emergency & Critical Care",
    1119: "Preventive & Community Medicine",
    1120: "Preventive & Community Medicine",
    1121: "Cardiology",
    1122: "Dermatology",
    1123: "Cardiology",
    1124: "Oncology",
    1125: "Cardiology",
    1126: "Cardiology",
    1127: "Neurology",
    1128: "Rheumatology",
    1129: "Cardiology",
    1130: "Medical Ethics & Communication",
    1132: "Ophthalmology",
    1134: "Obstetrics & Gynecology",
    1136: "Preventive & Community Medicine",
    1137: "Cardiology",
    1138: "Obstetrics & Gynecology",
    1139: "Gastroenterology",
}

EXPLANATIONS = {
1022: {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل خديج من أم عندها <bdi>gestational diabetes</bdi> وجاء بعد الولادة بـ<bdi>grunting</bdi> و<bdi>respiratory distress</bdi>. السؤال يبي الخطوة العملية الأولى بإدارة الحالة قبل تأكيد التشخيص الدقيق.",
    "clues": [
        ("Newborn preterm baby", "خداج يزيد خطر عدم نضج الرئة وضعف إنتاج <bdi>surfactant</bdi>"),
        ("gestational diabetes", "يرفع خطر تأخر نضج الرئة الجنينية وأمراض الجهاز التنفسي عند الولادة"),
        ("grunting and respiratory distress", "علامات ضيق تنفسي عند المولود تحتاج تدخل فوري"),
    ],
    "why_correct": [
        "أي مولود بضيق تنفسي وتأزم يحتاج أول شيء دعم الـ<bdi>oxygen</bdi> ومراقبة قريبة لحالته التنفسية والقلبية قبل أي فحص تشخيصي آخر.",
        "الأشعة والفحوصات مثل <bdi>chest x ray</bdi> أو <bdi>blood glucose</bdi> تفيد بالتشخيص لكنها لا تغني عن ضمان الأكسجين والاستقرار أولًا.",
        "إعطاء سوائل وريدية مباشرة بدون تقييم السبب قد يكون غير مناسب كخطوة أولى بدون دليل على نقص حجم واضح.",
    ],
    "when_changes": [
        "لو كان المولود مستقر وبس عنده شك بنقص سكر الدم، يصير فحص <bdi>blood glucose</bdi> هو الأولوية المباشرة.",
        "لو استمر الضيق التنفسي رغم الأكسجين وظهرت علامات فشل تنفسي، يصير التهوية الآلية هي الخطوة التالية.",
    ],
    "rule": "أي مولود بضيق تنفسي، دعم الـ<bdi>oxygen</bdi> والمراقبة القريبة هي الخطوة الأولى قبل باقي الفحوصات التشخيصية.",
    "comparison": None,
    "guideline_note": None,
},
1024: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "طفل عنده <bdi>bronchial asthma</bdi> متحكم فيه بالبخاخات، والأم قلقانة على مستقبل المرض بالبلوغ. السؤال عن أفضل تشخيص مستقبلي (<bdi>prognosis</bdi>) معروف بالدراسات الطبية.",
    "clues": [
        ("5-year-old child", "عمر صغير، أغلب حالات الربو بهالعمر مرتبطة بـ<bdi>viral wheeze</bdi> اللي يتحسن مع الكبر"),
        ("under control with inhalers", "استجابة جيدة للعلاج تدعم احتمالية التحسن مستقبلًا"),
    ],
    "why_correct": [
        "أغلب الأطفال اللي يبدأ الربو عندهم بعمر صغير يتحسنون تدريجيًا، وكثير منهم يتجاوز المرض تمامًا أو تقل شدته مع البلوغ.",
        "هذا هو السبب العلمي المعروف اللي يفسر ليش أهم نصيحة للأم هي التفاؤل الحذر بتحسن الحالة مستقبلًا مع استمرار المتابعة.",
        "القول بأن كل الأطفال يبقون ربويين بالبلوغ أو إنه لا يوجد علاقة بين ربو الطفولة والبلوغ غير دقيق علميًا.",
    ],
    "when_changes": [
        "لو كان الطفل عنده ربو شديد مستمر مع تحسس شديد (<bdi>atopy</bdi>) متعدد، يرتفع خطر استمرار المرض للبلوغ.",
        "لو بدأ الربو بعمر متأخر مع تاريخ عائلي قوي للربو التحسسي، تقل احتمالية التحسن الكامل.",
    ],
    "rule": "أغلب حالات الربو اللي تبدأ بالطفولة تتحسن أو تختفي مع البلوغ، خصوصًا لو كانت متحكم فيها جيدًا.",
    "comparison": None,
    "guideline_note": None,
},
1025: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "طبيب يبي ينشر صور قبل وبعد لمريض تحت العلاج على <bdi>TikTok</bdi>. السؤال يختبر مبدأ أساسي بأخلاقيات الطب: أي استخدام لصور أو بيانات المريض يحتاج إذنه الصريح.",
    "clues": [
        ("teenager with acne", "مريض قاصر، الصور تتعلق بحالته الصحية والجسدية"),
        ("post before-and-after photos on TikTok", "نشر علني لمحتوى طبي شخصي، يحتاج موافقة واضحة"),
    ],
    "why_correct": [
        "أي نشر لصور <bdi>patient</bdi> حتى لو لغرض تعليمي يحتاج أخذ <bdi>consent</bdi> صريح من المريض (وولي أمره لأنه قاصر) قبل النشر.",
        "الصور الطبية تعتبر معلومة خاصة محمية، والنشر بدون إذن يخالف مبدأ <bdi>privacy</bdi> و<bdi>autonomy</bdi>.",
        "الفائدة التعليمية المحتملة لا تبرر تجاوز حق المريض بالموافقة أو عدم تمييزه الشخصي بالصورة.",
    ],
    "when_changes": [
        "لو كانت الصور لغرض ملف المريض الطبي الداخلي فقط بدون نشر خارجي، يكفي توثيق داخلي عادي.",
        "لو رفض المريض أو وليه النشر بعد طلب الإذن، يجب الالتزام بالرفض ومنع أي نشر.",
    ],
    "rule": "نشر أي صورة أو معلومة تخص المريض على وسائل التواصل يحتاج أخذ <bdi>consent</bdi> صريح منه أولًا.",
    "comparison": None,
    "guideline_note": None,
},
1026: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "مولود بصوديوم منخفض، بوتاسيوم مرتفع جدًا، بيكربونات منخفضة (<bdi>metabolic acidosis</bdi>)، وسكر منخفض. هذا نمط كلاسيكي لـ<bdi>congenital adrenal hyperplasia</bdi> بشكل <bdi>salt-wasting</bdi>.",
    "clues": [
        ("Sodium 127", "<bdi>hyponatremia</bdi> واضحة، من فقد الملح الكلوي"),
        ("Potassium 6.8", "<bdi>hyperkalemia</bdi> شديدة، نتيجة نقص <bdi>aldosterone</bdi>"),
        ("Bicarbonate 15", "<bdi>metabolic acidosis</bdi> يدعم خلل بمحور الكظر"),
    ],
    "why_correct": [
        "هذا النمط (صوديوم منخفض، بوتاسيوم مرتفع، حموضة استقلابية، سكر منخفض) كلاسيكي لـ<bdi>21-hydroxylase deficiency</bdi> اللي يسبب <bdi>salt-wasting CAH</bdi>.",
        "هذا المرض ينتقل بصفة <bdi>autosomal recessive</bdi>، يعني الطفل يحتاج نسختين من الجين المعطوب من كل والد.",
        "باقي أنماط الوراثة (<bdi>X-linked</bdi>، <bdi>autosomal dominant</bdi>، <bdi>multifactorial</bdi>) لا تتوافق مع الفهم الجيني المعروف لهذا المرض.",
    ],
    "when_changes": [
        "لو كان المرض من نوع وراثي مرتبط بكروموسوم X مثل بعض أمراض الاستقلاب الأخرى، يختلف نمط الوراثة تمامًا.",
        "لو ظهرت الأعراض فقط عند الذكور بشكل متكرر عبر الأجيال من جهة الأم، يرجح نمط <bdi>X-linked</bdi>.",
    ],
    "rule": "<bdi>Salt-wasting congenital adrenal hyperplasia</bdi> سببها نقص إنزيم <bdi>21-hydroxylase</bdi> وتنتقل بصفة <bdi>autosomal recessive</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1027: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "مريضة روماتويد على <bdi>methotrexate</bdi> وهي بحالة <bdi>remission</bdi>، وفجأة طلعت تحاليل الكبد مرتفعة جدًا بعد ما كانت طبيعية. السؤال عن الخطوة الصحيحة تجاه سمية الكبد الدوائية.",
    "clues": [
        ("maintained on methotrexate 15 mg weekly", "دواء معروف بسميته الكبدية المحتملة"),
        ("Aspartate aminotransferase 300", "ارتفاع شديد جدًا بإنزيمات الكبد مقارنة بالطبيعي"),
        ("Albumin 30", "انخفاض الألبومين يدعم تأثر وظيفة الكبد"),
    ],
    "why_correct": [
        "ارتفاع إنزيمات الكبد بشكل كبير (أكثر من 3 أضعاف الطبيعي) عند مريضة على <bdi>methotrexate</bdi> يستدعي إيقاف الدواء فورًا كخطوة أولى لحماية الكبد.",
        "متابعة الدواء مع ارتفاع واضح بهذا الشكل خطر جدًا ويزيد احتمال تلف كبدي دائم (<bdi>fibrosis</bdi> أو <bdi>cirrhosis</bdi>).",
        "فحوصات زي <bdi>ultrasound</bdi> أو <bdi>biopsy</bdi> قد تفيد لاحقًا لكنها ليست الخطوة الأولى العاجلة مقارنة بإيقاف السبب المباشر المحتمل.",
    ],
    "when_changes": [
        "لو كان الارتفاع خفيف ومؤقت فقط (أقل من ضعف الطبيعي)، يكفي تقليل الجرعة والمتابعة القريبة دون إيقاف تام.",
        "لو استمر الارتفاع رغم إيقاف الدواء، يصير عمل <bdi>liver biopsy</bdi> أو <bdi>ultrasound</bdi> لازم لمعرفة سبب آخر.",
    ],
    "rule": "ارتفاع واضح بإنزيمات الكبد عند مريض على <bdi>methotrexate</bdi> يستدعي إيقاف الدواء فورًا كخطوة أولى.",
    "comparison": None,
    "guideline_note": None,
},
1028: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "طفلة ما أخذت أي تطعيمات، انجرحت بقضيب معدني ملوث وصار عندها تشنجات عضلية واختلاج. هذا نمط كلاسيكي لـ<bdi>tetanus</bdi>، والسؤال عن التطعيم المناسب لها.",
    "clues": [
        ("never received any vaccinations", "لا يوجد أي مناعة سابقة ضد <bdi>tetanus</bdi>"),
        ("injured by a contaminated metal rod", "جرح ملوث، بيئة مثالية لبكتيريا <bdi>Clostridium tetani</bdi>"),
        ("muscle spasms and convulsions", "علامات كلاسيكية لمرض <bdi>tetanus</bdi>"),
    ],
    "why_correct": [
        "التطعيم <bdi>DTaP</bdi> يحتوي على مكون <bdi>tetanus toxoid</bdi> ضمن ثلاثي اللقاح (الدفتيريا والسعال الديكي والكزاز) وهو المناسب لهالعمر.",
        "الطفلة غير محصنة أساسًا وعندها عرض سريري موحي بالكزاز، فتحتاج لقاح يحمي من هذا المرض تحديدًا ضمن برنامج التحصين الكامل.",
        "باقي اللقاحات (<bdi>OPV</bdi>، <bdi>IPV</bdi>، <bdi>Hib</bdi>) مهمة للتحصين الروتيني لكنها لا تتعلق بالعرض السريري الحالي.",
    ],
    "when_changes": [
        "لو كانت الطفلة مكتملة التحصين الأساسي وجاها جرح مماثل، العلاج يركز على الغرز المناعي (<bdi>immunoglobulin</bdi>) لو الجرح شديد التلوث.",
        "لو كانت الأعراض تنفسية بدل العصبية العضلية، يتوجه الشك لمرض آخر غير الكزاز.",
    ],
    "rule": "طفل غير محصن مع جرح ملوث وتشنجات عضلية يوجه لتشخيص <bdi>tetanus</bdi>، والحماية منه تكون بلقاح يحتوي <bdi>tetanus toxoid</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1029: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "طبيب شرح للمريض كل خطوات العملية والمضاعفات المحتملة، والسؤال عن أفضل طريقة لتوثيق أن المريض فهم وموافق فعليًا (<bdi>informed consent</bdi> سليم).",
    "clues": [
        ("explained all the steps of the procedure", "شرح تفصيلي جزء أساسي من <bdi>informed consent</bdi> الصحيح"),
        ("possible complications", "ذكر المخاطر المحتملة شرط أساسي لصحة الموافقة"),
        ("convert to open surgery", "تفصيل كامل حتى للسيناريوهات الاحتياطية المحتملة"),
    ],
    "why_correct": [
        "أفضل توثيق لضمان <bdi>informed consent</bdi> حقيقي هو كتابة ملاحظات مفصّلة توضح بالضبط وش فهمه المريض من الشرح، مو فقط إنه وقّع.",
        "التوثيق المفصّل يحمي الطبيب والمريض قانونيًا ويؤكد إن الموافقة كانت مبنية على فهم حقيقي للمخاطر والخيارات.",
        "أخذ موافقة شفهية من العائلة أو كتابة ملاحظات مختصرة لا تعكس مستوى الفهم الفعلي للمريض نفسه.",
    ],
    "when_changes": [
        "لو كان المريض فاقد الأهلية لاتخاذ القرار، يصير التوثيق مع وصي قانوني هو المطلوب بدل المريض نفسه.",
        "لو كانت العملية طارئة تهدد الحياة بدون وقت كافٍ للشرح، تطبق مبادئ <bdi>emergency consent</bdi> بدل التوثيق التفصيلي المعتاد.",
    ],
    "rule": "التوثيق الصحيح لـ<bdi>informed consent</bdi> يشمل كتابة تفاصيل واضحة عن مدى فهم المريض نفسه للإجراء ومخاطره.",
    "comparison": None,
    "guideline_note": None,
},
1030: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "طفل صغير عنده ضيق نفس وخفقان مع المجهود بعد عدوى تنفسية علوية قبل 3 أيام، والفحص أظهر <bdi>gallop rhythm</bdi>. السؤال عن العلامة اللي توجه فعليًا للتشخيص (غالبًا <bdi>myocarditis</bdi>) وسط علامات غير نوعية.",
    "clues": [
        ("history reveales URTI 3 days ago", "عدوى فيروسية سابقة، عامل خطر معروف لـ<bdi>myocarditis</bdi>"),
        ("gallop rythum", "علامة قلبية مباشرة توجه لخلل بوظيفة القلب نفسه"),
        ("high HR", "علامة غير نوعية ممكن تحدث بأسباب كثيرة"),
    ],
    "why_correct": [
        "<bdi>Gallop rhythm</bdi> علامة سريرية مباشرة ونوعية تدل على خلل بوظيفة عضلة القلب أو زيادة حجم داخل القلب، وهذا أقوى دليل يوجه للتشخيص القلبي.",
        "<bdi>Tachycardia</bdi> و<bdi>tachypnea</bdi> علامات غير نوعية ممكن تحدث بأي عدوى أو حمى بدون مشكلة قلبية فعلية.",
        "التاريخ المرضي مهم للسياق لكنه لوحده لا يثبت وجود مشكلة قلبية، بعكس العلامة الفيزيائية المباشرة.",
    ],
    "when_changes": [
        "لو كان الفحص القلبي طبيعي تمامًا بدون <bdi>gallop</bdi>، يقل الشك بوجود مشكلة قلبية فعلية ويتجه التفكير لسبب تنفسي بسيط.",
        "لو ظهرت وذمة بالأطراف أو كبد متضخم مع <bdi>gallop</bdi>، يتأكد اتجاه السبب لفشل قلبي بدل عدوى تنفسية بسيطة.",
    ],
    "rule": "العلامات الفيزيائية المباشرة والنوعية مثل <bdi>gallop rhythm</bdi> أقوى دليل تشخيصي من العلامات العامة غير النوعية مثل تسرع القلب والتنفس.",
    "comparison": None,
    "guideline_note": None,
},
1031: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "باحث يسوي دراسة على فحص فرز جديد، والسؤال عن حق المشارك الأساسي بالبحث الطبي حسب مبادئ أخلاقيات البحث (<bdi>research ethics</bdi>).",
    "clues": [
        ("Researcher wants to do a research", "سياق بحث علمي يخضع لمبادئ الموافقة المستنيرة والحقوق الأخلاقية"),
        ("What the participant right", "السؤال يركز على حق أساسي للمشارك بالدراسة"),
    ],
    "why_correct": [
        "من أهم حقوق أي مشارك بأي بحث طبي هو حقه بالانسحاب من الدراسة في أي وقت بدون أي تأثير على رعايته الطبية.",
        "هذا الحق جزء أساسي من مبادئ <bdi>informed consent</bdi> بالبحث العلمي، ويجب توضيحه للمشارك قبل بداية الدراسة.",
        "تبليغ المشاركين بنتائج فحصهم الفردي (موجب أو سالب) له اعتبارات أخلاقية خاصة وليس حق مطلق بكل أنواع الدراسات البحثية.",
    ],
    "when_changes": [
        "لو كان السؤال يركز على حق معرفة النتائج الفردية الموجبة تحديدًا، يختلف الجواب حسب نوع الدراسة وإمكانية التصرف بالنتيجة.",
        "لو كانت الدراسة فحص فرز بنتائج قابلة للتصرف (مثل تشخيص قابل للعلاج)، يصير تبليغ الحالات الموجبة واجب أخلاقي أيضًا.",
    ],
    "rule": "حق الانسحاب من الدراسة بأي وقت حق أساسي ثابت لكل مشارك بأي بحث طبي بدون استثناء.",
    "comparison": None,
    "guideline_note": None,
},
1032: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "امرأة عندها ربو بدون نوبات شديدة آخر 3 أشهر، لكن عندها كحة وصفير 2-3 مرات أسبوعيًا. هذا نمط <bdi>mild persistent asthma</bdi> يحتاج علاج مثبّت (<bdi>controller</bdi>) مو فقط علاج عند الحاجة.",
    "clues": [
        ("not had a severe attack for the last 3 months", "عدم وجود نوبات شديدة لا يعني التحكم الكامل بالمرض"),
        ("cough and wheezing 2-3 times each week", "تكرار الأعراض يوضع بتصنيف <bdi>mild persistent</bdi> يحتاج علاج يومي"),
    ],
    "why_correct": [
        "الأعراض المتكررة 2-3 مرات أسبوعيًا تضع المريضة بتصنيف <bdi>mild persistent asthma</bdi>، والعلاج الأساسي الموصى به هو <bdi>inhaled corticosteroid</bdi> يومي.",
        "<bdi>ICS</bdi> يقلل الالتهاب المزمن بالمجاري الهوائية ويمنع تطور الأعراض لنوبات أشد، بعكس أدوية الإنقاذ السريع.",
        "<bdi>Salbutamol</bdi> و<bdi>ipratropium</bdi> أدوية إنقاذ سريعة للأعراض الحادة فقط ولا تعالج الالتهاب المزمن تحت السطح.",
    ],
    "when_changes": [
        "لو كانت الأعراض أقل من مرتين بالأسبوع بدون أي تأثير على النشاط اليومي، يكفي علاج الإنقاذ عند الحاجة فقط دون مثبّت.",
        "لو استمرت الأعراض أو زادت رغم <bdi>ICS</bdi> بجرعة منخفضة، يضاف <bdi>LABA</bdi> مثل <bdi>salmeterol</bdi> كخطوة تالية.",
    ],
    "rule": "ربو بأعراض متكررة أكثر من مرتين بالأسبوع يحتاج <bdi>inhaled corticosteroid</bdi> يومي كعلاج أساسي مثبّت للالتهاب.",
    "comparison": None,
    "guideline_note": None,
},
1033: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "امرأة بعد 6 أيام من عملية جراحية عندها غثيان وتقيؤ وألم عضلي، مع احتباس براز وانتفاخ بطن، والتحاليل أظهرت نقص بوتاسيوم. السؤال عن الخطوة العاجلة الأهم قبل تحديد سبب النقص.",
    "clues": [
        ("6 days postoperative", "فترة ما بعد العملية فيها فقد سوائل وإلكترولايت محتمل من القيء وصعوبة الأكل"),
        ("unable to pass stool, with abdominal distension", "علامة <bdi>postoperative ileus</bdi> المصاحبة لاضطراب الإلكترولايت"),
        ("hypokalemia", "خطر مباشر على كهربية القلب يحتاج تقييم عاجل"),
    ],
    "why_correct": [
        "نقص البوتاسيوم يهدد بحدوث اضطراب نظم خطير بالقلب، فأول خطوة عملية وعاجلة هي عمل <bdi>ECG</bdi> لتقييم أي تأثير مباشر على القلب قبل أي فحص آخر.",
        "فحوصات زي <bdi>urine potassium</bdi> أو <bdi>stool potassium</bdi> تفيد لتحديد سبب النقص لاحقًا لكنها ليست الأولوية العاجلة الأولى.",
        "تقييم خطورة الحالة على القلب يسبق البحث عن السبب الدقيق للنقص عندما يكون المستوى منخفض بشكل قد يكون خطير.",
    ],
    "when_changes": [
        "لو كان مستوى البوتاسيوم منخفض بشكل خفيف فقط بدون أي أعراض قلبية، يصير تحديد السبب (<bdi>urine potassium</bdi>) هو الخطوة المناسبة.",
        "لو ظهر بالـ<bdi>ECG</bdi> تغيرات خطيرة، تصير المعالجة الفورية بالبوتاسيوم الوريدي أولوية قبل أي شيء آخر.",
    ],
    "rule": "أي نقص بوتاسيوم عند مريض بعد عملية يستدعي تقييم تأثيره على القلب بـ<bdi>ECG</bdi> كخطوة عاجلة أولى.",
    "comparison": None,
    "guideline_note": None,
},
1034: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "طفل عنده ربو وعدوى تنفسية متكررة، والأم تقول إنها تستخدم البخاخ مع <bdi>spacer</bdi> حسب الوصفة. السؤال عن أهم نصيحة تعليمية، وغالبًا المشكلة تكون بطريقة الاستخدام الفعلية مو بالالتزام نفسه.",
    "clues": [
        ("uses a metered-dose inhaler with a spacer as prescribed", "استخدام البخاخ موجود لكن ما يضمن صحة الطريقة الفعلية"),
        ("mild wheeze, sore throat, and erythema", "أعراض مستمرة تدل إن التحكم بالمرض غير كافٍ"),
    ],
    "why_correct": [
        "استمرار الأعراض رغم استخدام البخاخ يوجه لمراجعة طريقة الاستخدام الفعلية والتأكد من صحتها عمليًا مو فقط الاعتماد على كلام الأم.",
        "التأكد من طريقة استخدام <bdi>inhaler</bdi> و<bdi>spacer</bdi> خطوة أساسية وأولى بأي مريض ربو تستمر أعراضه قبل تغيير العلاج.",
        "إيقاف البخاخ أثناء البرد أو تجنب النشاط البدني كليًا نصائح غير صحيحة وتزيد خطر تفاقم الربو.",
    ],
    "when_changes": [
        "لو تأكدنا إن طريقة الاستخدام صحيحة تمامًا واستمرت الأعراض، يصير التفكير بزيادة جرعة العلاج المثبّت هو الخطوة التالية.",
        "لو كان الطفل يرفض استخدام <bdi>spacer</bdi> أساسًا، يصير التركيز على تدريبه وتشجيعه على الالتزام بالطريقة الصحيحة.",
    ],
    "rule": "عند استمرار أعراض الربو رغم العلاج، أول خطوة تعليمية هي التأكد من صحة طريقة استخدام البخاخ عمليًا.",
    "comparison": None,
    "guideline_note": None,
},
1035: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "طفل صغير عنده صفير يزيد مع الرضاعة والبكاء، والفحص أظهر صفير زفيري ثنائي أحادي النغمة (<bdi>monophasic</bdi>). هذا النمط يوجه لمشكلة بالمجرى الهوائي الكبير المرنة مثل <bdi>tracheomalacia</bdi> أو <bdi>laryngomalacia</bdi>.",
    "clues": [
        ("worsens during feeding and crying", "زيادة الصفير مع زيادة تدفق الهواء السريع تدعم مشكلة مرونة بالمجرى الهوائي"),
        ("monophasic bilateral expiratory wheeze", "صوت موحد النغمة يختلف عن صفير الربو المتعدد النغمات المرتبط بالمجاري الصغيرة"),
    ],
    "why_correct": [
        "هذا النمط من الصفير يوحي بمشكلة مرونة بالمجرى الهوائي الكبير (مثل <bdi>tracheomalacia</bdi>)، وأغلب هالحالات تتحسن تلقائيًا مع نمو الطفل.",
        "طمأنة الوالدين مع المتابعة هي الأنسب لأن الحالة حميدة بالغالب وتتحسن مع تقدم العمر بدون تدخل دوائي أو جراحي.",
        "موسعات الشعب أو الستيرويدات الجهازية تفيد بالربو لكنها لا تعالج السبب الميكانيكي بهذا النوع من الصفير.",
    ],
    "when_changes": [
        "لو كان هناك ضيق تنفسي شديد يهدد الحياة أو فشل بالنمو، يصير التصوير وتقييم المجرى الهوائي بالمنظار ضروري.",
        "لو كان الصفير متعدد النغمات ومرتبط بعدوى تنفسية فقط، يتجه التشخيص أكثر لربو الأطفال الفيروسي.",
    ],
    "rule": "صفير زفيري أحادي النغمة يزيد مع البكاء والرضاعة يوجه لمشكلة مرونة بالمجرى الهوائي، وأغلبها يتحسن تلقائيًا.",
    "comparison": None,
    "guideline_note": None,
},
    # EXPL_INSERT
}

WHY_WRONG = {
    # WW_INSERT
}

HIGHLIGHT_TERMS = {
    # HL_INSERT
}
