# -*- coding: utf-8 -*-
# Batch 07: questions 697-801 (100 questions, gaps present).

TOPICS = {
    697: "Gastroenterology",
    698: "Oncology",
    699: "Nephrology",
    700: "Respiratory Medicine",
    701: "Respiratory Medicine",
    702: "Pediatrics",
    703: "Pediatrics",
    704: "Hematology",
    705: "Pediatrics",
    706: "Biostatistics & Research Methods",
    707: "Pediatrics",
    708: "Neurology",
    709: "Gastroenterology",
    710: "Psychiatry",
    711: "Psychiatry",
    712: "General Surgery",
    713: "Neurology",
    714: "Pediatrics",
    715: "Rheumatology",
    716: "Geriatric Medicine",
    717: "Obstetrics & Gynecology",
    718: "Emergency & Critical Care",
    719: "Emergency & Critical Care",
    720: "Emergency & Critical Care",
    721: "Psychiatry",
    722: "Psychiatry",
    724: "Obstetrics & Gynecology",
    725: "ENT",
    726: "Cardiology",
    727: "Obstetrics & Gynecology",
    728: "Preventive & Community Medicine",
    729: "Biostatistics & Research Methods",
    730: "Biostatistics & Research Methods",
    731: "Biostatistics & Research Methods",
    732: "Biostatistics & Research Methods",
    733: "Infectious Diseases",
    734: "Pediatrics",
    735: "Pediatrics",
    736: "ENT",
    737: "Pediatrics",
    738: "Pediatrics",
    739: "Pediatrics",
    740: "Pediatrics",
    741: "Emergency & Critical Care",
    742: "Emergency & Critical Care",
    744: "Gastroenterology",
    745: "Medical Ethics & Communication",
    746: "Cardiology",
    747: "Respiratory Medicine",
    749: "Pediatrics",
    750: "Pediatrics",
    751: "Obstetrics & Gynecology",
    752: "Obstetrics & Gynecology",
    753: "Obstetrics & Gynecology",
    754: "Obstetrics & Gynecology",
    755: "Obstetrics & Gynecology",
    756: "Obstetrics & Gynecology",
    757: "Obstetrics & Gynecology",
    758: "Emergency & Critical Care",
    759: "Medical Ethics & Communication",
    760: "Biostatistics & Research Methods",
    761: "Gastroenterology",
    762: "Oncology",
    763: "Obstetrics & Gynecology",
    764: "Rheumatology",
    766: "Pediatrics",
    767: "Pediatrics",
    768: "General Surgery",
    769: "Dermatology",
    770: "Gastroenterology",
    771: "Preventive & Community Medicine",
    772: "Obstetrics & Gynecology",
    773: "Pediatrics",
    774: "Pediatrics",
    775: "Hematology",
    776: "Hematology",
    777: "Hematology",
    778: "Preventive & Community Medicine",
    779: "Pediatrics",
    780: "Gastroenterology",
    781: "Gastroenterology",
    782: "Infectious Diseases",
    783: "Obstetrics & Gynecology",
    784: "Medical Ethics & Communication",
    785: "Gastroenterology",
    786: "Hematology",
    787: "Pediatrics",
    788: "Gastroenterology",
    789: "Preventive & Community Medicine",
    790: "Infectious Diseases",
    791: "Cardiology",
    792: "Obstetrics & Gynecology",
    793: "Cardiology",
    794: "Emergency & Critical Care",
    795: "Infectious Diseases",
    796: "Cardiology",
    797: "Obstetrics & Gynecology",
    798: "Rheumatology",
    800: "Pediatrics",
    801: "Pediatrics",
}

EXPLANATIONS = {}
WHY_WRONG = {}
HIGHLIGHT_TERMS = {}
