# -*- coding: utf-8 -*-
# Batch 09 — questions 914-1021 (100 questions, gaps per source).

TOPICS = {
    914: "Respiratory Medicine",
    915: "Cardiology",
    916: "Pediatrics",
    917: "Obstetrics & Gynecology",
    918: "Obstetrics & Gynecology",
    919: "Gastroenterology",
    920: "Hematology",
    921: "Gastroenterology",
    922: "Pediatrics",
    923: "General Surgery",
    924: "Obstetrics & Gynecology",
    925: "Rheumatology",
    926: "Cardiology",
    927: "Cardiology",
    928: "Clinical Pharmacology & Toxicology",
    929: "Medical Ethics & Communication",
    930: "Pediatrics",
    931: "Infectious Diseases",
    932: "Pediatrics",
    933: "Pediatrics",
    934: "Medical Ethics & Communication",
    936: "Hematology",
    938: "Medical Ethics & Communication",
    939: "Hematology",
    940: "Cardiology",
    942: "Pediatrics",
    943: "Obstetrics & Gynecology",
    944: "Neurology",
    945: "Respiratory Medicine",
    946: "Rheumatology",
    947: "Infectious Diseases",
    948: "Psychiatry",
    949: "Nephrology",
    950: "Nephrology",
    951: "Respiratory Medicine",
    952: "Nephrology",
    953: "Oncology",
    954: "Emergency & Critical Care",
    955: "Clinical Pharmacology & Toxicology",
    956: "Infectious Diseases",
    957: "Gastroenterology",
    958: "Oncology",
    959: "Oncology",
    960: "Neurology",
    961: "Obstetrics & Gynecology",
    962: "Obstetrics & Gynecology",
    963: "Obstetrics & Gynecology",
    964: "Pediatrics",
    965: "Obstetrics & Gynecology",
    966: "Emergency & Critical Care",
    967: "Emergency & Critical Care",
    968: "Hematology",
    969: "Obstetrics & Gynecology",
    970: "General Surgery",
    971: "Biostatistics & Research Methods",
    972: "Nephrology",
    973: "Oncology",
    975: "Obstetrics & Gynecology",
    976: "Ophthalmology",
    979: "ENT",
    980: "General Surgery",
    981: "Endocrinology",
    982: "Pediatrics",
    983: "Cardiology",
    984: "Pediatrics",
    985: "Gastroenterology",
    986: "General Surgery",
    987: "Pediatrics",
    988: "Biostatistics & Research Methods",
    990: "Oncology",
    992: "Medical Ethics & Communication",
    993: "Medical Ethics & Communication",
    994: "Emergency & Critical Care",
    995: "Nephrology",
    996: "Respiratory Medicine",
    997: "Nephrology",
    998: "Emergency & Critical Care",
    999: "Endocrinology",
    1000: "Medical Ethics & Communication",
    1001: "Obstetrics & Gynecology",
    1002: "Obstetrics & Gynecology",
    1003: "Obstetrics & Gynecology",
    1004: "Obstetrics & Gynecology",
    1005: "Hematology",
    1006: "Ophthalmology",
    1007: "Respiratory Medicine",
    1008: "Infectious Diseases",
    1009: "Respiratory Medicine",
    1010: "Obstetrics & Gynecology",
    1011: "Urology",
    1012: "Biostatistics & Research Methods",
    1013: "Preventive & Community Medicine",
    1014: "Medical Ethics & Communication",
    1015: "Emergency & Critical Care",
    1016: "Endocrinology",
    1017: "Medical Ethics & Communication",
    1018: "Hematology",
    1019: "Neurology",
    1020: "Pediatrics",
    1021: "Pediatrics",
}

EXPLANATIONS = {
914: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "امرأة عندها <bdi>moderate persistent asthma</bdi> (أعراض يومية تقريبًا تعيق نشاطها كل الأسبوع)، والسؤال يبي الخطوة العلاجية الصحيحة بعد الـ<bdi>SABA</bdi> وحده.",
    "clues": [
        ("daily wheezing and breathlessness... several times a week", "أعراض متكررة جدًا، درجة <bdi>moderate persistent</bdi> مو <bdi>mild</bdi>"),
        ("moderate persistent asthma", "التصنيف مذكور صراحة بالسؤال، يحدد درجة الخطوة العلاجية المطلوبة"),
    ],
    "why_correct": [
        "بتصنيف شدة الـ<bdi>asthma</bdi>، درجة <bdi>moderate persistent</bdi> تحتاج خطوة علاجية أقوى من مجرد <bdi>low-dose ICS</bdi> لوحده.",
        "الخطوة المناسبة هي إضافة <bdi>low-dose inhaled corticosteroid</bdi> مع <bdi>long-acting B2-agonist</bdi> (<bdi>LABA</bdi>) معًا، وهذا يطابق درجة التصعيد العلاجي لهالمستوى من الشدة.",
        "الـ<bdi>SABA</bdi> يبقى للأعراض الحادة فقط، والعلاج المستمر يحتاج <bdi>controller</bdi> أقوى من <bdi>ICS</bdi> وحده.",
    ],
    "when_changes": [
        "لو كانت الأعراض أخف (مرتين بالأسبوع بس)، يصير <bdi>mild persistent</bdi> والخطوة تكون <bdi>low-dose ICS</bdi> لوحده بدون <bdi>LABA</bdi>.",
        "لو فشل علاج <bdi>ICS+LABA</bdi>، تصير الخطوة التالية زيادة الجرعة لـ<bdi>medium-dose ICS+LABA</bdi>.",
    ],
    "rule": "<bdi>Moderate persistent asthma</bdi> يحتاج إضافة <bdi>low-dose ICS</bdi> مع <bdi>LABA</bdi> معًا، مو <bdi>ICS</bdi> لوحده.",
    "comparison": None,
    "guideline_note": None,
},
915: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "رجل عنده نفخة قلبية انبساطية مبكرة عند قاعدة القلب، والسؤال يبي النوع الصحيح بين الخيارات المعطاة اعتمادًا على توقيتها ومكانها.",
    "clues": [
        ("early diastolic murmur at the base", "التوقيت انبساطي مبكر والمكان قاعدة القلب، نمط نفخة ارتجاع صمام"),
        ("dyspnea on exertion", "علامة قصور قلبي مرتبط بزيادة حمل حجمي على البطين"),
    ],
    "why_correct": [
        "من الخيارات الأربعة، النفخة الانبساطية المبكرة عند القاعدة هي <bdi>aortic regurgitation</bdi> (نفخة <bdi>decrescendo</bdi> كلاسيكية).",
        "باقي الخيارات توقيتها مختلف تمامًا: <bdi>mitral stenosis</bdi> نفختها انبساطية متوسطة عند القمة مو القاعدة، و<bdi>mitral regurgitation</bdi> و<bdi>aortic stenosis</bdi> نفختهم انقباضية.",
        "زيادة شدة النفخة بالشهيق فعليًا علامة كلاسيكية للنفخات اليمينية مثل <bdi>pulmonic regurgitation</bdi>، بس بين الخيارات المعطاة ما فيه خيار يمثلها، فالأقرب توقيتًا ومكانًا يبقى <bdi>aortic regurgitation</bdi>.",
    ],
    "when_changes": [
        "لو كان فيه خيار <bdi>pulmonic regurgitation</bdi> صريح، هو الأنسب فعليًا مع علامة زيادة الشدة بالشهيق (<bdi>Carvallo's sign</bdi>).",
        "لو النفخة تقل بالشهيق وتزيد بالزفير، هذا يدعم أكثر إنها نفخة يسارية مثل <bdi>aortic regurgitation</bdi>.",
    ],
    "rule": "النفخة الانبساطية المبكرة عند قاعدة القلب نمط كلاسيكي لـ<bdi>aortic regurgitation</bdi>، وزيادتها بالشهيق تدعم أصل يميني لو كان مذكور كخيار.",
    "comparison": {
        "headers": ["النفخة", "التوقيت", "المكان المعتاد"],
        "rows": [
            ["<bdi>Aortic regurgitation</bdi>", "انبساطي مبكر", "قاعدة القلب / الحافة اليسرى"],
            ["<bdi>Mitral stenosis</bdi>", "انبساطي متوسط", "القمة"],
        ],
    },
    "guideline_note": None,
},
916: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "مولود عنده <bdi>hypertrophic cardiomyopathy</bdi>، والسؤال يبي السبب الأموي الكلاسيكي لهالحالة.",
    "clues": [
        ("Newborn with hypertrophic cardiomyopathy", "سماكة عضلة القلب بالمولود، مرتبطة كلاسيكيًا بحالة أمومية معينة"),
        ("Maternal cause", "السؤال يحدد إنه عامل خطر من جهة الأم"),
    ],
    "why_correct": [
        "<bdi>Infant of diabetic mother</bdi> هي السبب الأموي الكلاسيكي لـ<bdi>transient hypertrophic cardiomyopathy</bdi> عند المولود بسبب فرط الأنسولين الجنيني.",
        "الحالة عادة مؤقتة وتتحسن تدريجيًا بعد الولادة مع ضبط سكر الأم.",
        "<bdi>SLE</bdi> الأمومية مرتبطة بـ<bdi>congenital heart block</bdi> عند المولود مو <bdi>hypertrophic cardiomyopathy</bdi>.",
    ],
    "when_changes": [
        "لو كان المولود عنده <bdi>heart block</bdi> خلقي بدل سماكة العضلة، يصير السبب الأقوى <bdi>maternal SLE</bdi> (أضداد <bdi>anti-Ro/La</bdi>).",
    ],
    "rule": "<bdi>Diabetes mellitus</bdi> عند الأم هي السبب الكلاسيكي لـ<bdi>hypertrophic cardiomyopathy</bdi> المؤقتة عند المولود.",
    "comparison": None,
    "guideline_note": None,
},
917: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "امرأة ولدت 6 أطفال كبار الحجم (<bdi>macrosomic</bdi>)، معرضة لضعف انقباض الرحم بعد الولادة، والسؤال يبي أفضل وقاية من <bdi>PPH</bdi>.",
    "clues": [
        ("6 macrosomic babies", "تاريخ يرفع خطر <bdi>uterine atony</bdi> بسبب تمدد الرحم المتكرر وحجم الأجنة"),
        ("how to prevent PPH", "السؤال عن الوقاية الأولى مو علاج نزيف قائم"),
    ],
    "why_correct": [
        "<bdi>Oxytocin</bdi> هو الخط الأول للوقاية من <bdi>PPH</bdi> ضمن الإدارة الفعالة للمرحلة الثالثة من الولادة لكل النساء.",
        "خطر <bdi>uterine atony</bdi> هنا مرتفع بسبب تعدد الولادات والأجنة الكبار، فالوقاية الروتينية بـ<bdi>oxytocin</bdi> أهم وأضمن.",
        "باقي الأدوية (<bdi>ergonovine</bdi>، <bdi>misoprostol</bdi>، <bdi>carboprost</bdi>) تُستخدم كخطوط ثانية أو لعلاج نزيف قائم، مو كوقاية أولى روتينية.",
    ],
    "when_changes": [
        "لو كان <bdi>oxytocin</bdi> غير متوفر، يصير <bdi>misoprostol</bdi> هو البديل المقبول للوقاية.",
        "لو عندها نزيف فعلي مستمر رغم <bdi>oxytocin</bdi>، يصير التصعيد لـ<bdi>carboprost</bdi> أو <bdi>ergonovine</bdi> حسب موانع الاستعمال.",
    ],
    "rule": "<bdi>Oxytocin</bdi> هو الخط الأول دايمًا للوقاية من <bdi>PPH</bdi> بعد الولادة لكل النساء.",
    "comparison": None,
    "guideline_note": None,
},
918: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "سؤال مباشر عن أفضل دواء للوقاية من <bdi>PPH</bdi> بشكل عام، بدون عوامل خطر إضافية مذكورة.",
    "clues": [
        ("PPH", "موضوع السؤال الأساسي، وقاية مو علاج"),
        ("how to prevent it", "يبي الخط الأول الروتيني"),
    ],
    "why_correct": [
        "<bdi>Oxytocin</bdi> هو الخط الأول الموصى به عالميًا للوقاية الروتينية من <bdi>PPH</bdi> لكل النساء بعد الولادة.",
        "فعاليته وأمانه أعلى من باقي الخيارات، وهو جزء أساسي من البروتوكول القياسي للمرحلة الثالثة من الولادة.",
    ],
    "when_changes": [
        "لو <bdi>oxytocin</bdi> غير متوفر، <bdi>misoprostol</bdi> يُستخدم كبديل للوقاية.",
        "لو فيه نزيف فعلي مستمر، <bdi>carboprost</bdi> يُستخدم كعلاج تصعيدي مو وقاية أولى.",
    ],
    "rule": "<bdi>Oxytocin</bdi> دايمًا الخط الأول للوقاية من <bdi>PPH</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
919: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "مريض عنده حصوات متعددة بالمرارة وحصوة تسد الـ<bdi>CBD</bdi> بالسونار، رغم عدم ظهور يرقان سريري واضح بعد. هذا نمط انسداد صفراوي ميكانيكي.",
    "clues": [
        ("Common bile duct (CBD) is obstructed by a stone", "دليل مباشر على انسداد صفراوي خارج الكبد سببه حصوة"),
        ("no pale stools or dark urine", "اليرقان السريري لسا ما ظهر، بس الانسداد التشريحي موجود فعليًا"),
        ("Normal gallbladder wall thickness", "يستبعد التهاب المرارة الحاد (<bdi>cholecystitis</bdi>) اللي يحتاج سماكة جدار وسائل حول المرارة"),
    ],
    "why_correct": [
        "وجود حصوة تسد الـ<bdi>CBD</bdi> بالتصوير هو التعريف المباشر لـ<bdi>obstructive jaundice</bdi> (انسداد صفراوي)، حتى لو اليرقان السريري لسا ما ظهر بوضوح.",
        "عدم سماكة جدار المرارة وعدم وجود سائل حولها يستبعد <bdi>cholecystitis</bdi> كتشخيص أساسي هنا.",
        "ما فيه دليل تصويري على التهاب البنكرياس (زيادة حجمه أو سائل حوله) ليدعم <bdi>pancreatitis</bdi>.",
    ],
    "when_changes": [
        "لو ظهرت سماكة جدار المرارة وسائل حولها بالسونار، يصير التشخيص الأقوى <bdi>acute cholecystitis</bdi>.",
        "لو ارتفع الأميلاز والليباز بشكل واضح، يصير <bdi>pancreatitis</bdi> هو الأقرب.",
    ],
    "rule": "حصوة تسد الـ<bdi>CBD</bdi> بالتصوير تعني <bdi>obstructive jaundice</bdi> حتى لو اليرقان السريري لسا غير واضح.",
    "comparison": None,
    "guideline_note": None,
},
920: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "مولود عنده تأخر انفصال الحبل السري مع تاريخ أسري مماثل، وتحاليل التخثر الأساسية (<bdi>PT</bdi>، <bdi>PTT</bdi>، زمن النزيف) طبيعية، بس زمن تحلل الخثرة طويل جدًا (5 ساعات). هذا نمط كلاسيكي لعيب بثبات الخثرة مو بتكوينها.",
    "clues": [
        ("delayed umbilical cord separation", "علامة كلاسيكية جدًا لنقص <bdi>Factor XIII</bdi> عند الأطفال"),
        ("normal PT, normal PTT and normal bleeding time", "يستبعد مشاكل تكوين الخثرة الأولية أو الثانوية المعتادة"),
        ("clot lysis take 5 hours", "تحلل الخثرة المتأخر يدل على خثرة غير مستقرة بسبب نقص <bdi>Factor XIII</bdi> اللي يثبت الفيبرين"),
    ],
    "why_correct": [
        "<bdi>Factor XIII</bdi> مسؤول عن تثبيت وربط خيوط الفيبرين بالخثرة، ونقصه ما يأثر على <bdi>PT</bdi> أو <bdi>PTT</bdi> لأنهم يقيسون تكوين الخثرة مو ثباتها.",
        "تأخر انفصال الحبل السري مع تاريخ أسري مماثل علامة كلاسيكية موصوفة بالكتب لنقص <bdi>Factor XIII</bdi>.",
        "<bdi>Von Willebrand disease</bdi> و<bdi>hemophilia</bdi> يطولون <bdi>PTT</bdi> أو زمن النزيف، وهذا غير موجود هنا لأن كل التحاليل الأساسية طبيعية.",
    ],
    "when_changes": [
        "لو كان زمن النزيف طويل مع عدد صفيحات طبيعي، يصير الاحتمال الأقوى <bdi>Von Willebrand disease</bdi> أو <bdi>Bernard-Soulier</bdi>.",
        "لو طال الـ<bdi>PTT</bdi> تحديدًا، يصير <bdi>hemophilia</bdi> هو الأقرب.",
    ],
    "rule": "تأخر انفصال الحبل السري مع تحاليل تخثر أساسية طبيعية وزمن تحلل خثرة طويل يوجه لنقص <bdi>Factor XIII</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
921: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "مريض عنده كتلة بطنية متضخمة بعد 6 أسابيع من نوبة التهاب بنكرياس حادة، والتصوير يظهر كيس سائل محدد الحدود. هذا نمط <bdi>pancreatic pseudocyst</bdi> ناضج يحتاج تصريف.",
    "clues": [
        ("pancreatitis 6 weeks ago", "المدة كافية لنضوج جدار الكيس، وهذا مهم لاختيار طريقة التصريف"),
        ("well defined fluid cyst", "جدار واضح ومحدد يدعم إنه <bdi>pseudocyst</bdi> ناضج جاهز للتصريف"),
        ("worsening abdominal pain and palpable enlarging mass", "أعراض ضغط موضعي تستدعي تدخل مو مجرد ملاحظة"),
    ],
    "why_correct": [
        "<bdi>Pseudocyst</bdi> ناضج (بعد أكثر من 4-6 أسابيع) مع أعراض متفاقمة من ألم وكتلة متزايدة يحتاج تصريف، والتصريف بالمنظار (<bdi>endoscopic drainage</bdi>) هو الخيار المفضل حاليًا لأنه أقل تدخلًا من الجراحة.",
        "المضادات الحيوية لا تفيد هنا لأن الكيس سائل غير مصاب (ما فيه دليل خراج أو إنتان).",
        "التصريف الجراحي المباشر يُحجز للحالات المعقدة أو الفاشلة بالمنظار، مو كخط أول روتيني لكيس ناضج محدد الحدود.",
    ],
    "when_changes": [
        "لو كان الكيس أصغر من 6 سم وبدون أعراض، المراقبة لوحدها كافية بدون تدخل.",
        "لو كان فيه دليل إنتان أو خراج، يصير التصريف أعجل وربما يحتاج تدخل جراحي أو عبر الجلد.",
    ],
    "rule": "<bdi>Pseudocyst</bdi> ناضج وعرضي (ألم، كتلة متزايدة) يُعالج بالتصريف، ويُفضل التصريف بالمنظار كخط أول.",
    "comparison": None,
    "guideline_note": None,
},
922: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "طفل عنده تاريخ أسري لارتفاع ضغط أساسي، والأهل يسألون عن الوقاية. السؤال يبي أفضل إجراء وقائي لطفل عنده عامل خطر بس بدون تشخيص ارتفاع ضغط فعلي.",
    "clues": [
        ("family history of essential hypertension", "عامل خطر وراثي يستدعي متابعة مو علاج فوري"),
        ("how to prevent or protect the kid", "السؤال عن وقاية مستقبلية مو علاج حالة موجودة"),
    ],
    "why_correct": [
        "الطفل ما عنده تشخيص ارتفاع ضغط فعلي، فبدء علاج دوائي (<bdi>C</bdi>) غير مناسب إطلاقًا بهالمرحلة.",
        "أفضل إجراء وقائي لطفل عنده تاريخ أسري هو المتابعة الدورية المنتظمة لقياس الضغط عند كل زيارة، لاكتشاف أي ارتفاع مبكرًا.",
        "تثبيط النشاط البدني (<bdi>A</bdi>) عكس التوصيات، لأن النشاط البدني المنتظم يحمي من ارتفاع الضغط مستقبلًا.",
    ],
    "when_changes": [
        "لو تأكد تشخيص ارتفاع ضغط فعلي بالطفل بقياسات متكررة، يصير النقاش حول تعديل نمط الحياة وربما علاج دوائي.",
        "لو كان الطفل سمين مع تاريخ أسري، تنضم توصيات تقليل الوزن والملح الزائد لبرنامج الوقاية.",
    ],
    "rule": "طفل عنده تاريخ أسري لارتفاع ضغط بس بدون تشخيص فعلي يحتاج متابعة دورية منتظمة للضغط، مو علاج دوائي مبكر.",
    "comparison": None,
    "guideline_note": None,
},
923: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "فتاة عندها ألم بالربع السفلي الأيمن خفيف بدون حمى ولا ارتفاع كريات دم بيضاء، والسؤال يبي أهم إجراء يمنع تفويت تشخيص مثل <bdi>appendicitis</bdi> المبكر.",
    "clues": [
        ("RLQ abdominal pain", "مكان الألم الكلاسيكي لـ<bdi>appendicitis</bdi> المبكر"),
        ("afebrile, normal WBC, mild tenderness", "علامات غير حاسمة بهذا الوقت، ما تستبعد <bdi>appendicitis</bdi> المبكر"),
        ("most important management to avoid missed diagnosis", "السؤال يحدد الهدف: عدم تفويت التشخيص"),
    ],
    "why_correct": [
        "بما إن الفحص غير حاسم والأعراض خفيفة، أفضل طريقة لمنع تفويت التشخيص هي الإدخال للمراقبة وإعادة الفحص السريري المتكرر خلال 24 ساعة.",
        "الإعادة للمنزل (<bdi>B</bdi>) تحمل خطر تفويت تدهور الحالة لو كانت بداية <bdi>appendicitis</bdi> فعلية.",
        "المسكنات وحدها (<bdi>C</bdi>) تخفف الألم بس ما تكشف التطور ولا تمنع تفويت التشخيص.",
    ],
    "when_changes": [
        "لو ظهرت حمى وارتفاع كريات دم بيضاء واضح، يصير التشخيص شبه مؤكد ويحتاج تدخل جراحي مباشر.",
        "لو كان الألم شديد مع علامات تهيج بريتوني واضحة، تصير الجراحة العاجلة هي الخطوة مباشرة بدون انتظار.",
    ],
    "rule": "ألم ربع سفلي أيمن خفيف بدون علامات حاسمة يحتاج إدخال للمراقبة وإعادة الفحص المتكرر لتجنب تفويت <bdi>appendicitis</bdi> المبكر.",
    "comparison": None,
    "guideline_note": None,
},
924: {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سؤال مباشر عن جرعة حمض الفوليك الروتينية لامرأة سليمة بعيادة ما قبل الحمل، بدون عوامل خطر إضافية.",
    "clues": [
        ("healthy woman", "ما فيه عوامل خطر إضافية (صرع، سكري، تاريخ عيب أنبوب عصبي سابق)"),
        ("preconception clinic", "الجرعة الروتينية المعتادة للوقاية من عيوب الأنبوب العصبي"),
    ],
    "why_correct": [
        "الجرعة الروتينية لحمض الفوليك لامرأة سليمة بدون عوامل خطر هي <bdi>1 mg</bdi> يوميًا بدءًا من قبل الحمل.",
        "الجرعات الأعلى (5 ملغ وما فوق) تُحجز للنساء عندهم عوامل خطر عالية لعيوب الأنبوب العصبي.",
    ],
    "when_changes": [
        "لو عندها تاريخ سابق لعيب أنبوب عصبي أو تاخذ أدوية صرع، تصير الجرعة الموصى بها <bdi>5 mg</bdi> يوميًا.",
        "لو كانت بدون عوامل خطر، تبقى الجرعة الروتينية <bdi>1 mg</bdi>.",
    ],
    "rule": "الجرعة الروتينية لحمض الفوليك بدون عوامل خطر هي <bdi>1 mg</bdi> يوميًا، وترفع لـ<bdi>5 mg</bdi> بوجود عوامل خطر.",
    "comparison": None,
    "guideline_note": None,
},
925: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "مريض معروف بـ<bdi>gout</bdi> و<bdi>psoriasis</bdi> ملتزم تمامًا على <bdi>allopurinol</bdi>، بس عنده ألم مفصلي جديد يشمل مفاصل متعددة (كاحل وركبتين) غير النمط المعتاد لنوبة <bdi>gout</bdi>. هذا يوجه لسبب التهابي آخر مرتبط بمرضه الجلدي.",
    "clues": [
        ("known case of psoriasis for several years", "تاريخ مرض جلدي مرتبط بنوع التهاب مفصلي مختلف عن <bdi>gout</bdi>"),
        ("using allopurinol regularly... has no improvement", "الالتزام بعلاج <bdi>gout</bdi> الوقائي بدون استجابة يقلل احتمال كونه نوبة <bdi>gout</bdi> فعلية"),
        ("left ankle, and bilateral knees", "نمط التهاب مفصلي متعدد وثنائي الجانب مو النمط الأحادي الكلاسيكي لـ<bdi>gout</bdi>"),
    ],
    "why_correct": [
        "الالتزام الكامل بـ<bdi>allopurinol</bdi> بدون أي تحسن يقلل كثيرًا احتمال كون الألم الجديد نوبة <bdi>gout</bdi> نشطة.",
        "النمط المتعدد والثنائي الجانب للمفاصل الجديدة مع تاريخ <bdi>psoriasis</bdi> طويل المدى يدعم <bdi>psoriatic arthritis</bdi> كسبب أرجح.",
        "<bdi>Pseudogout</bdi> ممكن نظريًا بس أقل احتمالًا من تشخيص مرتبط مباشرة بتاريخه الجلدي المعروف.",
    ],
    "when_changes": [
        "لو كان الألم محصور بإصبع القدم الكبير فقط مع ارتفاع حمض اليوريك، يصير <bdi>active gout</bdi> هو الأقرب رغم العلاج.",
        "لو كان المريض كبير بالسن مع تكلسات بالتصوير، يصير <bdi>pseudogout</bdi> احتمال أقوى.",
    ],
    "rule": "التهاب مفصلي متعدد وثنائي الجانب بمريض معروف بـ<bdi>psoriasis</bdi> رغم العلاج الكامل لـ<bdi>gout</bdi> يوجه لـ<bdi>psoriatic arthritis</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
926: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "رجل كبير بالسن بدون أعراض، عنده تضيق أورطي شديد بس وظيفة البطين الأيسر طبيعية. السؤال يبي الخطوة التالية المناسبة للمتابعة.",
    "clues": [
        ("asymptomatic", "غياب الأعراض مهم جدًا بقرار التدخل بتضيق الأورطي"),
        ("Normal left ventricular ejection fraction", "وظيفة البطين محفوظة، ما فيه دليل قصور قلبي يستدعي تدخل عاجل"),
    ],
    "why_correct": [
        "بتضيق الأورطي الشديد بدون أعراض ووظيفة بطين طبيعية، التوصية القياسية هي المراقبة الدقيقة (متابعة سريرية وإيكو دوري) بدون تدخل فوري.",
        "<bdi>LVH</bdi> موجود كتكيف طبيعي للبطين مع زيادة الضغط، وما يعتبر بمفرده مؤشر لتبديل الصمام إن كانت الوظيفة طبيعية وبدون أعراض.",
        "التدخل (جراحي أو <bdi>TAVI</bdi>) يُحجز للمرضى العرضيين أو عندهم مؤشرات أخرى مثل ضعف وظيفة البطين أو استجابة غير طبيعية لاختبار الجهد.",
    ],
    "when_changes": [
        "لو ظهرت أعراض مثل ضيق تنفس أو إغماء، يصير تبديل الصمام هو الخطوة المناسبة فورًا.",
        "لو انخفضت وظيفة البطين الأيسر رغم غياب الأعراض، يصير التدخل مبررًا كذلك.",
    ],
    "rule": "تضيق أورطي شديد بدون أعراض ووظيفة بطين طبيعية يُدار بالمراقبة الدقيقة، ويُحجز التدخل للعرضيين أو ضعف وظيفة البطين.",
    "comparison": None,
    "guideline_note": None,
},
927: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "رضيع عنده نفخة انقباضية قذفية مع تضيق أورطي مؤكد بالإيكو وتدرج ضغط مرتفع (60 ملم زئبق) رغم وظيفة بطين جيدة. السؤال يبي أفضل إدارة لتضيق أورطي شديد عند الأطفال.",
    "clues": [
        ("Aortic valve gradient of 60 mmHg", "تدرج مرتفع يدل على تضيق شديد يحتاج تدخل مو مجرد متابعة"),
        ("SOB on exertion with physical activity", "عرض يدعم إن التضيق أصبح مهم وظيفيًا"),
        ("good left ventricular systolic function", "يستبعد وجود قصور قلبي شديد حاليًا، بس التدرج المرتفع يبقى هو الأساس بقرار التدخل"),
    ],
    "why_correct": [
        "تدرج ضغط 60 ملم زئبق يصنف التضيق كشديد، ومع وجود أعراض (ضيق تنفس بالجهد) يصير التدخل مبررًا.",
        "<bdi>Balloon valvuloplasty</bdi> هو العلاج المفضل عند الأطفال لتضيق الصمام الأورطي الخلقي الشديد العرضي، أقل تدخلًا من الجراحة المباشرة.",
        "المتابعة لوحدها (<bdi>follow up</bdi>) غير كافية مع تدرج شديد وأعراض واضحة.",
    ],
    "when_changes": [
        "لو كان التدرج أقل من 40 ملم زئبق وبدون أعراض، تكون المتابعة الدورية كافية.",
        "لو فشلت <bdi>balloon valvuloplasty</bdi> أو كان التشريح غير مناسب لها، يصير التدخل الجراحي هو الخيار التالي.",
    ],
    "rule": "تضيق أورطي خلقي شديد (تدرج مرتفع) مع أعراض عند الأطفال يُعالج بـ<bdi>balloon valvuloplasty</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
928: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "مريض على علاج لارتفاع الكوليسترول مع تاريخ ضغط وسكري، وصار عنده تشنجات وعدم راحة بالعضلات. السؤال يبي الدواء الأكثر ارتباطًا بهالأعراض.",
    "clues": [
        ("high cholesterol level", "يوجه مباشرة لاستخدام <bdi>statin</bdi>"),
        ("cramps in muscle and uncomfortable feeling in legs", "عرض جانبي كلاسيكي معروف لأدوية <bdi>statin</bdi>"),
    ],
    "why_correct": [
        "<bdi>Atorvastatin</bdi> من فئة <bdi>statins</bdi>، وأعراض الألم والتشنج العضلي (<bdi>myopathy</bdi>) من أشهر أعراضها الجانبية المعروفة.",
        "<bdi>Lisinopril</bdi> (مثبط <bdi>ACE</bdi>) أعراضه الجانبية المعروفة سعال جاف وارتفاع بوتاسيوم، مو ألم عضلي.",
        "<bdi>Thiazide diuretics</bdi> ترتبط أكثر بنقص بوتاسيوم أو صوديوم مو تشنج عضلي مباشر بهذا النمط الكلاسيكي.",
    ],
    "when_changes": [
        "لو كانت الأعراض ضعف عضلي شديد مع ارتفاع إنزيمات العضلات (<bdi>CK</bdi>)، يصير التشخيص <bdi>statin-induced myopathy</bdi> أوضح ويحتاج إيقاف الدواء.",
        "لو كان العرض تشنج مع نقص بوتاسيوم بالتحاليل، يصير <bdi>thiazide</bdi> هو السبب الأرجح.",
    ],
    "rule": "ألم وتشنج عضلي عند مريض على <bdi>statin</bdi> يوجه مباشرة لـ<bdi>statin-induced myopathy</bdi> كسبب شائع ومعروف.",
    "comparison": None,
    "guideline_note": None,
},

WHY_WRONG = {}
HIGHLIGHT_TERMS = {}
