# -*- coding: utf-8 -*-
# SMLE 2026 Recalls — batch02 (questions 104-203)

TOPICS = {
    104: "Hematology",
    105: "Preventive & Community Medicine",
    106: "Preventive & Community Medicine",
    107: "Cardiology",
    108: "Pediatrics",
    109: "Obstetrics & Gynecology",
    110: "Gastroenterology",
    111: "Obstetrics & Gynecology",
    112: "Oncology",
    113: "Obstetrics & Gynecology",
    114: "Clinical Pharmacology & Toxicology",
    115: "Obstetrics & Gynecology",
    116: "Obstetrics & Gynecology",
    117: "Obstetrics & Gynecology",
    118: "Pediatrics",
    119: "Cardiology",
    120: "Pediatrics",
    121: "Endocrinology",
    122: "Biostatistics & Research Methods",
    123: "General Surgery",
    124: "Obstetrics & Gynecology",
    125: "Obstetrics & Gynecology",
    126: "Obstetrics & Gynecology",
    127: "Pediatrics",
    128: "Obstetrics & Gynecology",
    129: "Obstetrics & Gynecology",
    130: "Obstetrics & Gynecology",
    131: "ENT",
    132: "Nephrology",
    133: "Nephrology",
    134: "Pediatrics",
    135: "Cardiology",
    136: "Gastroenterology",
    137: "Nephrology",
    138: "Psychiatry",
    139: "Dermatology",
    140: "Respiratory Medicine",
    141: "Endocrinology",
    142: "Gastroenterology",
    143: "Neurology",
    144: "Obstetrics & Gynecology",
    145: "Pediatrics",
    146: "Cardiology",
    147: "Obstetrics & Gynecology",
    148: "Obstetrics & Gynecology",
    149: "Rheumatology",
    150: "Endocrinology",
    151: "Obstetrics & Gynecology",
    152: "Clinical Pharmacology & Toxicology",
    153: "Gastroenterology",
    154: "Pediatrics",
    155: "Obstetrics & Gynecology",
    156: "Emergency & Critical Care",
    157: "Pediatrics",
    158: "Obstetrics & Gynecology",
    159: "Obstetrics & Gynecology",
    160: "Obstetrics & Gynecology",
    161: "Musculoskeletal & Orthopedics",
    162: "Pediatrics",
    163: "Gastroenterology",
    164: "Neurology",
    165: "General Surgery",
    166: "General Surgery",
    167: "Cardiology",
    168: "Neurology",
    169: "Neurology",
    170: "General Surgery",
    171: "Obstetrics & Gynecology",
    172: "General Surgery",
    173: "Obstetrics & Gynecology",
    174: "Obstetrics & Gynecology",
    175: "Gastroenterology",
    176: "Pediatrics",
    177: "Rheumatology",
    178: "Obstetrics & Gynecology",
    179: "General Surgery",
    180: "Gastroenterology",
    181: "Gastroenterology",
    182: "Nephrology",
    183: "Gastroenterology",
    184: "Respiratory Medicine",
    185: "Nephrology",
    186: "Rheumatology",
    187: "Obstetrics & Gynecology",
    188: "Rheumatology",
    189: "Pediatrics",
    190: "Nephrology",
    191: "Respiratory Medicine",
    192: "Gastroenterology",
    193: "Respiratory Medicine",
    194: "Respiratory Medicine",
    195: "Nephrology",
    196: "Nephrology",
    197: "Respiratory Medicine",
    198: "Respiratory Medicine",
    199: "Pediatrics",
    200: "Hematology",
    201: "Obstetrics & Gynecology",
    202: "Nephrology",
    203: "Respiratory Medicine",
}

EXPLANATIONS = {
104: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "سؤال عن <bdi>transfusion reaction</bdi> صارت بسرعة (بعد 15 دقيقة بس)، والعلامة الرئيسية هي <bdi>hypotension</bdi> مع نقص أكسجين واضح (<bdi>SpO2 88%</bdi>). التركيز على الرئة والأكسجين يفرّق بين الأنواع.",
    "clues": [
        ("15 Minutes", "بداية سريعة جدًا للأعراض بعد بدء نقل الدم"),
        ("Hypotensive", "انخفاض ضغط مصاحب للتفاعل"),
        ("SpO2 88%", "نقص أكسجين شديد، العلامة الأهم اللي توجه للرئة مباشرة"),
    ],
    "why_correct": [
        "<bdi>Transfusion-related acute lung injury (TRALI)</bdi> يصير خلال ساعات قليلة من نقل الدم، وأهم علاماته هي نقص الأكسجين الحاد (<bdi>hypoxemia</bdi>) مع ضغط منخفض، بدون أي دليل على حمل زائد للسوائل.",
        "<bdi>Acute hemolytic transfusion reaction</bdi> سببها عدم توافق فصيلة الدم، وأعراضها الأساسية حمى وألم ظهر وبول دموي، مو نقص أكسجين كعلامة رئيسية.",
        "<bdi>Allergic reaction</bdi> عادة تعطي طفح جلدي وحكة وحكة بالحلق، ونادر تنزل الضغط ويختل الأكسجين بهذا الشكل الحاد بدون أعراض جلدية.",
    ],
    "when_changes": [
        "لو كان فيه طفح جلدي وحكة بدون مشاكل تنفسية، يصير التشخيص الأقرب <bdi>allergic reaction</bdi>.",
        "لو كانت هناك حمى وبول لونه أحمر غامق مع ألم بالظهر، يصير التشخيص الأقوى <bdi>acute hemolytic transfusion reaction</bdi>.",
    ],
    "rule": "نقص أكسجين حاد مع انخفاض ضغط خلال ساعات من نقل الدم بدون زيادة بالسوائل يوجه مباشرة لـ<bdi>TRALI</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
105: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "رجل بعمر 50 سنة، وهذا العمر وحده كافي لاستحقاق لقاح الحزام الناري (<bdi>shingles</bdi>)، بغض النظر عن تاريخه بالسكتة النزفية. السؤال يبي اللقاح المناسب لعمره وحالته.",
    "clues": [
        ("50-Year-Old", "العمر المحدد اللي يبدأ منه التوصية بلقاح <bdi>shingles</bdi> (النوع المعطل)"),
        ("Previous Hemorrhagic Stroke", "مرض سابق مستقر، ما فيه مانع لإعطاء لقاح غير حي"),
    ],
    "why_correct": [
        "لقاح <bdi>shingles (recombinant zoster vaccine)</bdi> يُعطى لجميع البالغين من عمر 50 فما فوق بشكل روتيني، وهو لقاح غير حي فمو ممنوع مع تاريخ السكتة.",
        "لقاح <bdi>Hepatitis A</bdi> مو روتيني لهذا العمر إلا لو فيه عامل خطر معين (سفر، مرض كبد).",
        "لقاح الإنفلونزا السنوي مهم بس يعطى سنويًا للجميع ومو مرتبط تحديدًا بهذا العمر كتوصية جديدة محددة.",
    ],
    "when_changes": [
        "لو كان عمره أقل من 50 سنة بدون أمراض مناعية، يصير لقاح <bdi>shingles</bdi> غير مستحق حاليًا.",
        "لو كان المريض يسافر لمنطقة ينتشر فيها <bdi>Hepatitis A</bdi>، يصير لقاح <bdi>Hepatitis A</bdi> هو الأولوية.",
    ],
    "rule": "لقاح الحزام الناري (<bdi>recombinant zoster vaccine</bdi>) يوصى به روتينيًا لكل من عمره 50 سنة فأكثر.",
    "comparison": None,
    "guideline_note": None,
},
106: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "رجل عمره 50 سنة مصاب بـ<bdi>COPD</bdi>، والسؤال يبي اللقاح المناسب حاليًا. مرض الرئة المزمن يرفع خطر العدوى التنفسية خصوصًا الإنفلونزا، فهذا هو أكثر لقاح مرتبط بحالته مباشرة.",
    "clues": [
        ("COPD", "مرض رئوي مزمن يرفع خطر المضاعفات من عدوى الجهاز التنفسي"),
        ("50-Year-Old", "عمر يستحق لقاح <bdi>shingles</bdi> كمان، بس السؤال يركز على مرضه التنفسي"),
    ],
    "why_correct": [
        "مرضى <bdi>COPD</bdi> معرضين لمضاعفات شديدة من <bdi>influenza</bdi>، فلقاح الإنفلونزا السنوي يُعطى روتينيًا لهم وله أولوية مرتبطة بمرضه الرئوي.",
        "لقاح <bdi>Hepatitis A</bdi> غير مرتبط بـ<bdi>COPD</bdi> إطلاقًا.",
        "لقاح <bdi>shingles</bdi> يستحقه بسبب عمره بس هو مو اللقاح الأكثر ارتباطًا بمرضه التنفسي المذكور بالسؤال.",
    ],
    "when_changes": [
        "لو كان السؤال يسأل عن اللقاح المرتبط بعمره فقط بدون ذكر <bdi>COPD</bdi>، يصير لقاح <bdi>shingles</bdi> هو الأقرب.",
        "لو ذكر السؤال أنه لم يأخذ لقاح المكورات الرئوية (<bdi>pneumococcal</bdi>) من قبل، هذا كمان يصير أولوية بمرض الرئة المزمن.",
    ],
    "rule": "مرضى <bdi>COPD</bdi> لازم يأخذوا لقاح الإنفلونزا السنوي لأنه يقلل خطر التفاقم الحاد والمضاعفات.",
    "comparison": None,
    "guideline_note": None,
},
107: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "رجل مسن سكري وضغط دخل بعملية بسبب أمعاء متموتة (دليل على نقص تروية مفاجئ)، وبعد استبعاد سبب قلبي بـ<bdi>ECG</bdi> و<bdi>Echo</bdi> طبيعيين، لازم نبحث عن مصدر غير ظاهر بالفحوصات العادية.",
    "clues": [
        ("necrotic bowel", "دليل على <bdi>acute mesenteric ischemia</bdi>، غالبًا من مصدر صمة قلبية"),
        ("ECG showed sinus rhythm", "لا يوجد رجفان أذيني لحظة الفحص، بس هذا لا يستبعد نوبات متقطعة"),
        ("Echo was normal", "لا يوجد خثرة أو ضعف بعضلة القلب، بس هذا لا يستبعد اضطراب نظم متقطع"),
    ],
    "why_correct": [
        "<bdi>Holter monitor</bdi> يراقب نظم القلب لساعات أو أيام، وهذا يكشف نوبات <bdi>paroxysmal atrial fibrillation</bdi> المتقطعة اللي ما ظهرت بـ<bdi>ECG</bdi> اللحظي، وهي سبب شائع لتكوّن خثرات تسبب انسداد بالأمعاء.",
        "الأمعاء المتموتة بدون سبب ظاهر توجه فعليًا لمصدر صمة (<bdi>embolic source</bdi>)، وأكثر سبب قابل للعلاج هو رجفان أذيني متقطع.",
        "<bdi>Exercise ECG</bdi> يفيد لتشخيص نقص تروية القلب أثناء الجهد، مو لاكتشاف اضطراب نظم متقطع.",
    ],
    "when_changes": [
        "لو كان الـ<bdi>ECG</bdi> يُظهر <bdi>atrial fibrillation</bdi> وقت الفحص، ما نحتاج <bdi>Holter</bdi> ونذهب مباشرة لعلاج <bdi>AF</bdi> ومنع الصمات.",
        "لو كان هناك دليل على خثرة بالـ<bdi>Echo</bdi>، يصير التركيز على مصدرها القلبي مباشرة بدل البحث عن نظم متقطع.",
    ],
    "rule": "نقص تروية بدون مصدر واضح بعد <bdi>ECG</bdi> و<bdi>Echo</bdi> طبيعيين يستدعي <bdi>Holter monitor</bdi> للبحث عن رجفان أذيني متقطع.",
    "comparison": None,
    "guideline_note": None,
},
108: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "رضيع عمره 6 أسابيع بتقيؤ نفور (<bdi>projectile vomiting</bdi>) مع جفاف وضعف نمو، والموجات الصوتية أكدت <bdi>pyloric stenosis</bdi>. السؤال يبي الخطوة الأولى، ومهم نفرّق بين التثبيت أولًا والجراحة.",
    "clues": [
        ("projectile vomiting after feeds", "علامة كلاسيكية لـ<bdi>pyloric stenosis</bdi>"),
        ("poor weight gain, and dehydration", "دليل على فقدان سوائل وشوارد لازم يُصحح قبل أي تخدير"),
        ("Ultrasound shows pyloric thickening", "تأكيد التشخيص بالتصوير"),
    ],
    "why_correct": [
        "الخطوة الأولى دايمًا هي تصحيح الجفاف وخلل الشوارد (<bdi>hypochloremic hypokalemic metabolic alkalosis</bdi> الشائع بهالحالة) بالسوائل الوريدية قبل التجهيز لعملية <bdi>pyloromyotomy</bdi>.",
        "<bdi>Pyloromyotomy</bdi> هو العلاج النهائي بس لازم يصير بعد تثبيت الطفل، مو كخطوة أولى فورية قبل التصحيح.",
        "تغيير نوع الحليب لا يعالج الانسداد الميكانيكي الموجود بالعضلة، والمراقبة فقط غير كافية مع جفاف وضعف نمو واضحين.",
    ],
    "when_changes": [
        "لو كان الطفل مستقر بدون جفاف أو خلل شوارد، تصير الخطوة التالية مباشرة <bdi>pyloromyotomy</bdi> بدون تأخير بالسوائل.",
        "لو ظهر انسداد جزئي بدون تأكيد تصويري، يحتاج تأكيد التشخيص أولًا بالموجات الصوتية قبل أي تدخل.",
    ],
    "rule": "بـ<bdi>pyloric stenosis</bdi>، التصحيح الكامل للجفاف والشوارد يسبق دايمًا الجراحة (<bdi>pyloromyotomy</bdi>).",
    "comparison": None,
    "guideline_note": None,
},
109: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "سؤال معلومة مباشرة عن أكثر نوع من فيروس <bdi>HPV</bdi> مرتبط بسرطان عنق الرحم. هذا من أساسيات <bdi>cervical cancer</bdi> اللي لازم تُحفظ.",
    "clues": [
        ("HPV", "الفيروس المسبب الأساسي لسرطان عنق الرحم"),
        ("cervical cancer", "النوع المرتبط بأنماط <bdi>high-risk</bdi> معينة من الفيروس"),
    ],
    "why_correct": [
        "أنماط <bdi>HPV 16 و18</bdi> هي الأكثر ارتباطًا بسرطان عنق الرحم، ومسؤولة عن أغلب الحالات حول العالم.",
        "أنماط <bdi>11 و12</bdi> مرتبطة أكثر بـ<bdi>genital warts</bdi> الحميدة مو السرطان.",
        "أنماط <bdi>32/36 و44</bdi> مو من الأنماط عالية الخطورة المعروفة المرتبطة بسرطان عنق الرحم.",
    ],
    "when_changes": [
        "لو السؤال يبي النمط المرتبط بالثآليل التناسلية الحميدة، يصير الجواب <bdi>HPV 6 و11</bdi>.",
        "لو السؤال يبي اللقاح الوقائي الأشمل، يصير الجواب لقاح <bdi>HPV</bdi> التسعاعي (<bdi>9-valent</bdi>) اللي يغطي الأنماط الخطيرة والحميدة معًا.",
    ],
    "rule": "<bdi>HPV 16 و18</bdi> هما الأنماط الأكثر ارتباطًا بسرطان عنق الرحم.",
    "comparison": None,
    "guideline_note": None,
},
110: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "مريضة بصفار (<bdi>jaundice</bdi>) وألم بالربع العلوي الأيمن مع ارتفاع إنزيمات الكبد والبيليروبين، يشير لمشكلة بالقناة الصفراوية أو الكبد. السؤال يبي أفضل تصوير أولي.",
    "clues": [
        ("jaundice", "ارتفاع البيليروبين، يوجه لمشكلة كبدية أو انسداد صفراوي"),
        ("RUQ tenderness", "موقع الألم يوجه مباشرة للكبد والمرارة والقناة الصفراوية"),
        ("LFT and bilirubin are elevated", "تأكيد اختبارات مخبرية لمشكلة كبدية/صفراوية"),
    ],
    "why_correct": [
        "الموجات الصوتية فوق البطن (<bdi>abdominal US</bdi>) هي الفحص الأول دايمًا عند الشك بمشكلة صفراوية أو كبدية، سريعة وغير مكلفة وتكشف حصوات وتوسع القناة الصفراوية.",
        "<bdi>MRCP</bdi> فحص أدق للقناة الصفراوية بس يُستخدم كخطوة ثانية لو الـ<bdi>US</bdi> غير حاسم أو فيه شك بحصوة بالقناة المشتركة.",
        "<bdi>CT</bdi> أقل حساسية من <bdi>US</bdi> لاكتشاف حصوات المرارة وأغلى، فمو الخيار الأول.",
    ],
    "when_changes": [
        "لو الـ<bdi>US</bdi> أظهر توسع بالقناة الصفراوية بدون سبب واضح، يصير الخطوة التالية <bdi>MRCP</bdi>.",
        "لو الشك بورم بالبنكرياس أو مضاعفات أخرى، يصير <bdi>CT</bdi> أو <bdi>MRCP</bdi> أكثر فائدة من <bdi>US</bdi> لوحده.",
    ],
    "rule": "الموجات الصوتية فوق البطن هي الفحص التصويري الأول عند الشك بمشكلة كبدية صفراوية.",
    "comparison": None,
    "guideline_note": None,
},
111: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "حامل بأسبوع 37 عندها تاريخ أمراض منقولة جنسيًا، والطبيب قلق من عدوى تسبب التهاب ملتحمة وعمى للمولود — هذا نمط كلاسيكي لعدوى <bdi>Chlamydia</bdi> أو <bdi>Gonorrhea</bdi>. السؤال يبي أفضل إجراء للوقاية.",
    "clues": [
        ("multiple sexual transmitted diseases", "عامل خطر قوي لعدوى <bdi>Chlamydia/Gonorrhea</bdi> غير مشخصة"),
        ("conjunctivitis and blindness in the newborn", "وصف كلاسيكي لـ<bdi>ophthalmia neonatorum</bdi>"),
        ("37th gestational week", "وقت كافٍ قبل الولادة لعلاج الأم ومنع انتقال العدوى"),
    ],
    "why_correct": [
        "إعطاء <bdi>azithromycin</bdi> للأم قبل الولادة يعالج العدوى المحتملة (<bdi>Chlamydia</bdi>) ويمنع انتقالها للمولود أثناء الولادة، وهذا أفضل إجراء وقائي حقيقي.",
        "<bdi>Reassurance</bdi> غير مناسب مع وجود خطر حقيقي وتاريخ أمراض منقولة جنسيًا.",
        "فحص المولود بعد الولادة (<bdi>newborn screening after delivery</bdi>) يكشف العدوى بعد ما تصير، مو وقاية فعلية قبلها.",
    ],
    "when_changes": [
        "لو كانت الأم بدون أعراض وبدون تاريخ خطر، يكفي المراقبة الروتينية بدون علاج تجريبي.",
        "لو تأكد التشخيص بفحص مخبري محدد قبل الولادة، يصير العلاج موجه حسب نوع العدوى المؤكدة.",
    ],
    "rule": "عند الشك بعدوى منقولة جنسيًا قريب من الولادة، علاج الأم (مثل <bdi>azithromycin</bdi>) قبل الولادة أفضل وقاية لعين المولود.",
    "comparison": None,
    "guideline_note": None,
},
112: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "سؤال عن معايير استئناف العلاج الكيماوي بعد <bdi>tumor lysis syndrome</bdi>، لازم ترجع لقيم الشوارد والكلى الطبيعية تقريبًا قبل إعادة العلاج.",
    "clues": [
        ("resume chemotherapy", "يعني لازم تتأكد إن المضاعفات الاستقلابية انحلت بشكل كافٍ"),
        ("tumor lysis syndrome", "متلازمة تحرر محتوى الخلايا السرطانية المفاجئ، ترفع حمض اليوريك والبوتاسيوم والفوسفات"),
    ],
    "why_correct": [
        "استئناف العلاج يحتاج رجوع حمض اليوريك والكرياتينين لمستويات طبيعية تقريبًا ورجوع <bdi>pH</bdi> لمعدل طبيعي، وهذا يطابق القيم الأقرب للمعدل الطبيعي بين الخيارات.",
        "القيم الأعلى بوضوح من الطبيعي (كرياتينين أعلى أو حمض يوريك أعلى بشكل ملحوظ) تدل على أن المتلازمة لسا نشطة ومو وقتها نعيد العلاج.",
        "لازم تطابق القيم الطبيعية المرجعية الصحيحة سوا لحمض اليوريك والكرياتينين والـ<bdi>pH</bdi>، مو قيمة واحدة بس.",
    ],
    "when_changes": [
        "لو كانت القيم كلها طبيعية تمامًا بدون أي ارتفاع، يصير استئناف العلاج أوضح وأسرع.",
        "لو ظل البوتاسيوم مرتفع رغم تحسن باقي القيم، لازم نعالجه أولًا قبل أي استئناف للعلاج الكيماوي.",
    ],
    "rule": "استئناف العلاج الكيماوي بعد <bdi>tumor lysis syndrome</bdi> يحتاج رجوع حمض اليوريك والكرياتينين والـ<bdi>pH</bdi> لمستويات طبيعية تقريبًا.",
    "comparison": None,
    "guideline_note": None,
},
113: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "امرأة عندها عقم 6 سنوات مع عسر طمث شديد ما استجاب للـ<bdi>naproxen</bdi>. هذا الثنائي (عقم + عسر طمث شديد مقاوم للـ<bdi>NSAIDs</bdi>) كلاسيكي لـ<bdi>endometriosis</bdi>.",
    "clues": [
        ("infertility for 6 years", "مرتبط بشكل قوي بـ<bdi>endometriosis</bdi> كسبب شائع للعقم"),
        ("severe dysmenorrhea unrelieved by naproxen", "ألم شديد مو مجرد ألم طمث عادي يستجيب للـ<bdi>NSAIDs</bdi>"),
    ],
    "why_correct": [
        "<bdi>Endometriosis</bdi> تسبب عسر طمث شديد مقاوم للعلاج المعتاد وترتبط بشكل قوي بالعقم بسبب الالتصاقات والالتهاب المزمن بالحوض.",
        "<bdi>Pelvic inflammatory disease</bdi> غالبًا يصاحبها حمى وإفرازات وألم حاد، غير مذكور هنا، وهي حالة حادة مو مزمنة بهذا الشكل.",
        "<bdi>PCOS</bdi> يسبب عقم بس عادة بدورة غير منتظمة وأعراض زيادة أندروجين، مو عسر طمث شديد كعلامة أساسية.",
    ],
    "when_changes": [
        "لو كانت الدورة غير منتظمة مع زيادة شعر الجسم ووزن، يصير <bdi>PCOS</bdi> هو الاحتمال الأقوى بدل <bdi>endometriosis</bdi>.",
        "لو فيه حمى وإفرازات مهبلية مع الألم، يصير <bdi>PID</bdi> هو التشخيص الأقرب.",
    ],
    "rule": "عقم مع عسر طمث شديد مقاوم للـ<bdi>NSAIDs</bdi> يوجه بقوة لتشخيص <bdi>endometriosis</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
    # MARKER_EXPLANATIONS
}

WHY_WRONG = {
104: {
    "A": "<bdi>Acute hemolytic reaction</bdi> سببها عدم توافق الدم، تعطي حمى وألم ظهر وبول دموي، مو نقص أكسجين كعلامة أساسية بهذا الشكل.",
    "C": "<bdi>Allergic reaction</bdi> عادة يصاحبها طفح وحكة، ونادر تنزل الضغط والأكسجين بهذه الشدة بدون أعراض جلدية.",
},
105: {
    "B": "<bdi>Hepatitis A</bdi> ليس روتيني لهذا العمر بدون عامل خطر محدد كالسفر أو مرض كبدي.",
    "C": "لقاح الإنفلونزا يعطى سنويًا للجميع، بس مو هو التوصية الجديدة المحددة المرتبطة بعمر 50 سنة.",
},
106: {
    "A": "لقاح <bdi>shingles</bdi> يستحقه بعمره، بس هو مو الأكثر ارتباطًا بمرضه التنفسي المذكور بالسؤال.",
    "B": "لقاح <bdi>Hepatitis A</bdi> غير مرتبط بـ<bdi>COPD</bdi> إطلاقًا.",
},
107: {
    "A": "<bdi>Exercise ECG</bdi> يكشف نقص تروية بالجهد، مو اضطراب نظم متقطع.",
    "C": "تكرار الـ<bdi>Echo</bdi> لن يضيف معلومة جديدة لأن النتيجة كانت طبيعية والمشكلة مو بعضلة القلب أو الصمامات.",
},
108: {
    "A": "<bdi>Pyloromyotomy</bdi> مباشرة بدون تصحيح الجفاف والشوارد أولًا خطر على الطفل أثناء التخدير.",
    "B": "تغيير الحليب لا يحل الانسداد الميكانيكي الموجود بعضلة البواب.",
    "D": "المراقبة فقط غير كافية مع جفاف واضح وضعف نمو مستمر يحتاجان تدخل.",
},
109: {
    "A": "أنماط <bdi>11 و12</bdi> مرتبطة بالثآليل التناسلية الحميدة مو سرطان عنق الرحم.",
    "C": "أنماط <bdi>32/36</bdi> مو من الأنماط عالية الخطورة المعروفة لسرطان عنق الرحم.",
    "D": "النمط <bdi>44</bdi> مو مرتبط بشكل أساسي بسرطان عنق الرحم.",
},
110: {
    "A": "<bdi>MRCP</bdi> فحص أدق بس يُستخدم كخطوة ثانية بعد الموجات الصوتية، مو كخطوة أولى.",
    "C": "<bdi>CT</bdi> أقل حساسية من <bdi>US</bdi> لاكتشاف حصوات المرارة وأغلى تكلفة.",
},
111: {
    "A": "<bdi>Reassurance</bdi> غير مناسب مع خطر حقيقي وتاريخ أمراض منقولة جنسيًا متعدد.",
    "C": "فحص المولود بعد الولادة يكشف العدوى بعد حدوثها، مو وقاية فعلية قبلها.",
    "D": "تحويلها لطبيب الأمراض المعدية بدون علاج فوري يأخر الوقاية والوقت ضيق قبل الولادة.",
},
112: {
    "A": "القيم هنا أقل من المعدل المطلوب لتأكيد انحلال المتلازمة بشكل كافٍ لحمض اليوريك.",
    "C": "قيمة الكرياتينين هنا أعلى من المستوى الطبيعي المطلوب لاستئناف العلاج بأمان.",
    "D": "قيمة الـ<bdi>pH</bdi> هنا خارج النطاق الطبيعي المطلوب لاستئناف العلاج.",
},
113: {
    "A": "<bdi>Endometritis</bdi> حالة التهابية حادة غالبًا بعد ولادة أو إجراء رحمي، مو مرتبطة بعقم طويل مع عسر طمث مزمن.",
    "B": "<bdi>PID</bdi> غالبًا يصاحبها حمى وإفرازات وألم حاد، غير مذكور هنا.",
    "D": "<bdi>PCOS</bdi> يسبب عقم بس بدورة غير منتظمة وأعراض زيادة أندروجين، مو عسر طمث شديد كعلامة أساسية.",
},
    # MARKER_WHY_WRONG
}

HIGHLIGHT_TERMS = {
    # MARKER_HIGHLIGHT
}
