# -*- coding: utf-8 -*-
# SMLE 2026 Recalls -- batch08 (questions 802-913, slice smle2026/data/slices/batch08.json)

TOPICS = {
    802: "Preventive & Community Medicine",
    804: "Medical Ethics & Communication",
    805: "Neurology",
    806: "General Surgery",
    808: "Obstetrics & Gynecology",
    809: "General Surgery",
    810: "Endocrinology",
    812: "Infectious Diseases",
    813: "Nephrology",
    814: "Preventive & Community Medicine",
    815: "Medical Ethics & Communication",
    816: "General Surgery",
    817: "Medical Ethics & Communication",
    819: "Pediatrics",
    820: "Pediatrics",
    821: "Pediatrics",
    822: "Preventive & Community Medicine",
    823: "Pediatrics",
    824: "Pediatrics",
    825: "Emergency & Critical Care",
    826: "Obstetrics & Gynecology",
    827: "Pediatrics",
    828: "Obstetrics & Gynecology",
    829: "Medical Ethics & Communication",
    831: "Geriatric Medicine",
    832: "Pediatrics",
    833: "Obstetrics & Gynecology",
    834: "Biostatistics & Research Methods",
    835: "Respiratory Medicine",
    836: "Gastroenterology",
    837: "Obstetrics & Gynecology",
    839: "Pediatrics",
    840: "Medical Ethics & Communication",
    841: "Medical Ethics & Communication",
    842: "Medical Ethics & Communication",
    843: "Medical Ethics & Communication",
    844: "Respiratory Medicine",
    845: "Cardiology",
    846: "Infectious Diseases",
    847: "Musculoskeletal & Orthopedics",
    852: "Pediatrics",
    853: "Cardiology",
    854: "Cardiology",
    855: "Obstetrics & Gynecology",
    856: "General Surgery",
    857: "Obstetrics & Gynecology",
    858: "General Surgery",
    859: "General Surgery",
    861: "Emergency & Critical Care",
    862: "Emergency & Critical Care",
    863: "Emergency & Critical Care",
    864: "ENT",
    865: "Preventive & Community Medicine",
    866: "Medical Ethics & Communication",
    867: "General Surgery",
    868: "Endocrinology",
    869: "Endocrinology",
    870: "Hematology",
    871: "Obstetrics & Gynecology",
    872: "Obstetrics & Gynecology",
    873: "Obstetrics & Gynecology",
    874: "Rheumatology",
    875: "Gastroenterology",
    876: "Nephrology",
    877: "Clinical Pharmacology & Toxicology",
    878: "Urology",
    879: "Emergency & Critical Care",
    880: "Emergency & Critical Care",
    881: "Cardiology",
    882: "Urology",
    883: "Oncology",
    885: "Pediatrics",
    886: "Oncology",
    887: "Gastroenterology",
    888: "Emergency & Critical Care",
    889: "Cardiology",
    890: "Rheumatology",
    891: "Medical Ethics & Communication",
    892: "Pediatrics",
    893: "Medical Ethics & Communication",
    894: "General Surgery",
    895: "Preventive & Community Medicine",
    896: "General Surgery",
    897: "Emergency & Critical Care",
    898: "Emergency & Critical Care",
    899: "Pediatrics",
    900: "Pediatrics",
    901: "Pediatrics",
    902: "Emergency & Critical Care",
    903: "Urology",
    904: "Urology",
    905: "Obstetrics & Gynecology",
    906: "Pediatrics",
    907: "Endocrinology",
    908: "Obstetrics & Gynecology",
    909: "Obstetrics & Gynecology",
    910: "Gastroenterology",
    911: "Neurology",
    912: "Biostatistics & Research Methods",
    913: "Biostatistics & Research Methods",
}

EXPLANATIONS = {}

WHY_WRONG = {}

HIGHLIGHT_TERMS = {}
