# -*- coding: utf-8 -*-
# SMLE 2026 Recalls — batch02 (questions 104-203)

TOPICS = {
    104: "Hematology",
    105: "Preventive & Community Medicine",
    106: "Preventive & Community Medicine",
    107: "Cardiology",
    108: "Pediatrics",
    109: "Obstetrics & Gynecology",
    110: "Gastroenterology",
    111: "Obstetrics & Gynecology",
    112: "Oncology",
    113: "Obstetrics & Gynecology",
    114: "Clinical Pharmacology & Toxicology",
    115: "Obstetrics & Gynecology",
    116: "Obstetrics & Gynecology",
    117: "Obstetrics & Gynecology",
    118: "Pediatrics",
    119: "Cardiology",
    120: "Pediatrics",
    121: "Endocrinology",
    122: "Biostatistics & Research Methods",
    123: "General Surgery",
    124: "Obstetrics & Gynecology",
    125: "Obstetrics & Gynecology",
    126: "Obstetrics & Gynecology",
    127: "Pediatrics",
    128: "Obstetrics & Gynecology",
    129: "Obstetrics & Gynecology",
    130: "Obstetrics & Gynecology",
    131: "ENT",
    132: "Nephrology",
    133: "Nephrology",
    134: "Pediatrics",
    135: "Cardiology",
    136: "Gastroenterology",
    137: "Nephrology",
    138: "Psychiatry",
    139: "Dermatology",
    140: "Respiratory Medicine",
    141: "Endocrinology",
    142: "Gastroenterology",
    143: "Neurology",
    144: "Obstetrics & Gynecology",
    145: "Pediatrics",
    146: "Cardiology",
    147: "Obstetrics & Gynecology",
    148: "Obstetrics & Gynecology",
    149: "Rheumatology",
    150: "Endocrinology",
    151: "Obstetrics & Gynecology",
    152: "Clinical Pharmacology & Toxicology",
    153: "Gastroenterology",
    154: "Pediatrics",
    155: "Obstetrics & Gynecology",
    156: "Emergency & Critical Care",
    157: "Pediatrics",
    158: "Obstetrics & Gynecology",
    159: "Obstetrics & Gynecology",
    160: "Obstetrics & Gynecology",
    161: "Musculoskeletal & Orthopedics",
    162: "Pediatrics",
    163: "Gastroenterology",
    164: "Neurology",
    165: "General Surgery",
    166: "General Surgery",
    167: "Cardiology",
    168: "Neurology",
    169: "Neurology",
    170: "General Surgery",
    171: "Obstetrics & Gynecology",
    172: "General Surgery",
    173: "Obstetrics & Gynecology",
    174: "Obstetrics & Gynecology",
    175: "Gastroenterology",
    176: "Pediatrics",
    177: "Rheumatology",
    178: "Obstetrics & Gynecology",
    179: "General Surgery",
    180: "Gastroenterology",
    181: "Gastroenterology",
    182: "Nephrology",
    183: "Gastroenterology",
    184: "Respiratory Medicine",
    185: "Nephrology",
    186: "Rheumatology",
    187: "Obstetrics & Gynecology",
    188: "Rheumatology",
    189: "Pediatrics",
    190: "Nephrology",
    191: "Respiratory Medicine",
    192: "Gastroenterology",
    193: "Respiratory Medicine",
    194: "Respiratory Medicine",
    195: "Nephrology",
    196: "Nephrology",
    197: "Respiratory Medicine",
    198: "Respiratory Medicine",
    199: "Pediatrics",
    200: "Hematology",
    201: "Obstetrics & Gynecology",
    202: "Nephrology",
    203: "Respiratory Medicine",
}

EXPLANATIONS = {
    # MARKER_EXPLANATIONS
}

WHY_WRONG = {
    # MARKER_WHY_WRONG
}

HIGHLIGHT_TERMS = {
    # MARKER_HIGHLIGHT
}
