# -*- coding: utf-8 -*-
# SMLE 2026 Recalls -- batch15 (questions from data/slices/batch15.json)

TOPICS = {
    1740: "Cardiology",
    1741: "Neurology",
    1742: "Respiratory Medicine",
    1743: "Endocrinology",
    1744: "Obstetrics & Gynecology",
    1745: "Gastroenterology",
    1746: "Gastroenterology",
    1747: "Obstetrics & Gynecology",
    1751: "Hematology",
    1752: "Hematology",
    1754: "Obstetrics & Gynecology",
    1755: "Infectious Diseases",
    1760: "General Surgery",
    1763: "Medical Ethics & Communication",
    1769: "Gastroenterology",
    1773: "Obstetrics & Gynecology",
    1774: "General Surgery",
    1775: "Obstetrics & Gynecology",
    1776: "Pediatrics",
    1777: "Obstetrics & Gynecology",
    1778: "Obstetrics & Gynecology",
    1779: "Respiratory Medicine",
    1786: "Pediatrics",
    1787: "General Surgery",
    1788: "General Surgery",
    1790: "General Surgery",
    1792: "Gastroenterology",
    1808: "Emergency & Critical Care",
    1809: "Medical Ethics & Communication",
    1810: "Medical Ethics & Communication",
    1811: "General Surgery",
    1813: "General Surgery",
    1814: "Pediatrics",
    1815: "Medical Ethics & Communication",
    1816: "Pediatrics",
    1817: "Emergency & Critical Care",
    1818: "Hematology",
    1819: "Obstetrics & Gynecology",
    1820: "Obstetrics & Gynecology",
    1821: "Hematology",
    1822: "Gastroenterology",
    1823: "Gastroenterology",
    1824: "Gastroenterology",
    1825: "Gastroenterology",
    1827: "Gastroenterology",
    1829: "Gastroenterology",
    1830: "Gastroenterology",
    1832: "Cardiology",
    1833: "Medical Ethics & Communication",
    1834: "Urology",
    1835: "Emergency & Critical Care",
    1836: "Urology",
    1837: "Preventive & Community Medicine",
    1838: "Pediatrics",
    1839: "Oncology",
    1840: "Cardiology",
    1841: "Obstetrics & Gynecology",
    1843: "Emergency & Critical Care",
    1844: "Emergency & Critical Care",
    1852: "Cardiology",
    1853: "Neurology",
    1854: "Nephrology",
    1855: "Nephrology",
    1857: "Obstetrics & Gynecology",
    1858: "Obstetrics & Gynecology",
    1859: "Obstetrics & Gynecology",
    1860: "Obstetrics & Gynecology",
    1861: "Obstetrics & Gynecology",
    1862: "Obstetrics & Gynecology",
    1863: "Obstetrics & Gynecology",
    1864: "Obstetrics & Gynecology",
    1866: "Obstetrics & Gynecology",
    1867: "Obstetrics & Gynecology",
    1868: "Obstetrics & Gynecology",
    1869: "Obstetrics & Gynecology",
    1870: "Obstetrics & Gynecology",
    1872: "Obstetrics & Gynecology",
    1873: "Obstetrics & Gynecology",
    1874: "Obstetrics & Gynecology",
    1875: "Obstetrics & Gynecology",
    1876: "Obstetrics & Gynecology",
    1877: "Gastroenterology",
    1878: "Gastroenterology",
    1879: "Obstetrics & Gynecology",
    1881: "Obstetrics & Gynecology",
    1886: "Obstetrics & Gynecology",
    1887: "Obstetrics & Gynecology",
    1888: "Obstetrics & Gynecology",
    1889: "Obstetrics & Gynecology",
    1890: "Pediatrics",
    1891: "Obstetrics & Gynecology",
    1892: "Obstetrics & Gynecology",
    1893: "Obstetrics & Gynecology",
    1896: "Pediatrics",
    1897: "Respiratory Medicine",
    1898: "Medical Ethics & Communication",
    1899: "Medical Ethics & Communication",
    1900: "Medical Ethics & Communication",
    1901: "Medical Ethics & Communication",
    1902: "Medical Ethics & Communication",
}

EXPLANATIONS = {
1740: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "رجل عنده <bdi>DM</bdi> و<bdi>CKD</bdi> وأخذ <bdi>ACS</bdi> حديثًا، يعني خطره القلبي عالي جدًا، ولازم نشوف وش أهم دواء يضاف لملف الدهون عنده.",
    "clues": [
        ("recently admitted for acute coronary syndrome", "<bdi>patient</bdi> بفئة الخطر العالي جدًا، يحتاج هدف <bdi>LDL</bdi> صارم"),
        ("high LDL, low HDL", "صورة دهون غير مثالية تحتاج علاج دوائي مباشر مو بس تعديل نمط حياة"),
    ],
    "why_correct": [
        "أي <bdi>patient</bdi> بتاريخ <bdi>ACS</bdi> يعتبر خطر قلبي عالي جدًا، والعلاج الأساسي الأول هو <bdi>high-intensity statin</bdi> مثل <bdi>Atorvastatin</bdi> بغض النظر عن رقم <bdi>LDL</bdi> الحالي.",
        "الـ<bdi>statin</bdi> يقلل <bdi>LDL</bdi> ويرفع <bdi>HDL</bdi> شوي، وله فائدة إضافية بتقليل خطر الحوادث القلبية مستقبلًا بعد <bdi>ACS</bdi>.",
        "ترك المريض بدون علاج دوائي (الخيار D) خطأ واضح بوجود خطر قلبي كلوي عالي.",
    ],
    "when_changes": [
        "لو كان المريض يشتكي من ألم عضلي شديد أو ارتفاع إنزيمات الكبد بشكل كبير مع الـ<bdi>statin</bdi>، يصير التفكير بخيار ثاني مثل <bdi>Ezetimibe</bdi>.",
        "لو كان الـ<bdi>LDL</bdi> لسى مرتفع رغم أقصى جرعة <bdi>statin</bdi> متحملة، نضيف <bdi>Ezetimibe</bdi> أو <bdi>PCSK9 inhibitor</bdi> فوقه.",
    ],
    "rule": "أي <bdi>patient</bdi> بتاريخ <bdi>ACS</bdi> يُعتبر خطر قلبي عالي جدًا ويحتاج <bdi>high-intensity statin</bdi> فورًا كجزء من <bdi>secondary prevention</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1741: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "مسن عنده <bdi>DM</bdi> و<bdi>HTN</bdi> و<bdi>AF</bdi> (رجفان أذيني) دخل بسبب <bdi>TIA</bdi>، والسؤال يبي أهم علاج يمنع تكرار الجلطة الدماغية.",
    "clues": [
        ("AF", "مصدر جلطات قلبية كلاسيكي، أكبر عامل خطر هنا"),
        ("admitted for TIA", "حدث جلطي عابر فعليًا حصل، يحتاج وقاية ثانوية فورية"),
    ],
    "why_correct": [
        "<bdi>AF</bdi> يسبب تكوّن جلطات داخل الأذين الأيسر، وهذا هو المصدر الأكثر احتمالًا للـ<bdi>TIA</bdi> هنا.",
        "<bdi>Oral anticoagulant</bdi> (مثل <bdi>warfarin</bdi> أو <bdi>DOAC</bdi>) هو العلاج الأساسي لمنع تكرار الجلطة الدماغية عند مرضى <bdi>AF</bdi>.",
        "علاج السكري أو الضغط مهم بس هو علاج مزمن للعامل الخطر، مو العلاج المباشر لمنع تكرار الحدث الجلطي نفسه.",
    ],
    "when_changes": [
        "لو كان المريض عنده مخاطر نزيف عالية جدًا أو مانع من مضادات التخثر، يصير التفكير بإجراءات ثانية مثل إغلاق الأذين الأيسر.",
        "لو كان سبب الـ<bdi>TIA</bdi> تضيق شديد بالشريان السباتي، يصير التركيز على <bdi>carotid endarterectomy</bdi> بدل مضاد التخثر فقط.",
    ],
    "rule": "مريض <bdi>AF</bdi> بعد <bdi>TIA</bdi> يحتاج <bdi>oral anticoagulation</bdi> كوقاية ثانوية من الجلطة الدماغية.",
    "comparison": None,
    "guideline_note": None,
},
1742: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "شاب مدخن عنده <bdi>COPD</bdi> جديد التشخيص بس أعراضه خفيفة (سعال مزمن فقط) وعلاماته الحيوية طبيعية، فالخطوة الأهم هي إزالة سبب المرض نفسه.",
    "clues": [
        ("smoker", "السبب الرئيسي لتطور <bdi>COPD</bdi> ولاستمرار تدهوره"),
        ("normal vitals, only chronic cough", "مرض خفيف حاليًا، ما يحتاج علاج دوائي مكثف الآن"),
    ],
    "why_correct": [
        "<bdi>Smoking cessation</bdi> هي الخطوة الوحيدة المثبتة بتقليل سرعة تدهور وظيفة الرئة بـ<bdi>COPD</bdi>، وتُعتبر أساس العلاج بكل المراحل.",
        "بمرض خفيف بدون ضيق تنفس واضح، نبدأ بالإجراء الأهم (ترك التدخين) قبل أي علاج دوائي إضافي.",
        "<bdi>Steroid</bdi> أو موسعات الشعب تستخدم لتخفيف الأعراض أو بالتفاقم، مو كخطوة أولى بمرض خفيف جدًا.",
    ],
    "when_changes": [
        "لو كان عنده ضيق تنفس مع نشاط يومي، يصير الجواب الأقوى إضافة موسع شعب قصير المدى مثل <bdi>ipratropium</bdi> أو <bdi>SABA</bdi> فوق ترك التدخين.",
        "لو صار تفاقم حاد مع زيادة إفرازات، يحتاج <bdi>steroid</bdi> ومضاد حيوي حسب الحالة.",
    ],
    "rule": "أهم خطوة بأي مريض <bdi>COPD</bdi> مدخن هي <bdi>smoking cessation</bdi>، قبل أي علاج دوائي.",
    "comparison": None,
    "guideline_note": None,
},
1743: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "طفل بعمر 10 سنوات عنده كثرة تبول وعطش مع <bdi>C-peptide</bdi> منخفض جدًا (0.09)، وهذا يدل على نقص شديد بإفراز الإنسولين الذاتي وهو العلامة المميزة لـ<bdi>Type 1 DM</bdi>.",
    "clues": [
        ("polyuria/polydipsia", "أعراض كلاسيكية لارتفاع سكر الدم عند طفل"),
        ("C-peptide 0.09 (low)", "دليل مباشر على نقص إنتاج الإنسولين من البنكرياس نفسه، يميز <bdi>Type 1</bdi> عن <bdi>Type 2</bdi>"),
    ],
    "why_correct": [
        "<bdi>C-peptide</bdi> المنخفض جدًا يعني خلايا البنكرياس بيتا ما تنتج إنسولين كافي، وهذا نمط <bdi>Type 1 DM</bdi> المناعي الذاتي.",
        "بـ<bdi>Type 2 DM</bdi> أو <bdi>MODY</bdi>، الـ<bdi>C-peptide</bdi> يكون طبيعي أو مرتفع لأن البنكرياس لسى يفرز إنسولين (مشكلته مقاومة الإنسولين مو نقصه).",
        "عمر الطفل الصغير مع هذا النمط المخبري يدعم <bdi>Type 1 DM</bdi> أكثر من أي سبب ثاني.",
    ],
    "when_changes": [
        "لو كان الـ<bdi>C-peptide</bdi> طبيعي أو مرتفع مع سمنة وتاريخ عائلي قوي، يصير <bdi>Type 2 DM</bdi> هو الأقرب.",
        "لو كان فيه تاريخ عائلي واضح على أجيال متعددة مع فرط سكر خفيف بدون أجسام مضادة، يصير <bdi>MODY</bdi> أقرب تشخيص.",
    ],
    "rule": "<bdi>C-peptide</bdi> منخفض جدًا عند طفل بأعراض سكر جديدة يؤكد نقص إنسولين ذاتي يعني <bdi>Type 1 DM</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1744: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "حامل بتاريخ ولادتين مبكرتين (<bdi>preterm delivery</bdi>) وجاءت الآن بنزول نقط دم خفيف، والسؤال يبي الدواء المباشر يعطى بهذا السيناريو.",
    "clues": [
        ("history of 2 preterm delivery", "عامل خطر قوي يستدعي علاج وقائي للحمل الحالي"),
        ("vaginal spotting", "علامة تستدعي دعم هرموني لدعم استمرار الحمل"),
    ],
    "why_correct": [
        "<bdi>Progesterone</bdi> (مهبلي أو عضلي) هو العلاج الوقائي المثبت لتقليل خطر الولادة المبكرة المتكررة عند الحوامل بتاريخ ولادات مبكرة سابقة.",
        "النزول الخفيف للدم مع هذا التاريخ يدعم إعطاء <bdi>progesterone</bdi> لدعم استمرار الحمل وتقليل خطر الولادة المبكرة.",
        "<bdi>Estrogen</bdi> ليس له دور علاجي بهذا السيناريو، وممكن يرفع خطر الجلطات بالحمل.",
    ],
    "when_changes": [
        "لو كان النزيف شديد مع ألم بطن قوي يوجه لمشكلة ثانية مثل انفصال مشيمة، يصير التقييم العاجل بالمستشفى أهم من الدواء مباشرة.",
        "لو كانت عنق الرحم قصيرة جدًا بالسونار فوق العلاج الهرموني، يُضاف خيار <bdi>cervical cerclage</bdi>.",
    ],
    "rule": "الحامل بتاريخ ولادة مبكرة متكررة تستفيد من <bdi>progesterone</bdi> الوقائي لتقليل خطر تكرارها.",
    "comparison": None,
    "guideline_note": None,
},
1745: {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "مسن عنده ألم شرسوفي 3 أشهر مع نزول وزن ويرقان وبول غامق، مع توسع بالقناة الصفراوية داخل وخارج الكبد وصورة ركود صفراوي، وهذا نمط <bdi>double duct sign</bdi> الكلاسيكي.",
    "clues": [
        ("dilatation of intrahepatic and extrahepatic duct", "توسع مزدوج بالقناة يوجه لانسداد بمستوى رأس البنكرياس، <bdi>double duct sign</bdi>"),
        ("wt loss, jaundice and dark urine", "نمط كلاسيكي لورم خبيث بالبنكرياس أو القناة الصفراوية"),
    ],
    "why_correct": [
        "توسع القناة الصفراوية داخل وخارج الكبد معًا مع توسع القناة البنكرياسية غالبًا (<bdi>double duct sign</bdi>) من أقوى علامات <bdi>pancreatic cancer</bdi> برأس البنكرياس.",
        "نزول الوزن التدريجي مع الألم الشرسوفي المزمن (3 أشهر) يدعم ورم خبيث بطيء التطور أكثر من حصوة.",
        "ما فيه ذكر لألم مغصي حاد مفاجئ يوجه لحصوة، والصورة هنا أقرب لانسداد تدريجي خبيث.",
    ],
    "when_changes": [
        "لو كان الألم مغصي حاد ومفاجئ مع حمى وتاريخ حصوات مرارية، يصير <bdi>common bile duct stone</bdi> أو <bdi>Mirizzi's syndrome</bdi> أقرب.",
        "لو كان الانسداد بمستوى القناة الصفراوية فوق التقاء القناتين الكبديتين بدون توسع القناة البنكرياسية، يصير <bdi>Klatskin tumour</bdi> أقرب.",
    ],
    "rule": "توسع مزدوج بالقناة الصفراوية والبنكرياسية (<bdi>double duct sign</bdi>) عند مسن بنزول وزن ويرقان يوجه لـ<bdi>pancreatic cancer</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1746: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "منظار قولون عند رجل 42 سنة استُخرج منه <bdi>tubular adenoma</bdi> حجمه 1.3 سم، والسؤال يبي فترة المراقبة المناسبة حسب حجم الزوائد.",
    "clues": [
        ("1.3 cm colonic polyp", "حجم أكبر من 1 سم، يُصنف بين الزوائد عالية الخطورة"),
        ("tubular adenoma", "نوع زائدة غدية حميدة بس تحتاج مراقبة حسب الحجم والعدد"),
    ],
    "why_correct": [
        "أي <bdi>adenoma</bdi> حجمه 1 سم أو أكبر يُصنف ضمن الزوائد عالية الخطورة، وفترة المراقبة الموصى بها بعد إزالتها الكاملة هي 3 سنوات.",
        "لو كانت الزائدة أصغر من 1 سم وعددها 1-2 فقط، فترة المراقبة تطول لـ7-10 سنوات، وهذا غير الحال هنا.",
        "عدم الحاجة لمراقبة (الخيار C) يصح فقط بزوائد غير غدية (مثل <bdi>hyperplastic polyp</bdi> صغيرة بالقولون البعيد)، مو بهذا الحجم.",
    ],
    "when_changes": [
        "لو كان حجم الزائدة أقل من 1 سم وبدون خلل تنسج عالي، يصير الجواب الأقوى بعد 7-10 سنوات.",
        "لو كان فيه 3 زوائد أو أكثر أو خلل تنسج عالي الدرجة، يصير الجواب الأقوى بعد سنة واحدة فقط.",
    ],
    "rule": "<bdi>Tubular adenoma</bdi> بحجم 1 سم أو أكبر يحتاج متابعة بمنظار قولون بعد 3 سنوات.",
    "comparison": {
        "headers": ["نوع الزائدة", "فترة المتابعة"],
        "rows": [
            ["1-2 <bdi>adenoma</bdi> أصغر من 1 سم", "7-10 سنوات"],
            ["<bdi>adenoma</bdi> 1 سم أو أكبر / 3+ زوائد", "3 سنوات"],
            ["خلل تنسج عالي أو زوائد متعددة كبيرة", "سنة واحدة"],
        ],
    },
    "guideline_note": None,
},
1747: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "سؤال عن علاج <bdi>molar pregnancy</bdi>، والعلاج الأساسي المعتمد هو تفريغ الرحم بطريقة الشفط.",
    "clues": [
        ("Molar pregnancy", "حمل عنقودي غير طبيعي يحتاج تفريغ كامل للرحم"),
        ("asked about its management", "السؤال يبي خطوة العلاج الأساسية"),
    ],
    "why_correct": [
        "<bdi>Suction evacuation</bdi> (الشفط) هو العلاج القياسي لتفريغ <bdi>molar pregnancy</bdi> بأمان وفعالية عالية.",
        "هذي الطريقة تقلل خطر ثقب الرحم مقارنة بأدوات أخرى، وتسمح بإرسال النسيج للفحص النسيجي.",
        "بعد التفريغ يتابع مستوى <bdi>beta-hCG</bdi> دوريًا للتأكد من عدم تحوله لـ<bdi>gestational trophoblastic neoplasia</bdi>.",
    ],
    "when_changes": [
        "لو كان حجم الرحم كبير جدًا مع نزيف شديد مهدد للحياة، ممكن يحتاج تدخل جراحي أوسع مثل <bdi>hysterectomy</bdi> بحالات نادرة جدًا.",
        "لو ارتفع <bdi>beta-hCG</bdi> أو ثبت بعد التفريغ، يصير التفكير بـ<bdi>chemotherapy</bdi> لعلاج ورم <bdi>trophoblastic</bdi> مستمر.",
    ],
    "rule": "العلاج الأساسي لـ<bdi>molar pregnancy</bdi> هو تفريغ الرحم بالشفط (<bdi>suction evacuation</bdi>) مع متابعة <bdi>beta-hCG</bdi> بعدها.",
    "comparison": None,
    "guideline_note": None,
},
1751: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "مريض بجلطة وريدية عميقة بدون سبب واضح (<bdi>unprovoked DVT</bdi>) وبدون تاريخ عائلي، متحمل <bdi>warfarin</bdi> كويس بـ<bdi>INR</bdi> مثالي، والسؤال يبي مدة العلاج المناسبة.",
    "clues": [
        ("unprovoked deep vein thrombosis", "جلطة بدون سبب مؤقت، خطر تكرارها عالي بعد إيقاف العلاج"),
        ("tolerating it very well", "ما فيه مشكلة نزيف تمنع الاستمرار بمضاد التخثر"),
    ],
    "why_correct": [
        "الجلطة الوريدية غير المسببة (<bdi>unprovoked</bdi>) لها خطر تكرار عالي جدًا بعد إيقاف مضاد التخثر، أعلى بكثير من الجلطة المسببة بعامل مؤقت.",
        "مع تحمل جيد لـ<bdi>warfarin</bdi> وبدون خطر نزيف عالي، الإرشادات الحديثة تفضل الاستمرار بمضاد التخثر لفترة طويلة أو إلى ما لا نهاية.",
        "إيقاف العلاج بعد 3 أو 6 أشهر فقط (الخيارين A وB) يرفع خطر تكرار الجلطة بشكل كبير بهذي الفئة.",
    ],
    "when_changes": [
        "لو كانت الجلطة مرتبطة بعامل مؤقت واضح (جراحة، سفر طويل)، يكفي علاج 3 أشهر فقط ويوقف.",
        "لو كان عند المريض خطر نزيف عالي جدًا أو رفض شخصي للاستمرار، يصير وزن الفائدة والضرر لصالح إيقاف العلاج بعد فترة محددة.",
    ],
    "rule": "الجلطة الوريدية غير المسببة بدون خطر نزيف عالي تستدعي عادة الاستمرار بمضاد التخثر لفترة طويلة أو إلى ما لا نهاية لتقليل خطر التكرار.",
    "comparison": {
        "headers": ["نوع الجلطة", "مدة العلاج"],
        "rows": [
            ["مسببة بعامل مؤقت", "3 أشهر"],
            ["غير مسببة (<bdi>unprovoked</bdi>)", "طويلة المدى / إلى ما لا نهاية إذا تحمل جيد"],
        ],
    },
    "guideline_note": None,
},
1752: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "نفس سيناريو جلطة وريدية عميقة غير مسببة بدون تاريخ عائلي، مع ذكر موقع الجلطة إنه قريب (<bdi>proximal</bdi> أو <bdi>popliteal</bdi>)، وكلاهما يُصنف جلطة قريبة (<bdi>proximal DVT</bdi>) تحتاج علاج طويل المدى.",
    "clues": [
        ("unprovoked", "بدون سبب مؤقت، خطر تكرار عالي"),
        ("PROXIMAL or POPILITEAL", "الوريد المأبضي يُصنف ضمن الجلطات القريبة (<bdi>proximal DVT</bdi>) وليس البعيدة"),
    ],
    "why_correct": [
        "الوريد المأبضي (<bdi>popliteal</bdi>) يُحسب جلطة قريبة (<bdi>proximal</bdi>)، وهذا يرفع خطورتها وأهمية العلاج طويل المدى.",
        "مع كونها غير مسببة وبدون خطر نزيف وبتحمل جيد لـ<bdi>warfarin</bdi>، الجواب الأقوى الاستمرار بمضاد التخثر إلى ما لا نهاية.",
        "إيقاف العلاج الآن أو بعد 6 أشهر فقط يرفع خطر تكرار الجلطة بهذي الفئة عالية الخطورة.",
    ],
    "when_changes": [
        "لو كانت الجلطة بوريد بعيد صغير (أسفل الركبة) وبدون عوامل خطر إضافية، فترة علاج 3 أشهر قد تكفي.",
        "لو ظهر تاريخ عائلي قوي لتخثر وراثي، يصير فحص <bdi>thrombophilia</bdi> مفيد لتوجيه مدة العلاج.",
    ],
    "rule": "الجلطة الوريدية القريبة (<bdi>proximal</bdi> بما فيها <bdi>popliteal</bdi>) غير المسببة تستدعي مضاد تخثر طويل المدى عند عدم وجود خطر نزيف.",
    "comparison": None,
    "guideline_note": None,
},
1754: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "حامل أول مرة بنهاية الحمل (39 أسبوع) ضغطها ارتفع فجأة (160/90) بدون بروتين بالبول وبدون أعراض تحذيرية، وتحاليلها طبيعية، وهذا نمط <bdi>gestational hypertension</bdi> الكلاسيكي.",
    "clues": [
        ("Blood pressure 160/90", "ارتفاع ضغط جديد مقارنة بزياراتها السابقة (120/70)"),
        ("negative for protein", "غياب البروتين بالبول يستبعد <bdi>preeclampsia</bdi> حاليًا"),
        ("denied any headache, visual changes", "غياب أعراض الخطورة يدعم ضغط حمل بسيط بدون تسمم حمل"),
    ],
    "why_correct": [
        "ارتفاع ضغط جديد بعد 20 أسبوع حمل بدون بروتين بالبول وبدون أعراض تحذيرية يُسمى <bdi>gestational hypertension</bdi>.",
        "التحاليل الطبيعية (<bdi>platelets</bdi>، إنزيمات الكبد) تدعم غياب <bdi>preeclampsia</bdi> حاليًا.",
        "لا يوجد تاريخ ضغط مرتفع قبل الحمل أو قبل 20 أسبوع، فهذا يستبعد <bdi>chronic hypertension</bdi>.",
    ],
    "when_changes": [
        "لو ظهر بروتين بالبول أو انخفضت الصفائح أو ارتفعت إنزيمات الكبد، يصير التشخيص <bdi>preeclampsia</bdi>.",
        "لو كانت تعاني صداع أو اضطراب رؤية مع الضغط المرتفع، يرتفع الشك لـ<bdi>preeclampsia</bdi> حتى بدون بروتين.",
    ],
    "rule": "ارتفاع ضغط جديد بعد 20 أسبوع بدون بروتين بول أو أعراض تحذيرية يُسمى <bdi>gestational hypertension</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1755: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "طفل أصيب بـ<bdi>meningococcal meningitis</bdi>، وإخوانه بنفس البيت بدون أعراض، والسؤال يبي نظام الوقاية الدوائية (<bdi>chemoprophylaxis</bdi>) المناسب للمقربين.",
    "clues": [
        ("meningococcal meningitis", "عدوى شديدة العدوى تستدعي وقاية فورية للمقربين"),
        ("brother and sister... asymptomatic", "مقربون بدون أعراض يحتاجون وقاية دوائية مو علاج"),
    ],
    "why_correct": [
        "<bdi>Ciprofloxacin</bdi> بجرعة واحدة فعال وعملي جدًا كوقاية للمقربين البالغين والأطفال الأكبر، وسهل الإعطاء بدون متابعة متكررة.",
        "خيارات <bdi>rifampin</bdi> تحتاج جرعات متكررة لعدة أيام، بينما الجرعة الواحدة من <bdi>ciprofloxacin</bdi> تضمن الالتزام بسهولة أكبر.",
        "<bdi>Penicillin</bdi> لوحده غير فعال كوقاية لأنه لا يقضي على الحمل البلعومي للبكتيريا بفعالية كافية.",
    ],
    "when_changes": [
        "لو كان المقرب طفل رضيع صغير جدًا، يصير <bdi>rifampin</bdi> أو <bdi>ceftriaxone</bdi> بالحقن العضلي الخيار الأنسب بدل <bdi>ciprofloxacin</bdi>.",
        "لو كانت الحامل من المقربين، يُفضل <bdi>ceftriaxone</bdi> بالحقن العضلي بدل <bdi>ciprofloxacin</bdi> أو <bdi>rifampin</bdi>.",
    ],
    "rule": "وقاية المقربين من <bdi>meningococcal meningitis</bdi> غالبًا <bdi>ciprofloxacin</bdi> جرعة واحدة، أو <bdi>rifampin</bdi>/<bdi>ceftriaxone</bdi> حسب الفئة العمرية.",
    "comparison": None,
    "guideline_note": None,
},
1760: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "رجل عنده كتلة بطنية نابضة (<bdi>pulsatile abdominal mass</bdi>) مع دليل على تمزقها، وهذا <bdi>ruptured AAA</bdi> يهدد الحياة فورًا.",
    "clues": [
        ("pulsatile abdominal mass", "علامة كلاسيكية لتمدد الشريان الأبهر البطني (<bdi>AAA</bdi>)"),
        ("evidence of rupture", "حالة إسعافية قصوى تهدد الحياة مباشرة"),
    ],
    "why_correct": [
        "<bdi>Ruptured AAA</bdi> حالة إسعافية قصوى، والعلاج الوحيد القطعي (<bdi>definitive</bdi>) هو <bdi>surgery</bdi> عاجلة لإيقاف النزيف وإصلاح الشريان.",
        "أي تأخير بالجراحة يرفع خطر الوفاة بشكل كبير جدًا، فلا مجال للعلاج التحفظي هنا.",
        "الأدوية لتقليل النزيف (الخيار B) لا تعالج السبب الأساسي ولا توقف النزيف الشرياني الفعلي.",
    ],
    "when_changes": [
        "لو كان التمدد مكتشف قبل التمزق وبدون أعراض، يصير القرار بين المراقبة الدورية أو الإصلاح الاختياري حسب الحجم.",
        "لو كان المريض غير مستقر جدًا بالنقل، يحتاج إنعاش سريع بالسوائل والدم أثناء التحضير الفوري للجراحة بالتوازي.",
    ],
    "rule": "تمزق تمدد الشريان الأبهر البطني (<bdi>ruptured AAA</bdi>) علاجه القطعي الوحيد <bdi>surgery</bdi> عاجلة.",
    "comparison": None,
    "guideline_note": None,
},
1763: {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "مريضة حمل خارج الرحم تتألم، والطبيب مشغول طلب من الممرضة تعطي دواء بدون رؤية المريضة، والسؤال يبي أفضل تصرف من ناحية السلامة والأخلاق الطبية.",
    "clues": [
        ("the doctor but he was busy", "الطبيب لم يفحص المريضة بنفسه قبل إعطاء الأمر"),
        ("asked her to give medication", "وصفة دواء عن بعد بدون تقييم مباشر للحالة الحرجة"),
    ],
    "why_correct": [
        "حالة <bdi>ectopic pregnancy</bdi> بألم بطن قد تكون طارئة جدًا (احتمال تمزق)، ولا يصح إعطاء دواء بناءً على وصف هاتفي بدون فحص الطبيب للمريضة مباشرة.",
        "الطبيب يجب يحضر لتقييم المريضة بنفسه قبل اتخاذ أي قرار علاجي بحالة قد تكون إسعافية.",
        "موافقة ممرضة ثانية (الخيار A) لا تحل المشكلة الأساسية وهي غياب تقييم طبي مباشر للحالة.",
    ],
    "when_changes": [
        "لو كانت الحالة مستقرة تمامًا ومعروفة سابقًا بخطة علاجية واضحة موثقة، يصير الأمر الهاتفي المحدود مقبول أكثر.",
        "لو كان هناك تدهور حاد بعلامات الحياة، يصير التصرف الفوري هو تفعيل بروتوكول الطوارئ وطلب حضور الطبيب عاجلًا.",
    ],
    "rule": "لا يُعطى علاج لحالة إسعافية محتملة بناءً على وصف هاتفي بدون تقييم مباشر من الطبيب.",
    "comparison": None,
    "guideline_note": None,
},
1769: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "السؤال مختصر جدًا ومبتور (فقط كلمة <bdi>HBV</bdi>)، لكن غالبًا يسأل عن أفضل علاج أولي لالتهاب الكبد الفيروسي <bdi>B</bdi> المزمن بين خيارين دوائيين.",
    "clues": [
        ("HBV", "التهاب الكبد الفيروسي <bdi>B</bdi> المزمن، يحتاج علاج مثبط للفيروس"),
    ],
    "why_correct": [
        "<bdi>Entecavir</bdi> دواء فموي من مجموعة <bdi>nucleos(t)ide analogues</bdi>، وهو خط أول لعلاج <bdi>chronic HBV</bdi> عند أغلب المرضى لأمانه وفعاليته وسهولة الاستخدام.",
        "<bdi>Interferon</bdi> له أعراض جانبية أكثر ومدة علاج محددة، ويُحجز لحالات معينة أو رغبة المريض بمدة علاج محدودة.",
        "بسبب نقص تفاصيل السؤال (لا يوجد ذكر لتليف أو حمل أو مناعة)، الخيار الأعم والأكثر استخدامًا كخط أول هو <bdi>entecavir</bdi>.",
    ],
    "when_changes": [
        "لو كانت المريضة حامل أو تخطط للحمل قريبًا، يصير <bdi>tenofovir</bdi> الخيار المفضل بدل <bdi>entecavir</bdi>.",
        "لو كان المريض يرغب بمدة علاج محددة ومستوى فيروس منخفض بدون تليف، يصير <bdi>interferon</bdi> خيار معقول.",
    ],
    "rule": "علاج <bdi>chronic HBV</bdi> الخط الأول غالبًا <bdi>nucleos(t)ide analogue</bdi> مثل <bdi>entecavir</bdi> أو <bdi>tenofovir</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1773: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "امرأة عندها لولب (<bdi>IUD</bdi>) من 3 سنوات، اختبار حمل موجب، وألم بطن شديد مع تجمع سائل كبير جدًا (13×15 سم) بدون كيس حمل وبمبيضين طبيعيين، وهذا نمط <bdi>ruptured ectopic pregnancy</bdi> بنزيف داخل البطن كبير.",
    "clues": [
        ("positive", "حمل فعلي موجود رغم اللولب، يرفع شك الحمل خارج الرحم"),
        ("No identified gestational sac", "غياب كيس الحمل داخل الرحم يدعم حمل خارج الرحم"),
        ("Fluid collection of approximately 13 x 15 cm", "تجمع سائل ضخم جدًا يدل على نزيف داخل البطن بسبب تمزق"),
    ],
    "why_correct": [
        "وجود حمل خارج الرحم مع تجمع سائل ضخم بالبطن (مو بس كمية قليلة بالحوض) يدل على نزيف داخل البطن ناتج عن تمزق فعلي للحمل الهاجر.",
        "الألم الشديد المعمم مع الغثيان والتقيؤ يدعم حالة بطن حاد ناتج عن نزيف، مو حمل خارج رحم سليم (<bdi>intact</bdi>).",
        "المبيضان الطبيعيان يستبعدان تمزق كيس جسم أصفر كبير كسبب رئيسي لكل هذا السائل.",
    ],
    "when_changes": [
        "لو كان السائل محدود بالحوض فقط وعلامات الحياة مستقرة تمامًا، يصير <bdi>intact ectopic pregnancy</bdi> أقرب تشخيص.",
        "لو كان هناك كيس بالمبيض مع سائل محدود وبدون علامات صدمة، يصير <bdi>ruptured corpus luteum</bdi> أقرب.",
    ],
    "rule": "حمل إيجابي مع تجمع سائل ضخم بالبطن وغياب كيس حمل برحم يدل على <bdi>ruptured ectopic pregnancy</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1774: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "شاب عنده ألم بالحفرة الحرقفية اليمنى 7 أيام مع كتلة محسوسة وارتفاع كريات الدم البيضاء، والسونار يوضح كتلة زائدية مع تجمع صديد، وهذا نمط <bdi>appendiceal mass</bdi> المتأخر يُعالج أولًا بشكل تحفظي.",
    "clues": [
        ("pain for 7 days", "تأخر بالعرض يسمح بتكوّن كتلة التهابية محاطة مو التهاب حاد مبكر"),
        ("appendiceal mass with Collection", "كتلة مغلفة التهابية مع تجمع، مناسبة للعلاج التحفظي أو التصريف مو الجراحة الفورية"),
    ],
    "why_correct": [
        "بوجود كتلة زائدية متكونة بعد أيام من الألم، الجراحة الفورية تكون أصعب وأخطر بسبب الالتصاقات الشديدة حولها.",
        "العلاج التحفظي (<bdi>non interventional</bdi>: مضادات حيوية مع أو بدون تصريف بالسونار للتجمع) هو الخط الأول، ويُتبع لاحقًا باستئصال زائدة مؤجل (<bdi>interval appendectomy</bdi>) إذا احتاج.",
        "الجراحة الفورية (المفتوحة أو بالمنظار) ترفع خطر مضاعفات كبيرة بوجود كتلة ملتهبة محاطة بنسيج هش.",
    ],
    "when_changes": [
        "لو كان المريض غير مستقر أو عنده علامات التهاب صفاق منتشر، يصير التدخل الجراحي العاجل ضروري بغض النظر عن وجود الكتلة.",
        "لو فشل العلاج التحفظي أو تدهورت الحالة، يصير التصريف الجراحي أو الاستئصال الفوري مطلوب.",
    ],
    "rule": "كتلة زائدية متكونة مع تجمع صديد تُعالج أولًا بشكل تحفظي (مضادات حيوية ± تصريف)، والجراحة الفورية تُجنّب إن أمكن.",
    "comparison": None,
    "guideline_note": None,
},
1775: {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سؤال عن تمزق الأغشية المبكر قبل الولادة (<bdi>PPROM</bdi>) وأفضل بروتين يساعد بتأكيد التشخيص عند الشك السريري.",
    "clues": [
        ("PPROM", "تمزق مبكر بالأغشية قبل اكتمال الحمل، يحتاج تأكيد مخبري بالحالات غير الواضحة"),
        ("protein could help establish the diagnosis", "فحص كيميائي محدد يميز سائل أمنيوسي عن إفرازات أخرى"),
    ],
    "why_correct": [
        "<bdi>Placental alpha-1 microglobulin 1 (PAMG-1)</bdi> فحص حساس ونوعي جدًا لتأكيد وجود سائل أمنيوسي بالمهبل، ويُستخدم تجاريًا كفحص تشخيصي مباشر لـ<bdi>PPROM</bdi>.",
        "هذا الفحص يفيد خصوصًا عند الشك السريري بدون علامة واضحة بالفحص الإكلينيكي المباشر (مثل تجمع سائل واضح بالمهبل).",
        "باقي البروتينات المذكورة (<bdi>PP14</bdi>، <bdi>vasopressinase</bdi>، <bdi>growth factor</bdi>) ليست الفحوصات المعتمدة لتشخيص تمزق الأغشية.",
    ],
    "when_changes": [
        "لو كان هناك تجمع سائل واضح بالفحص المهبلي المباشر (<bdi>pooling</bdi>)، يكفي التشخيص السريري بدون الحاجة لفحص <bdi>PAMG-1</bdi>.",
        "لو كان الفحص غير متوفر، تُستخدم فحوصات أخرى مثل <bdi>fern test</bdi> أو <bdi>nitrazine test</bdi> كبديل أقل دقة.",
    ],
    "rule": "<bdi>PAMG-1</bdi> فحص حساس ونوعي يساعد بتأكيد تشخيص <bdi>PPROM</bdi> عند الشك السريري غير الواضح.",
    "comparison": None,
    "guideline_note": None,
},
1776: {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "رضيع عمره 11 شهر عنده كسر بعظمتي الساعد اليمنى، تأخر الأهل بجلبه يومين وقالوا ما شافوا كدمات، والسؤال يبي أفضل تصرف من ناحية حماية الطفل.",
    "clues": [
        ("didn't bring him earlier", "تأخر بطلب العلاج بدون سبب طبي واضح، علامة تحذيرية بإصابات الأطفال"),
        ("ulnar and radial fracture", "كسر بعظمتين طويلتين برضيع صغير جدًا، نادر الحدوث بإصابة بسيطة"),
    ],
    "why_correct": [
        "كسر بعظمتين طويلتين برضيع لا يمشي بعد مع تأخر غير مفهوم بطلب العلاج يستدعي دائمًا استبعاد إيذاء الطفل (<bdi>child abuse</bdi>) حتى لو كان الطفل يبدو بحالة جيدة عمومًا.",
        "الواجب القانوني والأخلاقي هو علاج الكسر فورًا مع تبليغ الجهات المختصة بالوقت نفسه للتحقيق بدون تهمة مباشرة للأهل.",
        "تصديق الأهل بدون أي تحرٍ إضافي (الخيار B) يعرض الطفل لخطر تكرار الإصابة لو كان هناك إيذاء حقيقي.",
    ],
    "when_changes": [
        "لو كانت القصة متوافقة تمامًا مع الإصابة ومع عمر الطفل القادر على الحركة والسقوط، يقل الشك بإيذاء الطفل.",
        "لو ظهرت علامات إضافية مثل كسور متعددة بأعمار مختلفة أو حروق غير مفسرة، يرتفع الشك لإيذاء الطفل بشكل كبير ويستدعي تصوير شامل.",
    ],
    "rule": "كسر غير مفسر بوضوح برضيع صغير مع تأخر بطلب العلاج يستدعي علاج الإصابة وتبليغ الجهات المختصة لحماية الطفل.",
    "comparison": None,
    "guideline_note": None,
},
1777: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "امرأة عندها ليف رحمي (<bdi>leiomyoma</bdi>) مع نزيف دوري غزير، وما تبي حمل قريب، والسؤال يبي أفضل خطوة علاجية تالية قبل التفكير بتدخل أكبر.",
    "clues": [
        ("heavy menstruation", "العرض الأساسي المطلوب علاجه هو النزيف الغزير"),
        ("doesn't want children soon", "ما تبي تحافظ على الخصوبة فورًا، بس ما طلبت إنهاء الخصوبة بشكل دائم"),
    ],
    "why_correct": [
        "بوجود نزيف غزير مرتبط بليف رحمي وبدون رغبة بحمل فوري، يُبدأ أولًا بعلاج دوائي محافظ مثل <bdi>oral contraceptive pills</bdi> لتقليل النزيف.",
        "هذا الخيار أقل تدخلًا من الجراحة أو <bdi>embolization</bdi>، ويحافظ على الخصوبة المستقبلية إذا احتاجتها لاحقًا.",
        "<bdi>Hysterectomy</bdi> خيار نهائي يُترك لحالات فشل العلاج المحافظ أو عدم رغبة بالخصوبة إطلاقًا، وهذا غير مذكور هنا.",
    ],
    "when_changes": [
        "لو فشل العلاج الدوائي بالتحكم بالنزيف مع رغبة بالحفاظ على الرحم والخصوبة، يصير <bdi>myomectomy</bdi> أو <bdi>uterine artery embolization</bdi> الخيار التالي.",
        "لو كانت لا ترغب بالخصوبة إطلاقًا مستقبلًا وفشل كل علاج محافظ، يصير <bdi>hysterectomy</bdi> الخيار النهائي.",
    ],
    "rule": "نزيف غزير بسبب ليف رحمي عند امرأة لا تريد حمل فوري يُعالج أولًا بخيار دوائي محافظ مثل <bdi>OCPs</bdi> قبل التدخل الجراحي.",
    "comparison": None,
    "guideline_note": None,
},
1778: {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "حامل بأسبوع 30 عندها ألم شديد بالخاصرة ينتشر للفخذ مع رعشة وبرد، والتحليل يوضح كثرة خلايا صديد بالبول، وهذا نمط <bdi>pyelonephritis</bdi> الكلاسيكي بالحمل.",
    "clues": [
        ("severe pain in the right flank radiating to her groin", "ألم خاصرة منتشر، نمط يوجه للكلى أو الحالب"),
        ("rigors and chills", "علامة عدوى جهازية شديدة"),
        ("Numerous pus cells", "دليل مباشر على عدوى بولية فعلية"),
    ],
    "why_correct": [
        "ألم الخاصرة المنتشر مع رعشة وحمى وكثرة صديد بالبول يؤكد عدوى كلوية صاعدة (<bdi>pyelonephritis</bdi>)، شائعة جدًا بالحمل بسبب توسع الحالب الهرموني.",
        "الحمل يزيد خطر الركود البولي وصعود العدوى من المثانة للكلى، خصوصًا بالثلث الثاني والثالث.",
        "<bdi>Appendicitis</bdi> أو <bdi>round ligament torsion</bdi> لا يفسران كثرة الصديد بالبول، وهذا يستبعدهما كتشخيص أساسي.",
    ],
    "when_changes": [
        "لو كان الألم بالحفرة الحرقفية اليمنى بدون صديد بالبول، يصير <bdi>appendicitis</bdi> أقرب تشخيص خصوصًا بالحمل.",
        "لو كان الألم خفيف متقطع مع الحركة بدون حمى أو صديد بالبول، يصير <bdi>round ligament torsion</bdi> أقرب.",
    ],
    "rule": "ألم خاصرة مع حمى ورعشة وصديد بالبول عند حامل يؤكد <bdi>acute pyelonephritis</bdi>.",
    "comparison": None,
    "guideline_note": None,
},
1779: {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "امرأة شابة تستخدم حبوب منع الحمل، جاءت بضيق نفس مفاجئ وألم صدر نفَسي، والفحص السريري طبيعي، والسؤال يبي الفحص الأفضل لتأكيد تشخيص <bdi>pulmonary embolism</bdi> المشتبه به.",
    "clues": [
        ("sudden onset of shortness of breath", "بداية مفاجئة توجه لحدث جلطي حاد مثل <bdi>PE</bdi>"),
        ("using oral contraceptives", "عامل خطر معروف لتكوّن الجلطات الوريدية"),
        ("pleuritic chest pain", "ألم صدر مرتبط بالتنفس، نمط كلاسيكي لـ<bdi>PE</bdi> محيطي"),
    ],
    "why_correct": [
        "<bdi>Chest CT angiography</bdi> هو الفحص التصويري المباشر الذي يحدد وجود الجلطة داخل الشرايين الرئوية، ويُعتبر الفحص القطعي لتأكيد <bdi>PE</bdi> بأغلب الحالات.",
        "استخدام حبوب منع الحمل مع بداية مفاجئة لضيق نفس وألم نفَسي يرفع احتمال <bdi>PE</bdi> بشكل كافٍ لتجاوز خطوة الفحوصات الأولية مباشرة للتصوير التأكيدي.",
        "<bdi>D-dimer</bdi> فحص استبعادي بالحالات منخفضة الاحتمال، مو فحص تأكيدي للتشخيص عند احتمال واضح كهذا.",
    ],
    "when_changes": [
        "لو كان احتمال <bdi>PE</bdi> منخفض سريريًا بمقاييس مثل <bdi>Wells score</bdi>، يُستخدم <bdi>D-dimer</bdi> أولًا لاستبعاد الحاجة للتصوير.",
        "لو كانت المريضة حامل أو عندها حساسية من الصبغة الوريدية، يصير <bdi>V/Q scan</bdi> الخيار البديل المناسب.",
    ],
    "rule": "عند احتمال سريري واضح لـ<bdi>PE</bdi>، <bdi>CT pulmonary angiography</bdi> هو الفحص الأنسب لتأكيد التشخيص مباشرة.",
    "comparison": None,
    "guideline_note": None,
},
}

WHY_WRONG = {}

HIGHLIGHT_TERMS = {}
