"""Replace Arabic medical terms (diseases, signs, tests, procedures) with English {{terms}} in alh_out/*.json."""
import json, glob, re, sys

G = """
التهاب البربخ والخصية=epididymo-orchitis
التهاب البربخ=epididymitis
التواء الزائدة الخصوية=torsion of testicular appendage
التواء الزائدة=torsion of testicular appendage
التواء الخصية=testicular torsion
خصية معلقة=undescended testis
خصيات معلقة=undescended testes
خصية منسحبة=retractile testis
خصية منتبذة=ectopic testis
تثبيت الخصيتين=bilateral orchidopexy
تثبيت الخصية=orchidopexy
وذمة الصفن مجهولة السبب=idiopathic scrotal oedema
منعكس الخصية=cremasteric reflex
فتق أربي محتبس=incarcerated inguinal hernia
فتق إربي محتبس=incarcerated inguinal hernia
فتق أربي غير مباشر=indirect inguinal hernia
فتق أربي=inguinal hernia
فتق إربي=inguinal hernia
فتق محتبس=incarcerated hernia
فتق مختنق=strangulated hernia
فتق داخلي=internal hernia
الإحليل التحتي=hypospadias
إحليل تحتي=hypospadias
استئصال الزايدة=appendectomy
كتلة الزايدة=appendiceal mass
خراج الزايدة=appendiceal abscess
التهاب الزايدة=appendicitis
زايدة مثقوبة=perforated appendicitis
الزايدة طبيعية=appendix طبيعية
قاعدة الزايدة=base of appendix
طرف الزايدة=tip of appendix
رأس الزايدة=tip of appendix
زايدة=appendicitis
انسداد الأمعاء الدقيقة=small bowel obstruction
انسداد أمعاء=bowel obstruction
انسداد الأمعاء=bowel obstruction
انسداد التصاقات=adhesive bowel obstruction
انسداد حاد=acute bowel obstruction
انسداد كاذب=pseudo-obstruction
شلل الأمعاء=paralytic ileus
شلل أمعاء=paralytic ileus
التصاقات=adhesions
نقص تروية الأمعاء=mesenteric ischemia
جلطة بشريان الأمعاء=mesenteric embolism
جلطة شريان الأمعاء=mesenteric embolism
نقص التروية=ischemia
نقص تروية=ischemia
التهاب بريتوني منتشر=generalized peritonitis
التهاب بريتوني موضعي=localized peritonitis
التهاب بريتوني=peritonitis
ألم ارتدادي=rebound tenderness
ألم أشد من الفحص=pain out of proportion
ألم أكثر من الفحص=pain out of proportion
هوا تحت الحجاب=air under diaphragm
مستويات هوا وسوائل=air-fluid levels
هوا بالقنوات المرارية=pneumobilia
انسداد الأمعاء بحصوة مرارية=gallstone ileus
التهاب بنكرياس مراري=gallstone pancreatitis
التهاب بنكرياس حاد=acute pancreatitis
التهاب البنكرياس الحاد=acute pancreatitis
التهاب بنكرياس=pancreatitis
التهاب البنكرياس=pancreatitis
كيس كاذب=pseudocyst
تجمع سوائل بنكرياسي=pancreatic fluid collection
التهاب مرارة بدون حصوات=acalculous cholecystitis
التهاب مرارة حاد=acute cholecystitis
التهاب مرارة=cholecystitis
التهاب المرارة=cholecystitis
التهاب القنوات المرارية=cholangitis
التهاب قنوات=cholangitis
التهاب القنوات=cholangitis
مغص مراري=biliary colic
حصوات مرارة=gallstones
حصوات المرارة=gallstones
حصوة بالقناة المرارية=choledocholithiasis
حصوة بالقناة=choledocholithiasis
حصوات بالقنوات=choledocholithiasis
حصوات القناة=choledocholithiasis
مرارة خزفية=porcelain gallbladder
سليلة المرارة=gallbladder polyp
سليلة بالمرارة=gallbladder polyp
سرطان المرارة=gallbladder cancer
تجمع صفراوي=biloma
تجمع صفراء=biloma
تسريب صفراء=bile leak
استئصال المرارة=cholecystectomy
خراج أميبي=amebic liver abscess
خراج صديدي=pyogenic liver abscess
خراج تحت الحجاب=subphrenic abscess
كيس عداري=hydatid cyst
ورم وعائي=hemangioma
ورم غدي=adenoma
يرقان انسدادي=obstructive jaundice
يرقان=jaundice
تليف الكبد=cirrhosis
تليف كبدي=cirrhosis
نزيف هضمي علوي=upper GI bleeding
نزيف هضمي سفلي=lower GI bleeding
نزيف الجهاز الهضمي=GI bleeding
نزيف هضمي=GI bleeding
دوالي المريء=esophageal varices
رتج=diverticulum
رتوج=diverticula
التهاب الرتوج=diverticulitis
التهاب رتوج=diverticulitis
شق شرجي=anal fissure
بواسير=hemorrhoids
ناسور=fistula
قرحة هضمية=peptic ulcer
قرحة مثقوبة=perforated ulcer
قرحة الاثني عشر=duodenal ulcer
قرحة المعدة=gastric ulcer
ارتجاع=reflux
تضيق البواب=pyloric stenosis
رتق الاثني عشر=duodenal atresia
التواء الأمعاء=midgut volvulus
التواء السيني=sigmoid volvulus
انغلاف=intussusception
التواء=torsion
استفراغ أخضر=bilious vomiting
استفراغ مندفع=projectile vomiting
عقي=meconium
إمساك وظيفي=functional constipation
انحشار البراز=fecal impaction
انحشار براز=fecal impaction
تسريب براز=soiling
متلازمة القولون الأيسر الصغير=small left colon syndrome
التهاب الأمعاء الناخر=necrotizing enterocolitis
المغص الرضيعي=infantile colic
مغص رضيعي=infantile colic
التبول اللاإرادي=enuresis
تبول لا إرادي=enuresis
التبول الليلي=nocturnal enuresis
تبول ليلي=nocturnal enuresis
إنذار التبول=enuresis alarm
التهاب المسالك البولية=UTI
التهاب مسالك=UTI
التهاب المسالك=UTI
ارتجاع بولي=vesicoureteral reflux
غمازة عجزية=sacral dimple
حبل شوكي مربوط=tethered cord
السكري الكاذب=diabetes insipidus
سكري كاذب=diabetes insipidus
عطش نفسي=psychogenic polydipsia
حرمان الماء=water deprivation test
حول متقارب=esotropia
حول كاذب=pseudostrabismus
الحول=strabismus
حول ثابت=constant strabismus
حول متقطع=intermittent strabismus
حول مفاجئ=sudden strabismus
حول جديد=new-onset strabismus
حول حقيقي=true strabismus
الانعكاس الأحمر=red reflex
انعكاس أحمر=red reflex
انعكاس أبيض=leukocoria
الانعكاس القرني=corneal light reflex
انعكاس القرنية=corneal light reflex
انعكاس الضوء على القرنية=corneal light reflex
اختبار التغطية=cover test
كسل العين=amblyopia
كسل عين=amblyopia
ورم الشبكية=retinoblastoma
ورم شبكية=retinoblastoma
الساد الخلقي=congenital cataract
ساد خلقي=congenital cataract
قصر النظر=myopia
قصر نظر=myopia
طول النظر=hypermetropia
طول نظر=hypermetropia
عدسة مقعرة=concave lens
عدسة محدبة=convex lens
خدش القرنية=corneal abrasion
خدش=corneal abrasion
قرحة القرنية=corneal ulcer
نزيف تحت الملتحمة=subconjunctival hemorrhage
التهاب الملتحمة=conjunctivitis
التهاب ملتحمة=conjunctivitis
التهاب فوق الصلبة=episcleritis
التهاب الصلبة=scleritis
التهاب القزحية=iritis
إصابة مفتوحة للكرة=open globe injury
إصابة مفتوحة=open globe injury
جسم غريب داخل العين=intraocular foreign body
شلل العصب السادس=sixth nerve palsy
كيس القناة الدرقية اللسانية=thyroglossal cyst
كيس ليمفاوي=cystic hygroma
كيس خيشومي=branchial cyst
عقدة درقية=thyroid nodule
عقد درقية=thyroid nodules
عقدة سامة=toxic nodule
عقدة حارة=hot nodule
عقدة باردة=cold nodule
تضخم عقدي سام=toxic multinodular goiter
فرط جار الدرقية الأولي=primary hyperparathyroidism
فرط جار الدرقية=hyperparathyroidism
ورم غدي بالجار درقية=parathyroid adenoma
استئصال الجار درقية=parathyroidectomy
الجار درقية=parathyroid
فرط الدرقية=hyperthyroidism
فرط درقية=hyperthyroidism
قصور الدرقية=hypothyroidism
قصور درقية=hypothyroidism
قصور أولي=primary hypothyroidism
قصور مركزي=central hypothyroidism
استئصال الغدة كاملة=total thyroidectomy
استئصال الدرقية كاملة=total thyroidectomy
استئصال الدرقية=thyroidectomy
استئصال نصف الغدة=hemithyroidectomy
استئصال الفص=lobectomy
سرطان حليمي=papillary thyroid cancer
سرطان الدرقية النخاعي=medullary thyroid cancer
نقص الكالسيوم=hypocalcemia
نقص كالسيوم=hypocalcemia
فرط الكالسيوم=hypercalcemia
فرط كالسيوم=hypercalcemia
أزمة كالسيوم=hypercalcemic crisis
نقص المغنيسيوم=hypomagnesemia
نقص البوتاسيوم=hypokalemia
العصب الحنجري الراجع=recurrent laryngeal nerve
ورم دموي=hematoma
جحوظ=exophthalmos
سرطان الثدي=breast cancer
التهاب الثدي=mastitis
خراج الثدي=breast abscess
خراج بالثدي=breast abscess
نخر الدهون=fat necrosis
توسع القنوات=duct ectasia
ورم حليمي داخل القناة=intraductal papilloma
الورم الحليمي=intraductal papilloma
ورم فيلودي=phyllodes tumor
التغيرات الكيسية الليفية=fibrocystic changes
تغيرات كيسية ليفية=fibrocystic changes
تضخم الثدي عند الرجال=gynecomastia
تضخم ثدي=gynecomastia
إفرازات دموية=bloody nipple discharge
استئصال الثدي=mastectomy
استئصال موضعي واسع=wide local excision
شامات=nevi
التهاب النسيج الخلوي=cellulitis
التهاب نسيج خلوي=cellulitis
التهاب لفافة ناخر=necrotizing fasciitis
الالتهاب الناخر=necrotizing fasciitis
التهاب ناخر=necrotizing fasciitis
التهاب العظم=osteomyelitis
التهاب موضع الجراحة=surgical site infection
التهاب الجرح=wound infection
التهاب جرح=wound infection
غرغرينا غازية=gas gangrene
غرغرينا=gangrene
القرحة العصبية=neuropathic ulcer
قرحة عصبية=neuropathic ulcer
القرحة الشريانية=arterial ulcer
قرحة شريانية=arterial ulcer
القرحة الوريدية=venous ulcer
قرحة وريدية=venous ulcer
قرحة سكرية=diabetic foot ulcer
الاعتلال العصبي=neuropathy
اعتلال عصبي=neuropathy
العرج المتقطع=intermittent claudication
عرج متقطع=intermittent claudication
ألم الراحة=rest pain
مرض الشرايين الطرفية=peripheral arterial disease
تصلب الشرايين=atherosclerosis
نقص تروية حاد=acute limb ischemia
تضيق بالشريان السباتي=carotid stenosis
تضيق سباتي=carotid stenosis
استئصال بطانة الشريان=carotid endarterectomy
نوبة نقص تروية عابرة=TIA
نوبات نقص تروية عابرة=recurrent TIAs
نوبة عابرة=TIA
تسلخ الأبهر=aortic dissection
تمدد بالأبهر البطني=abdominal aortic aneurysm
تمدد الأبهر البطني=abdominal aortic aneurysm
تمزق الأبهر=aortic rupture
إصابة الأبهر=aortic injury
توسع المنصف=widened mediastinum
انضغاط القلب=cardiac tamponade
الاسترواح الضاغط=tension pneumothorax
استرواح ضاغط=tension pneumothorax
استرواح صدري=pneumothorax
الاسترواح=pneumothorax
نزيف بالصدر=hemothorax
نزيف كبير بالصدر=massive hemothorax
جلطة رئوية=pulmonary embolism
جلطة قلبية=myocardial infarction
جلطة دماغية=stroke
جلطة وريدية=DVT
رجفان أذيني=atrial fibrillation
فشل القلب=heart failure
فشل قلب=heart failure
وذمة رئوية=pulmonary edema
التهاب رئوي=pneumonia
انخماص رئة=atelectasis
انخماص=atelectasis
صمة دهنية=fat embolism
الصدمة العصبية=neurogenic shock
صدمة عصبية=neurogenic shock
الصدمة القلبية=cardiogenic shock
صدمة قلبية=cardiogenic shock
الصدمة الانسدادية=obstructive shock
صدمة انسدادية=obstructive shock
الصدمة الالتهابية=septic shock
صدمة التهابية=septic shock
الصدمة النزفية=hemorrhagic shock
صدمة نزفية=hemorrhagic shock
صدمة نقص الحجم=hypovolemic shock
الصدمة التوزيعية=distributive shock
هبوط ضغط=hypotension
هبوط الضغط=hypotension
تسارع النبض=tachycardia
تسارع نبض=tachycardia
بطء النبض=bradycardia
بطء نبض=bradycardia
متلازمة إعادة التغذية=refeeding syndrome
متلازمة الحيز البطني=abdominal compartment syndrome
متلازمة الحيز=compartment syndrome
نزيف تحت الجافية=subdural hematoma
نزيف فوق الجافية=epidural hematoma
خراج فوق الجافية بالعمود=spinal epidural abscess
انضغاط الحبل الشوكي=spinal cord compression
انضغاط حبل شوكي=spinal cord compression
إصابة حبل شوكي=spinal cord injury
علامات تموضع=lateralizing signs
علامة تموضع=lateralizing sign
انزياح بالخط الأوسط=midline shift
ارتفاع ضغط الدماغ=raised ICP
ارتفاع ضغط داخل الجمجمة=raised ICP
التصلب المتعدد=multiple sclerosis
كسر مفتوح=open fracture
الفترة الواعية=lucid interval
فترة واعية=lucid interval
سرطان خلايا حرشفية=squamous cell carcinoma
سرطان القولون=colorectal cancer
سرطان المعدة=gastric cancer
سرطان المريء=esophageal cancer
سرطان بروستاتا=prostate cancer
سرطان الأمبولة=ampullary cancer
ورم خبيث بالأطراف=limb sarcoma
أورام الأنسجة الرخوة=soft tissue sarcoma
الأشعة العادية=plain X-ray
أشعة عادية=plain X-ray
أشعة البطن=abdominal X-ray
أشعة الصدر=chest X-ray
منظار القولون=colonoscopy
منظار السيني=sigmoidoscopy
المنظار العلوي=upper GI endoscopy
منظار المعدة=upper GI endoscopy
منظار علوي=upper GI endoscopy
منظار الحنجرة=laryngoscopy
منظار القصبة=bronchoscopy
منظار بطني تشخيصي=diagnostic laparoscopy
المنظار البطني التشخيصي=diagnostic laparoscopy
المنظار التشخيصي=diagnostic laparoscopy
دراسة الصبغة العلوية=upper GI contrast study
دراسة صبغة علوية=upper GI contrast study
حقنة الباريوم=barium enema
حقنة باريوم=barium enema
حقنة شرجية بالهوا=air enema reduction
بلع الباريوم=barium swallow
خزعة المستقيم=rectal biopsy
خزعة استئصالية=excisional biopsy
خزعة=biopsy
تحليل البول=urinalysis
تحليل بول=urinalysis
مزرعة البول=urine culture
مزرعة الدم=blood culture
صورة الدم=CBC
غازات الدم=ABG
تخطيط القلب=ECG
فحص وظائف الرئة=pulmonary function tests
وظائف الرئة=pulmonary function tests
وظائف الكبد=LFTs
وظائف الغدة=thyroid function tests
قياس الضغط الشرجي=anorectal manometry
الفحص الشرجي=digital rectal examination
فحص شرجي=digital rectal examination
فتح البطن الاستكشافي=exploratory laparotomy
فتح البطن=laparotomy
فتح الجمجمة=craniotomy
شق اللفافة=fasciotomy
التنظيف الجراحي=surgical debridement
تنظيف جراحي=surgical debridement
الشق والتصريف=incision and drainage
شق وتصريف=incision and drainage
التصريف عن طريق الجلد=percutaneous drainage
تصريف عن طريق الجلد=percutaneous drainage
التصريف الداخلي=internal drainage
تصريف داخلي=internal drainage
التصريف الخارجي=external drainage
تصريف خارجي=external drainage
الشفط بالإبرة=needle aspiration
شفط بالإبرة=needle aspiration
إعادة التنبيب=reintubation
التنبيب=intubation
تنبيب=intubation
فتحة القصبة=tracheostomy
فتحة بالقصبة=tracheostomy
نقل الدم=blood transfusion
نقل دم=blood transfusion
السوائل الوريدية=IV fluids
سوائل وريدية=IV fluids
المضاد الوريدي=IV antibiotics
مضاد وريدي=IV antibiotics
المضاد الحيوي=antibiotics
مضاد حيوي=antibiotics
مضاد تجريبي=empirical antibiotics
رافع الضغط=vasopressor
رافع ضغط=vasopressor
مقوي قلب=inotrope
الأكسجين عالي الضغط=hyperbaric oxygen
جهاز الضغط السلبي=negative pressure wound therapy
التغذية الوريدية=TPN
أنبوب الأنف=NG tube
أنبوب التصريف=cholecystostomy tube
عملية تحويل مسار=gastric bypass
تحويل مسار المعدة=gastric bypass
تكميم المعدة=sleeve gastrectomy
تكميم معدة=sleeve gastrectomy
فتق=hernia
فتوق=hernias
خراج=abscess
خراجات=abscesses
كسر=fracture
كسور=fractures
قرحة=ulcer
قرح=ulcers
انسداد=obstruction
صدمة=shock
نزيف=bleeding
نزف=bleeding
أنيميا=anemia
فقر دم=anemia
فقر الدم=anemia
مجرى الهواء=airway
المجرى الهوائي=airway
حصوة=stone
حصوات=stones
سرطان=cancer
ورم=tumor
أورام=tumors
نخر=necrosis
وذمة=edema
التهاب الكبد=hepatitis
التهاب كبد=hepatitis
"""
PAIRS = [l.split("=", 1) for l in G.strip().splitlines() if "=" in l]
PAIRS.sort(key=lambda p: -len(p[0]))
AR = "\u0621-\u064A\u0671-\u06D3"

def build(ar):
    words = ar.split(" ")
    body = " ".join(("(?:ال)?" if i else "") + re.escape(w) for i, w in enumerate(words))
    return re.compile(rf"(?<![{AR}])(?P<p>[وف]?[بلك]?)(?P<a>ال|ل(?=ل))?{body}(?![{AR}])")
RX = [(build(a), e.strip()) for a, e in PAIRS]

def repl_text(s):
        # keep existing {{...}} untouched
    parts = re.split(r"(\{\{.*?\}\})", s)
    for i in range(0, len(parts), 2):
        t = parts[i]
        for rx, en in RX:
            def r(m):
                p, a = m.group("p"), m.group("a")
                e = en
                tail = ""
                if " طبيعية" in e:  # special: 'appendix طبيعية'
                    e, tail = e.split(" ", 1); tail = " " + tail
                if a == "ال": return f"{p}الـ{{{{{e}}}}}{tail}"
                if a == "ل": return f"{p}للـ{{{{{e}}}}}{tail}"
                if p.endswith(("ب", "ل", "ك")): return f"{p}ـ{{{{{e}}}}}{tail}"
                return f"{p}{{{{{e}}}}}{tail}"
            t = rx.sub(r, t)
        parts[i] = t
    out = "".join(parts)
    out = re.sub(r"\}\}\s*\{\{", " ", out) if False else out
    return out

def walk(x):
    if isinstance(x, str): return repl_text(x)
    if isinstance(x, list): return [walk(i) for i in x]
    if isinstance(x, dict): return {k: walk(v) for k, v in x.items()}
    return x

if __name__ == "__main__":
    n = 0
    for f in sorted(glob.glob("alh_out/*.json")):
        d = json.load(open(f)); new = walk(d)
        if new != d:
            n += 1
            json.dump(new, open(f, "w"), ensure_ascii=False, indent=1)
    print("files changed", n)
