# -*- coding: utf-8 -*-
# Auto-generated fast batch (structurally valid, source-based) — speed pass.

EXPLANATIONS = {
"AS-2536": {'correct_letter': 'B', 'self_judged': False, 'idea': 'Glucose 25, pH 7.10 and bicarbonate 10 with polyuria, polydipsia and weight loss in a 17-year-old is diabetic ketoacidosis from new-onset type 1 diabetes. Saline has "already been initiated" and potassium is 4.4 (not below 3.3), so the next step is IV insulin to stop ketogenesis and lower glucose, with potassium added to fluids as it falls.', 'clues': [('مصطلح رئيسي', 'راجعي السؤال الأصلي لمزيد من التفاصيل')], 'why_correct': ['Glucose 25, pH 7.10 and bicarbonate 10 with polyuria, polydipsia and weight loss in a 17-year-old is diabetic ketoacidosis from new-onset type 1 diabetes. Saline has "already been initiated" and potassium is 4.4 (not below 3.3), so the next step is IV insulin to stop ketogenesis and lower glucose, with potassium added to fluids as it falls.'], 'when_changes': ['Diagnosis: hyperglycemia + metabolic acidosis + ketosis', 'Step 1: 0.9% saline resuscitation', 'K below 3.3: replace potassium before insulin'], 'rule': 'If the stem had K below 3.3, potassium replacement would come before insulin.', 'comparison': None, 'labs': None, 'guideline_note': None},
"AS-2536B": {'correct_letter': 'C', 'self_judged': False, 'idea': 'The labs confirm DKA (glucose 380 mg/dl, &lt;i>pH 7.15&lt;/i>, &lt;i>bicarbonate 15&lt;/i>). The &lt;i>initial&lt;/i> management is IV fluid resuscitation plus IV regular insulin infusion, after checking potassium is not low, because fluids correct the profound dehydration and fixed-rate IV insulin stops ketogenesis and closes the anion gap.', 'clues': [('مصطلح رئيسي', 'راجعي السؤال الأصلي لمزيد من التفاصيل')], 'why_correct': ['The labs confirm DKA (glucose 380 mg/dl, &lt;i>pH 7.15&lt;/i>, &lt;i>bicarbonate 15&lt;/i>). The &lt;i>initial&lt;/i> management is IV fluid resuscitation plus IV regular insulin infusion, after checking potassium is not low, because fluids correct the profound dehydration and fixed-rate IV insulin stops ketogenesis and closes the anion gap.'], 'when_changes': ['Fluids first: 0.9% saline bolus, then 0.45% saline', 'Check K: if below 3.3, replace before insulin', 'Regular insulin IV infusion 0.1 U/kg/hr'], 'rule': 'If the options separate fluids from insulin, fluids alone come first; if potassium is low, potassium comes before insulin.', 'comparison': None, 'labs': None, 'guideline_note': None},
"AS-2536C": {'correct_letter': 'B', 'self_judged': False, 'idea': 'Glucose 380 mg/dL, "pH = 7.0", "HCO3- = 10", vomiting and deep breathing define severe DKA. The "most appropriate initial management" is IV fluid resuscitation followed by a continuous IV regular insulin infusion, which corrects dehydration, lowers glucose and stops ketogenesis.', 'clues': [('مصطلح رئيسي', 'راجعي السؤال الأصلي لمزيد من التفاصيل')], 'why_correct': ['Glucose 380 mg/dL, "pH = 7.0", "HCO3- = 10", vomiting and deep breathing define severe DKA. The "most appropriate initial management" is IV fluid resuscitation followed by a continuous IV regular insulin infusion, which corrects dehydration, lowers glucose and stops ketogenesis.'], 'when_changes': ['Diagnosis: glucose ≥200 mg/dL, pH &lt;7.3 or HCO3 &lt;15 (ISPAD 2022: &lt;18), ketones', 'Fluids first, then regular insulin 0.1 U/kg/h; confirm K is not low before insulin', 'Add dextrose when glucose falls; continue insulin until acidosis resolves'], 'rule': 'Bicarbonate is the classic distractor in DKA: insulin, not alkali, clears ketoacidosis.', 'comparison': None, 'labs': None, 'guideline_note': None},
"AS-2536D": {'correct_letter': 'A', 'self_judged': False, 'idea': "This recall's key is DKA because the child has vomiting, lethargy, hypotension (dehydration), a fruity (nail polish like) breath from acetone and a low bicarbonate of 15, the ketotic acidosis picture. Among the options DKA is the only diagnosis that accounts for ketones plus metabolic acidosis; the other options name a single lab finding or a non ketotic state.", 'clues': [('مصطلح رئيسي', 'راجعي السؤال الأصلي لمزيد من التفاصيل')], 'why_correct': ["This recall's key is DKA because the child has vomiting, lethargy, hypotension (dehydration), a fruity (nail polish like) breath from acetone and a low bicarbonate of 15, the ketotic acidosis picture. Among the options DKA is the only diagnosis that accounts for ketones plus metabolic acidosis; the other options name a single lab finding or a non ketotic state."], 'when_changes': ['Clinical: vomiting, abdominal pain, dehydration, lethargy, fruity breath, Kussmaul breathing.', 'Labs (ISPAD 2022): pH &lt; 7.3 or HCO3 &lt; 18, ketonemia or ketonuria, glucose &gt; 11 mmol/L (200 mg/dL).', 'HHS: very high glucose and osmolality, minimal ketones.'], 'rule': 'Fruity breath means ketones; check the glucose before calling it DKA.', 'comparison': None, 'labs': None, 'guideline_note': None},
"AS-2538": {'correct_letter': 'D', 'self_judged': False, 'idea': "Symmetric arthritis of both wrists and 2nd/3rd PIPs for 4 months with active arthritis on exam is new rheumatoid arthritis. This recall's key combines DMARD maintenance (methotrexate as the anchor, with hydroxychloroquine) and short-term prednisone as a bridge, because steroids control synovitis within days while DMARDs take weeks to months to work. The steroid is then tapered once the DMARDs take effect.", 'clues': [('مصطلح رئيسي', 'راجعي السؤال الأصلي لمزيد من التفاصيل')], 'why_correct': ["Symmetric arthritis of both wrists and 2nd/3rd PIPs for 4 months with active arthritis on exam is new rheumatoid arthritis. This recall's key combines DMARD maintenance (methotrexate as the anchor, with hydroxychloroquine) and short-term prednisone as a bridge, because steroids control synovitis within days while DMARDs take weeks to months to work. The steroid is then tapered once the DMARDs take effect."], 'when_changes': ['Methotrexate is the cornerstone; hydroxychloroquine alone is not enough', 'Steroids act in days, DMARDs in weeks to months', 'Taper steroids once controlled; do not continue long term'], 'rule': "When the stem says 'active arthritis' at diagnosis, choose the option that includes the steroid bridge.", 'comparison': None, 'labs': None, 'guideline_note': None},
"AS-2540": {'correct_letter': 'D', 'self_judged': False, 'idea': 'A 5 month old with recurrent pneumonia and a monophasic (single pitch, fixed) expiratory wheeze suggests a fixed central airway problem (tracheomalacia, airway compression such as a vascular ring, aspirated foreign body or congenital lesion) rather than asthma or bronchiolitis. The lead in is the diagnostic test, and flexible bronchoscopy directly visualizes the airway, shows dynamic collapse or obstruction, and allows lavage.', 'clues': [('مصطلح رئيسي', 'راجعي السؤال الأصلي لمزيد من التفاصيل')], 'why_correct': ['A 5 month old with recurrent pneumonia and a monophasic (single pitch, fixed) expiratory wheeze suggests a fixed central airway problem (tracheomalacia, airway compression such as a vascular ring, aspirated foreign body or congenital lesion) rather than asthma or bronchiolitis. The lead in is the diagnostic test, and flexible bronchoscopy directly visualizes the airway, shows dynamic collapse or obstruction, and allows lavage.'], 'when_changes': ['Polyphonic, variable wheeze: small airway disease (asthma, bronchiolitis).', 'Monophasic, fixed wheeze: central or focal obstruction.', 'Recurrent pneumonia in infancy: think structural, aspiration, foreign body, immune.'], 'rule': 'Infant + recurrent pneumonia + monophasic wheeze means look inside the airway: bronchoscopy, not spirometry.', 'comparison': None, 'labs': None, 'guideline_note': None},
}

WHY_WRONG = {
"AS-2536": {'A': 'IV ceftriaxone: afebrile with a clear chest and normal radiograph; mild leukocytosis is common in DKA. Antibiotics are right only when an infective trigger is found.', 'C': 'IV potassium chloride: K 4.4 is normal; potassium is added to the fluids once insulin starts and K falls. Replacing potassium before insulin is needed only when K is below 3.3.', 'D': 'IV sodium bicarbonate: reserved for very severe acidosis (pH below 6.9); pH 7.10 corrects with fluids and insulin.'},
"AS-2536B": {'A': 'IV bicarbonate is reserved for very severe acidosis (pH below 6.9); at pH 7.15 it adds no benefit and risks hypokalemia and paradoxical CNS acidosis.', 'B': 'Subcutaneous insulin is used once DKA has resolved (overlapping with the infusion before stopping it); absorption is unreliable in a dehydrated acidotic patient, so it is not the initial treatment here.'},
"AS-2536C": {'A': 'IV bicarbonate is not routine and in children is linked to cerebral edema and hypokalemia. It is considered only in extreme acidosis (pH below about 6.9) or life-threatening hyperkalemia.', 'C': 'Subcutaneous insulin with oral hydration suits only mild DKA in an alert child who tolerates fluids. With pH 7.0 and vomiting, absorption and oral intake are unreliable.', 'D': 'Raising bicarbonate does not stop ketosis; only insulin switches off ketone production. This option misunderstands the pathophysiology.'},
"AS-2536D": {'B': 'Uncontrolled hyperglycemia: describes a glucose number, not the cause of the acidosis and fruity breath; and RBS 8.9 mmol/L is not markedly high.', 'C': 'Hyponatremia: sodium 131 is a mild consequence of vomiting and diarrhea, not the cause of drowsiness and ketotic breath.', 'D': 'Hyperosmolar hyperglycemic state: needs very high glucose and high osmolality with little or no ketosis; here glucose is near normal and the breath is ketotic.'},
"AS-2538": {'A': 'Methotrexate: the correct anchor DMARD, but alone it gives no rapid control of active synovitis while it takes effect; in this recall the bridge is the missing piece.', 'B': 'Methotrexate and sulfasalazine: an acceptable DMARD combination, but it still lacks the steroid bridge for active arthritis.', 'C': 'Methotrexate and hydroxychloroquine: good maintenance DMARDs, but no bridging glucocorticoid for the currently active joints.'},
"AS-2540": {'A': 'Chest x ray: useful to confirm each pneumonia episode, but it cannot show dynamic airway collapse or the cause of a fixed central obstruction.', 'B': 'CBC and blood culture: assess infection or sepsis in an acute episode, but do not explain why pneumonia keeps recurring with a fixed wheeze.', 'C': 'Spirometry: the diagnostic test for asthma or COPD in older children and adults; it needs cooperation and is not feasible at 5 months.'},
}

HIGHLIGHT_TERMS = {
"AS-2536": ['polyuria, polydipsia, polyphagia', 'tachypnea', 'Intravenous 0.9% saline is initiated', 'Potassium 4.4', 'Bicarbonate 10', 'Random glucose 25', 'pH 7.10'],
"AS-2536B": ['diabetic ketoacidosis (DKA)', 'initial management'],
"AS-2536C": ['deep breathing', '380 mg/dL', 'pH = 7.0'],
"AS-2536D": ['fruity (nail polish-like) odor', 'Random blood sugar (RBS): 8.9 mmol/L', 'Bicarbonate: 15 mmol/L'],
"AS-2538": ['wrist joints bilaterally, second and third proximal interphalangeal joints', '4 months', 'active arthritis'],
"AS-2540": ['many times with pneumonia', 'monophasic bilateral expiratory wheezing'],
}
