# -*- coding: utf-8 -*-
# Batch r03 — OBGYN slice (abosarah2026/data/slices/r03.json), 141 questions.

EXPLANATIONS = {
"AS-0084": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "السؤال عن <bdi>TTTS</bdi> بتوأم <bdi>monochorionic</bdi> وتحديد <bdi>management</bdi> الصحيح حسب عمر <bdi>gestational age</bdi> واستمرار <bdi>disease</bdi>.",
    "clues": [
        ("24-week", "<bdi>gestational age</bdi> داخل نافذة <bdi>laser</bdi> (حوالي 16-26 أسبوع)"),
        ("monochorionic twin pregnancy", "شرط أساسي لحدوث <bdi>TTTS</bdi> (المشيمة مشتركة)"),
        ("twin-to-twin transfusion syndrome (TTTS)", "التشخيص نفسه معطى بالسؤال"),
    ],
    "why_correct": [
        "<bdi>TTTS</bdi> سببها <bdi>unbalanced vascular anastomoses</bdi> بالمشيمة المشتركة، وإذا تركت بدون <bdi>treatment</bdi> نسبة <bdi>perinatal mortality</bdi> عالية جدًا.",
        "عند <bdi>24 weeks</bdi> (ضمن نافذة 16-26 أسبوع) العلاج النهائي هو <bdi>fetoscopic laser photocoagulation</bdi> للـ<bdi>anastomoses</bdi>، وهذا يحسّن نسبة البقاء والنتائج العصبية.",
        "الـ<bdi>exertional dyspnea</bdi> عند الأم سببها تمدد الرحم من <bdi>polyhydramnios</bdi> عند الجنين المستقبل (<bdi>recipient twin</bdi>)، مو مشكلة بالأم نفسها.",
    ],
    "when_changes": [
        "لو كان الحمل بعمر 12 أسبوع (قبل نافذة <bdi>laser</bdi>)، الجواب يصير <bdi>expectant management</bdi> مع مراقبة قريبة.",
        "لو تجاوز الحمل نافذة <bdi>laser</bdi> (بعد 26 أسبوع تقريبًا)، الجواب يصير <bdi>amnioreduction</bdi> ثم التخطيط للولادة.",
    ],
    "rule": "الكلمة المفتاحية <bdi>monochorionic</bdi> هي شرط <bdi>TTTS</bdi>، والعمر الحملي هو اللي يحدد: قبل 16 أسبوع مراقبة، بين 16-26 <bdi>laser</bdi>، وبعدها <bdi>amnioreduction</bdi>/ولادة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0085": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "نفس سيناريو <bdi>TTTS</bdi> بس بعمر حملي أصغر (<bdi>12-week</bdi>)، قبل نافذة <bdi>laser</bdi>، فالجواب يتغيّر لـ<bdi>observation</bdi>.",
    "clues": [
        ("12-week", "قبل نافذة <bdi>laser ablation</bdi> (16-26 أسبوع) بكثير"),
        ("monochorionic twin pregnancy", "شرط <bdi>TTTS</bdi>"),
        ("twin-to-twin transfusion syndrome (TTTS)", "التشخيص معطى"),
    ],
    "why_correct": [
        "بعمر <bdi>12 weeks</bdi> فقط، حمل <bdi>monochorionic</bdi> مع ملامح <bdi>TTTS</bdi> يُدار بـ<bdi>expectant management</bdi> ومراقبة قريبة بـ<bdi>ultrasound</bdi>.",
        "<bdi>fetoscopic laser ablation</bdi> يصير ضمن نافذة 16-26 أسبوع تقريبًا، فما زال مبكر جدًا لإجرائه.",
        "الـ<bdi>exertional dyspnea</bdi> مع <bdi>examination</bdi> طبيعي هو <bdi>physiological</bdi> بالحمل، مو <bdi>complication</bdi>.",
    ],
    "when_changes": [
        "لو كان العمر الحملي 24 أسبوع (ضمن النافذة)، الجواب يصير <bdi>laser photocoagulation</bdi> للـ<bdi>anastomoses</bdi>.",
        "لو تدهورت الحالة لـ<bdi>stage II</bdi> أو أعلى وهي بعمر مناسب للـ<bdi>laser</bdi>، ننتقل من <bdi>observation</bdi> للتدخل فورًا.",
    ],
    "rule": "العمر الحملي هو الحاكم: قبل نافذة <bdi>laser</bdi> الجواب <bdi>observation</bdi>، وبالنافذة الجواب <bdi>laser</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0100": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "السؤال عن تشخيص <bdi>vaginitis</bdi> بالاعتماد على خصائص <bdi>discharge</bdi> ونتائج <bdi>microscopy</bdi>.",
    "clues": [
        ("Fishy Smell Vaginal Discharge", "رائحة سمكية مميزة لـ<bdi>bacterial vaginosis</bdi>"),
        ("Clue Cells And Positive Whiff Test", "علامتان تشخيصيتان كلاسيكيتان لـ<bdi>BV</bdi>"),
    ],
    "why_correct": [
        "<bdi>fishy smell</bdi> و<bdi>clue cells</bdi> و<bdi>positive whiff test</bdi> هي معايير تشخيص <bdi>bacterial vaginosis</bdi> الكلاسيكية.",
        "السبب فرط نمو <bdi>Gardnerella</bdi> و<bdi>anaerobes</bdi> مع قلة <bdi>lactobacilli</bdi>، والـ<bdi>discharge</bdi> رفيع رمادي-أبيض و<bdi>pH</bdi> أعلى من 4.5.",
        "<bdi>treatment</bdi> هو <bdi>metronidazole</bdi> للمريضة فقط، بدون حاجة لعلاج <bdi>partner</bdi>.",
    ],
    "when_changes": [
        "لو كان <bdi>discharge</bdi> رغوي أصفر-أخضر مع <bdi>strawberry cervix</bdi> وطفيليات متحركة، الجواب يصير <bdi>Trichomonas</bdi>.",
        "لو كان <bdi>discharge</bdi> سميك أبيض متجبن مع حكة و<bdi>pseudohyphae</bdi>، الجواب يصير <bdi>Candida</bdi>.",
    ],
    "rule": "<bdi>Clue cells</bdi> = <bdi>bacterial vaginosis</bdi>؛ طفيليات متحركة = <bdi>Trichomonas</bdi>، حتى لو كانت الرائحة سمكية بالحالتين.",
    "comparison": {
        "headers": ["النوع", "Discharge", "علامة مميزة"],
        "rows": [
            ["Bacterial Vaginosis", "رفيع رمادي، رائحة سمكية", "<bdi>Clue cells</bdi>، <bdi>whiff</bdi>+"],
            ["Trichomonas", "رغوي أصفر-أخضر", "<bdi>strawberry cervix</bdi>، طفيليات متحركة"],
            ["Candida", "سميك أبيض متجبن", "<bdi>pseudohyphae</bdi>، بدون رائحة"],
        ],
    },
    "labs": None,
    "guideline_note": None,
},
"AS-0102": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سيناريو <bdi>asthma</bdi> بالحمل، والسؤال عن <bdi>initial test</bdi> التشخيصي الصحيح.",
    "clues": [
        ("Cough And Dyspnea", "أعراض تنفسية تناسب <bdi>asthma</bdi>"),
        ("Bilateral Rhonchi", "علامة <bdi>obstruction</bdi> بالقصبات"),
        ("Allergy History", "عامل خطر لـ<bdi>atopy</bdi> و<bdi>asthma</bdi>"),
    ],
    "why_correct": [
        "<bdi>cough and dyspnea</bdi> مع <bdi>bilateral rhonchi</bdi> وتاريخ <bdi>allergy</bdi> يشير لـ<bdi>asthma</bdi>.",
        "<bdi>spirometry</bdi> هو <bdi>test of choice</bdi>: يبيّن انسداد (<bdi>FEV1/FVC</bdi> منخفض) مع تحسّن بعد <bdi>bronchodilator</bdi>.",
        "آمن وغير <bdi>invasive</bdi> حتى عند <bdi>28 weeks</bdi> حمل.",
    ],
    "when_changes": [
        "لو فيه حمى مع <bdi>crackles</bdi> موضعية، الجواب يصير <bdi>chest X-ray</bdi> لاستبعاد <bdi>pneumonia</bdi>.",
        "لو كانت الحالة <bdi>severe exacerbation</bdi> بضيق تنفس شديد، نحتاج <bdi>ABG</bdi> لتقييم الخطورة.",
    ],
    "rule": "اشتباه <bdi>asthma</bdi> = <bdi>spirometry</bdi> أولًا، حتى بالحمل؛ <bdi>CXR</bdi> فقط لو فيه اشتباه <bdi>pneumonia</bdi> أو <bdi>complication</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0109": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سؤال معلومة مباشرة عن أكثر أنماط <bdi>HPV</bdi> سببًا لـ<bdi>cervical cancer</bdi>.",
    "clues": [
        ("HPV", "فيروس مرتبط بـ<bdi>cervical cancer</bdi>"),
        ("cervical cancer", "الورم المطلوب معرفة سببه"),
    ],
    "why_correct": [
        "<bdi>HPV 16 و18</bdi> هما النوعان عالي الخطورة (<bdi>high-risk oncogenic</bdi>) ويسببان معًا حوالي 70% من <bdi>cervical cancer</bdi>.",
        "<bdi>HPV 16</bdi> الأكثر شيوعًا بشكل عام وغالبًا بـ<bdi>squamous cell carcinoma</bdi>، و<bdi>18</bdi> أكثر ارتباطًا بـ<bdi>adenocarcinoma</bdi>.",
        "بروتينات <bdi>E6 و E7</bdi> تعطّل <bdi>p53</bdi> و<bdi>Rb</bdi> فتسبب <bdi>dysplasia</bdi>.",
    ],
    "when_changes": [
        "لو السؤال عن سبب <bdi>genital warts</bdi>، الجواب يصير <bdi>HPV 6 و11</bdi> (منخفضة الخطورة).",
        "لو السؤال عن أنماط أخرى عالية الخطورة أقل شيوعًا، فيها <bdi>31, 33, 45, 52, 58</bdi>.",
    ],
    "rule": "ثبّت بذهنك: <bdi>warts = 6/11</bdi>، <bdi>cancer = 16/18</bdi>، ولا تخلط بينهم.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0111": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سيناريو <bdi>maternal STI</bdi> قد تسبب <bdi>conjunctivitis</bdi> و<bdi>blindness</bdi> للمولود، والسؤال عن إجراء <bdi>health promotion</bdi> و<bdi>prevention</bdi>.",
    "clues": [
        ("multiple sexual transmitted diseases", "عامل خطر لـ<bdi>STI</bdi> نشطة وقت الولادة"),
        ("37th gestational week", "قريب من الولادة، لازم علاج قبلها"),
        ("conjunctivitis and blindness in the newborn", "يوجه لـ<bdi>Chlamydia</bdi> أو <bdi>Gonorrhea</bdi> كسبب لـ<bdi>ophthalmia neonatorum</bdi>"),
    ],
    "why_correct": [
        "علاج الأم قبل الولادة هو <bdi>prevention</bdi> الحقيقي لإصابة المولود بعدوى العين.",
        "<bdi>Chlamydia</bdi> هو السبب الأكثر شيوعًا لـ<bdi>neonatal conjunctivitis</bdi>، وعلاجها بالحمل <bdi>azithromycin</bdi> (<bdi>doxycycline</bdi> يُتجنّب).",
        "إعطاء <bdi>azithromycin</bdi> للأم قبل الولادة يمنع انتقال العدوى للمولود وقت المرور بقناة الولادة.",
    ],
    "when_changes": [
        "لو كان السبب المؤكد <bdi>Gonorrhea</bdi> بدل <bdi>Chlamydia</bdi>، العلاج يصير <bdi>ceftriaxone</bdi> للأم.",
        "بعد الولادة، كل مولود يحتاج <bdi>ocular prophylaxis</bdi> كخط دفاع إضافي بغض النظر عن علاج الأم.",
    ],
    "rule": "«<bdi>health promotion and prevention</bdi>» بالسؤال يعني التصرف على الأم قبل الولادة، مو انتظار فحص المولود بعدها.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر وصف الإجابة بـ<bdi>uncertain</bdi> وذكر خيار <bdi>C</bdi> (فحص المولود) كاحتمال بديل، بس التصرف الوقائي الأقوى هو علاج الأم بـ<bdi>azithromycin</bdi> قبل الولادة.",
},
"AS-0113": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "سيناريو <bdi>infertility</bdi> طويل المدى مع <bdi>dysmenorrhea</bdi> شديد لا يستجيب لـ<bdi>NSAID</bdi>، يوجه لتشخيص <bdi>secondary dysmenorrhea</bdi>.",
    "clues": [
        ("infertility for 6 years", "مدة طويلة توجه لسبب عضوي يؤثر على الخصوبة"),
        ("severe dysmenorrhea unrelieved by naproxen", "فشل استجابة <bdi>NSAID</bdi> يميّز <bdi>secondary dysmenorrhea</bdi>"),
    ],
    "why_correct": [
        "اجتماع <bdi>infertility</bdi> طويل مع <bdi>dysmenorrhea</bdi> شديد لا يستجيب لـ<bdi>naproxen</bdi> هو الصورة الكلاسيكية لـ<bdi>endometriosis</bdi>.",
        "الزرع خارج الرحم (<bdi>ectopic endometrial implants</bdi>) يسبب التهاب دوري و<bdi>adhesions</bdi> تشوّه تشريح الأنابيب والمبيض، وهذا يفسر <bdi>infertility</bdi>.",
        "<bdi>primary dysmenorrhea</bdi> عادة يستجيب لـ<bdi>NSAIDs</bdi>، فالفشل يوجه لسبب ثانوي.",
    ],
    "when_changes": [
        "لو كانت المريضة أكبر سنًا ومتعددة الولادات مع <bdi>menorrhagia</bdi> ورحم منتشر متضخم طري، الجواب يصير <bdi>adenomyosis</bdi>.",
        "لو فيه حمى وإفرازات مع ألم وتاريخ عدوى، الجواب يصير <bdi>PID</bdi> مو <bdi>endometriosis</bdi>.",
    ],
    "rule": "<bdi>severe dysmenorrhea</bdi> مقاوم للـ<bdi>NSAID</bdi> + <bdi>infertility</bdi> = <bdi>endometriosis</bdi>؛ أضف <bdi>menorrhagia</bdi> ورحم متضخم طري بمتعددة الولادات ويصير <bdi>adenomyosis</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0115": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سيناريو تاريخ ولادي معقد (<bdi>spontaneous abortion</bdi>، حمل سليم، <bdi>PPROM</bdi> عند 28 أسبوع) بدون أعراض حالية، والسؤال عن أفضل تصرف بالحمل الحالي.",
    "clues": [
        ("spontaneous abortion", "لا يوجد تحديد <bdi>trimester</bdi>، فلا يؤكد <bdi>cervical insufficiency</bdi>"),
        ("PPROM at 28 weeks", "تاريخ ولادة مبكرة سابقة، عامل خطر لتكرارها"),
    ],
    "why_correct": [
        "تاريخ <bdi>PPROM at 28 weeks</bdi> يجعل هذا حمل <bdi>high-risk</bdi> لتكرار الولادة المبكرة، حتى وهي حاليًا بلا أعراض وفحصها طبيعي.",
        "التصرف الصحيح هو المتابعة بـ<bdi>high-risk clinic</bdi> مع مراقبة قريبة (مثل <bdi>cervical length</bdi> بـ<bdi>transvaginal ultrasound</bdi> وربما <bdi>progesterone</bdi>).",
        "لا يوجد بالتاريخ فقدان بالـ<bdi>second trimester</bdi> بدون ألم، فهي لا تستوفي معايير <bdi>history-indicated cerclage</bdi>.",
    ],
    "when_changes": [
        "لو كان لديها فقدان مؤكد بـ<bdi>second trimester</bdi> بدون ألم، الجواب يصير <bdi>cerclage</bdi> عند 13-14 أسبوع.",
        "لو فشل <bdi>cerclage</bdi> مهبلي سابق، الخيار يصير <bdi>abdominal cerclage</bdi> قبل حمل جديد (لا يصلح وهي حامل أصلًا).",
    ],
    "rule": "فقدان بدون ألم بـ<bdi>second trimester</bdi> يوجّه لـ<bdi>cerclage</bdi>؛ أما تاريخ <bdi>preterm birth/PPROM</bdi> لوحده يوجّه لمتابعة بعيادة <bdi>high-risk</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0116": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سيناريو <bdi>second stage of labor</bdi> مع أم مستنفذة و<bdi>CTG</bdi> غير مطمئن، والسؤال عن أسرع وأفضل طريقة ولادة.",
    "clues": [
        ("exhausted", "الأم لا تستطيع <bdi>pushing</bdi>، يفضّل أداة لا تعتمد على جهدها"),
        ("+2 station", "الرأس منخفض جدًا، يسمح بـ<bdi>instrumental delivery</bdi>"),
        ("late deceleration", "<bdi>CTG</bdi> غير مطمئن، يحتاج تعجيل الولادة"),
    ],
    "why_correct": [
        "هي بـ<bdi>second stage</bdi> (دفع مستمر)، والرأس <bdi>engaged at +2 station</bdi>، و<bdi>CTG</bdi> غير مطمئن (<bdi>minimal variability</bdi> مع <bdi>late deceleration</bdi>)، فلازم تعجيل الولادة.",
        "لما يكون <bdi>cervix</bdi> متوسع كامل والرأس عند <bdi>+2</bdi> أو أقل، <bdi>operative vaginal delivery</bdi> أسرع من <bdi>CS</bdi>.",
        "لأن الأم مستنفذة ولا تقدر تدفع، <bdi>forceps</bdi> هو الأداة المفضلة (<bdi>ventouse</bdi> يعتمد على جهد الأم بالدفع).",
    ],
    "when_changes": [
        "لو كان الرأس أعلى من مستوى <bdi>ischial spines</bdi> أو غير <bdi>engaged</bdi>، الجواب يصير <bdi>cesarean section</bdi>.",
        "لو كانت الأم قادرة على الدفع والـ<bdi>CTG</bdi> مطمئن، يمكن اعتبار <bdi>ventouse</bdi> بدل <bdi>forceps</bdi>.",
    ],
    "rule": "<bdi>CTG</bdi> غير مطمئن بـ<bdi>full dilation</bdi> لا يعني تلقائيًا <bdi>CS</bdi>؛ لو الرأس منخفض (كـ<bdi>+2</bdi>) الولادة تكون <bdi>instrumental</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0117": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سيناريو مشابه لكن بعمر حملي <bdi>33 weeks</bdi> (<bdi>preterm</bdi>) مع نزيف وهبوط ضغط، والسؤال عن طريقة الولادة الأسرع والأنسب.",
    "clues": [
        ("type 2 deceleration", "<bdi>CTG</bdi> غير مطمئن، تعجيل الولادة لازم"),
        ("+2 station", "الرأس منخفض يسمح بـ<bdi>instrumental delivery</bdi>"),
        ("Severe bleeding", "مع هبوط ضغط (<bdi>90/60</bdi>)، حالة تحتاج أسرع طريقة ولادة"),
    ],
    "why_correct": [
        "الجنين بحالة ضيق (<bdi>type 2 / late decelerations</bdi>) والأم تنزف وهابطة ضغط، فلازم تعجيل الولادة، والرأس عند <bdi>+2 station</bdi> يسمح بـ<bdi>instrumental vaginal delivery</bdi> كأسرع طريقة.",
        "لأن الحمل <bdi>33 weeks</bdi> فقط (<bdi>preterm</bdi>)، يُفضّل <bdi>forceps</bdi>: الـ<bdi>ventouse</bdi> يُتجنّب عمومًا قبل 34 أسبوع لخطر نزيف داخل الجمجمة وفروة الرأس.",
        "اختيار <bdi>instrumental delivery</bdi> أسرع من الانتقال لغرفة عمليات لـ<bdi>CS</bdi> بهذه الحالة الحرجة.",
    ],
    "when_changes": [
        "لو كان الحمل بعمر 34 أسبوع أو أكثر، <bdi>ventouse</bdi> يصير خيار مقبول بدل <bdi>forceps</bdi>.",
        "لو لم يكن <bdi>cervix</bdi> متوسع كامل أو الرأس أعلى من <bdi>+2</bdi>، الجواب يصير <bdi>cesarean section</bdi>.",
    ],
    "rule": "<bdi>preterm</bdi> (أقل من 34 أسبوع) مع رأس منخفض يحوّل الخيار من <bdi>ventouse</bdi> إلى <bdi>forceps</bdi>؛ عدم اكتمال التوسع يحوّله لـ<bdi>CS</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0118": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سيناريو <bdi>straddle injury</bdi> عند طفلة مع <bdi>vulvar hematoma</bdi> غير متمددة، والسؤال عن التصرف الصحيح.",
    "clues": [
        ("falling from a bicycle", "آلية <bdi>straddle injury</bdi> تفسّر الإصابة"),
        ("bluish hematoma", "<bdi>hematoma</bdi> موضعي واضح، ليس نازف نشط"),
        ("left labia", "موقع محدد وواضح للفحص"),
    ],
    "why_correct": [
        "هذا <bdi>vulvar hematoma</bdi> ناتج عن <bdi>straddle injury</bdi>، والآلية تناسب الإصابة بدون ذكر تمدد (<bdi>expanding</bdi>).",
        "الـ<bdi>hematoma</bdi> غير المتمددة تُدار بشكل <bdi>conservative</bdi>: <bdi>ice packs</bdi> و<bdi>analgesia</bdi> وراحة، مع التأكد من قدرتها على التبوّل.",
        "أغلب هذه الحالات تتحسّن بدون تدخل جراحي.",
    ],
    "when_changes": [
        "لو كانت الـ<bdi>hematoma</bdi> متمددة (<bdi>expanding</bdi>) بأي حجم، الجواب يصير <bdi>surgical evacuation</bdi>.",
        "لو فيه نزيف مهبلي أو اشتباه إصابة نافذة أو إصابة بالمسالك البولية، الجواب يصير <bdi>examination under anesthesia</bdi>.",
    ],
    "rule": "القاعدة: <bdi>expanding</bdi> = إخلاء جراحي بغض النظر عن الحجم؛ غير متمددة = <bdi>ice</bdi> وملاحظة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0124": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سيناريو <bdi>dyspnea</bdi> خفيف بالحمل بدون أي علامة خطر، والسؤال عن التصرف الصحيح (<bdi>reassurance</bdi> أم فحوصات).",
    "clues": [
        ("28-week pregnant", "حمل متقدم، <bdi>dyspnea</bdi> شائع فيه فسيولوجيًا"),
        ("medically and surgically free", "لا تاريخ مرضي يرفع الشك بسبب عضوي"),
        ("shortness of breath with exertion", "نمط <bdi>dyspnea</bdi> تدريجي مرتبط بالجهد، يناسب <bdi>physiological</bdi>"),
        ("Physical examination is unremarkable", "غياب أي علامة <bdi>red flag</bdi>"),
    ],
    "why_correct": [
        "<bdi>dyspnea</bdi> الخفيف مع الجهد شائع بالحمل الطبيعي: <bdi>progesterone</bdi> يزيد <bdi>tidal volume</bdi> و<bdi>minute ventilation</bdi>، والرحم المتضخم يرفع الحجاب الحاجز.",
        "بامرأة <bdi>medically free</bdi> بحمل غير معقد وفحص طبيعي وبدون علامات <bdi>heart failure</bdi>، التصرف الصحيح هو <bdi>education</bdi> و<bdi>reassurance</bdi> بأن هذا طبيعي.",
        "لا حاجة لفحوصات إضافية ما دام لا توجد علامات خطر.",
    ],
    "when_changes": [
        "لو كان فيه <bdi>dyspnea</bdi> بالراحة أو <bdi>orthopnea</bdi> أو <bdi>tachycardia</bdi>، لازم استبعاد أسباب مثل <bdi>peripartum cardiomyopathy</bdi> أو <bdi>PE</bdi>.",
        "لو فيه <bdi>wheeze</bdi> أو فحص صدري غير طبيعي، يصير الجواب فحص وظائف الرئة أو تقييم <bdi>asthma</bdi>.",
    ],
    "rule": "أي علامة خطر (<bdi>rest dyspnea</bdi>، ألم صدر، <bdi>tachycardia</bdi>، <bdi>hypoxia</bdi>) تحوّل الجواب من <bdi>reassurance</bdi> إلى استقصاء.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0125": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سيناريو <bdi>IUGR</bdi> عند <bdi>term</bdi> مع <bdi>AEDF</bdi> و<bdi>oligohydramnios</bdi> شديد، والسؤال عن أفضل طريقة ولادة.",
    "clues": [
        ("38 weeks", "عمر حملي قريب من <bdi>term</bdi>، الولادة ممكنة بأمان"),
        ("intrauterine growth restriction (IUGR)", "التشخيص الأساسي"),
        ("amniotic fluid index (AFI) of 3 cm", "<bdi>severe oligohydramnios</bdi>"),
        ("Absent end diastolic flow", "<bdi>AEDF</bdi> علامة ضعف احتياط جنيني شديد"),
    ],
    "why_correct": [
        "عند <bdi>38 weeks</bdi>، <bdi>IUGR</bdi> مع <bdi>absent end-diastolic flow</bdi> بالـ<bdi>umbilical artery</bdi> و<bdi>oligohydramnios</bdi> شديد (<bdi>AFI 3 cm</bdi>) يشير لجنين معرّض لخطر شديد، و<bdi>AEDF</bdi> بعد 34 أسبوع هو مؤشر للولادة.",
        "الجنين بـ<bdi>AEDF</bdi> عنده احتياط ضعيف لتحمّل الانقباضات، فالولادة تكون بـ<bdi>cesarean section</bdi> بدل <bdi>induction</bdi>.",
        "الانتظار لولادة طبيعية عفوية يعرّض الجنين لخطر <bdi>stillbirth</bdi>.",
    ],
    "when_changes": [
        "لو كان الـ<bdi>Doppler</bdi> طبيعي بـ<bdi>term IUGR</bdi>، الجواب يصير <bdi>induction of labor</bdi>.",
        "لو كان <bdi>reversed end-diastolic flow (REDV)</bdi> قبل 34 أسبوع، الولادة بـ<bdi>CS</bdi> عند 32 أسبوع أو أكثر.",
    ],
    "rule": "<bdi>IUGR</bdi> بـ<bdi>term</bdi> مع <bdi>Doppler</bdi> طبيعي = <bdi>induce</bdi>؛ مع <bdi>AEDF</bdi> أو <bdi>REDV</bdi> = <bdi>CS</bdi>.",
    "comparison": None,
    "labs": [["AFI", "3 cm", "severe oligohydramnios (<5 cm)"]],
    "guideline_note": None,
},
"AS-0126": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سؤال عن توقيت إعطاء <bdi>MMR vaccine</bdi> لامرأة حامل غير محصّنة ضد <bdi>rubella</bdi>.",
    "clues": [
        ("24 weeks", "هي حاليًا حامل، فلا يمكن إعطاء <bdi>live vaccine</bdi> الآن"),
        ("didn't receive rubella vaccine", "تحتاج <bdi>vaccination</bdi> لحمايتها مستقبلًا"),
    ],
    "why_correct": [
        "<bdi>MMR</bdi> هو <bdi>live attenuated vaccine</bdi> وممنوع بالحمل بسبب خطر نظري على الجنين.",
        "المرأة غير محصّنة ضد <bdi>rubella</bdi> تُعطى اللقاح <bdi>postpartum</bdi>، والأفضل قبل خروجها من المستشفى بعد الولادة.",
        "<bdi>breastfeeding</bdi> ليس <bdi>contraindication</bdi> لإعطاء اللقاح.",
    ],
    "when_changes": [
        "لو كانت غير حامل وتخطط للحمل، يُعطى اللقاح قبل الحمل بشهر تقريبًا لتجنّب التلقيح أثناء الحمل.",
        "لو كان اللقاح المطلوب <bdi>Tdap</bdi> (<bdi>inactivated</bdi>) فيُعطى بالحمل نفسه بين 27-36 أسبوع.",
    ],
    "rule": "اللقاحات الحية (<bdi>MMR</bdi>, <bdi>varicella</bdi>, <bdi>zoster</bdi>) تُعطى قبل الحمل أو بعده، لا أثناءه مطلقًا.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0128": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "سيناريو <bdi>severe pre-eclampsia</bdi> مع ضغط شديد، والسؤال عن الدواء الصحيح للعلاج الحاد للضغط.",
    "clues": [
        ("primigravida", "عامل خطر لـ<bdi>pre-eclampsia</bdi>"),
        ("36-weeks", "<bdi>gestational age</bdi> قريب من <bdi>term</bdi>"),
        ("headache, blurred vision", "أعراض <bdi>severe features</bdi> لـ<bdi>pre-eclampsia</bdi>"),
        ("160/110 mmHg", "<bdi>severe hypertension</bdi> يحتاج علاج <bdi>IV</bdi> فوري"),
        ("Protein ++", "<bdi>proteinuria</bdi> يدعم تشخيص <bdi>pre-eclampsia</bdi>"),
    ],
    "why_correct": [
        "<bdi>BP 160/110</bdi> مع <bdi>headache</bdi> و<bdi>blurred vision</bdi> و<bdi>proteinuria</bdi> عند 36 أسبوع = <bdi>pre-eclampsia with severe features</bdi>، والضغط الشديد يحتاج علاج <bdi>IV</bdi> عاجل.",
        "الأدوية <bdi>IV</bdi> الموصى بها هي <bdi>labetalol</bdi> (الخط الأول) و<bdi>hydralazine</bdi>؛ بغياب <bdi>labetalol</bdi> من الخيارات، <bdi>hydralazine</bdi> هو الصحيح.",
        "<bdi>magnesium sulfate</bdi> يُعطى أيضًا للوقاية من التشنجات، ثم تُخطط الولادة.",
    ],
    "when_changes": [
        "لو كان <bdi>labetalol</bdi> من ضمن الخيارات، يصير هو الجواب الأول للعلاج الحاد.",
        "لو كان الضغط مرتفع بشكل خفيف أو مزمن بدون شدة حادة، يُستخدم علاج فموي مثل <bdi>methyldopa</bdi> أو <bdi>nifedipine</bdi>.",
    ],
    "rule": "لو <bdi>labetalol</bdi> موجود بالخيارات اختاره للضغط الشديد الحاد؛ لو غير موجود فـ<bdi>hydralazine</bdi>. <bdi>methyldopa</bdi> لا يُستخدم للحالة الحادة أبدًا.",
    "comparison": None,
    "labs": [["Blood Pressure", "160/110 mmHg", "<140/90 mmHg"], ["Protein", "++", "absent"]],
    "guideline_note": None,
},
"AS-0129": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سيناريو <bdi>eclampsia</bdi> (تشنج أول عند حامل مع ضغط شديد و<bdi>proteinuria</bdi>)، والسؤال عن أولوية الخطوة العلاجية.",
    "clues": [
        ("32-weeks", "عمر حملي يسمح بمشاكل <bdi>pre-eclampsia/eclampsia</bdi>"),
        ("seizures", "علامة <bdi>eclampsia</bdi> المباشرة"),
        ("160/110 mmHg", "<bdi>severe hypertension</bdi>"),
        ("Protein +++", "<bdi>proteinuria</bdi> شديد يدعم <bdi>pre-eclampsia</bdi>"),
    ],
    "why_correct": [
        "تشنج أول عند <bdi>32 weeks</bdi> مع ضغط بمدى شديد (<bdi>160/110</bdi>) و<bdi>protein +++</bdi> يُعتبر <bdi>eclampsia</bdi> حتى يثبت العكس.",
        "بعد تثبيت <bdi>airway, breathing, circulation</bdi>، الأولوية هي <bdi>magnesium sulfate</bdi>، يوقف التشنج الحالي ويمنع تكراره، وهو أفضل من <bdi>diazepam</bdi> و<bdi>phenytoin</bdi>.",
        "ضبط الضغط والولادة تأتي بعد استقرار حالتها.",
    ],
    "when_changes": [
        "لو السؤال يسأل عن علاج الضغط الحاد نفسه، الجواب يصير <bdi>hydralazine</bdi> أو <bdi>labetalol</bdi>، مو <bdi>MgSO4</bdi>.",
        "لو ظهرت علامات تسمم <bdi>MgSO4</bdi> (فقدان المنعكسات، تثبيط تنفسي)، نوقف الدواء ونعطي <bdi>calcium gluconate</bdi>.",
    ],
    "rule": "تشنج بالحمل بعد 20 أسبوع = الجواب <bdi>MgSO4</bdi>، إلا لو السؤال يسأل تحديدًا عن <bdi>antihypertensive</bdi>.",
    "comparison": None,
    "labs": [["Blood Pressure", "160/110 mmHg", "<140/90 mmHg"], ["Protein", "+++", "absent"]],
    "guideline_note": None,
},
"AS-0130": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سيناريو <bdi>FGR</bdi> شديد مع <bdi>AEDF</bdi> و<bdi>oligohydramnios</bdi> قريب من 35 أسبوع، والسؤال عن طريقة الولادة.",
    "clues": [
        ("35 GA", "بعد نافذة 34 أسبوع، الولادة مطلوبة لا المراقبة"),
        ("Fetal weight is below the 10th centile", "تأكيد <bdi>FGR</bdi>"),
        ("Amniotic fluid Index is 3", "<bdi>severe oligohydramnios</bdi>"),
        ("Umbilical artery end diastolic flow is absent", "<bdi>AEDF</bdi> مؤشر شدة"),
    ],
    "why_correct": [
        "هذا <bdi>fetal growth restriction</bdi> (الوزن أقل من <bdi>10th centile</bdi>) مع قصور مشيمي شديد: <bdi>AFI 3</bdi> و<bdi>decreased fetal movement</bdi> و<bdi>absent end-diastolic flow</bdi>.",
        "مع <bdi>AEDF</bdi> بعمر 34 أسبوع أو أكثر، الجنين يُولد بدل المراقبة.",
        "جنين بـ<bdi>absent flow</bdi> وسائل قليل يتحمّل الانقباضات بشكل ضعيف، فالولادة تكون بـ<bdi>cesarean section</bdi> أفضل من <bdi>induction</bdi>.",
    ],
    "when_changes": [
        "لو كان العمر الحملي أقل من 34 أسبوع، الجواب يصير مراقبة يومية (<bdi>Doppler</bdi>, <bdi>BPP</bdi>, <bdi>NST</bdi>) مع إعطاء <bdi>steroids</bdi>.",
        "لو كان <bdi>Doppler</bdi> طبيعي أو خفيف الشذوذ قرب <bdi>term</bdi>، الجواب يصير <bdi>induction</bdi>.",
    ],
    "rule": "<bdi>AEDF</bdi> بعمر 34 أسبوع أو أكثر = ولادة بـ<bdi>CS</bdi>، مو انتظار ولا <bdi>steroids</bdi> ولا <bdi>induction</bdi>.",
    "comparison": None,
    "labs": [["AFI", "3", "severe oligohydramnios"], ["Fetal weight centile", "<10th centile", ">10th centile"]],
    "guideline_note": None,
},
"AS-0141": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سيناريو <bdi>failure to breastfeed</bdi> بعد <bdi>severe postpartum hemorrhage</bdi>، يوجه لتشخيص قصور الغدة النخامية بعد الولادة.",
    "clues": [
        ("failure to breastfeed", "أول علامة لنقص <bdi>prolactin</bdi>"),
        ("severe postpartum hemorrhage", "السبب الكامن (نقص تروية الغدة النخامية)"),
    ],
    "why_correct": [
        "<bdi>severe postpartum hemorrhage</bdi> (هنا من <bdi>retained placenta</bdi>) قد تسبب صدمة نقص حجم و<bdi>ischemic necrosis</bdi> للغدة النخامية المتضخمة بالحمل.",
        "أول علامة هي <bdi>failure to breastfeed</bdi> (فقد <bdi>prolactin</bdi>)، وبعدها قصور الغدة الأمامية يعطي <bdi>fatigue</bdi> و<bdi>dizziness</bdi> (نقص <bdi>ACTH</bdi> و<bdi>TSH</bdi>).",
        "هذا هو <bdi>Sheehan syndrome</bdi>، و<bdi>MRI</bdi> لاحقًا يبيّن <bdi>empty sella</bdi>.",
    ],
    "when_changes": [
        "لو كانت الصورة <bdi>galactorrhea</bdi> و<bdi>amenorrhea</bdi> بدون نزيف شديد، الجواب يصير <bdi>pituitary adenoma</bdi> (<bdi>prolactinoma</bdi>).",
        "لو بدأت الأعراض بصداع وفقدان حقل بصري بدون قصة نزيف، نفكر بـ<bdi>pituitary adenoma</bdi> أو <bdi>lymphocytic hypophysitis</bdi>.",
    ],
    "rule": "نزيف ولادي شديد + عدم قدرة على الرضاعة = <bdi>Sheehan syndrome</bdi>؛ <bdi>galactorrhea</bdi> بدلها يوجه لـ<bdi>prolactinoma</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0144": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سؤال عن أفضل دواء يُعطى قبل <bdi>myomectomy</bdi> لتصغير <bdi>fibroid</bdi> كبير قبل الجراحة.",
    "clues": [
        ("reduce the size of the uterine fibroid prior to", "الهدف هو تصغير الحجم قبل العملية، لا ضبط النزيف فقط"),
    ],
    "why_correct": [
        "الهدف هو <bdi>reduce the size</bdi> من <bdi>fibroid</bdi> كبير قبل <bdi>myomectomy</bdi>.",
        "<bdi>GnRH agonists</bdi> تصنع حالة مؤقتة من نقص <bdi>estrogen</bdi> تصغّر الـ<bdi>fibroid</bdi> وتقلل النزيف، وتسمح بتصحيح <bdi>anemia</bdi> قبل الجراحة.",
        "تُستخدم لفترة قصيرة فقط بسبب أعراض شبيهة بـ<bdi>menopause</bdi> وفقدان كثافة العظم.",
    ],
    "when_changes": [
        "لو كان الهدف فقط ضبط النزيف بفايبرويد صغير عرضي، الجواب يصير <bdi>combined contraceptive pills</bdi> أو <bdi>NSAIDs</bdi>.",
        "لو كانت تجويف الرحم مشوّه بشدة بالفايبرويد الكبير، لا يصلح وضع <bdi>IUD</bdi> بسبب ضعف الثبات.",
    ],
    "rule": "«تصغير الحجم» = <bdi>GnRH agonist</bdi>؛ «ضبط النزيف» = <bdi>OCP</bdi> أو علاج طبي آخر.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0147": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سؤال عن أفضل علامة تنبؤ بمضاعفات حملية عند امرأة بتاريخ <bdi>recurrent pregnancy loss</bdi>.",
    "clues": [
        ("recurrent pregnancy loss", "عامل خطر عالٍ لتكرار المضاعفات"),
        ("best predictor for pregnancy complication", "السؤال يبحث عن أقوى علامة إنذار"),
    ],
    "why_correct": [
        "بامرأة بتاريخ <bdi>recurrent pregnancy loss</bdi>، العرض الذي يتنبأ أكثر بمضاعفة (خصوصًا إجهاض آخر) هو <bdi>vaginal bleeding</bdi>.",
        "يُعتبر أهم علامة إنذار بالحمل بأي مرحلة، يشير لإجهاض بالبداية أو <bdi>previa</bdi>/<bdi>abruption</bdi> لاحقًا.",
    ],
    "when_changes": [
        "لو ظهر <bdi>bleeding</bdi> مع ألم شديد لاحقًا بالحمل، يوجه أكثر لـ<bdi>placental abruption</bdi>.",
        "لو كان <bdi>bleeding</bdi> بدون ألم بثلث أخير، يوجه لـ<bdi>placenta previa</bdi>.",
    ],
    "rule": "أعراض الحمل الحميدة الشائعة (<bdi>heartburn</bdi>, <bdi>ankle edema</bdi>) مجرد مشتتات؛ <bdi>bleeding</bdi> هو العلم الأحمر الحقيقي.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0148": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "فقدان حمل عند <bdi>18 weeks</bdi> بدون ألم مع تمزق مفاجئ للأغشية، يوجه لتشخيص قصور عنق الرحم.",
    "clues": [
        ("18 weeks", "ثلث ثاني، عمر نموذجي لـ<bdi>cervical incompetence</bdi>"),
        ("painless expulsion", "غياب الألم والانقباضات يميّز <bdi>cervical incompetence</bdi>"),
    ],
    "why_correct": [
        "فقدان عند <bdi>18 weeks</bdi> مع تمزق أغشية مفاجئ غير متوقع ثم طرد <bdi>painless</bdi> هو الصورة الكلاسيكية لـ<bdi>cervical incompetence</bdi>.",
        "عنق الرحم يتوسع بصمت بدون انقباضات، فتبرز الأغشية وتتمزق ويُطرد الحمل.",
        "يحدث نموذجيًا بين 16-24 أسبوع تقريبًا، ويُمنع بالحمل القادم بـ<bdi>cerclage</bdi>.",
    ],
    "when_changes": [
        "لو كان الفقدان بثلث أول، السبب الأكثر شيوعًا يصير <bdi>chromosomal abnormality</bdi>.",
        "لو كانت الانقباضات مؤلمة ومتكررة، نفكر بـ<bdi>bicornuate uterus</bdi> أو <bdi>preterm labor</bdi> بدل <bdi>cervical incompetence</bdi>.",
    ],
    "rule": "فقدان <bdi>painless</bdi> بثلث ثاني = عنق الرحم؛ ألم بانقباضات أو ثلث أول يوجه لأسباب أخرى.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0148B": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سيناريو <bdi>short cervix</bdi> متوسع مع بروز أغشية بثلث ثاني، والسؤال عن التشخيص الأدق من بين فئات الإجهاض.",
    "clues": [
        ("22 weeks", "ثلث ثاني، عمر نموذجي لـ<bdi>cervical incompetence</bdi>"),
        ("short soft cervix", "عنق الرحم غير طبيعي البنية"),
        ("1.5 cm dilated with herniation of fetal membranes", "توسع صامت مع بروز الأغشية بدون ألم شديد"),
    ],
    "why_correct": [
        "بعمر <bdi>22 weeks</bdi> لديها عنق رحم قصير طري متوسع 1.5 سم مع بروز الأغشية، وجنين حي ورحم مطابق للتاريخ، مع ألم <bdi>mild</bdi> فقط وبدون نزيف أو حمى.",
        "توسع عنق الرحم <bdi>painless</bdi> بثلث ثاني هو العلامة المميزة لـ<bdi>cervical incompetence</bdi>.",
    ],
    "when_changes": [
        "لو كان فيه نزيف مع <bdi>closed cervix</bdi>، الجواب يصير <bdi>threatened abortion</bdi>.",
        "لو كان فيه نزيف وطرد جزئي للمحتويات مع عنق مفتوح، الجواب يصير <bdi>incomplete abortion</bdi>.",
    ],
    "rule": "عنق رحم مفتوح وأغشية بارزة بألم ونزيف قليلين بثلث ثاني = قصور عنق الرحم، لا فئة إجهاض.",
    "comparison": {
        "headers": ["الحالة", "العنق", "النزيف/الألم"],
        "rows": [
            ["Threatened abortion", "مغلق", "نزيف، بدون ألم شديد"],
            ["Incomplete abortion", "مفتوح", "نزيف مع طرد جزئي"],
            ["Cervical incompetence", "مفتوح بصمت", "ألم خفيف، بدون نزيف يُذكر"],
        ],
    },
    "labs": None,
    "guideline_note": None,
},
"AS-0150": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سيناريو تخطيط للحمل عند مريضة <bdi>type 1 diabetes</bdi> بـ<bdi>HbA1c</bdi> مرتفع، والسؤال عن أفضل نصيحة لمنع <bdi>congenital malformation</bdi>.",
    "clues": [
        ("type 1 diabetes", "خطر <bdi>congenital malformations</bdi> مرتبط بالسكر غير المضبوط"),
        ("HbA1C 8.0", "مرتفع، خطر كبير أثناء <bdi>organogenesis</bdi>"),
        ("prevent congenital malformation", "محور السؤال الأساسي"),
    ],
    "why_correct": [
        "تخطط للحمل <bdi>next month</bdi> بـ<bdi>HbA1c 8.0%</bdi>. ارتفاع السكر حول فترة التلقيح وقت <bdi>organogenesis</bdi> هو السبب الرئيسي للـ<bdi>congenital malformations</bdi> بسكري الحمل.",
        "أفضل نصيحة هي <bdi>delay conception</bdi> لحين يصبح <bdi>HbA1c</bdi> أقرب للطبيعي بأمان (عادة أقل من 6.5% إن أمكن بدون <bdi>hypoglycemia</bdi>).",
    ],
    "when_changes": [
        "لو كان <bdi>HbA1c</bdi> فعلًا قريب من الطبيعي، تُنصح بالاستمرار بالحمل مع إيقاف <bdi>ACE inhibitors</bdi> وبدء <bdi>folic acid</bdi> بجرعة عالية.",
        "لو أرادت ضبط الضغط بالحمل، التحويل يكون من <bdi>ACE inhibitor</bdi> لـ<bdi>labetalol/nifedipine/methyldopa</bdi>، لا لـ<bdi>ARB</bdi>.",
    ],
    "rule": "قبل الحمل بسكري النوع الأول، أول خطوة هي ضبط <bdi>glucose</bdi> (<bdi>HbA1c</bdi>) قبل التلقيح، لا تبديل دواء داخل نفس الفئة الممنوعة.",
    "comparison": None,
    "labs": [["HbA1c", "8.0%", "4.7-5.6%"], ["24hr urine protein", "2000 mg/dl*", "see ref ranges given"], ["Creatinine", "88 mol/L", "44-115 mol/L"]],
    "guideline_note": None,
},
"AS-0151": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سؤال معلومة مباشرة عن السبب الأكثر شيوعًا لإجهاض الثلث الأول.",
    "clues": [
        ("first trimester miscarriage", "محدد بالثلث الأول تحديدًا"),
    ],
    "why_correct": [
        "حوالي نصف حالات فقدان الحمل بالثلث الأول سببها <bdi>chromosomal abnormalities</bdi>، غالبًا <bdi>autosomal trisomy</bdi>، وهذا يجعلها السبب الأكثر شيوعًا.",
    ],
    "when_changes": [
        "لو كان الفقدان بالثلث الثاني وبدون ألم، السبب الأكثر شيوعًا يصير <bdi>cervical incompetence</bdi>.",
        "لو كانت الحالة <bdi>recurrent</bdi> (تكرار 3 مرات أو أكثر)، نبحث عن سبب قابل للعلاج مثل <bdi>antiphospholipid syndrome</bdi>.",
    ],
    "rule": "توقيت الفقدان يحدد السبب الأكثر شيوعًا: ثلث أول = <bdi>chromosomal abnormality</bdi>، ثلث ثاني بدون ألم = <bdi>cervical incompetence</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0151B": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سؤال عن السبب الأكثر شيوعًا للإجهاض المتكرر (<bdi>recurrent</bdi>) بالثلث الأول، يختلف عن سؤال الحادثة المنفردة.",
    "clues": [
        ("3 consecutive miscarriage first trimester", "تكرار 3 مرات يغيّر السبب الأكثر شيوعًا عن الحادثة الواحدة"),
    ],
    "why_correct": [
        "المفتاح هو <bdi>three consecutive first trimester</bdi> losses (<bdi>recurrent miscarriage</bdi>).",
        "بين الأسباب المذكورة، <bdi>antiphospholipid syndrome</bdi> هو أهم سبب مكتسب للفقدان المتكرر المبكر: حالة فرط تخثر تسبب <bdi>placental thrombosis</bdi>.",
        "يُفحص بـ<bdi>lupus anticoagulant</bdi>, <bdi>anticardiolipin</bdi>, <bdi>anti-beta2 glycoprotein I</bdi>، ويُعالج بـ<bdi>low-dose aspirin</bdi> مع <bdi>heparin</bdi> بالحمل التالي.",
    ],
    "when_changes": [
        "لو كان السؤال عن حادثة فقدان منفردة بالثلث الأول، الجواب الأكثر شيوعًا يصير <bdi>chromosomal abnormality</bdi>.",
        "لو أظهرت الصور الطبية تشوهًا تشريحيًا بالرحم (<bdi>septate uterus</bdi>)، الجواب يصير سببًا تشريحيًا.",
    ],
    "rule": "فقدان مفرد بالثلث الأول = <bdi>chromosomal abnormality</bdi>؛ فقدان متكرر بدون خيار الكروموسومات = <bdi>APS</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0155": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "سيناريو حكة ويرقان بثلث ثالث مع نمط تحاليل <bdi>cholestatic</bdi>، يوجه لتشخيص <bdi>ICP</bdi>.",
    "clues": [
        ("30-week pregnant", "ثلث ثالث، عمر نموذجي لـ<bdi>intrahepatic cholestasis of pregnancy</bdi>"),
        ("pruritus and jaundice", "أعراض كلاسيكية لـ<bdi>cholestasis</bdi>"),
        ("Platelets count 160", "طبيعي، يستبعد <bdi>HELLP</bdi>"),
        ("Alkaline phosphatase 700", "ارتفاع كبير بنمط <bdi>cholestatic</bdi>"),
    ],
    "why_correct": [
        "عند <bdi>30 weeks</bdi> لديها <bdi>pruritus</bdi> و<bdi>jaundice</bdi> بنمط <bdi>cholestatic</bdi> (ALP مرتفع جدًا مع ارتفاع خفيف بـ<bdi>ALT/AST</bdi>) بدون حمى أو ألم أو قيء.",
        "<bdi>platelets</bdi> طبيعية (160) وبدون ذكر <bdi>hypertension</bdi>.",
        "حكة الثلث الثالث مع تحاليل كبدية <bdi>cholestatic</bdi> هي <bdi>intrahepatic cholestasis of pregnancy</bdi>، وتأكيدها بارتفاع <bdi>serum bile acids</bdi>.",
    ],
    "when_changes": [
        "لو كانت <bdi>platelets</bdi> منخفضة مع ألم وضغط مرتفع، الجواب يصير <bdi>HELLP syndrome</bdi>.",
        "لو فيه قيء وألم بطن علوي أيمن وحمى، نفكر بـ<bdi>viral hepatitis</bdi>.",
    ],
    "rule": "حكة بدون ألم أو حمى بالثلث الثالث = <bdi>cholestasis</bdi>؛ أضف انخفاض <bdi>platelets</bdi> أو ضغط مرتفع ويصير <bdi>HELLP</bdi>.",
    "comparison": None,
    "labs": [
        ["Platelets", "160 x10^9/L", "150-400 x10^9/L"],
        ["ALP", "700 IU/L", "39-117 IU/L"],
        ["ALT", "79 IU/L", "5-40 IU/L"],
        ["AST", "100 IU/L", "12-40 IU/L"],
    ],
    "guideline_note": None,
},
"AS-0158": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "سيناريو مخاض بوضع <bdi>complete breech</bdi> بالمخاض الفعلي بدون تقدم بعد ساعتين، يوجه لولادة قيصرية بدل الانتظار.",
    "clues": [
        ("38th week", "حمل بـ<bdi>term</bdi>"),
        ("4 cm dilation", "بمخاض فعلي"),
        ("complete breech", "وضع غير رأسي مستمر بالمخاض"),
        ("CTG is reactive", "لا يوجد ضيق جنيني حاليًا، بس الوضع هو المشكلة"),
        ("no change", "عدم تقدم بعد المراقبة"),
    ],
    "why_correct": [
        "هي بـ<bdi>term</bdi> وبمخاض فعلي (4 سم) مع <bdi>persistent breech</bdi>. الوضع غير الرأسي وقت الولادة يعتبر بذاته مؤشرًا لـ<bdi>cesarean section</bdi>.",
        "الولادة المهبلية المخطط لها بوضع <bdi>breech</bdi> تُحفظ لمعايير صارمة وطاقم خبرة؛ بدون تقدم بعد ساعتين، الأسلم هو <bdi>CS</bdi> الآن.",
    ],
    "when_changes": [
        "لو لم تكن بمخاض فعلي بعد (قبل 36-37 أسبوع)، الخيار المناسب يصير <bdi>external cephalic version</bdi>.",
        "لو كان الوضع رأسي (<bdi>cephalic</bdi>) بانقباضات غير كافية، يُستخدم <bdi>oxytocin</bdi> بدل <bdi>CS</bdi> المباشر.",
    ],
    "rule": "لا تُطبّق قواعد توقف المخاض الرأسي (انتظار/<bdi>oxytocin</bdi>) على <bdi>breech</bdi> بالمخاض؛ الوضع نفسه هو مؤشر <bdi>CS</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0159": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "نسخة مماثلة لـ<bdi>breech</bdi> بالمخاض بدون تحديد نوع <bdi>breech</bdi> أو وزن الجنين، ونفس مبدأ الولادة القيصرية.",
    "clues": [
        ("38th week", "حمل بـ<bdi>term</bdi>"),
        ("4 cm dilation", "بمخاض فعلي"),
        ("\"breech\" presentation", "وضع غير رأسي مستمر"),
        ("no change", "عدم تقدم بالمخاض"),
    ],
    "why_correct": [
        "جنين <bdi>term</bdi> بوضع <bdi>breech</bdi> وبمخاض فعلي (4 سم) بدون تقدم يُولد بـ<bdi>cesarean section</bdi>.",
        "استمرار الوضع غير الرأسي وقت الولادة هو بذاته مؤشر لـ<bdi>CS</bdi>، و<bdi>CS</bdi> المخطط هو الطريقة الموصى بها لأغلب حالات <bdi>breech</bdi> المفردة بـ<bdi>term</bdi>.",
    ],
    "when_changes": [
        "لو لم تكن بمخاض فعلي بعد (36-37 أسبوع)، الخيار المناسب يصير <bdi>external cephalic version</bdi>.",
        "لو كان الوضع رأسي بانقباضات غير كافية، يُستخدم <bdi>oxytocin</bdi> بدل <bdi>CS</bdi>.",
    ],
    "rule": "لا تُطبّق قواعد توقف المخاض الرأسي على <bdi>breech</bdi> بالمخاض؛ الوضع نفسه، مو الوقت، هو الذي يقرر <bdi>CS</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0160": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سيناريو ألم وحمى عند حامل بـ<bdi>fibroid</bdi> معروف بدون علامات مخاض، يوجه لتشخيص <bdi>red degeneration</bdi> وعلاجه المحافظ.",
    "clues": [
        ("uterine fibroid", "سبب كامن محتمل للألم"),
        ("34 weeks", "ثلث ثالث"),
        ("abdominal pain and fever", "صورة <bdi>red degeneration</bdi> الكلاسيكية"),
        ("cervix is closed", "يستبعد المخاض المبكر"),
        ("no uterine contractions", "يستبعد المخاض المبكر"),
    ],
    "why_correct": [
        "حامل بـ<bdi>fibroid</bdi> معروف تطوّر <bdi>abdominal pain and fever</bdi> لديها <bdi>red (carneous) degeneration</bdi>، أكثر مضاعفة شائعة للفايبرويد بالحمل، بسبب نمو سريع يفوق التغذية الدموية.",
        "<bdi>closed cervix</bdi> و<bdi>no contractions</bdi> تستبعد <bdi>preterm labor</bdi>.",
        "<bdi>red degeneration</bdi> تتحسّن تلقائيًا وتُدار بـ<bdi>observation</bdi> مع راحة ومسكنات وسوائل.",
    ],
    "when_changes": [
        "لو كان العنق يتوسع مع انقباضات منتظمة، الجواب يصير <bdi>preterm labor</bdi> لا <bdi>red degeneration</bdi>.",
        "لو ظهر ضيق جنيني أو مؤشر ولادي آخر، الجواب يصير <bdi>cesarean section</bdi> لذلك السبب، لا للفايبرويد نفسه.",
    ],
    "rule": "ألم وحمى خفيفة بوجود <bdi>fibroid</bdi> بالحمل مع عنق مغلق وبدون انقباضات = <bdi>red degeneration</bdi>، علاجها <bdi>conservative</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0171": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سؤال معلومة عن توقيت بدء <bdi>combined oral contraceptive pills</bdi> بعد الولادة لمن لا ترضّع.",
    "clues": [
        ("postpartum", "التوقيت بعد الولادة هو المحور"),
        ("not breastfeeding", "يرفع احتمالية البدء المبكر نسبيًا"),
        ("combined oral contraceptive pills (COCs)", "تحتوي <bdi>estrogen</bdi>، لها قيود VTE بعد الولادة"),
    ],
    "why_correct": [
        "خطر <bdi>VTE</bdi> بعد الولادة يرتفع خصوصًا بأول 21 يوم، وبين 21-42 يوم تُقبل <bdi>COCs</bdi> فقط بغياب عوامل خطر <bdi>VTE</bdi> إضافية.",
        "بعد 42 يوم (6 أسابيع) لا يوجد قيد خاص بعد الولادة لبدء <bdi>COCs</bdi>، وهذا أكثر توقيت مستقر ومتعارف عليه بالسؤال.",
    ],
    "when_changes": [
        "لو كانت ترضّع، يُفضّل تجنّب <bdi>estrogen</bdi> مبكرًا (يثبّط الحليب) والاعتماد على <bdi>progestogen-only</bdi>.",
        "لو كان عمرها أقل من 21 يوم بعد الولادة، <bdi>COCs</bdi> لا تُعطى أبدًا بسبب خطر <bdi>VTE</bdi>.",
    ],
    "rule": "السؤالان الحاسمان: هل ترضّع؟ وهل فيها عوامل خطر <bdi>VTE</bdi>؟ قبل 21 يوم ممنوعة دائمًا، وبعد 6 أسابيع لا قيد.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر وصف الإجابة بأنها <bdi>uncertain</bdi> ووجد تردد بين الخيار A (3 أسابيع) والخيار B (6 أسابيع)؛ اختيار B هو الأقرب للمبدأ العام (42 يوم = بلا قيد) رغم ذكر مصدر آخر لـ3 أسابيع.",
},
}

WHY_WRONG = {
"AS-0084": {
    "A": "<bdi>Termination</bdi> ليست الجواب المعياري مع وجود علاج جنيني فعّال؛ هي خيار استشاري فقط بحالات شديدة جدًا أو مكتشفة متأخرًا.",
    "B": "<bdi>Expectant observation</bdi> مناسبة فقط لمرض خفيف ومستقر (<bdi>stage I</bdi>)؛ هذه الحالة ضمن نافذة <bdi>laser</bdi> وتستدعي تدخلًا.",
    "D": "<bdi>Cesarean section</bdi> عند 24 أسبوع يعني خداج شديد جدًا؛ الولادة تُفكّر فيها فقط بأعمار حملية متأخرة أو لو العلاج الجنيني غير ممكن.",
},
"AS-0085": {
    "A": "<bdi>Termination</bdi> ليست التصرف الافتراضي؛ تُناقش فقط بمرض شديد غير قابل للعلاج بعد الاستشارة، لا كخطوة أولى بامرأة سليمة.",
    "C": "<bdi>Laser photocoagulation</bdi> هو علاج <bdi>TTTS</bdi> الواضح (<bdi>stage II</bdi> فأعلى) بين 16-26 أسبوع تقريبًا؛ بعمر 12 أسبوع هذا مبكر جدًا.",
    "D": "<bdi>Cesarean section</bdi> طريقة ولادة؛ بعمر 12 أسبوع الحمل بعيد جدًا عن <bdi>viability</bdi> ولا يوجد مؤشر للولادة.",
},
"AS-0102": {
    "B": "<bdi>Chest X-ray</bdi> لا يشخّص <bdi>asthma</bdi>؛ يُستخدم عند الاشتباه بـ<bdi>pneumonia</bdi> أو <bdi>complication</bdi> كـ<bdi>pneumothorax</bdi> (حمى، <bdi>crackles</bdi> موضعية).",
    "C": "<bdi>ABG</bdi> يُقيّم الخطورة بحالة <bdi>severe/life-threatening exacerbation</bdi>؛ ليس <bdi>initial diagnostic test</bdi>.",
    "D": "<bdi>Hemoglobin estimation</bdi> يبحث عن <bdi>anemia</bdi>، وهذا يفسّر <bdi>dyspnea</bdi> لكن لا يفسّر <bdi>rhonchi</bdi> و<bdi>atopy</bdi>.",
},
"AS-0109": {
    "A": "الزوج (11/12) ليس زوج <bdi>cervical cancer</bdi>؛ <bdi>HPV 6 و11</bdi> هما النوعان منخفضا الخطورة المسببان لـ<bdi>genital warts</bdi>، و<bdi>12</bdi> ليس نمطًا تناسليًا معروفًا.",
    "C": "<bdi>HPV 31 و33</bdi> أنماط <bdi>high-risk</bdi> يمكن أن تسبب سرطان لكن أقل شيوعًا بكثير من <bdi>16 و18</bdi>؛ <bdi>32 و36</bdi> ليسا من الأنماط المعروفة لسرطان عنق الرحم.",
    "D": "<bdi>HPV 44</bdi> نمط منخفض الخطورة مرتبط بآفات تناسلية حميدة، وليس سببًا مهمًا لـ<bdi>cervical cancer</bdi>.",
},
"AS-0113": {
    "A": "<bdi>Endometritis</bdi> يعطي حمى وألم رحمي وإفرازات كريهة، عادة بعد ولادة أو إجهاض أو تداخل، وليس سببًا لألم دوري طويل المدى.",
    "B": "<bdi>Leiomyomata</bdi> يسبب غالبًا <bdi>heavy menstrual bleeding</bdi> ورحم متضخم غير منتظم، وقد يؤثر على الخصوبة، لكن <bdi>severe NSAID-resistant dysmenorrhea</bdi> مع <bdi>infertility</bdi> هو نمط <bdi>endometriosis</bdi>.",
    "D": "<bdi>Pelvic congestion syndrome</bdi> يسبب ألمًا مزمنًا خفيفًا يزيد بالوقوف الطويل، عادة بمتعددات الولادة مع <bdi>varices</bdi> حوضية، وغير مرتبط بـ<bdi>infertility</bdi>.",
},
"AS-0115": {
    "A": "<bdi>Urgent cerclage</bdi> يُستخدم مع <bdi>cervix</bdi> مفتوح أو قصير بامرأة عندها فقدان سابق بـ<bdi>second trimester</bdi>؛ ليس لها فقدان مماثل موثق، ولا أعراض، وفحصها طبيعي، و<bdi>PPROM</bdi> ليس <bdi>cervical insufficiency</bdi>.",
    "B": "<bdi>Abdominal cerclage</bdi> يُحفظ لمن فشل معها <bdi>cerclage</bdi> مهبلي سابق؛ لم يسبق لها <bdi>cerclage</bdi> أصلًا، وهي حامل الآن فلا يمكن إجراء خطوة ما قبل الحمل.",
    "C": "متابعة بعيادة طب الأسرة تناسب امرأة منخفضة الخطورة؛ تاريخ <bdi>preterm PPROM</bdi> سابق عامل خطر رئيسي للتكرار ويحتاج رعاية متخصصة.",
},
"AS-0116": {
    "A": "<bdi>CS</bdi> يناسب رأسًا غير <bdi>engaged</bdi> أو أعلى من <bdi>ischial spines</bdi> (مثل <bdi>-3 station</bdi>)، أو عدم استيفاء معايير <bdi>instrumental</bdi>؛ هنا الرأس عند <bdi>+2</bdi> فالولادة <bdi>instrumental</bdi> أسرع.",
    "C": "إعادة التقييم بعد ساعة غير آمنة مع <bdi>late decelerations</bdi> و<bdi>minimal variability</bdi>؛ يجب تعجيل الولادة الآن.",
    "D": "<bdi>Oxytocin</bdi> يزيد الانقباضات ويزيد <bdi>fetal hypoxia</bdi> مع <bdi>late decelerations</bdi>؛ يُستخدم لانقباضات غير كافية مع <bdi>CTG</bdi> مطمئن، لا لأم مستنفذة وجنين بحالة ضيق.",
},
"AS-0117": {
    "B": "<bdi>Ventouse</bdi> مناسب بـ<bdi>term</bdi> والرأس عند <bdi>+2</bdi> أو أقل، لكنه يُتجنّب بالجنين <bdi>preterm</bdi> قبل 34 أسبوع لخطر نزيف تحت الغشاء وداخل الجمجمة.",
    "C": "<bdi>Cesarean section</bdi> يناسب عدم اكتمال توسع <bdi>cervix</bdi> أو رأس أعلى من <bdi>+2</bdi>؛ والرأس هنا بالفعل عند <bdi>+2</bdi> بامرأة متوسعة كاملة تنزف وهابطة ضغط، فالولادة <bdi>instrumental</bdi> أسرع من الوصول لـ<bdi>CS</bdi> وإجرائها.",
},
"AS-0118": {
    "B": "<bdi>hematoma</bdi> مغلقة بجلد سليم لا تحمل مؤشرًا للعدوى، فـ<bdi>prophylactic antibiotics</bdi> لا تضيف شيئًا.",
    "C": "<bdi>Examination under anesthesia</bdi> يُستخدم لطفلة لا يمكن فحصها بشكل كافٍ، أو عند نزيف مهبلي أو اشتباه إصابة نافذة/داخلية أو إصابة بالمسالك البولية؛ هنا الإصابة واضحة وموضعية.",
    "D": "<bdi>Surgical evacuation</bdi> يُستخدم لـ<bdi>hematoma</bdi> متمددة (<bdi>expanding</bdi>) بأي حجم أو كبيرة جدًا ومتوترة؛ <bdi>hematoma</bdi> غير متمددة تُعالج بـ<bdi>ice</bdi> وملاحظة.",
},
"AS-0124": {
    "B": "<bdi>iron supplements</bdi> قد تكون جزءًا من الرعاية الروتينية، لكنها لا تفسّر أو تعالج هذه الشكوى: لا يوجد ما يشير لـ<bdi>anemia</bdi> (لا شحوب، فحص طبيعي) و<bdi>dyspnea</bdi> هنا فسيولوجي.",
    "C": "<bdi>Pulmonary Function Test</bdi> يُطلب عند اشتباه مرض رئوي (<bdi>wheeze</bdi>، سعال، فحص غير طبيعي، <bdi>dyspnea</bdi> بالراحة)؛ مع فحص طبيعي لا حاجة له.",
},
"AS-0125": {
    "B": "انتظار ولادة عفوية يعرّض جنينًا معرّضًا للخطر لـ<bdi>stillbirth</bdi>؛ <bdi>observation</bdi> تناسب <bdi>IUGR</bdi> مع <bdi>Doppler</bdi> طبيعي قبل <bdi>term</bdi>.",
    "C": "<bdi>Induction</bdi> مناسب لـ<bdi>term IUGR</bdi> مع <bdi>Doppler</bdi> طبيعي (أو <bdi>oligohydramnios</bdi> معزول بـ<bdi>term</bdi>)؛ مع <bdi>AEDF</bdi> الجنين غالبًا لن يتحمّل المخاض.",
    "D": "<bdi>Reassurance</bdi> يتجاهل علامتين لضعف جنيني شديد (<bdi>AEDF</bdi> و<bdi>oligohydramnios</bdi> شديد).",
},
"AS-0126": {
    "A": "بعمر 28 أسبوع هي ما زالت حامل، واللقاح الحي ممنوع بأي عمر حملي (بخلاف <bdi>Tdap</bdi> الذي يُعطى بالـ<bdi>third trimester</bdi>).",
    "C": "هي غير محصّنة، فتحتاج التلقيح لحماية حملها المستقبلي من <bdi>congenital rubella syndrome</bdi>.",
    "D": "اللقاحات الحية لا تُعطى أثناء الحمل؛ لو أُعطيت بالخطأ فهذا ليس مؤشرًا لإنهاء الحمل، لكنه لا يُخطط له أبدًا.",
},
"AS-0128": {
    "A": "<bdi>Clonidine</bdi> ليس دواءً موصى به للضغط الشديد الحاد بالحمل؛ الخيارات الحادة هي <bdi>IV labetalol</bdi> أو <bdi>IV hydralazine</bdi> أو <bdi>oral nifedipine</bdi>.",
    "B": "<bdi>Methyldopa</bdi> دواء فموي بطيء التأثير للضغط الخفيف أو المزمن بالحمل، وليس للحالة الحادة الشديدة.",
    "D": "<bdi>Sodium nitroprusside</bdi> يُتجنّب بالحمل بسبب سمية <bdi>cyanide</bdi> الجنينية، ويُحفظ لحالات الطوارئ المقاومة فقط.",
},
"AS-0129": {
    "A": "<bdi>Steroids</bdi> تُستخدم لنضج رئة الجنين قبل ولادة مبكرة وقد تُعطى لاحقًا، لكنها لا تفعل شيء للتشنج؛ <bdi>MgSO4</bdi> أولًا.",
    "B": "<bdi>Diuretics</bdi> لا دور لها بـ<bdi>pre-eclampsia</bdi> أو <bdi>eclampsia</bdi>؛ هذه النساء ناقصات حجم داخل الأوعية، والإدرار يزيد سوء تروية المشيمة. صحيح فقط لـ<bdi>pulmonary edema</bdi>.",
    "C": "<bdi>Hydralazine</bdi> يعالج الضغط الشديد ويُعطى بالتوازي، لكنه لا يوقف ولا يمنع التشنجات. صحيح لو السؤال يسأل عن <bdi>antihypertensive</bdi> الحاد تحديدًا.",
},
"AS-0130": {
    "A": "<bdi>Steroid injection</bdi> تُعطى لولادات قبل 34 أسبوع؛ بعمر 35 أسبوع هذه ليست الخطوة المهمة ويجب ألا تؤخر ولادة جنين متضرر. صحيحة لو كان <bdi>FGR</bdi> قبل 34 أسبوع بوقت كافٍ لإعطائها.",
    "C": "<bdi>Induction</bdi> يعرّض جنينًا بنقص أكسجين مع <bdi>absent end-diastolic flow</bdi> وسائل قليل لساعات من الانقباضات، بخطر <bdi>fetal distress</bdi> عالٍ. يناسب <bdi>FGR</bdi> مع <bdi>Doppler</bdi> طبيعي أو خفيف الشذوذ قرب <bdi>term</bdi>.",
    "D": "<bdi>Expectant management</bdi> (مراقبة يومية) مخصصة لـ<bdi>AEDF</bdi> قبل 34 أسبوع فقط؛ بعمر 35 أسبوع مع حركة أقل، القاعدة تقول وَلِّد.",
},
"AS-0141": {
    "A": "<bdi>Pituitary adenoma</bdi> غير مرتبط بالنزيف؛ <bdi>prolactinoma</bdi> يسبب <bdi>galactorrhea</bdi> و<bdi>amenorrhea</bdi>، لا فشل الرضاعة. صحيح عند وجود كتلة بصداع أو فقدان حقل بصري بدون محرّض ولادي.",
    "C": "<bdi>Lymphocytic hypophysitis</bdi> التهاب مناعي بالغدة النخامية بآخر الحمل أو بعده، غالبًا بصداع وتأثير كتلة؛ القصة هنا تشير لنخر نقص تروية بسبب <bdi>severe PPH</bdi>.",
    "D": "<bdi>Subarachnoid hemorrhage</bdi> يعطي صداعًا مفاجئًا شديدًا مع تغيّر وعي، لا فشل رضاعة بعد أشهر.",
},
"AS-0144": {
    "B": "<bdi>Combined contraceptive pills</bdi> قد تضبط نزيف الفايبرويد لكنها لا تصغّر حجمه؛ تناسب ضبط الأعراض بفايبرويد صغير.",
    "C": "<bdi>IUD</bdi> (حتى نوع <bdi>levonorgestrel</bdi>) قد يقلل النزيف لكنه لا يصغّر الفايبرويد، والفايبرويد الكبير المشوّه لتجويف الرحم يجعل تثبيته غير موثوق.",
    "D": "<bdi>Progestogens</bdi> قد تقلل النزيف لكنها لا تصغّر الفايبرويد بشكل موثوق، وبعض الفايبرويدات تكبر تحت تأثير <bdi>progesterone</bdi>.",
},
"AS-0147": {
    "A": "<bdi>Heartburn</bdi> عرض حميد شائع سببه <bdi>progesterone</bdi> يرخي <bdi>lower esophageal sphincter</bdi>؛ لا يتنبأ بشيء.",
    "B": "<bdi>Ankle edema</bdi> المعتمد على الجاذبية فسيولوجي بالحمل؛ يصبح مهمًا فقط مع ضغط مرتفع أو <bdi>proteinuria</bdi> (<bdi>pre-eclampsia</bdi>).",
    "C": "<bdi>Abdominal pain</bdi> غير نوعي (ألم الرباط المدوّر، أسباب هضمية) وهو منبئ أضعف من النزيف؛ يصبح مهمًا عند اجتماعه مع نزيف (<bdi>abruption</bdi>, إجهاض, <bdi>ectopic</bdi>).",
},
"AS-0148": {
    "A": "<bdi>Bicornuate uterus</bdi> يسبب فقدانًا متكررًا ومخاضًا مبكرًا وسوء وضعية، عادة بانقباضات مؤلمة لا توسع صامت بدون ألم.",
    "B": "<bdi>Submucous fibroid</bdi> مرتبط بإجهاض مبكر ونزيف وألم، لا بتمزق أغشية صامت بالثلث الثاني.",
    "C": "<bdi>Intrauterine adhesions</bdi> (<bdi>Asherman syndrome</bdi>) تعطي <bdi>hypomenorrhea</bdi>/انقطاع طمث أو عقم أو فقدان مبكر متكرر بعد تداخل رحمي.",
},
"AS-0148B": {
    "A": "<bdi>Septic abortion</bdi> يحتاج حمى وإفرازات كريهة وألم رحمي، وكل هذا غير موجود هنا.",
    "B": "<bdi>Threatened abortion</bdi> يكون بنزيف مع عنق رحم <bdi>مغلق</bdi>، وعادة بالثلث الأول؛ هنا العنق مفتوح وبدون نزيف.",
    "C": "<bdi>Incomplete abortion</bdi> يعني نزيف مع طرد جزئي للمحتويات وعنق مفتوح؛ هنا الجنين ما زال حي بالرحم ولم يُطرد شيء.",
},
"AS-0150": {
    "A": "استبعاد الوجبات الخفيفة وأخذ 3 وجبات ثقيلة فقط يسبب تقلبات سكر وهبوطًا بمضخة <bdi>insulin</bdi>، ولا يعالج ارتفاع <bdi>HbA1c</bdi>.",
    "B": "<bdi>ARBs</bdi> لها تأثير تشويهي مثل <bdi>ACE inhibitors</bdi> بالضبط؛ كلاهما يجب إيقافه والتحويل لدواء آمن بالحمل (<bdi>labetalol</bdi>, <bdi>nifedipine</bdi>, <bdi>methyldopa</bdi>). صحيح فقط كبديل لسعال <bdi>ACE inhibitor</bdi> بغير حامل.",
    "C": "<bdi>Statins</bdi> ممنوعة بالحمل وبمن تخطط للحمل.",
},
"AS-0151": {
    "A": "<bdi>Obesity</bdi> يرفع خطر الإجهاض بشكل خفيف، لكنه عامل خطر لا السبب الأكثر شيوعًا.",
    "B": "نقص <bdi>folate</bdi> مرتبط أساسًا بـ<bdi>neural tube defects</bdi>، لا بأغلب الإجهاضات.",
    "C": "<bdi>Cervical incompetence</bdi> تسبب فقدانًا بالثلث <bdi>الثاني</bdi> بدون ألم (16-24 أسبوع)، لا إجهاض الثلث الأول.",
},
"AS-0151B": {
    "B": "<bdi>Cervical incompetence</bdi> تسبب فقدانًا بالثلث <bdi>الثاني</bdi>، لا إجهاضات متكررة بالثلث الأول.",
    "C": "تشوهات الرحم التشريحية قد تساهم بالفقدان المتكرر لكنها أقل شيوعًا من <bdi>APS</bdi> بهذا السيناريو الكلاسيكي. صحيحة لو أظهرت الصور تشوهًا تشريحيًا واضحًا.",
},
"AS-0155": {
    "A": "<bdi>Viral hepatitis</bdi> الحاد يعطي توعك وقيء وألم بالربع العلوي الأيمن وترانساميناز بمئات أو آلاف، لا صورة يغلب عليها ارتفاع <bdi>ALP</bdi> مع حكة.",
    "B": "<bdi>HELLP</bdi> يحتاج انحلال دم و<bdi>platelets منخفضة</bdi>، غالبًا مع ضغط مرتفع وألم شرسوفي؛ <bdi>platelets</bdi> هنا 160 وبدون ألم أو ضغط مرتفع مذكور.",
    "C": "<bdi>Budd-Chiari syndrome</bdi> يعطي ألمًا بالربع العلوي الأيمن وتضخم كبد طري و<bdi>ascites</bdi> بمريضة فرط تخثر؛ لا ألم هنا.",
},
"AS-0158": {
    "A": "<bdi>Oxytocin</bdi> لتسريع مخاض <bdi>breech</bdi> غير مناسب؛ يدفع جنينًا بوضع غير صحيح نحو ولادة مهبلية خطيرة. يناسب مخاضًا رأسيًا نشطًا بانقباضات غير كافية.",
    "B": "الانتظار ساعتين أخرى يناسب مخاضًا رأسيًا لم يصل لمعايير التوقف؛ هنا وضع <bdi>breech</bdi> نفسه هو المؤشر، فالتأخير لا يضيف شيء.",
    "D": "<bdi>External cephalic version</bdi> تُعرض تقريبًا بين 36-37 أسبوع قبل المخاض بأغشية سليمة؛ بمخاض فعلي لا تعد خيارًا.",
},
"AS-0159": {
    "A": "<bdi>Oxytocin</bdi> لمخاض رأسي نشط بانقباضات غير كافية؛ تحفيز مخاض <bdi>breech</bdi> غير المتقدم يحمل خطر انحباس الرأس ومشاكل بالحبل السري.",
    "B": "الانتظار يناسب مخاضًا رأسيًا لم تُستنفذ مدته؛ هنا وضع <bdi>breech</bdi> نفسه هو المؤشر، فالانتظار يؤخر <bdi>CS</bdi> اللازمة فقط.",
    "D": "<bdi>ECV</bdi> تُعرض قبل المخاض (36-37 أسبوع تقريبًا)؛ بمخاض فعلي وعنق متوسع لا تعد خيارًا مناسبًا.",
},
"AS-0160": {
    "B": "<bdi>Myomectomy</bdi> بالحمل يُتجنّب بسبب خطر نزيف شديد وفقدان الحمل؛ <bdi>red degeneration</bdi> تتحسّن بدون جراحة.",
    "C": "لا يوجد مؤشر ولادي للولادة؛ <bdi>cesarean section</bdi> يكون لضيق جنيني أو مؤشر آخر، لا لتدهور الفايبرويد.",
    "D": "الولادة لا تعالج <bdi>red degeneration</bdi>، وتحفيز المخاض بعمر 34 أسبوع يضيف خطر الخداج بدون فائدة؛ <bdi>induction</bdi> لمؤشرات ولادية محددة كتجاوز الموعد أو تمزق الأغشية بـ<bdi>term</bdi>.",
},
"AS-0171": {
    "A": "3 أسابيع قبل 21 يوم (أو قريبًا منه) تقع ضمن فترة خطر <bdi>VTE</bdi> الأعلى؛ <bdi>COCs</bdi> لا تُبدأ بهذه الفترة عمومًا.",
    "C": "9 أسابيع ليست نقطة فصل معيارية؛ المبدأ المعتمد هو 42 يوم (6 أسابيع) كحد عدم وجود قيد خاص بعد الولادة.",
    "D": "12 أسبوع أطول من اللازم وليست نقطة فصل معيارية بالمصادر القياسية لبدء <bdi>COCs</bdi> بعد الولادة.",
},
}

HIGHLIGHT_TERMS = {
"AS-0084": ["24-week", "monochorionic twin pregnancy", "twin-to-twin transfusion syndrome (TTTS)"],
"AS-0085": ["12-week", "monochorionic twin pregnancy", "twin-to-twin transfusion syndrome (TTTS)"],
"AS-0100": ["Fishy Smell Vaginal Discharge", "Clue Cells And Positive Whiff Test"],
"AS-0102": ["Cough And Dyspnea", "Bilateral Rhonchi", "Allergy History"],
"AS-0109": ["HPV", "cervical cancer"],
"AS-0111": ["multiple sexual transmitted diseases", "37th gestational week", "conjunctivitis and blindness in the newborn"],
"AS-0113": ["infertility for 6 years", "severe dysmenorrhea unrelieved by naproxen"],
"AS-0115": ["spontaneous abortion", "PPROM at 28 weeks"],
"AS-0116": ["exhausted", "+2 station", "late deceleration"],
"AS-0117": ["type 2 deceleration", "+2 station", "Severe bleeding"],
"AS-0118": ["falling from a bicycle", "bluish hematoma", "left labia"],
"AS-0124": ["28-week pregnant", "medically and surgically free", "shortness of breath with exertion", "Physical examination is unremarkable"],
"AS-0125": ["38 weeks", "intrauterine growth restriction (IUGR)", "amniotic fluid index (AFI) of 3 cm", "Absent end diastolic flow"],
"AS-0126": ["24 weeks", "didn't receive rubella vaccine"],
"AS-0128": ["primigravida", "36-weeks", "headache, blurred vision", "160/110 mmHg", "Protein ++"],
"AS-0129": ["32-weeks", "seizures", "160/110 mmHg", "Protein +++"],
"AS-0130": ["35 GA", "Fetal weight is below the 10th centile", "Amniotic fluid Index is 3", "Umbilical artery end diastolic flow is absent"],
"AS-0141": ["failure to breastfeed", "severe postpartum hemorrhage"],
"AS-0144": ["reduce the size of the uterine fibroid prior to"],
"AS-0147": ["recurrent pregnancy loss", "best predictor for pregnancy complication"],
"AS-0148": ["18 weeks", "painless expulsion"],
"AS-0148B": ["22 weeks", "short soft cervix", "1.5 cm dilated with herniation of fetal membranes"],
"AS-0150": ["type 1 diabetes", "HbA1C 8.0", "prevent congenital malformation"],
"AS-0151": ["first trimester miscarriage"],
"AS-0151B": ["3 consecutive miscarriage first trimester"],
"AS-0155": ["30-week pregnant", "pruritus and jaundice", "Platelets count 160", "Alkaline phosphatase 700"],
"AS-0158": ["38th week", "4 cm dilation", "complete breech", "CTG is reactive", "no change"],
"AS-0159": ["38th week", "4 cm dilation", "\"breech\" presentation", "no change"],
"AS-0160": ["uterine fibroid", "34 weeks", "abdominal pain and fever", "cervix is closed", "no uterine contractions"],
"AS-0171": ["postpartum", "not breastfeeding", "combined oral contraceptive pills (COCs)"],
}
