# -*- coding: utf-8 -*-
# Batch r01 — slice abosarah2026/data/slices/r01.json (141 questions)

EXPLANATIONS = {
"AS-0001": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "هذا سيناريو <bdi>near-miss wrong-site surgery</bdi>، والسؤال يبي <bdi>الإجراء الوقائي</bdi> الصحيح حسب <bdi>Universal Protocol</bdi> و<bdi>WHO Surgical Safety Checklist</bdi>، مو بس اللي كشف الخطأ هالمرة بالصدفة.",
    "clues": [
        ("wrong leg", "<bdi>near-miss wrong-site surgery</bdi>"),
        ("how to prevent", "السؤال يبي <bdi>إجراء وقائي</bdi> نظامي، مو وصف اللي كشف الخطأ بالصدفة"),
    ],
    "why_correct": [
        "<bdi>proper site marking</bdi> قبل <bdi>surgery</bdi> هي خطوة <bdi>prevention</bdi> الأساسية حسب <bdi>Universal Protocol</bdi>: الجراح نفسه يحدد مكان <bdi>surgery</bdi> بعلامة واضحة قبل دخول المريض لغرفة العمليات، والأفضل والمريض واعي يأكد المكان.",
        "بعد التحديد تجي خطوة <bdi>time-out</bdi> قبل الشق مباشرة مع الفريق كامل، كتأكيد أخير.",
        "مراجعة الملف (الخيار B) فعلاً كشفت <bdi>error</bdi> بهذا <bdi>case</bdi>، بس هي خطوة تحقق متأخرة وغير موثوقة لوحدها، مو <bdi>الإجراء المعياري</bdi> للوقاية من الأساس.",
    ],
    "when_changes": [
        "لو السؤال يبي <bdi>الخطوة الفورية</bdi> اللي تمنع الشق لحظة اكتشاف <bdi>error</bdi> (مو الوقاية الأصلية)، يصير الجواب وقف <bdi>procedure</bdi> فورًا والتحقق الجماعي (<bdi>time-out</bdi>).",
        "لو السؤال يركز على مين يتحمل <bdi>responsibility</bdi> الإبلاغ عن الشك، الجواب يصير إن أي عضو بالفريق (حتى الممرضة) لازم يتكلم فورًا بدون تردد.",
    ],
    "rule": "أي سؤال «كيف نمنع» <bdi>wrong-site surgery</bdi>، الجواب المعياري دايمًا <bdi>site marking</bdi> قبل <bdi>surgery</bdi> ضمن <bdi>Universal Protocol</bdi>، مو خطوة <bdi>detection</bdi> اللي حصلت بالصدفة بالسيناريو.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0045": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "السؤال عن <bdi>clinical privileges</bdi>: جراح أكمل <bdi>fellowship</bdi> وطالب يمارس <bdi>complex spinal surgeries</bdi>، وش أساس منح الصلاحية.",
    "clues": [
        ("completed a fellowship in spinal surgery", "<bdi>training</bdi> مكتمل، بس هذا لوحده مو كافي"),
        ("requesting clinical privileges", "السؤال عن أساس منح <bdi>privileges</bdi>"),
    ],
    "why_correct": [
        "<bdi>clinical privileges</bdi> تُمنح على أساس <bdi>demonstrated competence</bdi> الحالية لنفس <bdi>procedure</bdi> المطلوبة، مو على الألقاب أو سنوات الخبرة.",
        "لازم تقييم <bdi>performance</bdi> و<bdi>competency</bdi> الفعلية قبل منح <bdi>certification</bdi>/<bdi>privileges</bdi> — زي مراجعة <bdi>case logs</bdi> وتقييمات البرنامج وفترة <bdi>proctored evaluation</bdi>.",
        "فالجواب تقييم <bdi>competency</bdi> قبل <bdi>certification</bdi>، مو مجرد الشهادة أو الخبرة العامة.",
    ],
    "when_changes": [
        "لو السؤال يقول إن عنده <bdi>documented competence</bdi> و<bdi>case logs</bdi> كافية، الجواب يصير منح <bdi>privileges</bdi> مباشرة.",
        "لو ما فيه أي تقييم <bdi>performance</bdi> أصلاً، الجواب يرفض المنح لحد يصير فيه تقييم.",
    ],
    "rule": "<bdi>credentialing</bdi> و<bdi>privileging</bdi> أساسها <bdi>competence</bdi> مو <bdi>certificate</bdi> أو سنوات الخبرة؛ لازم تقييم <bdi>performance</bdi> فعلي لنفس <bdi>procedure</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0250": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "السؤال عن <bdi>death certificate</bdi>: المريض مات بسبب سلسلة أحداث بعد <bdi>CABG</bdi>، والمطلوب تحديد <bdi>primary cause of death</bdi> المسجل.",
    "clues": [
        ("surgical site infection that progressed to septicemia", "هذا هو <bdi>disease process</bdi> اللي أدى مباشرة لـ<bdi>multiorgan failure</bdi>"),
        ("primary cause of death in his death certificate", "يبي السبب اللي يُكتب بالشهادة، مو <bdi>mode of dying</bdi>"),
    ],
    "why_correct": [
        "<bdi>Septicemia</bdi> هي اللي قادت مباشرة إلى <bdi>multiorgan failure</bdi> المُميت؛ و<bdi>multiorgan failure</bdi> نفسه <bdi>mode of dying</bdi> فقط، ما يُقبل كـ<bdi>cause</bdi> مستقل.",
        "سلسلة <bdi>death certificate</bdi>: <bdi>ischemic heart disease</bdi> ثم <bdi>CABG</bdi> ثم <bdi>surgical site infection</bdi> ثم <bdi>septicemia</bdi> ثم <bdi>multiorgan failure</bdi> ثم <bdi>death</bdi>.",
        "هذا الـ<bdi>recall</bdi> يعتمد <bdi>septicemia</bdi> كالسبب المسجل لأنه <bdi>disease process</bdi> المباشر الذي أدى للوفاة.",
    ],
    "when_changes": [
        "لو السؤال يحدد «<bdi>underlying cause</bdi>» بوضوح، الجواب حسب <bdi>WHO definition</bdi> يصير <bdi>ischemic heart disease</bdi> (بداية السلسلة).",
        "لو السؤال يقول «<bdi>immediate</bdi>» أو «<bdi>direct</bdi>»، نروح لأعلى السلسلة (<bdi>septicemia</bdi>/<bdi>multiorgan failure</bdi>).",
    ],
    "rule": "في <bdi>death certificate</bdi>: لو السؤال «<bdi>immediate</bdi>» اطلع لأعلى السلسلة، لو «<bdi>underlying</bdi>» اطلع لأسفلها؛ و<bdi>procedures</bdi> و<bdi>modes of dying</bdi> لا تُكتب كسبب مستقل.",
    "comparison": None,
    "labs": None,
    "guideline_note": "هذا السؤال مُصنّف <bdi>Debated in source</bdi>: بعض النسخ تعتمد <bdi>ischemic heart disease</bdi> كالجواب حسب <bdi>underlying cause (WHO)</bdi>، لكن المصدر اعتمد <bdi>septicemia</bdi> كالجواب المؤكد — نحتفظ بإجابة المصدر <bdi>A</bdi>.",
},
"AS-0319": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "امرأة حامل <bdi>competent</bdi> رفضت <bdi>Caesarean section</bdi> لـ<bdi>Cephalo-pelvic Disproportion</bdi> بعد ما فُسّر لها <bdi>indication</bdi> بالكامل.",
    "clues": [
        ("the mother refused to do the surgery", "رفض <bdi>informed</bdi> من مريضة <bdi>competent</bdi>"),
    ],
    "why_correct": [
        "المرأة <bdi>competent</bdi> وفُهّمت <bdi>indication</bdi> كاملة، فلها حق <bdi>autonomy</bdi> في رفض <bdi>surgery</bdi> حتى لو فيه خطر على <bdi>fetus</bdi>.",
        "<bdi>maternal autonomy</bdi> تُحترم فوق <bdi>fetal interest</bdi>، فالفريق يوثّق الرفض <bdi>informed</bdi> ويستمر بأفضل <bdi>care</bdi> تقبله ويعطيها فرصة تغيّر رأيها.",
    ],
    "when_changes": [
        "لو المريضة فاقدة <bdi>capacity</bdi> (مثلاً فقدان وعي)، الجواب يصير <bdi>emergency treatment</bdi> بدون <bdi>consent</bdi> لإنقاذ الحياة.",
        "لو الزوج هو من يرفض بس المريضة <bdi>competent</bdi> وتوافق، رأي الزوج لا يُعتد به إطلاقًا.",
    ],
    "rule": "مريضة <bdi>competent</bdi> + رفض <bdi>informed</bdi> = نحترم قرارها حتى مع خطر على <bdi>fetus</bdi> أو <bdi>life</bdi>؛ لا الزوج ولا الطاقم يقدر يفرض <bdi>surgery</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0320": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "زوج مات وعنده <bdi>frozen sperms</bdi>، والزوجة تبي تستخدمها بعد وفاته — السؤال عن <bdi>Islamic/Saudi ART regulations</bdi> لـ<bdi>posthumous</bdi> استخدام.",
    "clues": [
        ("frozen sperms", "<bdi>assisted reproduction</bdi> محفوظة من زوج"),
        ("the husband died", "<bdi>marriage contract</bdi> انتهى بالوفاة"),
    ],
    "why_correct": [
        "بوفاة الزوج ينتهي <bdi>marriage contract</bdi>، و<bdi>assisted reproduction</bdi> بالنظام السعودي مسموح فقط بين زوج وزوجة في <bdi>valid marriage</bdi> قائم.",
        "لذلك لا يمكن للزوجة استخدام <bdi>sperms</bdi> المجمدة بعد وفاة زوجها، ويجب التخلص منها حسب <bdi>regulations</bdi>.",
    ],
    "when_changes": [
        "لو السؤال في <bdi>Western jurisdiction</bdi> وفيه <bdi>prior written consent</bdi> من الزوج، ممكن يُسمح بـ<bdi>posthumous use</bdi> هناك — بس هذا غير مطبّق بالسعودية.",
        "لو الزوج طلّق الزوجة قبل الوفاة، نفس المبدأ: انتهاء <bdi>marriage</bdi> يمنع الاستخدام.",
    ],
    "rule": "قاعدة <bdi>Saudi ART</bdi>: استخدام <bdi>gametes</bdi>/<bdi>embryos</bdi> فقط بين زوج وزوجة أحياء في <bdi>valid marriage</bdi>؛ الوفاة أو الطلاق يوقف الاستخدام حتى لو فيه <bdi>consent</bdi> سابق.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0325": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "<bdi>military</bdi> مريض يطلب <bdi>sick leave</bdi> لمدة أسبوعين بسبب <bdi>low back pain</bdi>، والفحص <bdi>normal</bdi> بالكامل — السؤال عن <bdi>appropriate management</bdi>.",
    "clues": [
        ("low back pain", "<bdi>symptom</bdi> بدون <bdi>objective findings</bdi>"),
        ("requests two weeks of sick leave", "طلب <bdi>sick leave</bdi> غير مبرر بالفحص"),
        ("muscle power is normal, there are no neurological deficits", "فحص <bdi>reassuring</bdi>، لا <bdi>red flags</bdi>"),
    ],
    "why_correct": [
        "الفحص <bdi>reassuring</bdi>: <bdi>normal muscle power</bdi>، لا <bdi>neurological deficit</bdi>، يجلس بارتياح — هذا <bdi>mechanical low back pain</bdi> بسيط لا يستدعي <bdi>sick leave</bdi> أسبوعين.",
        "الطبيب يرفض <bdi>sick leave</bdi> غير المبرر لكنه يستمر بعلاج <bdi>symptom</bdi>، فينصح بـ<bdi>muscle relaxation exercises</bdi> والنشاط.",
    ],
    "when_changes": [
        "لو ظهرت <bdi>red flags</bdi> (مثل <bdi>neurological deficit</bdi> أو <bdi>saddle anesthesia</bdi> أو <bdi>fever</bdi>)، الجواب يصير تحقيق أعمق (<bdi>investigation</bdi>) لا رفض بسيط.",
        "لو الفحص غير <bdi>normal</bdi> وفيه <bdi>deficit</bdi> حقيقي، يكون هناك مبرر لـ<bdi>sick leave</bdi> حسب شدة الحالة.",
    ],
    "rule": "<bdi>sick leave</bdi> شهادة <bdi>medical</bdi> تُمنح فقط لمبرر <bdi>objective</bdi>؛ مع فحص <bdi>normal</bdi> الجواب الصحيح يرفض <bdi>leave</bdi> لكنه يعالج <bdi>symptom</bdi> لا يتجاهله.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0364": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "باحثون يجمعون مرضى <bdi>Alzheimer's disease</bdi> لدراسة <bdi>fish oil</bdi> — السؤال عن <bdi>ethical framework</bdi> اللي تستخدمه <bdi>IRB</bdi> لتقييم <bdi>acceptability</bdi>.",
    "clues": [
        ("IRB", "<bdi>research ethics committee</bdi> تحكم بـ<bdi>duties</bdi> لا <bdi>outcomes</bdi> فقط"),
        ("ethical acceptability", "تقييم مبني على <bdi>rules/duties</bdi> تجاه كل مشارك"),
    ],
    "why_correct": [
        "لجان <bdi>research ethics</bdi> تحكم بـ<bdi>duties</bdi> تجاه كل مشارك: <bdi>informed consent</bdi> (خصوصًا مع مرضى <bdi>Alzheimer's</bdi> اللي قد يفقدون <bdi>capacity</bdi>)، احترام الأفراد وحماية <bdi>vulnerable</bdi> groups.",
        "هذا <bdi>duty-based reasoning</bdi> أي <bdi>Deontology</bdi>: الدراسة غير مقبولة لو خالفت هذه <bdi>duties</bdi> حتى لو <bdi>benefit</bdi> المتوقع للمجتمع كبير.",
    ],
    "when_changes": [
        "لو السؤال يسأل عن مبدأ <bdi>weighing risks vs benefits</bdi> للمجتمع ككل، يقرب لـ<bdi>Utilitarianism</bdi>، بس هذا مو ما تسأل عنه <bdi>IRB approval</bdi> بالأساس.",
        "لو السؤال عن سلوك الطبيب الفاضل لا القواعد، يصير <bdi>Virtue ethics</bdi>.",
    ],
    "rule": "مشاركون <bdi>vulnerable</bdi> + <bdi>IRB</bdi> = حماية مبنية على <bdi>duty-based (Deontology)</bdi> للأفراد، مو تعظيم <bdi>benefit</bdi> الكلي.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0380": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "جراح حذف <bdi>bleeding case</bdi> من <bdi>research report</bdi> حتى تبان نتائج <bdi>surgical procedure</bdi> أفضل — السؤال عن <bdi>ethical principle</bdi> المُنتهك.",
    "clues": [
        ("remove this case from the research report", "حذف متعمّد لبيانات حقيقية لتحسين الصورة — هذا <bdi>falsification</bdi>"),
    ],
    "why_correct": [
        "حذف <bdi>complication case</bdi> من <bdi>report</bdi> لتجميل النتائج = <bdi>falsification</bdi> متعمّدة للبيانات، وهذا انتهاك لـ<bdi>research integrity</bdi> (الصدق والدقة بالبحث).",
        "الضرر هنا في <bdi>truthfulness</bdi> للأدلة المنشورة، لا في <bdi>patient care</bdi> المباشر للمريض الذي نزف.",
    ],
    "when_changes": [
        "لو السيناريو عن تجاهل علاج <bdi>bleeding</bdi> نفسه، يصير الانتهاك <bdi>Non-maleficence</bdi> أو <bdi>Beneficence</bdi>.",
        "لو السؤال عن اختيار غير عادل للمشاركين بالدراسة، يصير <bdi>Research Justice</bdi>.",
    ],
    "rule": "<bdi>FFP misconduct</bdi> (<bdi>Fabrication</bdi>, <bdi>Falsification</bdi>, <bdi>Plagiarism</bdi>) كلها انتهاك لـ<bdi>research integrity</bdi>؛ حذف أو تعديل بيانات حقيقية = <bdi>Falsification</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0404": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طبيب غيّر بعض <bdi>data</bdi> الحقيقية وحذف أجزاء من <bdi>results</bdi> قبل النشر — السؤال عن تسمية هذا <bdi>misconduct</bdi>.",
    "clues": [
        ("made some changes to some of the data", "تعديل <bdi>data</bdi> حقيقية موجودة"),
        ("omitted other parts of his results", "حذف انتقائي لنتائج حقيقية"),
    ],
    "why_correct": [
        "عمل على <bdi>data</bdi> حقيقية جمعها بالفعل، بس <bdi>changed</bdi> بعضها و<bdi>omitted</bdi> أجزاء منها — هذا تعريف <bdi>Falsification</bdi> بالضبط.",
        "التلاعب أو الحذف الانتقائي لبيانات حقيقية حتى لا تعكس الواقع هو <bdi>Falsification</bdi>، لا اختراع بيانات جديدة.",
    ],
    "when_changes": [
        "لو اخترع <bdi>data</bdi> من الصفر (لم تكن موجودة أصلًا)، الجواب يصير <bdi>Fabrication</bdi>.",
        "لو أخذ نتائج أو كلام باحث آخر وقدّمها كأنها له، الجواب يصير <bdi>Plagiarism</bdi>.",
    ],
    "rule": "<bdi>Fabrication</bdi> = اختراع، <bdi>Falsification</bdi> = تعديل أو حذف بيانات حقيقية، <bdi>Plagiarism</bdi> = سرقة الفضل؛ كلمة «changed/omitted» تدل على <bdi>Falsification</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0428": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "فتاة <bdi>16 y/o</bdi> حامل تبي معلومات عن <bdi>abortion</bdi> لأسباب <bdi>financial</bdi> و<bdi>educational</bdi>، وهذا يخالف رأي الطبيب الشخصي.",
    "clues": [
        ("16 y/o", "مريضة <bdi>minor/adolescent</bdi> تطلب معلومة عن <bdi>her own care</bdi>"),
        ("against doctor idea", "رأي الطبيب الشخصي لا يمنع إعطاء <bdi>information</bdi>"),
    ],
    "why_correct": [
        "رأي الطبيب الشخصي (<bdi>against doctor idea</bdi>) ما يصح يمنع وصول المريضة لمعلومة دقيقة؛ الواجب الأخلاقي احترام <bdi>autonomy</bdi> وإعطاء <bdi>unbiased information</bdi> كاملة عن كل الخيارات المسموحة قانونيًا.",
        "للمريضة حق المعرفة عن <bdi>care</bdi> الخاصة بها، والطبيب يدعم اتخاذ القرار دون فرض رأيه.",
    ],
    "when_changes": [
        "لو الطبيب عنده <bdi>conscientious objection</bdi> عن إجراء <bdi>procedure</bdi> نفسه، يحق له الرفض لكنه يجب أن يُحيل لزميل ويعطي <bdi>information</bdi> كاملة.",
        "لو كانت حالة <bdi>emergency</bdi> تهدد الحياة، يختلف <bdi>management</bdi> لصالح التدخل الفوري.",
    ],
    "rule": "<bdi>conscientious objection</bdi> يحدد ما تفعله أنت، لا ما تخبر به المريضة؛ احجب <bdi>information</bdi> أو <bdi>reporting</bdi> المريضة دائمًا خيار خاطئ.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0428B": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "مريضة حامل بـ<bdi>severe preeclampsia</bdi> يُنصح لها بـ<bdi>termination of pregnancy</bdi>، وكلا الوالدين رفضا — السؤال عن <bdi>management</bdi>.",
    "clues": [
        ("severe preeclampsia", "حالة خطيرة تستدعي <bdi>termination</bdi> حسب نصيحة الطبيب"),
        ("both parent refused", "رفض <bdi>informed</bdi> من المريضة (والزوج)"),
    ],
    "why_correct": [
        "الطبيب أوضح الحالة ونصح بـ<bdi>termination</bdi>، لكن المريضة (وزوجها) رفضا بعد الشرح — رفض <bdi>competent</bdi> و<bdi>informed</bdi> يُحترم حتى مع خطورة الحالة.",
        "يوثّق الطبيب الرفض ويستمر بـ<bdi>monitoring</bdi> وعلاج ضمن ما تقبله المريضة، مع إعادة طرح النقاش لاحقًا.",
    ],
    "when_changes": [
        "لو المريضة فقدت <bdi>capacity</bdi> (مثل <bdi>eclampsia</bdi> مع تشنجات)، الجواب يصير التدخل <bdi>emergency</bdi> لإنقاذ الحياة.",
        "لو الشك بوجود <bdi>genuine dilemma</bdi> حول <bdi>capacity</bdi> نفسها، يصير دور <bdi>ethical committee</bdi> مناسب.",
    ],
    "rule": "رفض <bdi>competent informed</bdi> يُحترم حتى لو مُهدد للحياة؛ لا الزوج ولا الأقارب يقرر عن مريضة <bdi>competent</bdi>، ولا يُتجاوز قرارها إلا بفقد <bdi>capacity</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0438": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طبيب <bdi>junior</bdi> بلّغ عن <bdi>misconduct</bdi> طبيب <bdi>senior</bdi> (تلاعب بـ<bdi>documentation</bdi> وإجراءات غير ضرورية للمال)، وبعدها تلقى <bdi>alarming letter</bdi> من السينيور — ما الخطوة الصحيحة؟",
    "clues": [
        ("alarming letter", "<bdi>retaliation</bdi> محتملة بعد <bdi>reporting</bdi> سليم"),
    ],
    "why_correct": [
        "الجونيور قام بالصحيح بتبليغ <bdi>misconduct</bdi>، والآن يتعرض لـ<bdi>intimidation</bdi> عبر <bdi>warning letter</bdi>.",
        "الخطوة الآمنة والمهنية توثيق <bdi>misconduct</bdi> الأصلي و<bdi>retaliation</bdi> الحالي بسجل واضح ومكتوب، وهذا يحفظ حقوقه القانونية ويدعم أي تصعيد رسمي لاحق.",
    ],
    "when_changes": [
        "لو ما فيه خطر <bdi>retaliation</bdi> وكانت القضية الأولى لم تُحل أصلًا، الجواب يصير تصعيد مباشر لـ<bdi>regulator</bdi> أو جهة رسمية أعلى.",
        "لو كانت المسألة سوء تفاهم بسيط بلا دليل <bdi>misconduct</bdi> حقيقي، يصير حوار مباشر خيارًا أوليًا مقبولًا.",
    ],
    "rule": "سلّم <bdi>whistleblowing</bdi>: وثّق الحقائق، بلّغ عبر القناة الرسمية بالمؤسسة، صعّد للجهة التنظيمية لو لم يُحل؛ عند التهديد بعد التبليغ ابدأ بالتوثيق لا الصمت ولا المواجهة الشخصية.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0497": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "دراسة <bdi>e-research</bdi> عن مرضى <bdi>gastritis</bdi> يستخدمون <bdi>NSAIDs</bdi>، والمشاركة عبر <bdi>online interview</bdi> — السؤال عن <bdi>ethical error</bdi> بهذا التصميم.",
    "clues": [
        ("e-research", "بحث <bdi>electronic</bdi> يتعامل مع بيانات صحية حساسة"),
        ("online interview", "جمع معلومات <bdi>health data</bdi> عبر الإنترنت"),
    ],
    "why_correct": [
        "المشاركة عبر <bdi>online interview</bdi> تتعامل مع بيانات صحية شخصية (<bdi>gastritis</bdi> وتأثير أدوية) — الخطر الأخلاقي الأساسي في <bdi>e-research</bdi> هو فقدان <bdi>confidentiality</bdi> أثناء الجمع أو النقل الإلكتروني.",
        "لذا <bdi>privacy</bdi> هي القلق الأخلاقي الرئيسي المستهدف بهذا <bdi>recall</bdi>.",
    ],
    "when_changes": [
        "لو السؤال عن <bdi>methodological validity</bdi> (دقة البيانات) لا أخلاقيات، يصير التركيز على <bdi>accuracy</bdi> لا <bdi>privacy</bdi>.",
        "لو السؤال يسأل عن حق الانسحاب من الدراسة، نفس الحق متوفر <bdi>online</bdi> كأي دراسة أخرى.",
    ],
    "rule": "<bdi>e-research</bdi> أو جمع بيانات <bdi>electronic</bdi> = الخطر الأخلاقي الأساسي هو <bdi>privacy/confidentiality</bdi>؛ احمِ البيانات بـ<bdi>encryption</bdi> و<bdi>anonymisation</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0517": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طبيب <bdi>internal medicine</bdi> بخبرة <bdi>10 years</bdi> يعرف أنه ضعيف في <bdi>immunology</bdi> — السؤال عن الطريقة الصحيحة للتحسين.",
    "clues": [
        ("Weak Regarding Immunology", "تحديد <bdi>knowledge gap</bdi> واضح"),
        ("Improve", "يبي طريقة <bdi>structured</bdi> للتحسين"),
    ],
    "why_correct": [
        "حدد <bdi>knowledge gap</bdi> محدد (<bdi>immunology</bdi>)، والطريقة المعتمدة لتحديث المعرفة هي <bdi>continuing medical education (CME)</bdi> المنظمة مثل حضور <bdi>conferences and workshops</bdi>.",
        "هذا يضمن تحديث <bdi>evidence-based practice</bdi> بشكل موثوق أكثر من الطرق غير الرسمية.",
    ],
    "when_changes": [
        "لو السؤال يبي حل سريع لحالة واحدة فقط، يصير سؤال <bdi>colleague</bdi> كافٍ لحظيًا.",
        "لو السؤال يركز على <bdi>self-directed learning</bdi> بدون حاجة لـ<bdi>formal accreditation</bdi>، تصير القراءة الحرة مقبولة جزئيًا.",
    ],
    "rule": "التعلم المستمر: حدد <bdi>gap</bdi> ثم استخدم <bdi>CME</bdi> منظم (<bdi>conferences</bdi>, <bdi>workshops</bdi>, <bdi>accredited courses</bdi>) لإغلاقه، لا الطرق غير الرسمية.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0518": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "نفس سيناريو AS-0517: طبيب <bdi>internal medicine</bdi> بخبرة <bdi>10 years</bdi> ضعيف في <bdi>immunology</bdi> ويبي يكون <bdi>updated</bdi> عن <bdi>latest therapies</bdi>.",
    "clues": [
        ("Updated About LATEST THERPAIES", "يبي مصدر معرفة <bdi>current</bdi> وموثوق"),
    ],
    "why_correct": [
        "حدد <bdi>knowledge gap</bdi> محدد (<bdi>immunology</bdi>) ويبي <bdi>latest therapies</bdi> — <bdi>CME</bdi> المنظمة مثل <bdi>conferences and workshops</bdi> هي الطريقة المعتمدة لمتابعة <bdi>latest evidence</bdi>.",
        "هذا أوثق من الطرق غير الرسمية لتحديث الممارسة بأحدث <bdi>therapies</bdi>.",
    ],
    "when_changes": [
        "لو كانت الحاجة لحالة <bdi>single case</bdi> وقتية، سؤال <bdi>colleagues</bdi> يكفي.",
        "لو كان الهدف <bdi>general awareness</bdi> بدون حاجة <bdi>formal accreditation</bdi>، القراءة الحرة مقبولة جزئيًا.",
    ],
    "rule": "التعلم المستمر: حدد <bdi>gap</bdi> ثم استخدم <bdi>CME</bdi> منظم (<bdi>conferences</bdi>, <bdi>workshops</bdi>) لمتابعة <bdi>latest therapies</bdi> بشكل موثوق.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-2461": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل عنده <bdi>peanut allergy</bdi> و<bdi>asthma</bdi> أخذ أدوية دون تسجيل <bdi>allergy</bdi> — اكتُشف وقت <bdi>handover</bdi>. السؤال عن <bdi>ethical principle</bdi>/<bdi>patient safety goal</bdi> الأوسع.",
    "clues": [
        ("peanut allergy", "<bdi>critical allergy</bdi> لم تُنقل بين الطاقم"),
        ("without the allergy being documented", "فشل في نقل معلومة حرجة بين الطاقم"),
    ],
    "why_correct": [
        "اكتُشف الخطأ أثناء <bdi>nurse handover</bdi>: معلومة <bdi>allergy</bdi> لم تُنقل أو تُسجل، فأخذ الطفل أدوية بالخطأ.",
        "<bdi>handover</bdi> نقطة خطر عالية لسوء <bdi>communication</bdi>، والمبدأ الأوسع المستهدف هو تحسين <bdi>communication</bdi> بين مزودي <bdi>healthcare</bdi> لضمان <bdi>patient safety</bdi>.",
        "<bdi>documentation</bdi> جزء من الحل لكنه إجراء أضيق؛ المبدأ الشامل هو <bdi>communication</bdi> الفعّالة عند <bdi>handover</bdi>.",
    ],
    "when_changes": [
        "لو كان الخطأ إعطاء دواء لمريض خاطئ، الجواب يصير استخدام <bdi>two patient identifiers</bdi>.",
        "لو كان السبب جهل العائلة بكيفية التعامل مع <bdi>allergy</bdi>، الجواب يصير <bdi>patient education</bdi>.",
    ],
    "rule": "طابق الخطأ بـ<bdi>patient safety goal</bdi> المناسب: فقدان معلومة عند <bdi>handover</bdi> = تحسين <bdi>communication</bdi>؛ مريض خاطئ = <bdi>two identifiers</bdi>؛ جهل العائلة = <bdi>education</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-2496": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "حامل بـ<bdi>last trimester</bdi> عندها علامات <bdi>severe pre-eclampsia</bdi> (<bdi>headache</bdi>, <bdi>blurred vision</bdi>, <bdi>BP</bdi> مرتفع، <bdi>CTG</bdi> متسرع) وترفض <bdi>admission</bdi> وتطلب المغادرة.",
    "clues": [
        ("refuses the admission and asked to leave the hospital", "رفض <bdi>competent</bdi> لعلاج موصى به بشدة"),
    ],
    "why_correct": [
        "<bdi>headache</bdi> و<bdi>blurred vision</bdi> مع <bdi>BP</bdi> حوالي <bdi>160/95</bdi> في <bdi>last trimester</bdi> علامات <bdi>severe pre-eclampsia</bdi>، وتسرّع <bdi>fetal heart rate</bdi> (<bdi>CTG 170</bdi>) يزيد القلق على <bdi>fetus</bdi>.",
        "بس هي <bdi>competent adult</bdi> ترفض، فالطبيب يوضح <bdi>risks</bdi> المحددة لها وللجنين (<bdi>eclampsia</bdi>, <bdi>stroke</bdi>, <bdi>abruption</bdi>) ويحاول إقناعها.",
        "لو استمرت بالرفض، تُحترم <bdi>autonomy</bdi> وتوقّع <bdi>discharge against medical advice (DAMA)</bdi> مع توثيق وفتح باب الرجوع.",
    ],
    "when_changes": [
        "لو فقدت <bdi>capacity</bdi> (مثل تشنج <bdi>eclampsia</bdi>)، الجواب يصير التدخل <bdi>emergency</bdi> بدون انتظار <bdi>consent</bdi>.",
        "لو وافقت بعد الشرح على <bdi>admission</bdi>، الجواب يصير المتابعة الروتينية بعلاج <bdi>BP</bdi> والتحضير للولادة.",
    ],
    "rule": "مع مريضة <bdi>competent</bdi> ترفض علاجًا مُشار إليه: اشرح <bdi>risks</bdi> وحاول الإقناع، وإن استمر الرفض وثّق <bdi>DAMA</bdi>؛ الخطورة الطبية لا تلغي <bdi>capacity</bdi> كمعيار التدخل.",
    "comparison": None,
    "labs": [["Blood pressure", "160/95 mmHg", "&lt;140/90 mmHg"], ["Fetal heart rate (CTG)", "170 bpm", "110-160 bpm"]],
    "guideline_note": None,
},
"AS-2537": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "فريق <bdi>trauma</bdi> بالـ<bdi>Emergency Department</bdi> يراجع <bdi>airway</bdi>, <bdi>breathing</bdi>, <bdi>circulation</bdi> بالتتابع، كل عضو يعلن الحالة بصوت عالٍ — السؤال عن نوع <bdi>communication tool</bdi> من <bdi>TeamSTEPPS</bdi>.",
    "clues": [
        ("communication", "نوع أداة <bdi>TeamSTEPPS</bdi> المستخدمة أثناء <bdi>resuscitation</bdi>"),
    ],
    "why_correct": [
        "القائد يسأل عن حالة كل عنصر حرج (<bdi>airway</bdi>, <bdi>breathing</bdi>, <bdi>circulation</bdi>) والعضو يعلن الحالة بصوت عالٍ لكل الفريق — هذا تعريف <bdi>call-out</bdi> في <bdi>TeamSTEPPS</bdi>.",
        "<bdi>call-out</bdi> يضمن سماع الكل للمعلومة الحرجة بنفس الوقت أثناء <bdi>emergency</bdi> والاستعداد للخطوة التالية.",
    ],
    "when_changes": [
        "لو كانت الممرضة تكرر الأمر ثم يؤكده الطبيب، يصير <bdi>closed-loop communication</bdi>/<bdi>check-back</bdi>.",
        "لو كان الهدف تسليم الحالة أو تصعيد قلق بصيغة منظمة، يصير <bdi>SBAR</bdi>.",
    ],
    "rule": "إعلان حالة <bdi>vitals/ABC</bdi> للفريق كامل أثناء <bdi>resuscitation</bdi> = <bdi>call-out</bdi>؛ تكرار وتأكيد الأمر = <bdi>closed-loop/check-back</bdi>؛ تسليم منظم = <bdi>SBAR</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0002": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "سؤال حساب <bdi>sensitivity</bdi> لـ<bdi>new screening test</bdi> مقابل <bdi>mammogram</bdi> كـ<bdi>reference standard</bdi>.",
    "clues": [
        ("200 women", "كل من <bdi>mammogram</bdi> صنّفهم <bdi>positive</bdi> = مرجع <bdi>disease status</bdi>"),
        ("180", "<bdi>true positives</bdi> اللي ضبطها الاختبار الجديد"),
        ("misses 20", "<bdi>false negatives</bdi>"),
        ("sensitivity", "يبي المقياس المحدد: <bdi>TP/(TP+FN)</bdi>"),
    ],
    "why_correct": [
        "<bdi>Sensitivity</bdi> = <bdi>true positives</bdi> / كل من يحمل <bdi>disease</bdi> حسب <bdi>reference standard</bdi>.",
        "<bdi>mammogram</bdi> صنّف <bdi>200</bdi> امرأة <bdi>positive</bdi>؛ الاختبار الجديد ضبط <bdi>180</bdi> منهم وفوّت <bdi>20</bdi> (<bdi>false negatives</bdi>).",
        "<bdi>sensitivity</bdi> = 180 / (180+20) = 180/200 = <bdi>90%</bdi>. الـ<bdi>50 false positives</bdi> من الـ<bdi>800</bdi> تؤثر على <bdi>specificity</bdi> لا <bdi>sensitivity</bdi>.",
    ],
    "when_changes": [
        "لو سُئل عن <bdi>Positive Predictive Value</bdi>، نستخدم 180/(180+50) ≈ 78%.",
        "لو سُئل عن <bdi>specificity</bdi>، نحسب <bdi>TN/(TN+FP)</bdi> = 750/800 ≈ 94%.",
    ],
    "rule": "<bdi>Sensitivity</bdi> و<bdi>specificity</bdi> يُقرآن من عمود <bdi>true disease status</bdi> (عمودي)، بينما <bdi>PPV/NPV</bdi> يُقرآن من صف <bdi>test result</bdi> (أفقي).",
    "comparison": {"headers": ["المقياس", "الصيغة", "القيمة"], "rows": [["Sensitivity", "TP/(TP+FN)", "180/200 = 90%"], ["Specificity", "TN/(TN+FP)", "750/800 ≈ 94%"], ["PPV", "TP/(TP+FP)", "180/230 ≈ 78%"]]},
    "labs": None,
    "guideline_note": None,
},
"AS-0007": {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "<bdi>PSA</bdi> عالميًا لـ<bdi>prostate cancer screening</bdi>، بس <bdi>low specificity</bdi> أدت لـ<bdi>overtreatment</bdi> — السؤال عن <bdi>inclusion criteria</bdi> الصحيح لاستخدامه.",
    "clues": [
        ("low specificity", "كثرة <bdi>false positives</bdi> تسبب <bdi>overdiagnosis</bdi>"),
        ("over treatment", "نتيجة مباشرة لتوسيع استخدام <bdi>PSA</bdi> بلا معايير"),
    ],
    "why_correct": [
        "لا يوجد <bdi>answer_letter</bdi> مؤكد من المصدر لهذا السؤال، فحكمنا هنا <bdi>clinical judgment</bdi> مستقل.",
        "المصدر الطبي يدعم <bdi>shared decision making</bdi> لـ<bdi>PSA screening</bdi> بالتركيز على <bdi>higher-risk groups</bdi> مثل أصحاب <bdi>family history</bdi> أو <bdi>high risk ancestry</bdi>، لتحسين <bdi>pretest probability</bdi> وتقليل <bdi>overtreatment</bdi> الناتج عن <bdi>low specificity</bdi>.",
        "هذا يقلل نسبة <bdi>false positives</bdi> لأن استخدام <bdi>PSA</bdi> في مجموعة بها انتشار أعلى يرفع <bdi>Positive Predictive Value</bdi>.",
    ],
    "when_changes": [
        "لو المريض عنده <bdi>symptoms</bdi>، يصير استخدام <bdi>PSA</bdi> لأغراض <bdi>diagnostic</bdi> لا <bdi>screening</bdi>.",
        "لو السؤال عن <bdi>general population screening</bdi> بلا تحديد خطر، الاعتماد على <bdi>shared decision making</bdi> العام لا التركيز الحصري على خطر مرتفع.",
    ],
    "rule": "<bdi>screening</bdi> يعني أشخاص بلا <bdi>symptoms</bdi>؛ مع <bdi>low specificity</bdi> كـ<bdi>PSA</bdi>، تقييد الاستخدام لذوي <bdi>higher risk</bdi> يرفع <bdi>PPV</bdi> ويقلل <bdi>overtreatment</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر نفسه لم يحسم هذا السؤال (علّمه المُجمِّع بـ«??» على الخيارين A و C)؛ اخترنا A حسب مبدأ تقليل <bdi>false positives</bdi> برفع <bdi>pretest probability</bdi>.",
},
"AS-0105": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "رجل <bdi>50-year-old</bdi> بـ<bdi>HTN</bdi> متحكم به و<bdi>hemorrhagic stroke</bdi> متعافي تمامًا، أخذ <bdi>influenza vaccine</bdi> منذ <bdi>6 months</bdi> — أي <bdi>vaccine</bdi> يُعطى الآن؟",
    "clues": [
        ("50-year-old", "العتبة العمرية لـ<bdi>recombinant zoster vaccine</bdi>"),
        ("received the seasonal influenza vaccine 6 months ago", "<bdi>influenza</bdi> مُعطى هذا الموسم، فلا حاجة لجرعة إضافية"),
    ],
    "why_correct": [
        "عمره <bdi>50</bdi>، و<bdi>recombinant zoster vaccine</bdi> موصى به لكل البالغين <bdi>immunocompetent</bdi> من عمر <bdi>50</bdi> فأكثر (<bdi>2 doses</bdi>)، بدون شرط تاريخ <bdi>chickenpox/shingles</bdi>.",
        "<bdi>HTN</bdi> و<bdi>recovered hemorrhagic stroke</bdi> ليسا <bdi>contraindication</bdi>، و<bdi>influenza</bdi> هذا الموسم مُعطى فعلًا (قبل <bdi>6 months</bdi>)، فـ<bdi>zoster vaccine</bdi> هو المستحق الآن.",
    ],
    "when_changes": [
        "لو كان عمره أقل من <bdi>50</bdi> بلا <bdi>immunocompromise</bdi>، لا يُعطى <bdi>zoster vaccine</bdi> بعد.",
        "لو كان الموسم الحالي الجديد بدون <bdi>influenza vaccine</bdi> مُعطى، يصير <bdi>influenza vaccine</bdi> المستحق.",
    ],
    "rule": "<bdi>adult vaccines</bdi> تُحدد أولًا بالعمر ثم بـ<bdi>risk conditions</bdi>: عمر <bdi>≥50</bdi> = <bdi>recombinant zoster</bdi> (<bdi>2 doses</bdi>)؛ لا يوجد «<bdi>booster</bdi>» لـ<bdi>influenza</bdi> بالبالغين، فقط جرعة سنوية واحدة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0106": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "رجل <bdi>50-year-old</bdi> عنده <bdi>COPD</bdi> — أي <bdi>vaccine</bdi> يُعطى الآن؟",
    "clues": [
        ("50-Year-Old", "العتبة العمرية لـ<bdi>recombinant zoster vaccine</bdi>"),
    ],
    "why_correct": [
        "عمر <bdi>50</bdi> هو المحرك: <bdi>recombinant zoster vaccine</bdi> موصى به لكل البالغين من عمر <bdi>50</bdi> فأكثر (<bdi>2 doses</bdi>)، و<bdi>COPD</bdi> ليس <bdi>contraindication</bdi> لأنه <bdi>non-live vaccine</bdi>.",
        "الخيارات الأخرى تفشل بذاتها: <bdi>Hepatitis A</bdi> لا دليل لاستخدامه هنا، و<bdi>influenza</bdi> بالبالغين ليس له «<bdi>booster</bdi>».",
    ],
    "when_changes": [
        "لو ذُكر أنه لم يأخذ <bdi>influenza vaccine</bdi> هذا الموسم، يصير الجواب الجرعة السنوية لـ<bdi>influenza</bdi> (مهمة جدًا مع <bdi>COPD</bdi>).",
        "لو كان عمره أصغر من <bdi>50</bdi>، <bdi>zoster vaccine</bdi> غير مستحق إلا لو <bdi>immunocompromised</bdi>.",
    ],
    "rule": "<bdi>adult vaccines</bdi>: العمر أولًا ثم <bdi>comorbidity</bdi>؛ عمر <bdi>≥50</bdi> = <bdi>recombinant zoster</bdi>؛ <bdi>COPD</bdi> يعني أهمية <bdi>annual influenza</bdi> و<bdi>pneumococcal vaccine</bdi>، لا «<bdi>booster</bdi>».",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0122": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "اختبار جديد تم تطويره لـ«يشمل حتى <bdi>missed cases</bdi>» — السؤال عن أي مقياس يرتفع.",
    "clues": [
        ("include the missed cases", "تقليل <bdi>false negatives</bdi> هو الهدف من التطوير"),
    ],
    "why_correct": [
        "اختبار جديد «يشمل حتى <bdi>missed cases</bdi>» يعني تقليل <bdi>false negatives</bdi>.",
        "<bdi>Sensitivity</bdi> = <bdi>TP/(TP+FN)</bdi>، فتقليل <bdi>false negatives</bdi> يرفع <bdi>sensitivity</bdi> — هذا المطلوب في <bdi>screening</bdi> حيث فوات حالة هو أكبر ضرر.",
    ],
    "when_changes": [
        "لو السؤال عن اختبار <bdi>confirmatory</bdi> يقلل <bdi>false positives</bdi>، الجواب يصير <bdi>specificity</bdi>.",
        "لو زاد <bdi>prevalence</bdi> بالمجتمع المُختبر، يرتفع <bdi>PPV</bdi> أيضًا لكن هذا لا يرتبط مباشرة بتقليل <bdi>missed cases</bdi>.",
    ],
    "rule": "<bdi>screening</bdi> يبحث عن <bdi>high sensitivity</bdi> (<bdi>SnNout</bdi>)؛ <bdi>confirmation</bdi> يبحث عن <bdi>high specificity</bdi> (<bdi>SpPin</bdi>)؛ <bdi>PPV/NPV</bdi> يتغيران مع <bdi>prevalence</bdi> لا <bdi>sensitivity/specificity</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0316": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "تكرار لنفس سؤال AS-0105: رجل <bdi>50-year-old</bdi> بـ<bdi>HTN</bdi> و<bdi>hemorrhagic stroke</bdi> متعافي، أخذ <bdi>influenza vaccine</bdi> منذ <bdi>6 months</bdi>.",
    "clues": [
        ("50-year-old", "العتبة العمرية لـ<bdi>recombinant zoster vaccine</bdi>"),
        ("received the seasonal influenza vaccine 6 months ago", "<bdi>influenza</bdi> مُعطى فعلًا هذا الموسم"),
    ],
    "why_correct": [
        "عمره <bdi>50</bdi>، فـ<bdi>recombinant zoster vaccine</bdi> موصى به لكل البالغين من عمر <bdi>50</bdi> فأكثر (<bdi>2 doses</bdi>).",
        "<bdi>HTN</bdi> و<bdi>recovered hemorrhagic stroke</bdi> ليسا <bdi>contraindication</bdi>، و<bdi>influenza</bdi> هذا الموسم مُعطى فعلًا، فـ<bdi>zoster vaccine</bdi> هو المستحق.",
    ],
    "when_changes": [
        "لو كان عمره أقل من <bdi>50</bdi>، لا يُعطى <bdi>zoster vaccine</bdi>.",
        "لو لم يُعط <bdi>influenza</bdi> هذا الموسم، يصير هو المستحق.",
    ],
    "rule": "<bdi>adult vaccines</bdi> تُحدد أولًا بالعمر ثم بـ<bdi>risk conditions</bdi>: عمر <bdi>≥50</bdi> = <bdi>recombinant zoster</bdi>؛ لا «<bdi>booster</bdi>» لـ<bdi>influenza</bdi> بالبالغين.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0361": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "تكرار لنفس مفهوم AS-0122: اختبار جديد طُوّر «ليشمل حتى <bdi>missed cases</bdi>» — أي مقياس يرتفع.",
    "clues": [
        ("even include the missed cases", "تقليل <bdi>false negatives</bdi> هو الهدف"),
    ],
    "why_correct": [
        "اختبار جديد يشمل <bdi>missed cases</bdi> يعني تقليل <bdi>false negatives</bdi>، وهذا يرفع <bdi>sensitivity</bdi> = <bdi>TP/(TP+FN)</bdi>.",
        "هذا المطلوب في <bdi>screening</bdi> لتجنب فوات الحالات.",
    ],
    "when_changes": [
        "لو كان الهدف تقليل <bdi>false positives</bdi>، الجواب يصير <bdi>specificity</bdi>.",
    ],
    "rule": "<bdi>screening</bdi> = <bdi>high sensitivity</bdi>؛ <bdi>confirmation</bdi> = <bdi>high specificity</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0365": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "دراسة على <bdi>1000 people</bdi> لمدة <bdi>one year</bdi>، <bdi>15</bdi> منهم أصيبوا بـ<bdi>breast cancer</bdi> — كيف تُفسّر <bdi>incidence</bdi> هذي؟",
    "clues": [
        ("1000 people for one year", "<bdi>denominator</bdi> + <bdi>time period</bdi>"),
        ("15 of them developed", "<bdi>new cases</bdi> = <bdi>numerator</bdi> لـ<bdi>incidence</bdi>"),
        ("incidence", "يحدد الصيغة الصحيحة"),
    ],
    "why_correct": [
        "<bdi>Incidence</bdi> = <bdi>new cases</bdi> في <bdi>population at risk</bdi> خلال <bdi>defined time period</bdi>.",
        "هنا <bdi>15 new cases</bdi> من <bdi>1000 people</bdi> خلال <bdi>one year</bdi> = <bdi>15 per 1000 per year</bdi>.",
        "فقط الخيار D يحافظ على الثلاث عناصر: <bdi>numerator</bdi>, <bdi>denominator</bdi>, و<bdi>time</bdi>.",
    ],
    "when_changes": [
        "لو السؤال عن <bdi>prevalence</bdi> (عدد من «<bdi>have</bdi>» المرض حاليًا)، الصيغة تختلف ولا تحتاج <bdi>time period</bdi> محدد.",
    ],
    "rule": "<bdi>Incidence</bdi> = <bdi>new cases / population at risk / time</bdi>؛ كلمة «<bdi>develop</bdi>» تدل على <bdi>incidence</bdi> وكلمة «<bdi>have</bdi>» تدل على <bdi>prevalence</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0424": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "<bdi>case-control study</bdi> بين <bdi>cesarean section</bdi> و<bdi>type 1 diabetes</bdi> — حساب <bdi>odds ratio</bdi>.",
    "clues": [
        ("case-control study", "نستخدم <bdi>odds ratio</bdi> لا <bdi>relative risk</bdi>"),
        ("80 were delivered by cesarean section and 120 by vaginal delivery", "بيانات <bdi>cases</bdi> (مرضى <bdi>T1DM</bdi>)"),
        ("160 were delivered by cesarean section and 40 by vaginal delivery", "بيانات <bdi>controls</bdi>"),
        ("odds ratio", "الصيغة: (a×d)/(b×c)"),
    ],
    "why_correct": [
        "<bdi>Odds ratio</bdi> بـ<bdi>case-control study</bdi> = (a × d) / (b × c).",
        "هذا الـ<bdi>recall</bdi> يعتمد <bdi>vaginal delivery</bdi> كـ<bdi>exposure</bdi>: (120 × 160) / (80 × 40) = 19200/3200 = <bdi>6</bdi>.",
        "لو اعتُمد <bdi>cesarean section</bdi> كـ<bdi>exposure</bdi> كما ينص السؤال حرفيًا، تكون النتيجة معكوسة (1/6 ≈ 0.17) وهي غير متوفرة بالخيارات، مما يرجّح أن هذا <bdi>recall</bdi> بدّل التسميات.",
    ],
    "when_changes": [
        "لو اعتُمدت <bdi>cesarean section</bdi> كـ<bdi>exposure</bdi> بشكل صحيح حسب نص السؤال، الناتج يصير <bdi>1/6 ≈ 0.17</bdi> (<bdi>protective</bdi>).",
    ],
    "rule": "<bdi>OR = (a×d)/(b×c)</bdi> في <bdi>case-control study</bdi>؛ عكس تسمية <bdi>exposure</bdi> يعكس <bdi>OR</bdi> (مثل <bdi>6</bdi> تصير <bdi>1/6</bdi>).",
    "comparison": {"headers": ["", "CS", "Vaginal"], "rows": [["T1DM (cases)", "80 (a)", "120 (b)"], ["No T1DM (controls)", "160 (c)", "40 (d)"]]},
    "labs": None,
    "guideline_note": "هذا السؤال فيه تضارب محتمل بترتيب <bdi>exposure</bdi>؛ احتفظنا بإجابة المصدر <bdi>D (6)</bdi> كما جاءت.",
},
"AS-0445": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "مريض <bdi>diabetic</bdi> و<bdi>hypertensive</bdi> مع <bdi>well controlled</bdi> لكنه فوّت مواعيد كثيرة — أي <bdi>quality domain</bdi> يحاول الطبيب تحقيقه؟",
    "clues": [
        ("missed multiple appointments", "مشكلة <bdi>engagement</bdi> لا نتيجة <bdi>clinical</bdi>"),
        ("medical value", "يبي أحد مجالات <bdi>IOM quality</bdi>"),
    ],
    "why_correct": [
        "مرضه <bdi>well controlled</bdi>، فالقلق ليس النتيجة <bdi>clinical</bdi> بل أنه «فوّت مواعيد متعددة» — الطبيب يريد إشراكه واستكشاف حواجزه وتفضيلاته.",
        "رعاية تحترم وتستجيب لحاجات المريض الفردية وقيمه هي <bdi>patient centredness</bdi> ضمن مجالات <bdi>IOM (STEEEP)</bdi>.",
    ],
    "when_changes": [
        "لو كان السبب إهدار موارد أو وقت بالعيادة، يصير <bdi>Efficiency</bdi>.",
        "لو كان السبب تأخير النظام نفسه بمواعيد العيادة، يصير <bdi>Timeliness</bdi>.",
    ],
    "rule": "<bdi>IOM quality domains (STEEEP)</bdi>: تحكم <bdi>clinical</bdi> جيد مع ضعف الحضور/الالتزام = <bdi>patient centredness</bdi>؛ تأخير نظامي = <bdi>timeliness</bdi>.",
    "comparison": None,
    "labs": [["HbA1c", "7.2%", "&lt;7% (individualized target)"]],
    "guideline_note": None,
},
"AS-0478": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "دراسة <bdi>colon cancer</bdi> بمجتمع <bdi>100,000</bdi>: <bdi>existing cases 300</bdi>, <bdi>new cases 75</bdi> — حساب <bdi>cumulative prevalence</bdi>.",
    "clues": [
        ("100,000", "<bdi>denominator</bdi>"),
        ("Existing cases: 300, New cases: 75", "يُجمعان سوا لـ<bdi>cumulative prevalence</bdi>"),
        ("cumulative prevalence", "يحدد الصيغة: <bdi>existing + new</bdi>"),
    ],
    "why_correct": [
        "«<bdi>Cumulative</bdi>» (<bdi>period</bdi>) <bdi>prevalence</bdi> تحسب كل من كان مصاب خلال الفترة: <bdi>existing</bdi> زائد <bdi>new</bdi>.",
        "(300 + 75) / 100,000 = 375/100,000 = <bdi>0.375%</bdi> (= 3.75 لكل 1000).",
    ],
    "when_changes": [
        "لو سُئل عن <bdi>point prevalence</bdi> فقط، نستخدم <bdi>existing cases</bdi> فقط (300/100,000 = 0.3%).",
        "لو سُئل عن <bdi>incidence</bdi>، نستخدم <bdi>new cases / population at risk</bdi> (75/99,700 تقريبًا).",
    ],
    "rule": "<bdi>cumulative (period) prevalence</bdi> = <bdi>(existing + new) / population</bdi>؛ <bdi>point prevalence</bdi> = <bdi>existing only / population</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0478B": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "عيادة تدرس <bdi>migraine prevalence</bdi> بين <bdi>200 adult patients</bdi> حضروا يوم معين، <bdi>75</bdi> منهم عندهم <bdi>migraine</bdi> حاليًا — السؤال عن <bdi>prevalence</bdi> «بين هذا المرضى».",
    "clues": [
        ("200 adult patients", "<bdi>denominator</bdi> الصحيح هو من دُرس فعليًا"),
        ("75 patients currently have migraine", "<bdi>numerator</bdi> لـ<bdi>prevalence</bdi>"),
        ("among these patients", "يحدد <bdi>denominator</bdi> = <bdi>200</bdi> لا <bdi>100,000</bdi>"),
    ],
    "why_correct": [
        "<bdi>Prevalence</bdi> = <bdi>existing cases</bdi> / <bdi>population studied</bdi>. مجتمع الدراسة هو <bdi>200</bdi> شخص بالعيادة.",
        "75 «حاليًا مصابين» من 200 = 75/200 = <bdi>0.375 (37.5%)</bdi>. رقم «<bdi>population is 100000</bdi>» مجرد <bdi>distractor</bdi> لأن <bdi>denominator</bdi> يجب يكون من فُحص فعليًا.",
    ],
    "when_changes": [
        "لو كان السؤال عن <bdi>prevalence</bdi> للمجتمع الكامل (<bdi>100,000</bdi>)، يختلف الحساب تمامًا ويحتاج بيانات أخرى.",
    ],
    "rule": "<bdi>denominator</bdi> الصحيح لـ<bdi>prevalence</bdi> هو من دُرس فعليًا، لا رقم <bdi>population</bdi> الإضافي المذكور كـ<bdi>distractor</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
}

WHY_WRONG = {
"AS-0001": {
    "A": "تجاهل الشك وعدم التبليغ هو بالضبط السلوك اللي يسبب مثل هالخطأ، مو حل له.",
    "B": "مراجعة الملف خطوة تحقق مفيدة بس متأخرة وغير كافية لوحدها كإجراء وقائي معياري.",
},
"AS-0045": {
    "A": "سنوات الخبرة العامة بـ<bdi>orthopaedics</bdi> لا تثبت <bdi>competence</bdi> في <bdi>procedure</bdi> الجديدة المحددة؛ <bdi>privileges</bdi> خاصة بكل <bdi>procedure</bdi>.",
    "B": "الشهادة تثبت إكمال <bdi>training</bdi> فقط، لا <bdi>verified competence</bdi>؛ <bdi>credentialing</bdi> يحتاج تقييم <bdi>performance</bdi> فعلي.",
    "C": "فترة انتظار ثابتة ليست معيار <bdi>competence</bdi>؛ بعد التحقق من <bdi>competence</bdi> يمكن منح <bdi>privileges</bdi> دون تأخير تعسفي.",
},
"AS-0250": {
    "B": "<bdi>ischemic heart disease</bdi> هي <bdi>background condition</bdi> التي أدت لـ<bdi>CABG</bdi>؛ في هذا <bdi>recall</bdi> تُدرج أدنى بالسلسلة لا كالسبب المُعتمد.",
    "C": "<bdi>congestive heart failure</bdi> لم تُذكر بأي جزء من السلسلة، وهي حالة <bdi>terminal</bdi> غامضة لا تُكتب كسبب بدون <bdi>underlying disease</bdi> محدد.",
    "D": "الإجراء (<bdi>procedure</bdi>) ليس <bdi>disease</bdi>؛ <bdi>CABG</bdi> يُسجّل ضمن السلسلة (عملية تعقّدت بـ<bdi>infection</bdi>) لا كسبب الوفاة.",
},
"AS-0319": {
    "B": "إجراء <bdi>surgery</bdi> على مريضة <bdi>competent</bdi> رافضة انتهاك لـ<bdi>autonomy</bdi> ويُعد نوعًا من <bdi>assault</bdi>؛ العلاج بلا <bdi>consent</bdi> فقط عند فقد <bdi>capacity</bdi> بحالة <bdi>emergency</bdi>.",
    "C": "الزوج لا يحق له <bdi>consent</bdi> نيابة عن زوجته <bdi>competent</bdi> ولا تجاوز رفضها؛ رأيه يُعتد به فقط لو فقدت هي <bdi>capacity</bdi>.",
},
"AS-0320": {
    "A": "تكرار الجلسات الاستشارية لا يغيّر <bdi>legal</bdi> و<bdi>religious status</bdi>: لا عدد من الجلسات يجعل <bdi>posthumous use</bdi> جائزًا.",
    "B": "عائلة الزوج لا سلطة لها على <bdi>gametes</bdi> ولا على تكاثر الأرملة؛ موافقتهم لا تُشرّع الاستخدام بعد انتهاء <bdi>marriage</bdi>.",
    "D": "<bdi>consent</bdi> مسبق من الزوج يسمح بـ<bdi>posthumous use</bdi> في بعض الدول الغربية، لكن حسب النظام السعودي حتى <bdi>consent</bdi> لا يتجاوز انتهاء <bdi>marriage</bdi> بالوفاة.",
},
"AS-0325": {
    "A": "رفض <bdi>leave</bdi> صحيح، لكن مجرد توبيخه للالتزام بالعمل يتجاهل <bdi>complaint</bdi> ولا يقدم أي علاج؛ الطبيب يعالج <bdi>symptom</bdi> لا يحكم على دوافع المريض.",
    "B": "أسبوع <bdi>leave</bdi> غير مبرر بفحص <bdi>normal</bdi>، والراحة أو قلة النشاط تؤخر الشفاء في <bdi>simple back pain</bdi>.",
    "C": "منح أسبوعين كاملين لمجرد طلبه يعني <bdi>certification</bdi> لعدم لياقة بلا أساس <bdi>clinical</bdi>، وهذا شهادة غير صادقة.",
},
"AS-0364": {
    "A": "<bdi>Utilitarianism</bdi> يحكم بالفعل فقط على أساس أكبر <bdi>benefit</bdi> لأكبر عدد؛ <bdi>IRB</bdi> يوازن <bdi>risk/benefit</bdi> لكن لن يوافق على إيذاء أو استغلال أفراد لمجرد <bdi>benefit</bdi> عام كبير.",
    "C": "<bdi>Ethical skepticism</bdi> يشك بوجود معرفة أخلاقية موضوعية؛ موقف فلسفي لا <bdi>framework</bdi> للموافقة على البحث.",
    "D": "<bdi>Comparativeism</bdi> ليس <bdi>framework</bdi> معروفًا يُستخدم في مراجعة أخلاقيات البحث.",
},
"AS-0380": {
    "A": "<bdi>Beneficence</bdi> واجب التصرف لمصلحة المريض؛ لا يوجد دليل أنه قصّر بعلاج المريضة النازفة.",
    "B": "<bdi>Research Justice</bdi> يخص عدالة اختيار المشاركين وتوزيع أعباء/فوائد البحث، لا الصدق في نشر النتائج.",
    "D": "<bdi>Non-maleficence</bdi> يخص إلحاق الضرر بالمريض؛ <bdi>bleeding</bdi> كان <bdi>complication</bdi> والخطأ في إخفائه من البيانات.",
},
"AS-0404": {
    "B": "<bdi>Fabrication</bdi> يعني اختراع <bdi>data</bdi> أو <bdi>results</bdi> لم تُجمع أبدًا؛ هنا البيانات موجودة فعلاً وتم تعديلها أو حذفها.",
    "C": "<bdi>Plagiarism</bdi> هو تقديم أفكار أو كلمات أو نتائج شخص آخر كأنها لك دون نسب؛ لا شيء هنا مأخوذ من غيره.",
},
"AS-0428": {
    "B": "المعتقدات الشخصية قد تسمح للطبيب بالامتناع عن إجراء <bdi>procedure</bdi>، لكن لا تسمح أبدًا بحجب <bdi>information</bdi>؛ أقل الواجب إعطاء المعلومة والإحالة.",
    "C": "إعطاء <bdi>information</bdi> ليس عملًا غير قانوني؛ رفض كل مساعدة يتخلى عن المريضة ويدفعها لخيارات غير آمنة.",
    "D": "مجرد السؤال عن <bdi>abortion</bdi> ليس جريمة تستدعي <bdi>reporting</bdi>؛ التبليغ عنها ينتهك <bdi>confidentiality</bdi> ويهدم الثقة.",
},
"AS-0428B": {
    "A": "الإحالة لطبيب آخر لا تعالج مسألة <bdi>informed refusal</bdi> وتؤخر <bdi>care</bdi> فقط بحالة خطيرة.",
    "C": "لجنة <bdi>ethics committee</bdi> لا تتجاوز قرار مريضة <bdi>competent</bdi>؛ تُستخدم لمعضلات حقيقية كفقد <bdi>capacity</bdi>، لا لرفض واضح <bdi>informed</bdi>.",
    "D": "تجاوز رغبتهما وإجراء <bdi>termination</bdi> رغمًا عنهم يعني علاج بلا <bdi>consent</bdi>، انتهاك لـ<bdi>autonomy</bdi> ويُعد <bdi>assault</bdi>.",
},
"AS-0438": {
    "A": "الصمت يسمح باستمرار <bdi>retaliation</bdi> و<bdi>misconduct</bdi> الأصلي ويترك الجونيور بلا حماية.",
    "B": "مواجهة السينيور مباشرة بعد تبليغ سابق قد تصعّد النزاع ولا توفر حماية رسمية؛ القضايا تُحل عبر القنوات الرسمية.",
},
"AS-0497": {
    "B": "دقة جمع المعلومات مسألة <bdi>methodological</bdi> أو <bdi>validity</bdi>، لا خطأ أخلاقي بتصميم البحث.",
    "C": "يمكن أخذ وتوثيق <bdi>consent</bdi> إلكترونيًا؛ صعوبة متابعته أقل أهمية من خطر انكشاف بيانات المشاركين.",
    "D": "يمكن للمشارك إيقاف <bdi>online interview</bdi> في أي وقت؛ حق الانسحاب لا يضيع لأن الدراسة إلكترونية.",
},
"AS-0517": {
    "A": "سؤال الزملاء مفيد لحالة واحدة لكنه غير رسمي وقد لا يعكس آخر <bdi>evidence</bdi>.",
    "B": "القراءة مفيدة، لكن القراءة غير المنظمة بالوقت الحر أقل موثوقية من <bdi>CME</bdi> الرسمية لتحديث متعمد عن <bdi>therapies</bdi> جديدة.",
},
"AS-0518": {
    "A": "سؤال الزملاء مفيد لحالة واحدة لكنه غير رسمي وقد لا يعكس آخر <bdi>evidence</bdi>.",
    "B": "القراءة مفيدة، لكن القراءة غير المنظمة بالوقت الحر أقل موثوقية من <bdi>CME</bdi> الرسمية لتحديث متعمد عن <bdi>latest therapies</bdi>.",
},
"AS-2461": {
    "A": "<bdi>documentation</bdi> إجراء جزئي أضيق؛ المبدأ الشامل المستهدف هو <bdi>communication</bdi> عند <bdi>handover</bdi>.",
    "B": "<bdi>two patient identifiers</bdi> تمنع خطأ المريض الخاطئ؛ هنا المريض الصحيح عولج، لكن <bdi>allergy</bdi> معروفة لم تُنقل.",
    "D": "هذا خلل بين الطاقم الطبي لا نقص معرفة العائلة، فـ<bdi>patient education</bdi> لا يعالج المشكلة الأساسية.",
},
"AS-2496": {
    "A": "إجبارها على <bdi>admission</bdi> يتجاوز <bdi>autonomy</bdi> لمريضة <bdi>competent</bdi> ويُعد <bdi>battery</bdi>؛ العلاج القسري فقط عند فقد <bdi>capacity</bdi> بحالة <bdi>true emergency</bdi>.",
    "C": "تركها تذهب ببساطة يتجاهل واجب الإخبار؛ الرفض يكون صحيحًا فقط لو كان <bdi>informed</bdi>، فلازم تُشرح <bdi>risks</bdi> ويُوثّق <bdi>DAMA</bdi>.",
    "D": "خيار غير مكتمل بلا محتوى واضح؛ التسلسل الأخلاقي المتوقع هو شرح، محاولة إقناع، ثم احترام الرفض <bdi>informed</bdi> (<bdi>DAMA</bdi>).",
},
"AS-2537": {
    "A": "<bdi>check-back</bdi> يعني تكرار المستقبل للأمر وتأكيد المرسل له؛ هنا لا أحد كرر أو أكد رسالة، الممرضة فقط تعلن النتائج.",
    "B": "<bdi>SBAR</bdi> صيغة منظمة لـ<bdi>handover</bdi> أو تصعيد قلق عن مريض، لا لتقارير سريعة متتابعة أثناء <bdi>primary survey</bdi>.",
    "C": "<bdi>closed-loop communication</bdi> يعني إعطاء أمر، تكراره من المستقبل، وتأكيد المرسل؛ هنا أسئلة وأجوبة تُعلن للفريق بدون حلقة تكرار وتأكيد.",
},
"AS-0002": {
    "A": "70% لا يطابق أي حساب صحيح من هذه الأرقام؛ <bdi>sensitivity</bdi> تستخدم فقط الـ<bdi>200</bdi> امرأة المرجعية.",
    "B": "80% قريب من <bdi>Positive Predictive Value</bdi> (180/(180+50) ≈ 78%)، وهو يستخدم كل <bdi>test positives</bdi> كـ<bdi>denominator</bdi> لا كل المصابات.",
    "D": "100% تتطلب صفر <bdi>false negatives</bdi>؛ الاختبار فوّت 20 من الـ200 مصابة.",
},
"AS-0007": {
    "B": "التركيز على <bdi>symptomatic patients</bdi> يحوّل الاستخدام من <bdi>screening</bdi> إلى <bdi>diagnostic</bdi>، وهذا خارج تعريف <bdi>screening criteria</bdi> المطلوب.",
    "C": "اكتشاف أكبر عدد ممكن من الناس يزيد <bdi>false positives</bdi> أكثر بسبب <bdi>low specificity</bdi>، ويزيد <bdi>overtreatment</bdi> بدل تقليله.",
},
"AS-0105": {
    "B": "<bdi>Hepatitis A vaccine</bdi> لمجموعات خطر محددة (سفر، مرض كبد مزمن، تعرض مهني)؛ لا شيء منها ينطبق هنا.",
    "C": "<bdi>influenza vaccine</bdi> بالبالغين جرعة سنوية واحدة فقط؛ لا يوجد «<bdi>booster</bdi>»، وهو أخذ جرعة هذا الموسم قبل <bdi>6 months</bdi>.",
},
"AS-0106": {
    "B": "<bdi>Hepatitis A vaccine</bdi> مرتبط بخطر محدد (سفر، مرض كبد، تعرض مهني)؛ <bdi>COPD</bdi> ليس من مؤشراته.",
    "C": "<bdi>influenza vaccine</bdi> بالبالغين جرعة سنوية واحدة فقط بلا «<bdi>booster</bdi>»؛ <bdi>COPD</bdi> يجعل الجرعة السنوية مهمة لكنها ليست جرعة إضافية.",
},
"AS-0122": {
    "A": "<bdi>Specificity</bdi> تعكس تحديد السليمين بدقة (قليل <bdi>false positives</bdi>)؛ تُعطى الأولوية لاختبارات <bdi>confirmatory</bdi> لا لصيد <bdi>missed cases</bdi>.",
    "C": "<bdi>Positive Predictive Value</bdi> تعتمد على <bdi>prevalence</bdi> وتنخفض عادة عند توسيع الاختبار لصيد حالات أكثر.",
    "D": "<bdi>Negative Predictive Value</bdi> ترتفع فعلًا مع تقليل <bdi>false negatives</bdi>، لكن الخاصية الجوهرية للاختبار التي تُعرّف «عدم فوات الحالات» هي <bdi>sensitivity</bdi>.",
},
"AS-0316": {
    "B": "<bdi>Hepatitis A vaccine</bdi> لمجموعات خطر محددة؛ لا شيء منها ينطبق هنا.",
    "C": "<bdi>influenza vaccine</bdi> جرعة سنوية واحدة فقط؛ لا يوجد «<bdi>booster</bdi>»، وهو أخذها فعلًا.",
},
"AS-0361": {
    "A": "<bdi>Specificity</bdi> تعكس تحديد السليمين بدقة؛ ليست الهدف من اختبار يصيد <bdi>missed cases</bdi>.",
    "C": "<bdi>PPV</bdi> يعتمد على <bdi>prevalence</bdi> وغالبًا ينخفض عند توسيع الاختبار.",
    "D": "<bdi>NPV</bdi> ترتفع لكن الخاصية الجوهرية المقصودة هي <bdi>sensitivity</bdi>.",
},
"AS-0365": {
    "A": "15/1000 تساوي 1.5% لا 15%؛ و«<bdi>have</bdi>» تصف <bdi>prevalence</bdi> (حالات موجودة) لا <bdi>incidence</bdi> (حالات جديدة).",
    "B": "أي صيغة «15%» تضع العشرية بمكان خاطئ؛ 15 من 1000 هي 1.5%.",
    "C": "يحذف <bdi>denominator</bdi>؛ <bdi>incidence</bdi> بدون <bdi>population at risk</bdi> (لكل 1000) لا يمكن تفسيره أو تعميمه.",
},
"AS-0424": {
    "A": "2.5 لا ينتج من أي <bdi>cross-product</bdi> صحيح لهذه الأرقام.",
    "B": "4 هو <bdi>odds</bdi> لـ<bdi>CS</bdi> بين <bdi>controls</bdi> فقط (160/40)، لا <bdi>ratio</bdi> يقارن <bdi>cases</bdi> بـ<bdi>controls</bdi>.",
    "C": "5 لا يطابق <bdi>cross-product</bdi>؛ حساب (a×d)/(b×c) يعطي 6 (أو معكوسها 1/6)، لا 5.",
},
"AS-0445": {
    "A": "<bdi>Efficiency</bdi> تعني تجنب إهدار الموارد (أجهزة، وقت، مال)؛ القلق هنا عن <bdi>engagement</bdi> المريض لا إهدار الموارد.",
    "B": "<bdi>Timeliness</bdi> تعني تقليل التأخير الناتج عن النظام؛ هنا الفجوة سببها المريض نفسه بتفويت المواعيد، لا تأخير بالخدمة.",
},
"AS-0478": {
    "B": "0.45% لا تنتج من أي استخدام صحيح لهذه الأرقام؛ إجمالي الحالات 375 لا 450 من كل 100,000.",
    "C": "الأرقام صحيحة لكن الوحدة خاطئة: 375 من 100,000 تساوي 3.75 لكل 1000، لا 0.375 لكل 1000 (خطأ بمقدار عشرة أضعاف).",
    "D": "كلا الـ<bdi>numerator</bdi> والوحدة خاطئان؛ 0.45 لكل 1000 يعني 45 من 100,000.",
},
"AS-0478B": {
    "B": "0.375 لكل 1000 أصغر بألف مرة من الصحيح؛ 0.375 كنسبة تساوي 375 لكل 1000 لا 0.375.",
    "C": "0.45 لا ينتج من 75/200 (يحتاج 90 حالة من 200)، ولا من 75/100,000 (تعطي 0.00075).",
    "D": "قيمة ووحدة خاطئتان معًا؛ لا 75/200 ولا 75/100,000 تعطي 0.45 لكل 1000.",
},
}

HIGHLIGHT_TERMS = {
"AS-0001": ["wrong leg", "how to prevent"],
"AS-0045": ["completed a fellowship in spinal surgery", "requesting clinical privileges"],
"AS-0250": ["surgical site infection that progressed to septicemia", "primary cause of death in his death certificate"],
"AS-0319": ["the mother refused to do the surgery"],
"AS-0320": ["frozen sperms", "the husband died"],
"AS-0325": ["military service member", "low back pain", "requests two weeks of sick leave", "muscle power is normal, there are no neurological deficits"],
"AS-0364": ["IRB", "ethical acceptability"],
"AS-0380": ["remove this case from the research report"],
"AS-0404": ["made some changes to some of the data", "omitted other parts of his results"],
"AS-0428": ["16 y/o", "against doctor idea"],
"AS-0428B": ["severe preeclampsia", "both parent refused"],
"AS-0438": ["alarming letter"],
"AS-0497": ["e-research", "online interview"],
"AS-0517": ["Weak Regarding Immunology", "Improve"],
"AS-0518": ["Updated About LATEST THERPAIES"],
"AS-2461": ["peanut allergy", "without the allergy being documented"],
"AS-2496": ["refuses the admission and asked to leave the hospital"],
"AS-2537": ["communication"],
"AS-0002": ["200 women", "180", "misses 20", "sensitivity"],
"AS-0007": ["low specificity", "over treatment"],
"AS-0105": ["50-year-old", "received the seasonal influenza vaccine 6 months ago"],
"AS-0106": ["50-Year-Old"],
"AS-0122": ["include the missed cases"],
"AS-0316": ["50-year-old", "received the seasonal influenza vaccine 6 months ago"],
"AS-0361": ["even include the missed cases"],
"AS-0365": ["1000 people for one year", "15 of them developed", "incidence"],
"AS-0424": ["case-control study", "80 were delivered by cesarean section and 120 by vaginal delivery", "160 were delivered by cesarean section and 40 by vaginal delivery", "odds ratio"],
"AS-0445": ["missed multiple appointments", "medical value"],
"AS-0478": ["100,000", "Existing cases: 300, New cases: 75", "cumulative prevalence"],
"AS-0478B": ["200 adult patients", "75 patients currently have migraine", "among these patients"],
}
