# -*- coding: utf-8 -*-
# Batch r12 — AboSarah SMLE 2026 explanations (141 questions).

EXPLANATIONS = {
"AS-1193": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "هذا <bdi>severe symptomatic hypokalemia</bdi> بعد <bdi>colectomy</bdi>، والسؤال يبي أهم خطوة بترتيب <bdi>ABC</bdi> مو مجرد فحص إضافي.",
    "clues": [
        ("post op 6 days of colectomy", "فقدان سوائل وأملاح من الجهاز الهضمي بعد <bdi>surgery</bdi> (شفط أنبوب أو <bdi>ileus</bdi>)"),
        ("Potassium 2.5 (low)", "<bdi>severe hypokalemia</bdi> خطيرة تهدد التنفس والقلب"),
        ("most critical to check", "السؤال يبي أخطر شي نتأكد منه أول، مو أي فحص عادي"),
    ],
    "why_correct": [
        "<bdi>potassium</bdi> بمستوى 2.5 مع <bdi>weakness</bdi> و<bdi>fatigue</bdi> و<bdi>palpitations</bdi> يعني <bdi>severe symptomatic hypokalemia</bdi> ممكن تشل عضلات <bdi>respiration</bdi>.",
        "فبترتيب <bdi>ABC</bdi> أول شي نتأكد منه هو <bdi>respiratory distress</bdi> (الـ<bdi>airway</bdi> والـ<bdi>breathing</bdi>)، جنب مراقبة القلب والتعويض الوريدي للـ<bdi>potassium</bdi>.",
        "باقي الخيارات مفيدة بس متأخرة أو غير مباشرة مقارنة بخطر توقف التنفس.",
    ],
    "when_changes": [
        "لو كان من ضمن الخيارات متابعة <bdi>ECG</bdi> أو <bdi>cardiac monitoring</bdi>، بتنافس بقوة، لكن بين الخيارات الموجودة التنفس يسبق.",
        "لو كان <bdi>potassium</bdi> خفيف وبدون أعراض، الجواب يصير تعويض فموي بسيط لا فحص طوارئ.",
    ],
    "rule": "<bdi>severe hypokalemia</bdi> الأول نؤمّن <bdi>ABC</bdi> ونتابع القلب، ثم تعويض <bdi>IV potassium</bdi>.",
    "comparison": None,
    "labs": [["Potassium", "2.5 mmol/L", "3.5-5.1 mmol/L"]],
    "guideline_note": None,
},
"AS-1194": {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "<bdi>unstable pelvic fracture</bdi> مع نزيف نشط، والسؤال يبي الخطوة الأولى بين خيارين فقط، والسؤال فيه نقص خيارات بالمصدر فاحتاج حكمي <bdi>clinical</bdi>.",
    "clues": [
        ("pelvic fracture", "نزيف الحوض أغلبه <bdi>venous</bdi> أو من سطح الكسر، مو شريان واحد يحتاج جراحة فورية"),
        ("actively bleeding", "<bdi>hemorrhagic shock</bdi> يحتاج تعويض دم مبكر"),
        ("BP = 80/50", "<bdi>hypotension</bdi> يأكد <bdi>shock</bdi>"),
    ],
    "why_correct": [
        "<bdi>unstable pelvic fracture</bdi> مع <bdi>hemorrhagic shock</bdi> الخطوة الأولى هي الإنعاش بـ<bdi>blood products</bdi> (<bdi>packed RBC</bdi>) مع ربط الحوض بـ<bdi>pelvic binder</bdi>، مو جراحة فورية.",
        "<bdi>laparotomy</bdi> ما تفيد نزيف الحوض نفسه إلا إذا كان فيه مصدر داخل البطن أكّده <bdi>FAST</bdi> موجب؛ هنا الوصف نزيف حوضي بس، فـ<bdi>laparotomy</bdi> ما هي الخطوة المباشرة.",
        "بين الخيارين المتاحين، تعويض الدم أقرب للخط الأول المعياري من دخول غرفة العمليات مباشرة بدون تأكيد مصدر داخل البطن.",
    ],
    "when_changes": [
        "لو ذكر السؤال <bdi>FAST</bdi> موجب (دم داخل البطن)، الجواب يصير <bdi>laparotomy</bdi> فورًا.",
        "لو <bdi>FAST</bdi> سالب والمريض ما استقر بعد تعويض الدم، الخطوة تصير <bdi>angioembolization</bdi> أو <bdi>preperitoneal packing</bdi>.",
    ],
    "rule": "نزيف الحوض الوحشي يتعامل معه بـ<bdi>pelvic binder</bdi> وتعويض دم أول، و<bdi>laparotomy</bdi> فقط لو فيه مصدر داخل البطن مؤكد.",
    "comparison": None,
    "labs": [["Blood pressure", "80/50 mmHg", "90-120/60-80 mmHg"]],
    "guideline_note": "المصدر نفسه لم يحدد جواب لهذا السؤال، فهذا تحليل حسب <bdi>clinical judgment</bdi>.",
},
"AS-1198": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "السؤال يفرّق بين <bdi>SIRS</bdi> و<bdi>sepsis</bdi> و<bdi>surgical site infection</bdi> بعد <bdi>laparoscopic cholecystectomy</bdi>.",
    "clues": [
        ("72 year old", "<bdi>elderly</bdi> لكن ما يغيّر التصنيف"),
        ("fever, tachycardia and leukocytosis", "معايير <bdi>SIRS</bdi> متحققة"),
        ("slight erythema and no pus formation", "لا يوجد دليل عدوى بالجرح يبرر <bdi>surgical site infection</bdi>"),
    ],
    "why_correct": [
        "تحقق عدة معايير <bdi>SIRS</bdi> مع بعض: <bdi>temperature 38.6</bdi> (فوق 38)، <bdi>HR 116</bdi> (فوق 90) و<bdi>leukocytosis</bdi>.",
        "الجرح فيه <bdi>slight erythema</bdi> بدون <bdi>pus</bdi>، يعني لا يوجد مصدر عدوى مؤكد، فالتصنيف الأدق <bdi>SIRS</bdi> لا <bdi>infection</bdi> محددة.",
        "<bdi>SIRS</bdi> استجابة جسدية عامة للعملية نفسها وشائعة بالأيام الأولى بعد <bdi>surgery</bdi>.",
    ],
    "when_changes": [
        "لو ظهر إفراز <bdi>purulent</bdi> من الجرح أو توسّع <bdi>cellulitis</bdi>، الجواب يصير <bdi>surgical site infection</bdi>.",
        "لو تأكد مصدر عدوى (بول، رئة) مع نفس معايير <bdi>SIRS</bdi>، الجواب يصير <bdi>sepsis</bdi>.",
    ],
    "rule": "معايير <bdi>SIRS</bdi> متحققة بدون مصدر عدوى مؤكد = <bdi>SIRS</bdi>؛ وجود مصدر عدوى يحوّلها <bdi>sepsis</bdi>.",
    "comparison": None,
    "labs": [
        ["Temperature", "38.6 °C", "36.1-37.2 °C"],
        ["Heart rate", "116 bpm", "60-100 bpm"],
        ["Blood pressure", "90/60 mmHg", "90-120/60-80 mmHg"],
    ],
    "guideline_note": None,
},
"AS-1201": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "السؤال يختبر أشهر مضاعفة بعد <bdi>total thyroidectomy</bdi>: تنميل حول الفم مرتبط بـ<bdi>calcium</bdi> لا الأعصاب.",
    "clues": [
        ("total thyroidectomy", "خطر إصابة أو إزالة الغدد <bdi>parathyroid</bdi> أثناء العملية"),
        ("numbness around the mouth", "علامة <bdi>hypocalcemia</bdi> الكلاسيكية"),
    ],
    "why_correct": [
        "تنميل حول الفم والأطراف بعد <bdi>total thyroidectomy</bdi> هي الصورة الكلاسيكية لـ<bdi>hypocalcemia</bdi>.",
        "السبب <bdi>hypoparathyroidism</bdi> من إصابة أو نقص تروية أو إزالة غير مقصودة لغدد <bdi>parathyroid</bdi>، وتظهر خلال 24 إلى 72 ساعة.",
        "نتحقق بعلامتي <bdi>Chvostek</bdi> و<bdi>Trousseau</bdi> ونقيس <bdi>serum calcium</bdi>.",
    ],
    "when_changes": [
        "لو الأعراض بحّة بالصوت أو <bdi>aspiration</bdi>، الجواب يصير إصابة <bdi>recurrent laryngeal nerve</bdi>.",
        "لو الأعراض ظهرت بعد أسابيع (تعب وبرود)، الجواب يصير <bdi>hypothyroidism</bdi> من نقص الهرمون المخزّن.",
    ],
    "rule": "تنميل بعد <bdi>thyroidectomy</bdi> = مشكلة <bdi>parathyroid/calcium</bdi>، أما تغيّر الصوت = مشكلة عصب.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1216": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "<bdi>ulcerative colitis</bdi> مع <bdi>toxic megacolon</bdi> فشل علاجها دوائيًا، والسؤال يبي العلاج <bdi>URGENT</bdi> النهائي.",
    "clues": [
        ("ulcerative colitis", "مرض التهابي مزمن بالقولون"),
        ("fulminant disease complicated by toxic megacolon", "خطر <bdi>perforation</bdi> مرتفع، حالة طارئة"),
        ("URGENT", "يبي الحل الحاسم لا الدعم فقط"),
    ],
    "why_correct": [
        "<bdi>UC</bdi> فشلت بعد علاجات دوائية متعددة وأصبحت <bdi>fulminant</bdi> مع <bdi>toxic megacolon</bdi>، وخطر <bdi>perforation</bdi> عالي، فالعلاج <bdi>URGENT</bdi> النهائي هو <bdi>colectomy</bdi> (<bdi>subtotal/total</bdi> مع <bdi>end ileostomy</bdi>).",
        "قبل العملية يتم إنعاش سريع: <bdi>IV fluids</bdi>، <bdi>NPO</bdi>، <bdi>IV antibiotics</bdi> و<bdi>steroids</bdi>، لكن هذه خطوات تحضيرية لا تعوّض عن الجراحة بعد فشل الدواء.",
    ],
    "when_changes": [
        "لو السؤال يبي الخطوة الأولى الداعمة قبل تأكد الفشل الدوائي، الجواب يصير <bdi>IV fluids</bdi> وإيقاف الأكل.",
        "لو المريض استجاب للعلاج الدوائي وتحسّن، لا حاجة لـ<bdi>colectomy</bdi>.",
    ],
    "rule": "إذا قال السؤال إن العلاج الدوائي فشل بالفعل، الجواب <bdi>colectomy</bdi> لا مزيد من الأدوية.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1221": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "رجل بصحة جيدة مع <bdi>hernia</bdi> أولية أحادية الجانب، والسؤال يبي العلاج الجراحي المعياري.",
    "clues": [
        ("68-year-old", "مريض بالغ بصحة جيدة"),
        ("left reducible inguinal hernia", "<bdi>hernia</bdi> أولية أحادية الجانب <bdi>reducible</bdi>"),
    ],
    "why_correct": [
        "رجل \"<bdi>otherwise healthy</bdi>\" مع <bdi>hernia</bdi> أولية أحادية \"<bdi>reducible</bdi>\" يُنصح له بـ<bdi>open mesh repair</bdi> (<bdi>Lichtenstein</bdi>).",
        "<bdi>mesh</bdi> يقلل نسبة <bdi>recurrence</bdi> مقارنة بالإصلاح بدونها، والطريقة المفتوحة هي الخيار المعياري الأول لـ<bdi>hernia</bdi> أولية أحادية.",
    ],
    "when_changes": [
        "لو كانت <bdi>hernia</bdi> ثنائية الجانب أو متكررة بعد عملية مفتوحة، الجواب يصير <bdi>laparoscopic repair</bdi>.",
        "لو المريض غير مناسب للجراحة أو الأعراض خفيفة جدًا، الجواب يصير <bdi>non-surgical</bdi> (مراقبة).",
    ],
    "rule": "<bdi>hernia</bdi> أولية أحادية بمريض بصحة جيدة = <bdi>open mesh repair</bdi>؛ ثنائية أو متكررة تحوّل الجواب لـ<bdi>laparoscopic</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1229": {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "تنميل حول الفم بعد <bdi>thyroidectomy</bdi>، والسؤال فيه خيارين فقط فاستخدم المعرفة الطبية المباشرة.",
    "clues": [
        ("thyroidectomy", "خطر إصابة غدد <bdi>parathyroid</bdi>"),
        ("peri oral tingling", "علامة <bdi>hypocalcemia</bdi> الكلاسيكية لا <bdi>thyroid storm</bdi>"),
    ],
    "why_correct": [
        "تنميل حول الفم بعد <bdi>thyroidectomy</bdi> هو العلامة الكلاسيكية لـ<bdi>hypocalcemia</bdi> الناتجة عن <bdi>hypoparathyroidism</bdi> (إصابة أو إزالة غير مقصودة لغدد <bdi>parathyroid</bdi>).",
        "<bdi>thyroid storm</bdi> يعطي حرارة وتسرّع قلب وهياج، لا تنميل، فهو لا يناسب هذا الوصف.",
    ],
    "when_changes": [
        "لو ظهرت حرارة عالية وتسرّع قلب وهياج بعد العملية، الجواب يصير <bdi>thyroid storm</bdi>.",
        "لو ظهرت تشنجات يد ورجل واضحة (<bdi>carpopedal spasm</bdi>) مع التنميل، يأكد أكثر <bdi>hypocalcemia</bdi>.",
    ],
    "rule": "تنميل بعد <bdi>thyroidectomy</bdi> = مشكلة <bdi>calcium/parathyroid</bdi> دايمًا.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1233": {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "تسرّع قلب بدون جرح خارجي واضح، والسؤال يبي نوع <bdi>shock</bdi> بين خيارين فقط؛ المصدر نفسه يشك إن \"<bdi>hypertensive</bdi>\" غلط مطبعي ومقصود \"<bdi>hypotensive</bdi>\".",
    "clues": [
        ("tachycardic", "<bdi>compensatory tachycardia</bdi> تناسب <bdi>hypovolemic shock</bdi> أكثر"),
        ("no obvious external injury", "لا يمنع نزيف داخلي (مثل بالبطن أو الصدر)"),
    ],
    "why_correct": [
        "<bdi>hypovolemic shock</bdi> يعطي <bdi>tachycardia</bdi> تعويضية مع انقباض أوعية محيطية، وهذا يطابق الوصف.",
        "عدم وجود جرح خارجي لا يستبعد نزيف داخلي خفي (<bdi>occult hemorrhage</bdi>) كسبب للـ<bdi>hypovolemic shock</bdi>.",
        "<bdi>neurogenic shock</bdi> عادة يعطي <bdi>bradycardia</bdi> أو نبض طبيعي مع جلد دافئ بسبب فقد التوتر الودي، وهذا يخالف \"<bdi>tachycardic</bdi>\" بالسؤال.",
    ],
    "when_changes": [
        "لو كان المريض <bdi>bradycardic</bdi> مع جلد دافئ وإصابة بالعمود الفقري، الجواب يصير <bdi>neurogenic shock</bdi>.",
        "لو ذكر السؤال إصابة نخاعية واضحة، يرجّح <bdi>neurogenic</bdi> أكثر.",
    ],
    "rule": "<bdi>tachycardia</bdi> يرجّح نزيف/<bdi>hypovolemic</bdi>، و<bdi>bradycardia</bdi> مع جلد دافئ بعد إصابة نخاعية يرجّح <bdi>neurogenic</bdi>.",
    "comparison": {
        "headers": ["النوع", "HR", "الجلد"],
        "rows": [
            ["<bdi>Hypovolemic</bdi>", "مرتفع", "بارد"],
            ["<bdi>Neurogenic</bdi>", "طبيعي/منخفض", "دافئ"],
        ],
    },
    "labs": None,
    "guideline_note": "المصدر نفسه يشير أن كلمة \"<bdi>hypertensive</bdi>\" قد تكون خطأ مطبعي والمقصود \"<bdi>hypotensive</bdi>\"، وهذا لم يغيّر الاستنتاج لأن التركيز على <bdi>HR</bdi> والجلد.",
},
"AS-1234": {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "مريض <bdi>hypotensive</bdi> <bdi>tachycardic</bdi> مع <bdi>GCS</bdi> منخفض، والسؤال فيه خيارين فقط ويبي الخطوة الأولى الشاملة.",
    "clues": [
        ("Hypotensive tachycardic", "علامات <bdi>shock</bdi>"),
        ("GCS low", "احتمال إصابة بالرأس أو نقص تروية الدماغ"),
    ],
    "why_correct": [
        "بأي مريض متدهور (<bdi>shock</bdi> + <bdi>GCS</bdi> منخفض) الخطوة الأولى هي <bdi>primary survey</bdi> الكامل حسب <bdi>ABCDE</bdi>، لأنه يحدد ويعالج كل التهديدات المميتة بترتيب.",
        "<bdi>fluid resuscitation</bdi> جزء من خطوة <bdi>C</bdi> داخل <bdi>ABCDE</bdi>، لكنه خطوة واحدة فقط ولا يغطي <bdi>airway</bdi> أو <bdi>breathing</bdi> أو فحص <bdi>disability</bdi>.",
    ],
    "when_changes": [
        "لو السؤال يحدد إن <bdi>airway</bdi> و<bdi>breathing</bdi> مؤمّنين بالفعل ويبي خطوة علاج الدورة الدموية تحديدًا، الجواب يصير <bdi>fluid resuscitation</bdi>.",
        "لو <bdi>GCS</bdi> أقل من أو يساوي 8، يضاف تأمين مجرى هواء محدد ضمن نفس <bdi>primary survey</bdi>.",
    ],
    "rule": "بأي سؤال يبي \"الخطوة الأولى\" بمريض رضوض غير مستقر، الجواب الشامل <bdi>primary survey (ABCDE)</bdi> يسبق أي تدخل واحد كـ<bdi>fluids</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1234B": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "مريض حادث سيارة واعي لكن <bdi>disoriented</bdi> بعد إصابة رأس، والسؤال يبي الخطوة الأولى.",
    "clues": [
        ("MVA", "آلية رضية عالية الطاقة"),
        ("head trauma", "احتمال إصابة دماغية"),
        ("conscious but disoriented", "خلل بـ<bdi>disability</bdi> لكن المريض واعي"),
    ],
    "why_correct": [
        "أي مريض \"<bdi>MVA</bdi>\" يبدأ بـ<bdi>primary survey (ABCDE)</bdi> لإيجاد وعلاج التهديدات المميتة فورًا، حتى لو كان \"<bdi>conscious</bdi>\".",
        "\"<bdi>disoriented</bdi>\" بعد إصابة الرأس يُقيَّم ضمن <bdi>D</bdi> (<bdi>GCS</bdi> والحدقتين)، لكن <bdi>airway</bdi> و<bdi>breathing</bdi> و<bdi>circulation</bdi> لازم تُؤمَّن أولًا.",
        "التصوير والفحص التفصيلي يجيان بعد <bdi>primary survey</bdi> والإنعاش.",
    ],
    "when_changes": [
        "لو <bdi>GCS</bdi> أقل من أو يساوي 8 بعد تأمين <bdi>primary survey</bdi>، الخطوة التالية تأمين <bdi>airway</bdi> نهائي.",
        "لو انتهى <bdi>primary survey</bdi> واستقر المريض، الخطوة التالية <bdi>head CT</bdi>.",
    ],
    "rule": "أي رضّة ولو كان المريض واعيًا، لا شي يسبق <bdi>primary survey (ABCDE)</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1239": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "آفة متقشرة ورطبة بالحلمة بامرأة بعمر 55 مع تصوير طبيعي، والسؤال يبي الخطوة التالية.",
    "clues": [
        ("scaly, oozing lesion on the right nipple", "صورة كلاسيكية لـ<bdi>Paget disease</bdi> للحلمة لحد ما يثبت العكس"),
        ("no palpable breast masses", "لا كتلة واضحة لكن هذا لا يستبعد <bdi>Paget</bdi>"),
    ],
    "why_correct": [
        "آفة متقشرة ورطبة مستمرة أسابيع بامرأة بعمر 55 هي \"<bdi>Paget disease</bdi>\" للحلمة لحد ما يثبت العكس.",
        "<bdi>mammogram</bdi> و<bdi>ultrasound</bdi> الطبيعيين لا يستبعدون <bdi>Paget</bdi>، لأنها ممكن تكون محصورة بالحلمة أو مرتبطة بـ<bdi>DCIS</bdi> خفي.",
        "التشخيص يتأكد بـ<bdi>nipple biopsy</bdi> (<bdi>punch</bdi> أو <bdi>wedge</bdi> أو كامل السمك).",
    ],
    "when_changes": [
        "لو كانت الآفة ثنائية الجانب حاكّة وتبدأ بـ<bdi>areola</bdi> وتستجيب للعلاج، الجواب يتجه لـ<bdi>eczema</bdi> وإحالة جلدية.",
        "لو نجحت تجربة <bdi>steroid cream</bdi> بالكامل، يرجّح <bdi>eczema</bdi> لا <bdi>Paget</bdi>.",
    ],
    "rule": "إكزيما حلمة أحادية مستمرة بامرأة كبيرة = <bdi>biopsy</bdi> مباشرة، لا تجربة <bdi>steroid</bdi> ولا إحالة جلدية.",
    "comparison": {
        "headers": ["", "<bdi>Paget disease</bdi>", "<bdi>Eczema</bdi>"],
        "rows": [
            ["البداية", "بالحلمة ثم تنتشر", "بالـ<bdi>areola</bdi> وتجنّب الحلمة"],
            ["الجانب", "أحادي عادة", "ثنائي عادة"],
        ],
    },
    "labs": None,
    "guideline_note": None,
},
"AS-1248": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "امرأة سمينة مع <bdi>jaundice</bdi> ونمط مخبري <bdi>cholestatic</bdi> واضح، والسؤال يبي الخطوة التالية بالتشخيص.",
    "clues": [
        ("obese", "عامل خطر لـ<bdi>gallstones</bdi>"),
        ("jaundice", "ارتفاع <bdi>bilirubin</bdi>"),
        ("tender liver", "التهاب أو انسداد كبدي"),
        ("direct bilirubin 79", "ارتفاع <bdi>conjugated bilirubin</bdi>"),
        ("alkaline phosphatase 1000", "ارتفاع كبير يرجّح نمط <bdi>cholestatic</bdi>"),
    ],
    "why_correct": [
        "ارتفاع \"<bdi>direct bilirubin</bdi>\" مع ارتفاع كبير بـ\"<bdi>alkaline phosphatase</bdi>\" وارتفاع خفيف بإنزيمات الكبد هو نمط <bdi>cholestatic</bdi>.",
        "الخطوة الأولى <bdi>abdominal ultrasound</bdi> لمعرفة إذا كانت القنوات الصفراوية متوسعة، فيفرق بين انسداد خارج الكبد (مثل حصوات بامرأة سمينة) أو ركود داخل الكبد.",
        "<bdi>ultrasound</bdi> رخيص وغير جراحي ومتوفر، فهو الخطوة المعيارية الأولى.",
    ],
    "when_changes": [
        "لو كان <bdi>ultrasound</bdi> غير حاسم أو يبي تحديد مستوى الانسداد بدقة، الخطوة التالية <bdi>MRCP</bdi>.",
        "لو نفت الصور وجود انسداد بالقنوات، يُنظر بـ<bdi>liver biopsy</bdi> لأسباب داخل الكبد.",
    ],
    "rule": "أي نمط <bdi>cholestatic</bdi> (ارتفاع <bdi>ALP</bdi> و<bdi>direct bilirubin</bdi>) يبدأ دايمًا بـ<bdi>ultrasound</bdi>.",
    "comparison": None,
    "labs": [
        ["RBC", "4 ×10¹²/L", "4.2-5.4 ×10¹²/L (female)"],
        ["Hemoglobin", "110 g/L", "120-160 g/L (female)"],
        ["Platelets", "212 ×10⁹/L", "150-400 ×10⁹/L"],
        ["WBC", "18 ×10⁹/L", "4.5-10.5 ×10⁹/L"],
        ["Direct bilirubin", "79 µmol/L", "1.5-6.5 µmol/L"],
        ["Total bilirubin", "98 µmol/L", "3.5-16.5 µmol/L"],
        ["AST", "70 U/L", "12-40 U/L"],
        ["ALT", "150 U/L", "5-40 U/L"],
        ["Alkaline phosphatase", "1000 U/L", "39-117 U/L"],
    ],
    "guideline_note": None,
},
"AS-1251": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "كتلة شرجية مؤلمة زرقاء بعد إمساك، ومفتاح المصدر مرتبط بـ<bdi>sphincterotomy</bdi> مع تحفظ واضح عن دقة الوصف.",
    "clues": [
        ("perianal painful lump for 12 hours", "ألم حاد بدأ مبكرًا، مدة قصيرة جدًا"),
        ("dome-shaped, bluish, tender swelling", "صورة <bdi>perianal hematoma</bdi> (<bdi>thrombosed external hemorrhoid</bdi>) أكثر من <bdi>fissure</bdi>"),
    ],
    "why_correct": [
        "مفتاح هذا الـ<bdi>recall</bdi> يربط الكتلة بتشنج العضلة العاصرة الشرجية مثل حالات <bdi>fissure</bdi>، فيختار <bdi>lateral sphincterotomy</bdi>.",
        "لكن الوصف الفعلي (كتلة \"<bdi>dome-shaped, bluish, tender</bdi>\" تحت الجلد الشرجي خلال \"<bdi>12 hours</bdi>\") يطابق <bdi>perianal hematoma</bdi> لا <bdi>fissure</bdi> مزمنة، و<bdi>sphincterotomy</bdi> هي العملية المعيارية لـ<bdi>chronic anal fissure</bdi> لا لهذه الكتلة.",
        "خذ هذا الجواب مع تحفظ المصدر نفسه، راجع ملاحظة <bdi>guideline</bdi> أدناه.",
    ],
    "when_changes": [
        "لو كانت الحالة فعلًا <bdi>chronic fissure</bdi> (أكثر من 6 أسابيع) بدون كتلة، الجواب الصحيح طبيًا <bdi>lateral sphincterotomy</bdi> كما بالمفتاح.",
        "لو كانت كتلة مؤلمة بدون حرارة أو صديد ومضى عليها أكثر من 72 ساعة، الجواب يصير <bdi>conservative management</bdi>.",
    ],
    "rule": "كتلة زرقاء مؤلمة شرجية = <bdi>perianal hematoma</bdi>؛ العاصرة (<bdi>sphincterotomy</bdi>) تخص <bdi>chronic fissure</bdi> فقط.",
    "comparison": None,
    "labs": None,
    "guideline_note": "وصف الحالة (كتلة زرقاء تحت الجلد خلال 12 ساعة) يطابق <bdi>perianal hematoma</bdi> أكثر من <bdi>fissure</bdi>، ومفتاح المصدر يبدو غير متسق مع الوصف؛ أُبقي على <bdi>answer_letter</bdi> المصدر (<bdi>C</bdi>) كما يطلب القاعدة، مع هذا التنبيه.",
},
"AS-1257": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "آفة جلدية محددة الحدود وحمراء ومؤلمة برجل كبير بالسن، والسؤال يبي الفحص التالي.",
    "clues": [
        ("well demarcated, red, painful to touch", "صورة التهاب/عدوى جلدية (<bdi>erysipelas</bdi> أو <bdi>cellulitis</bdi>) لا ورم مصطبغ"),
    ],
    "why_correct": [
        "آفة \"<bdi>well demarcated, red, painful</bdi>\" برجل كبير بالسن تمثل التهاب جلدي معدي، فالفحص التالي هو <bdi>ultrasound</bdi> لمعرفة إذا كان فيه <bdi>abscess</bdi> تحتاج تصريف.",
        "<bdi>ultrasound</bdi> سريع وبدون إشعاع ومتوفر بجانب السرير.",
    ],
    "when_changes": [
        "لو كانت الآفة مصطبغة وغير منتظمة الحدود (مشتبه <bdi>melanoma</bdi>)، الجواب يصير <bdi>excisional biopsy</bdi> لا <bdi>ultrasound</bdi>.",
        "لو كان هناك تدهور سريع وألم شديد مع فقاعات أو موت نسيجي (<bdi>necrotizing fasciitis</bdi>)، الجواب يصير جراحة فورية بدون تأخير بالتصوير.",
    ],
    "rule": "آفة حمراء مؤلمة محددة الحدود = عدوى جلدية، والفحص التالي <bdi>ultrasound</bdi> للبحث عن صديد.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1272": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "أنثى بعد حادث سيارة مع ألم بطني شديد وضغط منخفض، والسؤال يبي الخطوة الأولية الصحيحة بالإنعاش الرضحي الحديث.",
    "clues": [
        ("MVA", "آلية رضية عالية الطاقة"),
        ("severe abdominal pain", "اشتباه نزيف داخل البطن"),
        ("BP 83/50", "<bdi>hemorrhagic shock</bdi>"),
    ],
    "why_correct": [
        "بعد \"<bdi>MVA</bdi>\" مع \"<bdi>severe abdominal pain</bdi>\" و\"<bdi>BP 83/50</bdi>\" هذه المريضة بـ<bdi>hemorrhagic shock</bdi> من نزيف داخل بطني مفترض.",
        "إنعاش الرضوض الحديث (<bdi>ATLS</bdi>) يفضّل نقل <bdi>blood products</bdi> مبكرًا على كمية كبيرة من <bdi>crystalloid</bdi> بمريض رضحي منخفض الضغط، فتعويض الدم هو الخطوة الأولية.",
        "عدم ذكر مستوى <bdi>Hb</bdi> لا يهم هنا لأن <bdi>Hb</bdi> يتأخر بالانعكاس عن فقدان الدم الحاد.",
    ],
    "when_changes": [
        "لو كان الضغط طبيعيًا والألم خفيف بدون علامات <bdi>shock</bdi>، الخطوة الأولى تصير تصوير (<bdi>CT</bdi>) لا نقل دم.",
        "لو كان المريض مستقر بعد تعويض محدود وفحص <bdi>FAST</bdi> موجب، الخطوة التالية <bdi>laparotomy</bdi>.",
    ],
    "rule": "مريض رضحي منخفض الضغط = تعويض دم مبكر، لا ننتظر نتيجة <bdi>Hb</bdi> ولا نكتفي بالمراقبة.",
    "comparison": None,
    "labs": [["Blood pressure", "83/50 mmHg", "90-120/60-80 mmHg"]],
    "guideline_note": None,
},
"AS-1275": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "شابة بألم كتف شديد وتشوه واضح وعدم قدرة على التبعيد، والسؤال يبي الفحص التالي قبل أي رد.",
    "clues": [
        ("visible deformity of the shoulder", "يرجّح <bdi>dislocation</bdi> أو كسر بأعلى العضد"),
        ("inability to abduct the arm", "فقدان وظيفي يدعم <bdi>dislocation</bdi>"),
    ],
    "why_correct": [
        "\"<bdi>severe shoulder pain</bdi>\" مع \"<bdi>visible deformity</bdi>\" و\"<bdi>inability to abduct</bdi>\" يرجّح <bdi>shoulder dislocation</bdi> (غالبًا أمامي) أو كسر بأعلى العضد.",
        "<bdi>plain X-ray</bdi> (<bdi>AP</bdi> مع جانبي أو <bdi>axillary</bdi>) هو الفحص الأول: يأكد نوع <bdi>dislocation</bdi> واتجاهه ويكشف أي كسر مصاحب قبل أي محاولة رد.",
    ],
    "when_changes": [
        "لو كان فيه علامات إصابة وعائية صلبة (نبض غائب، ورم متمدد)، الجواب يصير <bdi>surgical exploration</bdi>.",
        "لو استمرت الأعراض بعد الرد وشك بإصابة نسيج رخو، الجواب يصير <bdi>MRI</bdi>.",
    ],
    "rule": "أي اشتباه <bdi>dislocation</bdi> أو كسر، الخطوة الأولى دايمًا <bdi>X-ray</bdi> قبل أي رد أو تصوير متقدم.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1280": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "السؤال عام عن السبب الفعلي لخطر العدوى بهذا السيناريو (أدوات جراحية مستخدمة سابقًا)، ويبي الإجراء الذي يمنع تكرار المشكلة مستقبلًا.",
    "clues": [
        ("previously used surgical instruments", "مصدر التلوث الأساسي بالسيناريو"),
        ("surgical site infection", "النتيجة المطلوب الوقاية منها"),
    ],
    "why_correct": [
        "مشكلة السيناريو هي استخدام \"<bdi>previously used surgical instruments</bdi>\"، فالإجراء اللي يزيل هذا المصدر هو <bdi>sterilization</bdi> صحيح للأدوات قبل العملية القادمة.",
        "السؤال عام أكثر من كونه عن هذا المريض نفسه: لا شي يرجع تعرضه السابق، لكن <bdi>sterilization</bdi> الصحيح هو اللي يمنع <bdi>surgical site infection</bdi> مستقبلًا.",
    ],
    "when_changes": [
        "لو كان السؤال عن الوقاية العامة من <bdi>SSI</bdi> بدون ذكر أدوات ملوثة، تدخل عوامل أخرى مثل <bdi>normothermia</bdi> و<bdi>prophylactic antibiotics</bdi> قبل الشق.",
        "لو أعطي <bdi>antibiotics</bdi> قبل الشق بساعة، هذا إجراء وقائي صحيح منفصل عن مشكلة الأدوات.",
    ],
    "rule": "طابق الإجراء الوقائي مع سبب الفشل المذكور بالسؤال؛ أدوات ملوثة = <bdi>sterilization</bdi> صحيح.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1281": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "رجل بتاريخ <bdi>peptic ulcer</bdi> مع بطن حاد و<bdi>shock</bdi>، والسؤال يبي الخطوة الأولية قبل الجراحة.",
    "clues": [
        ("past history of peptic ulcer", "يرجّح <bdi>perforated peptic ulcer</bdi>"),
        ("guarding, Rebound", "التهاب بريتوني"),
        ("Skin cool and clammy", "علامة <bdi>shock</bdi>"),
        ("Hypotensive 87/60", "<bdi>hemodynamic instability</bdi>"),
    ],
    "why_correct": [
        "تاريخ \"<bdi>peptic ulcer</bdi>\" مع ألم منتشر و\"<bdi>guarding, Rebound</bdi>\" يرجّح \"<bdi>perforated peptic ulcer</bdi>\" مع التهاب بريتوني.",
        "المريض بـ<bdi>shock</bdi> (جلد بارد ورطب، <bdi>BP 87/60</bdi>، <bdi>HR 120</bdi>) من فقد سوائل داخل البريتون، فالخطوة الأولية <bdi>IV fluid resuscitation</bdi>.",
        "<bdi>laparotomy</bdi> هي العلاج النهائي، لكنها تأتي بعد الإنعاش.",
    ],
    "when_changes": [
        "لو استمر <bdi>hypotension</bdi> بعد إنعاش كافٍ بالسوائل، يُضاف <bdi>vasopressor</bdi>.",
        "بعد استقرار المريض بالسوائل، الخطوة التالية <bdi>laparotomy</bdi> (<bdi>omental patch</bdi> للثقب العفجي).",
    ],
    "rule": "\"الخطوة الأولية\" بأي بطن حاد مع <bdi>shock</bdi> = سوائل وريدية؛ \"النهائية\" = جراحة.",
    "comparison": None,
    "labs": [
        ["Blood pressure", "87/60 mmHg", "90-120/60-80 mmHg"],
        ["Heart rate", "120 bpm", "60-100 bpm"],
    ],
    "guideline_note": None,
},
"AS-1281B": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "نفس صورة <bdi>perforated peptic ulcer</bdi> مع <bdi>shock</bdi>، نسخة ثانية بخيارات مختلفة لكن نفس المنطق.",
    "clues": [
        ("peptic ulcer", "يرجّح <bdi>perforation</bdi>"),
        ("rebound tenderness with guarding", "التهاب بريتوني"),
        ("blood pressure was 85/55", "<bdi>hypotension</bdi>"),
        ("tachycardia 120", "استجابة تعويضية لـ<bdi>shock</bdi>"),
    ],
    "why_correct": [
        "حالة \"<bdi>known case of peptic ulcer</bdi>\" مع \"<bdi>rebound tenderness with guarding</bdi>\" تعني <bdi>perforated ulcer</bdi> مع التهاب بريتوني، و\"<bdi>85/55</bdi>\" مع \"<bdi>tachycardia 120</bdi>\" تعني <bdi>shock</bdi>.",
        "\"<bdi>initial management</bdi>\" هو <bdi>IV fluid</bdi> (<bdi>crystalloid</bdi>) لاستعادة الحجم الدوراني؛ بقية الخطوات (<bdi>antibiotics</bdi>، تصوير، جراحة) تتبع بعد بدء الإنعاش.",
    ],
    "when_changes": [
        "لو استمر <bdi>hypotension</bdi> رغم سوائل كافية، يُضاف <bdi>vasopressor</bdi>.",
        "لو كان المريض ينزف (<bdi>melena</bdi> أو <bdi>hematemesis</bdi> مع <bdi>Hb</bdi> منخفض)، الصورة تتحول لنزيف وتحتاج <bdi>blood transfusion</bdi> لا فقط سوائل.",
    ],
    "rule": "علامات التهاب بريتوني مع <bdi>shock</bdi> = ثقب، وأول خطوة <bdi>IV fluid</bdi>؛ نزيف مع <bdi>melena/hematemesis</bdi> = ينتقل التفكير لتعويض الدم.",
    "comparison": None,
    "labs": [
        ["Blood pressure", "85/55 mmHg", "90-120/60-80 mmHg"],
        ["Heart rate", "120 bpm", "60-100 bpm"],
    ],
    "guideline_note": None,
},
"AS-1317": {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "تورم مؤلم ودافئ بالساعد بعد إصابة بسيطة، والسؤال يبي الخطوة التالية بدون تفاصيل عن وجود تجمع صديد أو علامات تسمم؛ اختيار الأقرب سريريًا.",
    "clues": [
        ("minor Injury", "بوابة دخول محتملة للعدوى"),
        ("painful swelling in forearm", "تورم موضعي محتمل تجمع"),
        ("warmth", "التهاب موضعي نشط"),
    ],
    "why_correct": [
        "تورم مؤلم دافئ موضعي بعد إصابة بسيطة بدون علامات تسمم شامل يرجّح تجمع صديد موضعي (<bdi>abscess</bdi>) أكثر من التهاب منتشر فقط.",
        "الخطوة العملية الأقرب بين الخيارات هي <bdi>incision and drainage</bdi> للتجمع الموضعي، لأن المضاد الحيوي وحده لا يفرّغ صديدًا متكونًا، و<bdi>MRI</bdi> و<bdi>wide excision</bdi> غير مناسبين لحالة التهابية بسيطة.",
    ],
    "when_changes": [
        "لو كان التورم منتشر بدون تجمع واضح (لا <bdi>fluctuance</bdi>)، الجواب يصير <bdi>antibiotics</bdi> فقط.",
        "لو ظهر ألم غير متناسب وتغيّر لون الجلد وتسمم شامل، الجواب يصير جراحة طارئة (اشتباه <bdi>necrotizing fasciitis</bdi>).",
    ],
    "rule": "التورم الدافئ المؤلم بعد إصابة: وجود تجمع (<bdi>fluctuance</bdi>) يحوّل الجواب لـ<bdi>drainage</bdi>، غيابه يحوّله لـ<bdi>antibiotics</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر لم يحدد جواب لهذا السؤال، فهذا تحليل حسب <bdi>clinical judgment</bdi> بسبب نقص تفاصيل عن وجود تجمع أو تسمم شامل.",
},
"AS-1317B": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بعمر 5 سنوات مع آفة جلدية سريعة التفاقم وألم غير متناسب وتسمم شامل، صورة كلاسيكية لـ<bdi>necrotizing fasciitis</bdi>.",
    "clues": [
        ("rapidly progressive painful skin lesion", "انتشار سريع يرجّح عدوى عميقة خطيرة"),
        ("pain is severe and disproportionate to the physical findings", "علامة تحذيرية كلاسيكية لـ<bdi>necrotizing fasciitis</bdi>"),
        ("febrile and appears toxic", "تسمم جهازي"),
        ("patches of purple discoloration", "موت نسيجي بالجلد"),
    ],
    "why_correct": [
        "\"<bdi>rapidly progressive</bdi>\" مع ألم \"<bdi>disproportionate</bdi>\" وطفل \"<bdi>toxic</bdi>\" و\"<bdi>purple discoloration</bdi>\" يصف <bdi>necrotizing fasciitis</bdi>.",
        "هذا طارئ جراحي: <bdi>surgical consultation</bdi> عاجل للتنضير مع <bdi>broad-spectrum IV antibiotics</bdi>، لأن العدوى تنتشر بالـ<bdi>fascia</bdi> أسرع من ما يظهر على الجلد.",
    ],
    "when_changes": [
        "لو كان المريض مستقر وتشخيصه غير واضح، يُسمح بـ<bdi>MRI</bdi> لتقييم امتداد <bdi>fascia</bdi> بدون تأخير التنضير.",
        "لو كانت الآفة سطحية بسيطة بدون تسمم (مثل <bdi>impetigo</bdi>)، الجواب يصير علاج موضعي بسيط.",
    ],
    "rule": "ألم غير متناسب مع انتشار سريع وتسمم شامل = <bdi>necrotizing fasciitis</bdi>، والعلاج تنضير جراحي عاجل + مضاد حيوي واسع، لا تصوير يؤخر العملية.",
    "comparison": None,
    "labs": [["Temperature", "febrile (توكسيك)", "36.1-37.2 °C"]],
    "guideline_note": None,
},
"AS-1319": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "خراج زائدي كبير متكوّن بالصور، والسؤال يبي التعامل الصحيح بدون جراحة فورية بمجال ملتهب.",
    "clues": [
        ("appendicular abscess", "تجمع صديد منظم يحتاج تصريف أولًا"),
    ],
    "why_correct": [
        "الصور تظهر <bdi>appendicitis</bdi> مع <bdi>fecolith</bdi> و<bdi>appendicular abscess</bdi> كبير \"<bdi>reaching the flank</bdi>\".",
        "الخراج الزائدي المنظم يُعالج بتصريف <bdi>percutaneous drainage</bdi> موجّه بالصور مع <bdi>IV antibiotics</bdi>، ثم استئصال الزائدة لاحقًا (<bdi>interval appendectomy</bdi>).",
        "الجراحة المبكرة بمجال ملتهب هش ترفع خطر إصابة الأمعاء والناسور واستئصال أمعاء غير مخطط له.",
    ],
    "when_changes": [
        "لو كانت الصورة <bdi>phlegmon</bdi> (كتلة بدون تجمع)، الجواب يصير <bdi>IV antibiotics</bdi> فقط بدون تصريف.",
        "لو كان المريض غير مستقر أو فيه التهاب بريتوني منتشر، الجواب يصير جراحة فورية.",
    ],
    "rule": "خراج زائدي منظم = تصريف أولًا ثم استئصال لاحق؛ <bdi>phlegmon</bdi> = مضاد حيوي فقط.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1320": {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "رجل كبير 4 أيام بعد استبدال ركبة، حمى وتسرّع قلب وارتفاع كريات الدم البيضاء مع ارتشاح بالرئة اليمنى، بدون ضغط مذكور، والسؤال يبي الخطوة الأولية الحقيقية.",
    "clues": [
        ("4 days post knee replacement", "توقيت متوسط بعد العملية"),
        ("Temp 38.9", "حمى واضحة"),
        ("Xray: right lower lobe infilteration", "صورة <bdi>pneumonia</bdi>"),
    ],
    "why_correct": [
        "حمى وتسرّع قلب وارتفاع <bdi>WBC</bdi> مع ارتشاح جديد بالرئة = <bdi>pneumonia</bdi> مع استجابة <bdi>SIRS</bdi>.",
        "بما إن الضغط الدموي غير مذكور (أي لا يوجد <bdi>hypotension</bdi> مؤكد)، الخطوة الأولية الحقيقية هي البدء بـ<bdi>broad-spectrum antibiotics</bdi> بعد أخذ المزارع، لا الانتظار أو الاعتبار غير ذي صلة.",
        "<bdi>DVT prophylaxis</bdi> إجراء روتيني مستمر لكنه لا يعالج الحمى والعدوى الحالية.",
    ],
    "when_changes": [
        "لو ذُكر <bdi>hypotension</bdi> أو ضعف تروية، الخطوة الأولية تصير سوائل ومضاد حيوي معًا بالساعة الأولى.",
        "لو كان الكشف السريري طبيعي تمامًا بدون صورة رئة، يُفكر أكثر بأسباب أخرى حسب يوم ما بعد العملية.",
    ],
    "rule": "حمى بدون <bdi>hypotension</bdi> موثقة: العلاج الأولي يوجَّه لمصدر العدوى نفسه (<bdi>antibiotics</bdi>)، لا لسوائل فقط.",
    "comparison": None,
    "labs": [
        ["Heart rate", "115 bpm", "60-100 bpm"],
        ["Temperature", "38.9 °C", "36.1-37.2 °C"],
        ["WBC", "15 ×10⁹/L", "4.5-10.5 ×10⁹/L"],
    ],
    "guideline_note": "المصدر لم يحدد جواب لهذا السؤال؛ التحليل اعتمد على غياب <bdi>hypotension</bdi> موثقة بالسيناريو.",
},
"AS-1325": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "عقدة درقية بحجم 3 سم بمواصفات موجية مريبة بامرأة شابة بدون أعراض، والسؤال يبي الخطوة التالية بعد <bdi>ultrasound</bdi>.",
    "clues": [
        ("Hypo echoic and inside it microcalcifications", "ملامح موجية مريبة"),
        ("Size: 3 cm", "أكبر بكثير من حد أخذ العينة"),
    ],
    "why_correct": [
        "عقدة 3 سم \"<bdi>hypoechoic</bdi>\" مع \"<bdi>microcalcifications</bdi>\" ملامحها مريبة وفوق حد أخذ العينة بكثير، فالخطوة التالية <bdi>FNA biopsy</bdi>.",
        "كون المريضة شابة وبدون أعراض وغدة متحركة لا يقلل الشك؛ الملامح الموجية هي الفاصل.",
        "نتيجة الخلايا (<bdi>Bethesda</bdi>) هي اللي تقرر الجراحة أو المتابعة بعد ذلك.",
    ],
    "when_changes": [
        "لو كان <bdi>TSH</bdi> منخفض، الخطوة التالية تتحول لـ<bdi>thyroid scan</bdi> لا <bdi>FNA</bdi> مباشرة.",
        "لو كانت العقدة أقل من 1 سم بدون ملامح مريبة، الجواب يصير <bdi>ultrasound follow-up</bdi>.",
    ],
    "rule": "عقدة مريبة موجيًا بحجم يستدعي أخذ عينة = <bdi>FNA</bdi> مباشرة، بدون <bdi>thyroxine</bdi> ولا جراحة قبل التشخيص الخلوي.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1328": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "قرحة سكري برائحة كريهة، والسؤال يبي الخطوة الأولية الأكثر فائدة قبل أي علاج مساعد آخر.",
    "clues": [
        ("diabetic", "عامل خطر لقرحة قدم سكري وتأخر التئام"),
        ("foul-smelling ulcer", "يرجّح نسيج ميت أو مصاب بعدوى"),
    ],
    "why_correct": [
        "رائحة كريهة بقرحة سكري تعني وجود نسيج ميت أو ملوث، ولا جرح يلتئم أو تنتهي عدواه وهو موجود.",
        "<bdi>debridement</bdi> هو الخطوة الأولية الأكثر فائدة: يزيل العبء البكتيري ويسمح بتقييم العمق (عظم، خراج) وأخذ مزارع عميقة.",
        "كل الإجراءات المساعدة الأخرى تعمل فقط على جرح نظيف بعد التنضير.",
    ],
    "when_changes": [
        "بعد التنضير وتكون نسيج نظيف لا يلتئم، الجواب يصير <bdi>negative pressure wound therapy</bdi>.",
        "لو فشلت الرعاية المعيارية بجرح نقص تروية مزمن، يُنظر بـ<bdi>hyperbaric oxygen therapy</bdi>.",
    ],
    "rule": "جرح ميت أو كريه الرائحة = <bdi>debridement</bdi> أولًا؛ كل باقي العلاجات تنتظر جرحًا نظيفًا.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1332": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "بعد <bdi>MI</bdi> اختفت كل النبضات تحت الفخذ بينما نبض الفخذ سليم، وهذا يصف <bdi>acute arterial embolism</bdi> لا <bdi>DVT</bdi> كما ذُكر بالسؤال.",
    "clues": [
        ("femoral pulse intact but all pulses below cannot be felt", "علامة انسداد شرياني حاد عند تفرّع الشريان الفخذي"),
    ],
    "why_correct": [
        "فقدان كل النبضات تحت الفخذ مع سلامة نبض الفخذ هو صورة <bdi>acute arterial occlusion</bdi>، وذكر \"<bdi>DVT</bdi>\" بالسؤال يبدو غلط بالنص الأصلي.",
        "بعد <bdi>MI</bdi>، جلطة بالبطين الأيسر (<bdi>mural thrombus</bdi>) مصدر كلاسيكي للانسداد الشرياني (<bdi>embolism</bdi>)، فالعلاج النهائي للطرف المهدد هو <bdi>embolectomy</bdi> (<bdi>Fogarty balloon</bdi>).",
        "<bdi>heparin</bdi> يُعطى فورًا كخطوة إنعاش، لكنه غير موجود بين الخيارات.",
    ],
    "when_changes": [
        "لو كان المريض له تاريخ <bdi>claudication</bdi> مزمن (<bdi>PAD</bdi>)، يرجّح <bdi>thrombosis</bdi> وتُستخدم <bdi>angiography</bdi> ثم <bdi>thrombolysis</bdi> أو <bdi>bypass</bdi>.",
        "لو كان الطرف غير قابل للإنقاذ (شلل ثابت، تلون داكن)، الجواب يصير بتر.",
    ],
    "rule": "انسداد شرياني حاد بمصدر قلبي واضح (بعد <bdi>MI</bdi>، بدون تاريخ <bdi>claudication</bdi>) = <bdi>embolectomy</bdi> فورًا.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1340": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بعمر سنتين وخصية غير محسوسة بالصفن، والسؤال يبي التوقيت الصحيح للجراحة.",
    "clues": [
        ("right testis is not palpable in the scrotum", "<bdi>undescended testis</bdi> متأخر عن عمر النزول التلقائي"),
    ],
    "why_correct": [
        "طفل بعمر سنتين وخصيته غير نازلة تجاوز عمر النزول التلقائي (حوالي 6 أشهر)، والجراحة المثالية بين 6 و18 شهر، فبعمر سنتين تكون متأخرة ويجب تنفيذها الآن.",
        "<bdi>surgical repair now</bdi> يحمي الخصوبة ويقلل خطر <bdi>torsion</bdi> ويسمح بفحص لاحق لاستبعاد ورم.",
    ],
    "when_changes": [
        "لو كان الطفل أقل من 6 أشهر، الجواب يصير مراقبة لاحتمال النزول التلقائي.",
        "لو كانت الخصية <bdi>retractile</bdi> (تنزل باليد وتبقى)، لا حاجة للجراحة.",
    ],
    "rule": "خصية غير نازلة بعمر 2 سنة = جراحة الآن، لا تأخير.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1340B": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "رضيع بعمر 5 أشهر بقيء غير صفراوي وكتلة زيتونية الشكل، صورة كلاسيكية لـ<bdi>hypertrophic pyloric stenosis</bdi>.",
    "clues": [
        ("5-month-old", "أكبر من العمر النموذجي لكن الصورة كلاسيكية"),
        ("non-bilious vomiting", "يميّز عن انسداد أسفل العفج"),
        ("olive-shaped mass palpable in the epigastric region", "علامة تشخيصية كلاسيكية"),
    ],
    "why_correct": [
        "قيء \"<bdi>non-bilious</bdi>\" مع جفاف وكتلة \"<bdi>olive-shaped</bdi>\" بالمنطقة فوق السرّة هو <bdi>hypertrophic pyloric stenosis</bdi>.",
        "العلاج النهائي <bdi>Ramstedt pyloromyotomy</bdi> لشق العضلة المتضخمة؛ ليست حالة طارئة، فيُصحَّح الجفاف وخلل الأملاح (<bdi>hypochloremic hypokalemic alkalosis</bdi>) بمحلول ملحي قبل الجراحة.",
    ],
    "when_changes": [
        "لو كان السؤال عن الخطوة \"الفورية\" أو \"الأولية\"، الجواب يصير تصحيح الجفاف والأملاح أولًا لا <bdi>pyloromyotomy</bdi> مباشرة.",
        "لو كان المريض بالغ بتضيق بوابي مكتسب (تندّب هضمي)، الجواب يصير <bdi>balloon dilatation</bdi>.",
    ],
    "rule": "تضيق البواب الضخامي الطفلي = تصحيح السوائل والأملاح أولًا، ثم <bdi>pyloromyotomy</bdi> كعلاج نهائي.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1349": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "<bdi>testicular torsion</bdi> بالأطفال، والسؤال يبي الفترة الذهبية الصحيحة للعلاج.",
    "clues": [
        ("testicular torsion", "حالة طارئة مرتبطة بالزمن"),
        ("golden hour", "يبي الرقم الدقيق للفترة الذهبية"),
    ],
    "why_correct": [
        "<bdi>testicular torsion</bdi> تلوي الحبل المنوي وتقطع الدم الشرياني، وبقاء الخصية سليمة يعتمد على سرعة فك اللوي.",
        "أعلى نسبة إنقاذ عند فك اللوي خلال حوالي 6 ساعات من بدء الألم، وهذا هو الرقم المعتمد للفترة الذهبية.",
        "هذا هو سبب التوجه المباشر لاستكشاف الصفن سريريًا بدون انتظار تصوير عند الاشتباه القوي.",
    ],
    "when_changes": [
        "لو تجاوزت الفترة 12 ساعة، نسبة الإنقاذ تنخفض كثيرًا رغم استمرار الاستكشاف.",
        "لو تجاوزت 24 ساعة، الخصية غالبًا غير قابلة للحياة وقد تحتاج استئصال.",
    ],
    "rule": "الفترة الذهبية لإنقاذ الخصية في <bdi>torsion</bdi> حوالي 6 ساعات من بدء الألم.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1351": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "سؤال عن التصوير المفضل عند الاشتباه بـ<bdi>testicular torsion</bdi> حين يُستخدم تصوير فعلًا.",
    "clues": [
        ("testicular torsion", "حالة حرجة بالزمن تحتاج تصوير سريع إن استُخدم"),
    ],
    "why_correct": [
        "عند استخدام تصوير لاشتباه <bdi>torsion</bdi>، الفحص المفضل هو <bdi>Doppler ultrasound</bdi> للصفن: سريع وبجانب السرير وبدون إشعاع ويظهر نقص أو غياب التروية بالخصية المصابة.",
        "تذكّر ترتيب الأولويات: <bdi>torsion</bdi> تشخيص سريري، والاشتباه القوي يذهب مباشرة للاستكشاف الجراحي بدون تصوير؛ <bdi>Doppler</bdi> يُحجز للحالات غير الواضحة.",
    ],
    "when_changes": [
        "لو كان الاشتباه السريري قوي وواضح، الجواب يصير استكشاف جراحي مباشر لا تصوير.",
        "لو كانت الصورة <bdi>epididymo-orchitis</bdi> (تروية مرتفعة)، العلاج يصير مضاد حيوي ومضاد التهاب.",
    ],
    "rule": "تصوير اشتباه <bdi>torsion</bdi> عند الحاجة = <bdi>Doppler ultrasound</bdi>؛ الاشتباه القوي يتخطى التصوير مباشرة للجراحة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
}

WHY_WRONG = {
"AS-1193": {
    "B": "<bdi>ABG</bdi> فحص مختبري مفيد لاحقًا (قد يظهر <bdi>metabolic alkalosis</bdi> مصاحب)، لكنه ليس تقييم الخطر المباشر على الحياة.",
    "C": "تاريخ الغذاء يفسر <bdi>hypokalemia</bdi> المزمن، لكنه لا يغيّر التعامل الطارئ مع <bdi>potassium 2.5</bdi> مع أعراض.",
    "D": "مراقبة البول مهمة قبل إعطاء <bdi>potassium</bdi> (تجنب <bdi>hyperkalemia</bdi> لو فيه قصور كلوي)، لكنها ليست أخطر شي نتحقق منه بمريض ضعيف قد يفشل تنفسه.",
},
"AS-1194": {
    "A": "<bdi>laparotomy</bdi> فورية ليست الخطوة المباشرة لنزيف حوضي بلا تأكيد مصدر داخل البطن؛ نزيف الحوض يتعامل معه غالبًا بـ<bdi>binder</bdi> و<bdi>angioembolization</bdi>.",
},
"AS-1198": {
    "A": "<bdi>thrombophilia</bdi> ميل للتخثر لا يسبب حرارة و<bdi>leukocytosis</bdi>؛ يهم فقط لو ظهر <bdi>DVT</bdi> أو <bdi>PE</bdi>.",
    "B": "<bdi>UTI</bdi> سبب كلاسيكي لحرارة اليوم الثاني أو الثالث بعد العملية، لكن لا يوجد دليل بولي يدعمه هنا.",
    "C": "<bdi>surgical site infection</bdi> تحتاج علامات جرح حقيقية مثل صديد أو احمرار منتشر، وهذا غير موجود (<bdi>slight erythema</bdi> فقط بدون صديد).",
},
"AS-1201": {
    "B": "إصابة <bdi>recurrent laryngeal nerve</bdi> تسبب بحّة أو اختناق، لا تنميل حول الفم والأطراف.",
    "C": "<bdi>hypothyroidism</bdi> بعد العملية يتطور خلال أسابيع بتعب وبرود، لا تنميل حاد فوري.",
    "D": "<bdi>vitamin D deficiency</bdi> سبب مزمن لـ<bdi>hypocalcemia</bdi>، لكن ظهور الأعراض فورًا بعد <bdi>thyroidectomy</bdi> يرجّح إصابة الغدد مباشرة.",
},
"AS-1216": {
    "B": "<bdi>methotrexate</bdi> دواء مناعي بطيء للعلاج التثبيتي، لا دور له بالحالة الحادة الشديدة أو <bdi>toxic megacolon</bdi>.",
    "C": "<bdi>antibiotics</bdi> جزء من الرعاية الداعمة، لكنها لا تعالج القولون الفاشل نفسه، ووحدها ليست العلاج العاجل بعد فشل الدواء.",
    "D": "<bdi>TPN</bdi> دعم غذائي فقط ولا يفيد بالقولون المتوسع المسموم؛ قد تكون الجواب فقط لو السؤال عن الدعم الغذائي.",
},
"AS-1221": {
    "A": "<bdi>simple repair</bdi> بدون <bdi>mesh</bdi> له نسبة <bdi>recurrence</bdi> أعلى؛ يُستخدم فقط لو كان المجال ملوثًا وتجنّب <bdi>mesh</bdi> ضروري.",
    "C": "<bdi>laparoscopic repair</bdi> يُفضّل للحالات الثنائية أو المتكررة أو لو الأولوية تعافي أسرع؛ لا ينطبق هنا.",
    "D": "<bdi>non-surgical treatment</bdi> يناسب مريضًا بأعراض خفيفة جدًا أو غير مناسب للجراحة؛ هذا المريض بصحة جيدة ونُصح بالجراحة.",
},
"AS-1229": {
    "B": "<bdi>thyroid storm</bdi> يعطي حرارة وتسرّع قلب وهياج، لا تنميل حول الفم.",
},
"AS-1233": {
    "B": "<bdi>neurogenic shock</bdi> يرتبط بـ<bdi>bradycardia</bdi> أو نبض طبيعي وجلد دافئ بسبب فقد التوتر الودي، وهذا يخالف \"<bdi>tachycardic</bdi>\" المذكور.",
},
"AS-1234": {
    "A": "<bdi>fluid resuscitation</bdi> جزء واحد فقط من خطوة <bdi>C</bdi>؛ وحده لا يغطي <bdi>airway</bdi> أو <bdi>breathing</bdi> أو فحص <bdi>GCS</bdi>.",
},
"AS-1234B": {
    "B": "<bdi>head CT</bdi> مطلوب لاحقًا، لكن فقط بعد اكتمال <bdi>primary survey</bdi> واستقرار المريض لدخول الماسح.",
    "C": "<bdi>head-to-toe exam</bdi> هو <bdi>secondary survey</bdi>، يأتي بعد <bdi>primary survey</bdi> والإنعاش لا قبله.",
    "D": "<bdi>observation</bdi> غير آمنة بمريض <bdi>disoriented</bdi> بعد حادث سيارة؛ تناسب فقط مريضًا واعيًا تمامًا بإصابة رأس خفيفة بدون معايير تصوير.",
},
"AS-1239": {
    "A": "إحالة لطبيب جلدية تؤخر تشخيص ورم محتمل؛ تناسب فقط إكزيما ثنائية الجانب حاكّة تجنّب الحلمة أو تستجيب للعلاج.",
    "B": "تجربة <bdi>steroid cream</bdi> قد تُحسّن مظهر <bdi>Paget disease</bdi> ظاهريًا وتؤخر التشخيص؛ تُستخدم فقط لإكزيما نموذجية ثنائية مع <bdi>biopsy</bdi> لو فشلت.",
},
"AS-1248": {
    "A": "<bdi>MRCP</bdi> خطوة ثانية تُستخدم لو <bdi>ultrasound</bdi> غير حاسم أو لتحديد مستوى الانسداد قبل التدخل.",
    "B": "<bdi>liver biopsy</bdi> إجراء غازي يُنظر فيه فقط لو نفت الصور وجود انسداد بالقنوات.",
    "D": "<bdi>CT</bdi> أقل حساسية من <bdi>ultrasound</bdi> لرؤية الحصوات ويضيف إشعاع وصبغة؛ يناسب الاشتباه بورم أو التحديد بعد <bdi>ultrasound</bdi>.",
},
"AS-1251": {
    "A": "<bdi>conservative management</bdi> هو المعيار لو كانت الكتلة متأخرة (أكثر من 72 ساعة تقريبًا) أو الألم خفيف، لكن مفتاح هذا السؤال يتجه لتفسير آخر.",
    "B": "<bdi>rubber band ligation</bdi> تخص <bdi>internal hemorrhoids</bdi> فوق الخط الحساس فقط، ولا تُستخدم أبدًا على كتلة خارجية حساسة كهذه.",
    "D": "<bdi>aspiration</bdi> لا تفرّغ <bdi>thrombosed external hemorrhoid</bdi> لأن المحتوى دم متجلط؛ التفريغ المبكر يكون بشق أو استئصال لا بإبرة.",
},
"AS-1257": {
    "A": "<bdi>punch biopsy</bdi> يناسب آفة جلدية مشبوهة تحتاج نسيج مرضي (طفح غير نمطي أو ورم محتمل)؛ آفة حمراء حادة مؤلمة تمثل عدوى لا تحتاج <bdi>biopsy</bdi>.",
    "B": "<bdi>MRI</bdi> يُحجز لاشتباه عدوى عميقة مثل <bdi>necrotizing fasciitis</bdi> أو <bdi>osteomyelitis</bdi>، لا كفحص أول لآفة جلدية سطحية.",
    "C": "<bdi>X-ray</bdi> يفيد فقط لو شُك بغاز بالنسيج أو جسم غريب أو إصابة عظمية؛ لا يظهر تجمع سوائل بالنسيج الرخو.",
},
"AS-1272": {
    "A": "<bdi>crystalloid</bdi> ممكن كجرعة محدودة، لكن \"<bdi>observe</bdi>\" غير آمن بمريض رضحي منخفض الضغط؛ كميات <bdi>crystalloid</bdi> كبيرة تخفف عوامل التخثر وتزيد النزيف.",
    "B": "<bdi>laparotomy</bdi> هي الخطوة النهائية لمريض غير مستقر مع <bdi>FAST</bdi> موجب أو التهاب بريتوني، لكن الإنعاش بالدم يبدأ أولًا ويستمر مع قرار الجراحة.",
},
"AS-1275": {
    "A": "<bdi>MRI</bdi> يخص إصابة النسيج الرخو مثل تمزق <bdi>rotator cuff</bdi> أو <bdi>labral tear</bdi>، غالبًا بعد الرد أو لأعراض مستمرة؛ ليس الفحص الأول لتشوه حاد.",
    "B": "<bdi>CT</bdi> يُستخدم لكسور معقدة (مثل <bdi>glenoid</bdi> أو رأس العضد) لو كان <bdi>X-ray</bdi> غير حاسم أو للتخطيط الجراحي، لا كخطوة أولى.",
    "D": "<bdi>surgical exploration</bdi> تخص علامات إصابة وعائية صلبة (نبض غائب، ورم متمدد)؛ لا شي هنا يرجّح ذلك، و<bdi>dislocation</bdi> تُرد مغلقًا بعد <bdi>X-ray</bdi>.",
},
"AS-1280": {
    "A": "<bdi>antibiotics</bdi> بعد العملية لا تقلل معدل <bdi>SSI</bdi> وتزيد خطر المقاومة؛ الفعالية فقط لو أُعطيت قبل الشق.",
    "B": "الحفاظ على <bdi>normothermia</bdi> إجراء وقائي حقيقي بشكل عام، لكنه لا يعالج فشل هذا السيناريو المحدد (أدوات ملوثة).",
    "D": "القول بعدم وجود تأثير على الجرح خاطئ؛ أدوات غير معقمة ترفع خطر العدوى بوضوح.",
},
"AS-1281": {
    "B": "<bdi>laparotomy</bdi> (<bdi>omental patch</bdi> للثقب العفجي) علاج نهائي للثقب، لكنها تأتي بعد الإنعاش بالسوائل؛ الجراحة بمريض نقص حجم خطرة.",
    "C": "<bdi>vasopressors</bdi> فقط لـ<bdi>shock</bdi> المستمر بعد سوائل كافية؛ إعطاؤها بمريض نقص حجم يزيد سوء تروية الأعضاء.",
},
"AS-1281B": {
    "B": "<bdi>vasopressor</bdi> يُضاف فقط لو استمر <bdi>hypotension</bdi> رغم سوائل كافية؛ بمريض نقص حجم يسوء التروية.",
    "C": "<bdi>blood transfusion</bdi> لـ<bdi>hemorrhagic shock</bdi> (قرحة نازفة مع <bdi>melena</bdi>/<bdi>hematemesis</bdi> و<bdi>Hb</bdi> منخفض)؛ هنا الصورة ثقب مع التهاب بريتوني لا نزيف.",
    "D": "<bdi>IV antibiotics</bdi> جزء من علاج الثقب والتهاب البريتون، لكن استعادة الدورة الدموية تسبقها بمريض منخفض الضغط.",
},
"AS-1317": {
    "A": "<bdi>MRI</bdi> ليست الخطوة العملية الأولى بتورم موضعي بعد إصابة بسيطة؛ تُحجز لحالات غير واضحة أو اشتباه عميق.",
    "B": "<bdi>wide excision</bdi> تخص كتل صلبة مشبوهة بورم (<bdi>sarcoma</bdi>) بعد تصوير وخزعة، لا تورمًا التهابيًا حادًا بعد إصابة.",
    "D": "<bdi>IV antibiotics</bdi> وحدها لا تفرّغ تجمع صديد متكوّن؛ تحتاج تصريف أولًا لو فيه <bdi>fluctuance</bdi>.",
},
"AS-1317B": {
    "A": "<bdi>MRI</bdi> ممكن يظهر امتداد <bdi>fascia</bdi>، لكن انتظار التصوير يؤخر التنضير ويرفع خطر الوفاة؛ التشخيص سريري ويتأكد بالعملية.",
    "C": "المضاد الحيوي الموضعي والمسكن يناسبان فقط عدوى سطحية بسيطة مثل <bdi>impetigo</bdi>؛ لا دور لهما بعدوى نسيج رخو عميقة مهددة للحياة.",
},
"AS-1319": {
    "A": "<bdi>open drainage</bdi> أكثر توسعًا، يُحجز للتجمعات التي لا يمكن الوصول لها بالجلد أو فشل التصريف بالجلد.",
    "C": "استئصال الزائدة الآن يعني التشريح وسط تجمع ملتهب هش، مع خطر إصابة أمعاء وناسور؛ تُستأصل لاحقًا كخطوة فاصلة.",
    "D": "<bdi>laparoscopic appendectomy</bdi> صحيح لـ<bdi>appendicitis</bdi> غير المعقد، لكن مع خراج متكوّن تُستأصل الزائدة لاحقًا بعد التصريف.",
},
"AS-1320": {
    "A": "القول بأن الحالة \"غير ذات صلة\" خاطئ؛ الحمى والارتشاح الرئوي يحتاجان تدخل فعلي.",
    "B": "<bdi>IV fluid</bdi> وحدها لا تعالج مصدر العدوى الرئوي؛ تُعطى بجانب العلاج لو فيه ضعف تروية، وهذا غير مؤكد هنا.",
    "D": "<bdi>DVT prophylaxis</bdi> إجراء روتيني مستمر، لكنه لا يعالج الحمى والعدوى الحالية المذكورة بالسؤال.",
},
"AS-1325": {
    "B": "<bdi>thyroxine</bdi> لتثبيط <bdi>TSH</bdi> لا يعالج أو يصغّر عقدة مريبة؛ يؤخر تشخيص سرطان محتمل.",
    "C": "<bdi>discharge</bdi> (أو متابعة <bdi>ultrasound</bdi>) تناسب عقدة أقل من سنتيمتر أو ملامح حميدة بوضوح؛ هذه 3 سم بملامح خبيثة.",
    "D": "<bdi>thyroidectomy</bdi> تأتي بعد نتيجة الخلايا (مثل <bdi>Bethesda</bdi> مريب) أو أعراض ضغط؛ تنفيذها قبل <bdi>FNA</bdi> يتخطى التشخيص.",
},
"AS-1328": {
    "B": "منتجات العناية المتقدمة بالجرح تدعم جرحًا نظيفًا متكوّنًا بعد التنضير؛ على نسيج ميت ومصاب لا تعالج السبب.",
    "C": "<bdi>hyperbaric oxygen therapy</bdi> علاج مساعد لحالات مختارة مقاومة أو نقص تروية بعد فشل الرعاية المعيارية، لا خطوة أولى.",
    "D": "<bdi>negative pressure wound therapy</bdi> تُستخدم بعد التنضير على جرح غير ملتئم؛ ممنوعة فوق نسيج ميت أو مصاب بشدة وبدون علاج.",
},
"AS-1332": {
    "A": "<bdi>warfarin</bdi> فموي للوقاية طويلة الأمد بعد الحدث (مثل <bdi>mural thrombus</bdi> أو <bdi>AF</bdi>)؛ لا يفيد طرفًا مهددًا حاليًا.",
    "C": "<bdi>angiography</bdi> تفيد لو كان السبب غير واضح (تاريخ <bdi>claudication</bdi> مزمن) والطرف غير مهدد فورًا؛ مصدر صمة قلبية واضح مع غياب نبض حاد يذهب مباشرة لـ<bdi>embolectomy</bdi>.",
    "D": "<bdi>catheter-directed thrombolysis</bdi> تناسب تجلط موضعي على تصلب شرايين مزمن أو انسداد وعاء صغير؛ صمة قلبية حديثة عند تفرّع رئيسي تُعالج جراحيًا وهذا أسرع وأضمن.",
},
"AS-1340": {
    "A": "تأجيل الجراحة لعمر 5 سنوات يرفع خطر تلف الخلايا الجرثومية والعقم؛ التأخير غير مفضل بعد تجاوز نافذة النزول التلقائي.",
    "C": "عدم التدخل يناسب رضيعًا أقل من 6 أشهر تقريبًا أو خصية <bdi>retractile</bdi> تنزل وتبقى؛ لا ينطبق هنا.",
},
"AS-1340B": {
    "B": "<bdi>balloon dilatation</bdi> تُستخدم لتضيق بوابي مكتسب بالبالغين (تندّب هضمي)؛ التضخم العضلي الطفلي يُعالج بـ<bdi>pyloromyotomy</bdi>.",
    "C": "<bdi>gastrojejunostomy</bdi> تحويل جراحي لانسداد مخرج المعدة بالبالغين (مثل ورم)؛ غير ضرورية وأكثر تعقيدًا برضيع.",
},
"AS-1349": {
    "B": "8 ساعات تجاوزت الفترة الذهبية؛ نسبة الإنقاذ تنخفض تدريجيًا بعد 6 ساعات رغم استمرار الاستكشاف.",
    "C": "بحلول 12 ساعة نسبة الإنقاذ منخفضة كثيرًا؛ ليست الفترة المستهدفة.",
    "D": "بحلول 24 ساعة الخصية غالبًا غير قابلة للحياة وقد تحتاج استئصال، رغم استمرار الاستكشاف.",
},
"AS-1351": {
    "A": "<bdi>plain X-ray</bdi> لا يظهر الخصية أو تروية الدم؛ لا دور له بألم الصفن.",
    "B": "<bdi>MRI</bdi> يظهر تروية الخصية لكنه بطيء وغير متوفر بسهولة، فيهدر فترة نقص التروية الحرجة.",
    "D": "<bdi>CT</bdi> يعرّض الغدد التناسلية للإشعاع ولا يقيّم تروية الخصية؛ يناسب مغص كلوي أو مشاكل بطنية لا الصفن.",
},
}

HIGHLIGHT_TERMS = {
"AS-1193": ["post op 6 days of colectomy", "Potassium 2.5 (low)", "most critical to check"],
"AS-1194": ["pelvic fracture", "actively bleeding", "BP = 80/50"],
"AS-1198": ["72 year old", "fever, tachycardia and leukocytosis", "slight erythema and no pus formation"],
"AS-1201": ["total thyroidectomy", "numbness around the mouth"],
"AS-1216": ["ulcerative colitis", "fulminant disease complicated by toxic megacolon", "URGENT"],
"AS-1221": ["68-year-old", "left reducible inguinal hernia"],
"AS-1229": ["thyroidectomy", "peri oral tingling"],
"AS-1233": ["tachycardic", "no obvious external injury"],
"AS-1234": ["Hypotensive tachycardic", "GCS low"],
"AS-1234B": ["MVA", "head trauma", "conscious but disoriented"],
"AS-1239": ["scaly, oozing lesion on the right nipple", "no palpable breast masses"],
"AS-1248": ["obese", "jaundice", "tender liver", "direct bilirubin 79", "alkaline phosphatase 1000"],
"AS-1251": ["perianal painful lump for 12 hours", "dome-shaped, bluish, tender swelling"],
"AS-1257": ["well demarcated, red, painful to touch"],
"AS-1272": ["MVA", "severe abdominal pain", "BP 83/50"],
"AS-1275": ["visible deformity of the shoulder", "inability to abduct the arm"],
"AS-1280": ["previously used surgical instruments", "surgical site infection"],
"AS-1281": ["past history of peptic ulcer", "severe abdominal pain", "guarding, Rebound", "Skin cool and clammy", "Hypotensive 87/60"],
"AS-1281B": ["peptic ulcer", "rebound tenderness with guarding", "blood pressure was 85/55", "tachycardia 120"],
"AS-1317": ["minor Injury", "painful swelling in forearm", "warmth"],
"AS-1317B": ["rapidly progressive painful skin lesion", "pain is severe and disproportionate to the physical findings", "febrile and appears toxic", "patches of purple discoloration"],
"AS-1319": ["appendicular abscess"],
"AS-1320": ["4 days post knee replacement", "Temp 38.9", "Xray: right lower lobe infilteration"],
"AS-1325": ["Hypo echoic and inside it microcalcifications", "Size: 3 cm"],
"AS-1328": ["diabetic", "foul-smelling ulcer"],
"AS-1332": ["femoral pulse intact but all pulses below cannot be felt"],
"AS-1340": ["right testis is not palpable in the scrotum"],
"AS-1340B": ["5-month-old", "non-bilious vomiting", "olive-shaped mass palpable in the epigastric region"],
"AS-1349": ["testicular torsion", "golden hour"],
"AS-1351": ["testicular torsion"],
}
