# -*- coding: utf-8 -*-
# Explanation batch for slice r07.json (141 questions, AS-0254 ... AS-0796 range).

EXPLANATIONS = {
"AS-0254": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "الصورة هنا <bdi>hemolysis</bdi> بعد <bdi>mycoplasma pneumonia</bdi>، والسؤال يبي نفرق بين <bdi>cold agglutinin AIHA</bdi> المرتبط بالعدوى والـ<bdi>drug-induced hemolysis</bdi>.",
    "clues": [
        ("mycoplasma pneumonia", "سبب كلاسيكي لـ<bdi>cold agglutinin autoimmune hemolytic anemia</bdi> (أضداد <bdi>IgM</bdi>)"),
        ("yellowish discolouration of the eyes", "<bdi>jaundice</bdi> من زيادة <bdi>indirect bilirubin</bdi> بسبب التكسير"),
        ("Haptoglobin 0.4", "<bdi>haptoglobin</bdi> منخفض يأكد وجود <bdi>hemolysis</bdi> نشط"),
    ],
    "why_correct": [
        "علامات <bdi>hemolysis</bdi> واضحة: <bdi>Hb</bdi> منخفض، <bdi>reticulocyte</bdi> مرتفع، <bdi>haptoglobin</bdi> منخفض، و<bdi>AST</bdi> أعلى من <bdi>ALT</bdi> (لأنه يتحرر من <bdi>RBCs</bdi> المتكسرة).",
        "التوقيت مهم: التكسير صار مع عدوى <bdi>mycoplasma</bdi>، مو بعد دواء جديد، فهذا يرجح <bdi>cold agglutinin</bdi> مو <bdi>drug-induced hemolysis</bdi>.",
        "لما يكون التكسير واضح وشديد سريريًا (<bdi>Hb</bdi> منخفض جدًا)، يعطى <bdi>corticosteroids</bdi> حتى لو الاستجابة بالـ<bdi>cold agglutinin disease</bdi> ضعيفة نسبيًا، لأن فيه عنصر مناعي نشط يحتاج تثبيط.",
    ],
    "when_changes": [
        "لو التكسير بدأ بعد <bdi>antibiotic</bdi> جديد مباشرة بدون علاقة بعدوى <bdi>mycoplasma</bdi>، يصير الجواب وقف الدواء (<bdi>stop the drug</bdi>).",
        "لو كان المرض <bdi>primary cold agglutinin disease</bdi> بدون عدوى حادة، يصير العلاج المفضل <bdi>rituximab</bdi> لأن <bdi>steroids</bdi> فعاليتها ضعيفة فيه.",
    ],
    "rule": "<bdi>mycoplasma</bdi> مع <bdi>hemolysis</bdi> يعني <bdi>cold agglutinins</bdi> مو <bdi>antibiotic toxicity</bdi>؛ والقرار بين <bdi>supportive care</bdi> و<bdi>corticosteroids</bdi> يعتمد على شدة التكسير سريريًا.",
    "comparison": None,
    "labs": [["Hemoglobin", "60", "120-170 g/L"], ["Reticulocyte", "4% (high)", "0.5-2.5%"], ["Haptoglobin", "0.4", "0.3-2.0 g/L (low for active hemolysis)"]],
    "guideline_note": "المصدر وضع هذا الجواب كـ<bdi>uncertain</bdi> وذكر إشارة استفهام على الخيارين B وC، لكن الملاحظة التفسيرية (<bdi>compiler note</bdi>) ترجح C لأن التكسير سببه <bdi>mycoplasma</bdi> لا الدواء.",
},
"AS-0254B": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "نفس صورة <bdi>hemolysis</bdi> بس هنا التوقيت يربطها بدواء جديد بدأ بعد الدخول، فالسؤال يختبر <bdi>drug-induced immune hemolytic anemia</bdi>.",
    "clues": [
        ("put on medications", "التكسير بدأ بعد بدء أدوية جديدة بالمستشفى، مو بعد عدوى"),
        ("Hb: 68", "<bdi>anemia</bdi> شديد يدل على <bdi>acute hemolysis</bdi> نشط"),
        ("LDH: high", "<bdi>LDH</bdi> مرتفع من تكسير <bdi>RBCs</bdi>، يدعم التشخيص"),
    ],
    "why_correct": [
        "التكسير بدأ <bdi>3 days</bdi> بعد دخول المستشفى وبدء أدوية جديدة، وهذا التوقيت هو العلامة الأساسية لـ<bdi>drug-induced immune hemolysis</bdi>.",
        "الخطوة الأولى والأهم بهذا النوع هي وقف الدواء المسبب (هنا <bdi>antibiotic</bdi>)؛ أغلب الحالات تتحسن بعد السحب مباشرة.",
        "علامات التكسير (<bdi>Hb</bdi> منخفض، <bdi>reticulocyte</bdi> مرتفع، <bdi>haptoglobin</bdi> منخفض، <bdi>LDH</bdi> مرتفع) تؤكد النشاط الحاد.",
    ],
    "when_changes": [
        "لو التكسير بدأ مع عدوى <bdi>mycoplasma</bdi> أو <bdi>EBV</bdi> بدون دواء جديد، يصير الجواب <bdi>supportive care</bdi> للعدوى مو وقف دواء.",
        "لو استمر التكسير شديد بعد وقف الدواء، يضاف <bdi>corticosteroids</bdi> كخطوة مساعدة.",
    ],
    "rule": "تكسير جديد بعد دواء جديد = وقف الدواء أولًا؛ تكسير مع <bdi>mycoplasma</bdi> = فكّر بـ<bdi>cold agglutinins</bdi> مباشرة.",
    "comparison": None,
    "labs": [["Hemoglobin", "68", "120 g/L+ (normal above)"], ["Reticulocyte", "4%", "0.5-2.5%"], ["Haptoglobin", "low", "0.3-2.0 g/L"], ["LDH", "high (300-600)", "lab-dependent, typically &lt;250 U/L"]],
    "guideline_note": None,
},
"AS-0262": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "السؤال عن الهدف الصحيح لضغط الدم بعد <bdi>intracerebral hemorrhage</bdi> في مريض مستقر <bdi>hemodynamically</bdi>.",
    "clues": [
        ("intracerebral hemorrhage", "نزيف دماغي ناتج عن ضغط غير متحكم فيه، يحتاج خفض ضغط متوازن"),
        ("hemodynamically stable", "ما فيه صدمة تمنعنا من خفض الضغط بأمان"),
    ],
    "why_correct": [
        "الهدف الحالي المقبول في <bdi>ICH</bdi> هو خفض <bdi>systolic BP</bdi> إلى حوالي 140 مع إبقائه ضمن مجال 130 إلى 150 تقريبًا.",
        "خفض الضغط بسرعة ولكن بسلاسة (بـ<bdi>IV labetalol</bdi> أو <bdi>nicardipine</bdi>) يقلل خطر توسع النزيف بدون التسبب بنقص تروية.",
        "النزول لأقل من 130 ربط بزيادة الضرر، فالهدف هو مجال معتدل مو أدنى قيمة ممكنة.",
    ],
    "when_changes": [
        "لو كان المريض يعاني <bdi>ischemic stroke</bdi> بدون علاج حالّ للخثرة، الهدف يصير أعلى من 220/120 فقط.",
        "لو كان مرشح لعلاج <bdi>tPA</bdi>، الهدف يصير أقل من 185/110 قبل العلاج وأقل من 180/105 بعده.",
    ],
    "rule": "نزيف دماغي بسبب ضغط مرتفع = خفض <bdi>SBP</bdi> إلى حوالي 140 بسلاسة، بدون النزول تحت 130.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر نفسه ذكر تعارض بين الإجابتين B و C (\"C or B\")، فهذا الجواب فيه خلاف داخل المصدر، لكن الأقرب للإرشادات الحديثة هو C.",
},
"AS-0267": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "مريض تحسن من الالتهاب الرئوي لكن ظهر عنده نقص بالصفائح، والسؤال يبي الدواء المسبب من بين الأدوية المعطاة فعليًا.",
    "clues": [
        ("Reduced platelets count", "نقص صفائح جديد بعد بدء أدوية، يوجه لـ<bdi>drug-induced thrombocytopenia</bdi>"),
    ],
    "why_correct": [
        "<bdi>ceftriaxone</bdi> سبب معروف لـ<bdi>drug-induced immune thrombocytopenia</bdi> عن طريق أضداد تعتمد على الدواء تدمر الصفائح.",
        "المريض تحسن سريريًا من الالتهاب الرئوي، فيمكن تغيير المضاد الحيوي لدواء آخر مناسب لإكمال العلاج بأمان.",
        "لازم نحصر السبب بين الأدوية التي أُعطيت فعليًا فقط، مو كل دواء معروف بالتسبب بهذا التأثير.",
    ],
    "when_changes": [
        "لو كان المريض على <bdi>heparin</bdi>، لازم نفكر بـ<bdi>HIT</bdi> ونحسب <bdi>4T score</bdi> بدل التفكير بمضاد حيوي.",
        "لو <bdi>vancomycin</bdi> كان من ضمن الأدوية المعطاة فعليًا، يصير هو المرشح الأقوى.",
    ],
    "rule": "نقص صفائح جديد بعد أدوية = حدد السبب من بين الأدوية المعطاة فعليًا وأوقفه؛ الصفائح ترجع بأيام.",
    "comparison": None,
    "labs": [["Platelets", "~70", "150-400 x10^9/L"]],
    "guideline_note": None,
},
"AS-0275": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "السؤال يفرق بين <bdi>type 1</bdi> و<bdi>type 2 diabetes</bdi> باستخدام <bdi>C-peptide</bdi> كمقياس لإفراز الإنسولين الذاتي.",
    "clues": [
        ("positive family history of type1 diabetes mellitus", "عامل خطر يدعم <bdi>type 1 DM</bdi>"),
        ("C-peptide 0.09 (low)", "دليل مباشر على نقص شديد بإفراز الإنسولين الذاتي"),
    ],
    "why_correct": [
        "ارتفاع <bdi>HbA1c</bdi> يأكد وجود <bdi>diabetes mellitus</bdi>، و<bdi>C-peptide</bdi> المنخفض جدًا يعني غياب إنسولين ذاتي، وهذا يحدد <bdi>type 1 DM</bdi> (حتى بالبالغين، <bdi>LADA</bdi>).",
        "التاريخ العائلي لـ<bdi>type 1 DM</bdi> يدعم التشخيص.",
        "ارتفاع <bdi>PTH</bdi> والكالسيوم يمثل <bdi>primary hyperparathyroidism</bdi>، وهو تشخيص منفصل لا يغيّر تشخيص السكري.",
    ],
    "when_changes": [
        "لو كان <bdi>C-peptide</bdi> طبيعي أو مرتفع مع سمنة، يصير الجواب <bdi>type 2 DM</bdi>.",
        "لو كان المريض أصغر مع عدة أجيال مصابين و<bdi>C-peptide</bdi> محفوظ، يفكر بـ<bdi>MODY</bdi>.",
    ],
    "rule": "<bdi>C-peptide</bdi> منخفض = نقص إنسولين ذاتي = <bdi>type 1 DM</bdi>؛ طبيعي أو مرتفع = مقاومة إنسولين (<bdi>type 2</bdi> أو <bdi>MODY</bdi>).",
    "comparison": None,
    "labs": [["HbA1c", "8.5%", "4.0-5.6%"], ["C-peptide", "0.09 (low)", "variable, typically 0.3-2.0 nmol/L"]],
    "guideline_note": None,
},
"AS-0278": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "<bdi>cholesterol</bdi> طبيعي على جرعة عالية من <bdi>statin</bdi>، والمشكلة المتبقية ارتفاع خفيف بالـ<bdi>triglycerides</bdi>، فالخطوة التالية علاج موجه للـ<bdi>TG</bdi>.",
    "clues": [
        ("high dose of atorvastatins", "الهدف من <bdi>LDL</bdi> محقق فعلًا، فما نحتاج زيادة جرعة <bdi>statin</bdi>"),
        ("Triglycerides: significantly elevated (2.8)", "ارتفاع خفيف بالـ<bdi>TG</bdi> هو المشكلة المتبقية فقط"),
    ],
    "why_correct": [
        "بما إن <bdi>cholesterol</bdi> ضمن الطبيعي على جرعة عالية من <bdi>statin</bdi>، هدف <bdi>LDL</bdi> محقق.",
        "المتبقي ارتفاع خفيف بـ<bdi>triglycerides</bdi>، والخطوة المناسبة هي <bdi>omega-3 fatty acids</bdi> مع تعديل نمط الحياة.",
        "<bdi>omega-3</bdi> له فائدة قلبية مثبتة بالمرضى اللي عندهم <bdi>TG</bdi> متبقي مرتفع مع <bdi>ASCVD</bdi> أو سكري.",
    ],
    "when_changes": [
        "لو <bdi>LDL</bdi> كان أعلى من الهدف على نفس جرعة <bdi>statin</bdi>، الجواب يصير زيادة الجرعة أو إضافة <bdi>ezetimibe</bdi>.",
        "لو <bdi>TG</bdi> كان مرتفع جدًا بمستوى خطر <bdi>pancreatitis</bdi>، الجواب يصير <bdi>fibrate</bdi>.",
    ],
    "rule": "ارتفاع خفيف بـ<bdi>TG</bdi> مع <bdi>LDL</bdi> ضمن الهدف على <bdi>statin</bdi> = نمط حياة + <bdi>omega-3</bdi>؛ <bdi>niacin</bdi> غير مستخدم حاليًا.",
    "comparison": None,
    "labs": [["Triglycerides", "2.8 mmol/L", "normal up to ~2.2 mmol/L"]],
    "guideline_note": None,
},
"AS-0297": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "السؤال اختبار مطابقة: نشوف أرقام المريض الفعلية وأي معيار جاهزية يطابقها فيزيولوجيًا وضمن حد <bdi>TLS</bdi>.",
    "clues": [
        ("tumor lysis syndrome (TLS)", "السؤال عن معايير الجاهزية لإعادة <bdi>chemotherapy</bdi> بعد <bdi>TLS</bdi>"),
        ("resumption of chemotherapy", "نبحث عن المعيار الذي يثبت تعافي الاضطرابات الكيميائية"),
    ],
    "why_correct": [
        "أرقام المريض (<bdi>uric acid 460</bdi>، <bdi>creatinine 135</bdi>، <bdi>pH 7.2</bdi>) تحقق معايير الخيار B بالكامل.",
        "عتبة <bdi>uric acid</bdi> لـ<bdi>TLS</bdi> تقريبًا 476 (8 mg/dL)، فأقل من 475 يعني أن فرط حمض اليوريك تعافى.",
        "نختبر أرقام المريض الفعلية مقابل كل معيار، ونستثني أي قيمة مستحيلة فيزيولوجيًا.",
    ],
    "when_changes": [
        "لو كان <bdi>uric acid</bdi> المريض 400 مثلًا، أي معيار بعتبة أقل من 475 يبقى صحيحًا أيضًا، لكن المطابقة تبقى بنفس الطريقة.",
        "أي خيار فيه <bdi>pH ≥ 8</bdi> يُستثنى مباشرة لأنه غير متوافق مع الحياة.",
    ],
    "rule": "في أسئلة المطابقة بالعتبات، اختبر أرقام المريض ضد كل خيار واستثن القيم المستحيلة فيزيولوجيًا.",
    "comparison": None,
    "labs": [["Uric acid", "460", "below ~475-476 umol/L (TLS threshold)"], ["Creatinine", "135", "below 141 umol/L"], ["Blood pH", "7.2", "≥7"]],
    "guideline_note": None,
},
"AS-0322": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "ألم عضلي معمم مع ضعف عند مريض على <bdi>atorvastatin</bdi>، والسؤال يحدد الدواء المسبب الأكثر احتمالًا.",
    "clues": [
        ("atorvastatin", "السبب الأكثر شيوعًا للأعراض العضلية المعممة"),
        ("muscle weakness and generalized muscle aches", "الوصف الكلاسيكي لـ<bdi>statin-associated muscle symptoms</bdi>"),
    ],
    "why_correct": [
        "<bdi>muscle weakness</bdi> مع ألم عضلي معمم عند مريض على <bdi>atorvastatin</bdi> هو العرض الجانبي الكلاسيكي لـ<bdi>statins</bdi>.",
        "لازم نفحص <bdi>CK</bdi> و<bdi>renal function</bdi>، وإذا كان <bdi>CK</bdi> مرتفع أو الأعراض لا تحمل، يوقف أو يغيّر <bdi>statin</bdi>.",
        "هذا العرض يتدرج من ألم بسيط (<bdi>myalgia</bdi>) إلى ضعف حقيقي (<bdi>myopathy</bdi>) وإلى حالات نادرة شديدة (<bdi>rhabdomyolysis</bdi>).",
    ],
    "when_changes": [
        "لو كان الضعف مرتبط بانخفاض <bdi>potassium</bdi> أو تشنجات بعد <bdi>thiazide</bdi>، يصير السبب هو الـ<bdi>diuretic</bdi>.",
        "لو كان العرض سعال جاف أو <bdi>angioedema</bdi>، يصير السبب <bdi>lisinopril</bdi>.",
    ],
    "rule": "ألم وضعف عضلي معمم عند مريض على <bdi>statin</bdi> = اعتبره <bdi>statin myopathy</bdi> حتى يثبت العكس، وافحص <bdi>CK</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0323": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "<bdi>aortic stenosis</bdi> بدون أعراض ومع <bdi>EF</bdi> طبيعي لا يحتاج تدخل، بل متابعة دورية.",
    "clues": [
        ("bicuspid aortic stenosis", "نوع تشريحي من التضيق يحتاج تقييم دوري"),
        ("normal EF, no LV dilation", "القلب يعمل بشكل جيد، لا دليل على فشل عضلة القلب"),
        ("with no symptoms", "غياب الأعراض هو العامل الحاسم لعدم التدخل"),
    ],
    "why_correct": [
        "قرار التدخل بـ<bdi>aortic stenosis</bdi> يعتمد على وجود <bdi>symptoms</bdi> أو ضعف بوظيفة البطين، وكلاهما غائب هنا.",
        "<bdi>LVH</bdi> هو استجابة تعويضية طبيعية لزيادة الحمل على الضغط، وليس مؤشرًا بذاته للجراحة.",
        "المتابعة الدورية بالفحص السريري والـ<bdi>echocardiography</bdi> المتكررة هي الخطوة الصحيحة، مع تدخل فوري عند ظهور أعراض.",
    ],
    "when_changes": [
        "لو ظهرت أعراض مثل <bdi>angina</bdi> أو <bdi>syncope</bdi> أو <bdi>dyspnea</bdi>، يصير الجواب استبدال الصمام.",
        "لو انخفض <bdi>EF</bdi>، يصير الجواب أيضًا استبدال الصمام حتى بدون أعراض واضحة.",
    ],
    "rule": "<bdi>AS</bdi> بدون أعراض و<bdi>EF</bdi> طبيعي = متابعة؛ أي عرض أو انخفاض <bdi>EF</bdi> = استبدال الصمام.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0333": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "السؤال يختبر حساب معايير <bdi>SIRS</bdi> بدقة بعد تدخل على القناة المرارية.",
    "clues": [
        ("cholangitis intervention", "تدخل حديث يمكن يسبب استجابة التهابية"),
        ("HR 92", "معيار واحد من معايير <bdi>SIRS</bdi> (أعلى من 90)"),
        ("WBC low", "معيار آخر من معايير <bdi>SIRS</bdi> (أقل من 4000)"),
    ],
    "why_correct": [
        "المريض يحقق معيارين من <bdi>SIRS</bdi>: <bdi>HR 92</bdi> (أعلى من 90) و<bdi>WBC</bdi> منخفض (أقل من 4000).",
        "درجة الحرارة 38 بالضبط لا تحتسب لأن العتبة هي أعلى من 38، و<bdi>RR 18</bdi> لا يحتسب لأن العتبة أعلى من 20.",
        "ضغط الدم 115/88 طبيعي، وهذا يستثني <bdi>septic shock</bdi>، والمصدر لم يثبت عدوى مؤكدة لذا بقي عند مستوى <bdi>SIRS</bdi>.",
    ],
    "when_changes": [
        "لو ثبت مصدر عدوى واضح (مزارع إيجابية أو دعامة ملتهبة)، يصير الجواب <bdi>sepsis</bdi>.",
        "لو انخفض ضغط الدم بشكل لا يستجيب للسوائل، يصير الجواب <bdi>septic shock</bdi>.",
    ],
    "rule": "عدّ كل معيار بدقة؛ القيمة المساوية للعتبة بالضبط لا تحتسب، ومعيارين أو أكثر = <bdi>SIRS</bdi>.",
    "comparison": None,
    "labs": [["Heart rate", "92/min", ">90/min counts"], ["Temperature", "38 C", ">38 C counts (38 exactly does not)"], ["Respiratory rate", "18/min", ">20/min counts"]],
    "guideline_note": None,
},
"AS-0336": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "دم بالبول بدون ألم مع ارتفاع ضغط بعد 3 أسابيع من التهاب بالحلق يوجه لـ<bdi>post-streptococcal glomerulonephritis</bdi>.",
    "clues": [
        ("red Urine for 5 days", "بيلة دموية بدون ألم تدل على مشكلة كبيّة مو حصوة أو عدوى"),
        ("tonsillitis 3 weeks ago", "فترة كامنة من 1 إلى 3 أسابيع تحدد التشخيص"),
        ("elevated blood pressure", "جزء من الصورة الكلوية (<bdi>nephritic syndrome</bdi>)"),
    ],
    "why_correct": [
        "بيلة دموية بدون ألم مع ارتفاع ضغط ظاهرة <bdi>3 weeks</bdi> بعد التهاب حلق هي صورة <bdi>nephritic</bdi> كلاسيكية بعد عدوى.",
        "غياب الألم يستثني الحصوة، وفترة الكمون 1 إلى 3 أسابيع هي العلامة الحاسمة لـ<bdi>PSGN</bdi>.",
        "عمره <bdi>18</bdi> سنة يستثني <bdi>hypernephroma</bdi> اللي يصيب كبار السن.",
    ],
    "when_changes": [
        "لو ظهر الدم بالبول بعد 1 إلى 2 يوم فقط من العدوى (<bdi>synpharyngitic</bdi>)، الجواب يصير <bdi>IgA nephropathy</bdi>.",
        "لو كان المريض كبير بالسن مع كتلة بالخصر، يفكر بـ<bdi>hypernephroma</bdi>.",
    ],
    "rule": "فترة الكمون بعد التهاب الحلق تحدد التشخيص: أيام = <bdi>IgA nephropathy</bdi>؛ أسابيع = <bdi>PSGN</bdi>.",
    "comparison": None,
    "labs": [["Blood pressure", "160/100 mmHg", "below 120/80 mmHg"]],
    "guideline_note": None,
},
"AS-0337": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "ارتباك جديد عند مريض مسن مع حمى وعسر تبول يوجه لـ<bdi>delirium</bdi> سببه عدوى مسالك بولية، والعلاج هو علاج السبب.",
    "clues": [
        ("elderly", "عمر يرفع احتمالية <bdi>delirium</bdi> كاستجابة لأي ضغط جسدي"),
        ("fever, dysuria", "علامات مباشرة على <bdi>UTI</bdi>"),
        ("leukocytes present", "تأكيد وجود عدوى بالبول"),
        ("reverse the CNS symptoms", "السؤال عن السبب الذي سيحل الارتباك فعليًا"),
    ],
    "why_correct": [
        "مريض مسن مع حمى وعسر تبول وخلايا بيضاء بالبول يعني عدوى مسالك بولية، والارتباك الجديد هو <bdi>delirium</bdi> ناتج عنها.",
        "<bdi>delirium</bdi> يتحسن بعلاج سببه، والمضاد الحيوي المناسب هو ما يعالج سبب الارتباك.",
        "<bdi>Na 132</bdi> انخفاض خفيف جدًا ولا يفسر لحاله ارتباك حاد بهذا الشكل.",
    ],
    "when_changes": [
        "لو كان الصوديوم منخفض جدًا أو ينخفض بسرعة مع تشنجات، يصير تصحيح الصوديوم هو الأولوية.",
        "لو كان هناك علامات <bdi>tetany</bdi> أو <bdi>QT prolongation</bdi>، يفكر بتصحيح الكالسيوم.",
    ],
    "rule": "ارتباك حاد عند مسن مع حمى وعلامات مسالك بولية = <bdi>delirium</bdi> حتى يثبت العكس، وعلاجه هو علاج العدوى المسببة.",
    "comparison": None,
    "labs": [["Sodium", "132 mmol/L", "135-145 mmol/L"], ["Calcium", "1.6 mmol/L", "2.1-2.6 mmol/L"]],
    "guideline_note": None,
},
"AS-0339": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "نزيف دماغي خطير عند مريضة على <bdi>warfarin</bdi> تحتاج جراحة عاجلة، والسؤال عن أسرع طريقة لعكس تأثير <bdi>warfarin</bdi>.",
    "clues": [
        ("On Warfarin", "مضاد تخثر يحتاج عكس فوري عند نزيف خطير"),
        ("Subdural Hematoma", "نزيف داخل الجمجمة يهدد الحياة ويحتاج تدخل عاجل"),
        ("Already Received Vitamin K", "<bdi>vitamin K</bdi> أُعطي لكنه بطيء، يحتاج تعويض عوامل فوري"),
        ("Requires Urgent Surgical Evacuation", "الجراحة العاجلة تحتاج تصحيح <bdi>INR</bdi> فورًا"),
    ],
    "why_correct": [
        "<bdi>subdural hematoma</bdi> على <bdi>warfarin</bdi> نزيف يهدد الحياة ويحتاج عكس فوري بغض النظر عن قيمة <bdi>INR</bdi>.",
        "<bdi>vitamin K</bdi> أُعطي لكن تأثيره يحتاج ساعات، فنحتاج تعويض عوامل تخثر سريع.",
        "<bdi>4-factor PCC</bdi> يعوض العوامل II وVII وIX وX بحجم صغير وبدقائق، وهو مفضل على <bdi>FFP</bdi> لعكس <bdi>warfarin</bdi> العاجل.",
    ],
    "when_changes": [
        "لو كان <bdi>PCC</bdi> غير متوفر، يصير الجواب <bdi>FFP</bdi> كبديل.",
        "بعد السيطرة على النزيف، إعادة <bdi>warfarin</bdi> تكون بتقييم متخصص فقط، مو فورًا.",
    ],
    "rule": "نزيف خطير على <bdi>warfarin</bdi> = <bdi>vitamin K</bdi> + <bdi>4-factor PCC</bdi> فورًا (أو <bdi>FFP</bdi> إذا ما توفر <bdi>PCC</bdi>).",
    "comparison": None,
    "labs": [["INR", "3.9", "0.8-1.2 (therapeutic on warfarin ~2-3)"]],
    "guideline_note": None,
},
"AS-0340": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "<bdi>asthma</bdi> غير متحكم فيه على مرحلة 1 (<bdi>SABA</bdi> فقط)، والسؤال عن العلاج المضاف المناسب حسب سلم العلاج.",
    "clues": [
        ("mild intermittent asthma", "كانت الحالة بالأصل خفيفة ومتقطعة"),
        ("using her inhaler at least 3 times a week", "دليل على عدم تحكم كافٍ"),
        ("wake up in the middle of the night", "استيقاظ ليلي علامة أساسية على عدم التحكم"),
    ],
    "why_correct": [
        "استخدام البخاخ أكثر من مرتين بالأسبوع والاستيقاظ الليلي يعني أن <bdi>asthma</bdi> غير متحكم فيه على <bdi>SABA</bdi> فقط.",
        "الخطوة الصحيحة هي الانتقال للمرحلة 2 وإضافة علاج يومي وقائي.",
        "<bdi>inhaled corticosteroid</bdi> بجرعة منخفضة هو العلاج الوقائي المفضل في هذه المرحلة.",
    ],
    "when_changes": [
        "لو استمر عدم التحكم على <bdi>ICS</bdi> المنخفض، تضاف <bdi>LABA</bdi> للمرحلة 3.",
        "لو استمر مع جرعة متوسطة أو عالية من <bdi>ICS+LABA</bdi>، يفكر بإضافة <bdi>LTRA</bdi>.",
    ],
    "rule": "<bdi>LABA</bdi> بدون <bdi>ICS</bdi> خطأ دائمًا بالـ<bdi>asthma</bdi>؛ أول علاج وقائي يضاف هو <bdi>ICS</bdi> بجرعة منخفضة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0343": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "مريض سكري نوع 1 بغيبوبة سكر منخفض لكنه واعٍ، والسؤال عن الخطوة الأولى المناسبة.",
    "clues": [
        ("type 1 DM", "خطر مستمر لـ<bdi>hypoglycemia</bdi> مع علاج الإنسولين"),
        ("symptoms of hypoglycemia", "أعراض نقص سكر تحتاج تصحيح سريع"),
    ],
    "why_correct": [
        "المريض بغرفة الانتظار وظهرت عليه الأعراض، يعني أنه واعٍ وقادر على البلع.",
        "المريض الواعي القادر على البلع يعالج بكربوهيدرات سريعة عن طريق الفم مثل العصير.",
        "نعيد قياس السكر بعد 15 دقيقة ونكرر إذا بقي منخفض، بدون حاجة لوريد في هذه الحالة.",
    ],
    "when_changes": [
        "لو كان المريض فاقد الوعي أو لا يستطيع البلع وبدون وريد، يصير الجواب <bdi>glucagon</bdi> عضلي أو تحت الجلد.",
        "لو كان فاقد الوعي ومعه وريد، يصير الجواب <bdi>IV dextrose</bdi> مركّز.",
    ],
    "rule": "النعاس ليس فقدان وعي؛ إذا استطاع المريض البلع، الجلوكوز الفموي هو الخطوة الأولى.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0347": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "<bdi>acute chest syndrome</bdi> شديد مع إصابة رئوية ثنائية يحتاج علاج فوري بـ<bdi>exchange transfusion</bdi> لا علاج وقائي طويل الأمد.",
    "clues": [
        ("sickle cell disease", "مرض يرفع خطر <bdi>acute chest syndrome</bdi>"),
        ("acute chest syndrome", "الحالة الحادة التي نتعامل معها الآن"),
        ("bilateral lung infiltrates", "علامة على شدة المرض وامتداده لفصين أو أكثر"),
    ],
    "why_correct": [
        "إصابة رئوية ثنائية مع <bdi>acute chest syndrome</bdi> تدل على مرض شديد، وهذا مؤشر لـ<bdi>exchange transfusion</bdi>.",
        "<bdi>exchange transfusion</bdi> يخفض نسبة <bdi>HbS</bdi> بسرعة بدون زيادة لزوجة الدم، فيحسن الأكسجين ويوقف تكسير إضافي.",
        "يعطى مع الأكسجين والسوائل ومسكنات ومضادات حيوية واسعة المدى كجزء من العلاج الشامل.",
    ],
    "when_changes": [
        "لو كانت الحالة خفيفة بدون إصابة ثنائية، يكفي <bdi>simple transfusion</bdi>.",
        "لو السؤال عن تقليل تكرار النوبات مستقبلًا، الجواب يصير <bdi>hydroxyurea</bdi>.",
    ],
    "rule": "علاج النوبة الحادة الشديدة = <bdi>exchange transfusion</bdi>؛ الوقاية من النوبات المستقبلية = <bdi>hydroxyurea</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0349": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "نسخة مكررة من سؤال <bdi>acute chest syndrome</bdi> الشديد، نفس المنطق تمامًا.",
    "clues": [
        ("sickle cell disease", "مرض يرفع خطر <bdi>acute chest syndrome</bdi>"),
        ("acute chest syndrome", "الحالة الحادة الحالية"),
        ("bilateral lung infiltrates", "علامة على شدة المرض"),
    ],
    "why_correct": [
        "إصابة رئوية ثنائية مع <bdi>acute chest syndrome</bdi> تدل على مرض شديد يحتاج <bdi>exchange transfusion</bdi>.",
        "هذا الإجراء يخفض <bdi>HbS</bdi> بسرعة بدون رفع لزوجة الدم، فيحسن الأكسجين ويوقف التكسير.",
        "يصاحبه أكسجين وسوائل ومسكنات ومضادات حيوية واسعة المدى.",
    ],
    "when_changes": [
        "لو الحالة خفيفة، يكفي <bdi>simple transfusion</bdi>.",
        "للوقاية طويلة الأمد من النوبات، الجواب <bdi>hydroxyurea</bdi>.",
    ],
    "rule": "علاج النوبة الحادة الشديدة = <bdi>exchange transfusion</bdi>؛ الوقاية المستقبلية = <bdi>hydroxyurea</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0350": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "متلازمة شريان تاجي حادة عند مريض بعوامل خطر متعددة، والسؤال عن أقوى عامل خطر مذكور بالسيناريو.",
    "clues": [
        ("5-pack-year smoker", "تدخين خفيف نسبيًا، مو العامل الأقوى هنا"),
        ("blood pressure is 150/92", "ضغط مرتفع فعليًا أثناء العرض"),
    ],
    "why_correct": [
        "ارتفاع الضغط <bdi>150/92</bdi> موجود فعليًا عند العرض، و<bdi>hypertension</bdi> من أهم وأشهر عوامل خطر <bdi>coronary artery disease</bdi>.",
        "التدخين هنا خفيف (<bdi>5 pack-years</bdi> فقط)، فلا يعتبر العامل الأقوى بهذا السيناريو.",
        "عمره <bdi>40</bdi> سنة أقل من عتبة خطر العمر للرجال (<bdi>45</bdi> سنة)، فلا يحتسب كعامل خطر هنا.",
    ],
    "when_changes": [
        "لو كان التاريخ التدخيني ثقيل أو طويل المدى، يصير التدخين هو الإجابة.",
        "لو كان عمر المريض 45 أو أكبر، يصير العمر عامل خطر مهم.",
    ],
    "rule": "اختر عامل الخطر الذي حدد السؤال قيمته بوضوح كغير طبيعي، مو مجرد العامل المذكور.",
    "comparison": None,
    "labs": [["Blood pressure", "150/92 mmHg", "below 120/80 mmHg"]],
    "guideline_note": None,
},
"AS-0359": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "حمى مع نقص شديد بالخلايا البيضاء والعدلات بعد العلاج الكيميائي هي حالة طارئة (<bdi>febrile neutropenia</bdi>).",
    "clues": [
        ("chemotherapy", "عامل خطر رئيسي لنقص المناعة"),
        ("fever", "علامة الطوارئ الأساسية بهذا السيناريو"),
        ("low neutrophils", "يؤكد غياب الدفاع المناعي الطبيعي"),
    ],
    "why_correct": [
        "حمى بعد علاج كيميائي مع نقص خلايا بيضاء وعدلات هي <bdi>febrile neutropenia</bdi>، حالة طارئة طبية.",
        "بعد أخذ المزارع، يجب بدء مضادات حيوية وريدية واسعة المدى فورًا لأن العدوى قد تتطور لصدمة إنتانية بسرعة.",
        "لا ننتظر نتائج المزارع ولا نحدد بؤرة العدوى قبل بدء العلاج.",
    ],
    "when_changes": [
        "لو كان هناك شك بـ<bdi>herpes</bdi> أو <bdi>influenza</bdi> محدد، يضاف مضاد فيروسات موجّه.",
        "لو استمرت الحمى بعد أيام من المضادات الحيوية، يضاف مضاد فطريات.",
    ],
    "rule": "حمى بعد علاج كيميائي مع نقص عدلات = ابدأ مضادات حيوية وريدية واسعة فورًا بعد المزارع، بدون انتظار.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0367": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "ارتفاع ضغط مقاوم مع نقص بوتاسيوم وقلوية استقلابية يوجه لـ<bdi>primary hyperaldosteronism</bdi>، والسؤال عن اختبار الفحص الأول.",
    "clues": [
        ("persistent HTN despite being on 2 antihypertensive", "ضغط مقاوم للعلاج يوجه للبحث عن سبب ثانوي"),
        ("hypokalemia and metabolic alkalosis", "الصورة الكيميائية الكلاسيكية لزيادة الألدوستيرون"),
    ],
    "why_correct": [
        "ضغط مقاوم مع نقص بوتاسيوم وقلوية استقلابية عند شاب يوجه لـ<bdi>primary hyperaldosteronism</bdi>.",
        "زيادة الألدوستيرون تحتفظ بالصوديوم وتفرز البوتاسيوم والهيدروجين، مما يفسر الصورة الكيميائية.",
        "اختبار الفحص الأول هو نسبة <bdi>aldosterone:renin ratio</bdi>، التي تكون مرتفعة لأن الألدوستيرون مرتفع والرينين مثبط.",
    ],
    "when_changes": [
        "لو كان المريض يعاني صداع نوبي مع تعرق وخفقان، يفكر بـ<bdi>pheochromocytoma</bdi> ويطلب <bdi>plasma metanephrines</bdi>.",
        "لو كان مريض مسن بتصلب شرايين مع كلى غير متماثلة، يفكر بـ<bdi>renal artery stenosis</bdi>.",
    ],
    "rule": "ضغط مرتفع + نقص بوتاسيوم + قلوية استقلابية = ابدأ بـ<bdi>aldosterone:renin ratio</bdi> لفحص <bdi>Conn syndrome</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
}

WHY_WRONG = {
"AS-0254": {
    "A": "المراقبة فقط غير كافية مع <bdi>Hb</bdi> منخفض جدًا (60) يدل على تكسير نشط وشديد يحتاج تدخل.",
    "B": "وقف المضاد الحيوي غير صحيح لأن سبب التكسير هو <bdi>mycoplasma</bdi> نفسه، مو المضاد الحيوي.",
    "D": "<bdi>rituximab</bdi> يستخدم بالـ<bdi>primary cold agglutinin disease</bdi> المزمن أو عند فشل <bdi>steroids</bdi>، مو كخط أول هنا.",
},
"AS-0254B": {
    "A": "<bdi>aspirin</bdi> ليس له دور بعلاج التكسير، وهو سبب معروف لتحفيز التكسير بمرض <bdi>G6PD deficiency</bdi> ويزيد خطر النزيف.",
    "B": "<bdi>rituximab</bdi> يستخدم بالـ<bdi>warm AIHA</bdi> المعند أو <bdi>primary cold agglutinin disease</bdi>، مو كخط أول لتكسير سببه دواء يمكن وقفه.",
    "C": "<bdi>corticosteroids</bdi> خط أول لتكسير <bdi>warm AIHA</bdi> المناعي، أما بالتكسير المرتبط بدواء فهي علاج مساعد بعد وقف الدواء فقط.",
},
"AS-0262": {
    "A": "خفض الضغط لهذا المستوى (100-120) أقل من الهدف الموصى به، وقد يزيد خطر نقص التروية.",
    "B": "120-140 قريب من الهدف لكن أقل من النطاق الأدنى المقبول حاليًا (130-150)، وقد يكون خطأ إذا نزل الضغط تحت 130.",
    "D": "160-180 أعلى بكثير من الهدف المطلوب لخفض خطر توسع النزيف.",
},
"AS-0267": {
    "A": "<bdi>paracetamol</bdi> نادرًا جدًا يسبب نقص صفائح، وهو مسكن آمن عمومًا.",
    "B": "<bdi>tramadol</bdi> أعراضه الجانبية أساسًا على الجهاز العصبي المركزي، لا تسبب تكسير صفائح.",
    "D": "<bdi>vancomycin</bdi> سبب حقيقي لنقص صفائح مناعي، لكنه لم يُعطَ لهذا المريض أصلًا فلا يمكن اعتباره السبب.",
},
"AS-0275": {
    "B": "<bdi>type 2 DM</bdi> يكون فيه <bdi>C-peptide</bdi> طبيعي أو مرتفع نتيجة مقاومة الإنسولين، وهذا يعارض القيمة المنخفضة جدًا هنا.",
    "C": "<bdi>central diabetes insipidus</bdi> يسبب بوال وعطش مع بول مخفف وصوديوم مرتفع، لكن <bdi>HbA1c</bdi> هنا يفسر الأعراض بوضوح.",
    "D": "<bdi>MODY</bdi> يكون وراثيًا سائدًا مع <bdi>C-peptide</bdi> محفوظ وأضداد سلبية، وهذا لا يتوافق مع نقص الإنسولين الشديد هنا.",
},
"AS-0278": {
    "A": "زيادة جرعة <bdi>statin</bdi> لن تضيف تحسنًا كبيرًا بالـ<bdi>triglycerides</bdi> بينما الـ<bdi>LDL</bdi> محقق هدفه بالفعل.",
    "C": "<bdi>niacin</bdi> لم يثبت فائدة قلبية إضافية مع <bdi>statin</bdi> وله أعراض جانبية كثيرة، فلم يعد يُنصح به.",
    "D": "<bdi>evolocumab</bdi> يستخدم لخفض <bdi>LDL</bdi> المرتفع على جرعة قصوى من <bdi>statin</bdi>، وتأثيره على الـ<bdi>TG</bdi> ضعيف.",
},
"AS-0297": {
    "A": "عتبة <bdi>375</bdi> أكثر صرامة من العتبة الحقيقية لـ<bdi>TLS</bdi>، وستحجب المريض عن استئناف العلاج رغم تعافيه.",
    "C": "<bdi>pH</bdi> مساوٍ أو أعلى من 8 غير متوافق مع الحياة، فهذا المعيار مستحيل فيزيولوجيًا.",
},
"AS-0322": {
    "A": "<bdi>lisinopril</bdi> يسبب سعال جاف وتورم وارتفاع بوتاسيوم وكرياتينين، مو ألم عضلي.",
    "B": "<bdi>thiazide</bdi> يسبب ضعف عن طريق نقص بوتاسيوم أو صوديوم، وهذا يحتاج دليل مخبري يدعمه، بخلاف الألم العضلي المعمم هنا.",
},
"AS-0323": {
    "A": "<bdi>TAVR</bdi> يُستخدم للحالات العرضية الشديدة أو ضعف <bdi>EF</bdi>، وهذا المريض بدون أعراض وبوظيفة قلب طبيعية.",
    "B": "استبدال الصمام الجراحي يُحتاج فقط إذا ظهرت أعراض أو انخفض <bdi>EF</bdi>، وحتى عندها الصمام الحيوي مفضل بهذا العمر.",
},
"AS-0333": {
    "A": "<bdi>sepsis</bdi> يحتاج دليل عدوى مؤكد أو مفترض بوضوح، والمصدر لم يثبت ذلك هنا.",
    "C": "<bdi>bacteremia</bdi> يناسب رجفة بدون تحقق أي معيار من <bdi>SIRS</bdi>، لكن هنا تحقق معياران.",
    "D": "<bdi>septic shock</bdi> يحتاج انخفاض ضغط لا يستجيب للسوائل، وضغط المريض طبيعي هنا (115/88).",
},
"AS-0336": {
    "A": "<bdi>kidney stone</bdi> يسبب ألمًا متقطعًا شديدًا، وهذا المريض بدون أي ألم.",
    "B": "<bdi>hypernephroma</bdi> يصيب كبار السن مع كتلة بالخصر، غير متوقع بعمر 18 وبعد التهاب حلق.",
    "C": "<bdi>IgA nephropathy</bdi> يحدث خلال أيام من العدوى، بينما هنا الفترة 3 أسابيع، وهذا يناسب <bdi>PSGN</bdi> أكثر.",
},
"AS-0337": {
    "A": "<bdi>Na 132</bdi> انخفاض خفيف لا يفسر غالبًا ارتباكًا حادًا بهذا الشكل.",
    "B": "<bdi>calcium gluconate</bdi> يستخدم لعلاج نقص كالسيوم شديد مع أعراض تشنجية، وليس هذا السيناريو.",
    "C": "<bdi>IV fluids</bdi> علاج مساعد لو كان هناك جفاف، لكنه لا يعالج سبب الارتباك المباشر (العدوى).",
},
"AS-0339": {
    "A": "إعادة <bdi>warfarin</bdi> أثناء نزيف دماغي فعال وجراحة قادمة يزيد خطر النزيف بشكل خطير.",
    "B": "<bdi>FFP</bdi> فعّال لكنه أبطأ ويحتاج حجم أكبر وتذويب، فهو بديل فقط عند عدم توفر <bdi>PCC</bdi>.",
    "C": "<bdi>rFVIIa</bdi> ليس جزء من البروتوكول القياسي لعكس <bdi>warfarin</bdi> وله خطر تكوّن خثرات.",
},
"AS-0340": {
    "A": "<bdi>leukotriene receptor antagonist</bdi> خيار إضافي أو بديل في مراحل متأخرة، مو العلاج الأول المفضل هنا.",
    "B": "<bdi>LABA</bdi> وحدها بدون <bdi>ICS</bdi> تزيد خطر الوفاة بالـ<bdi>asthma</bdi> ولا تستخدم بمفردها أبدًا.",
    "D": "<bdi>cromolyn</bdi> فعاليته ضعيفة ولا يعتبر علاج وقائي مفضل بالإرشادات الحالية.",
},
"AS-0343": {
    "B": "<bdi>normal saline</bdi> لا يحتوي سكر، فلا يفيد بعلاج نقص السكر أصلًا.",
    "C": "<bdi>5% dextrose IV</bdi> أبطأ وغير ضروري لمريض قادر على البلع، وتركيزه ضعيف للتصحيح السريع.",
},
"AS-0347": {
    "A": "<bdi>allopurinol</bdi> يخفض حمض اليوريك فقط، لا علاقة له بعلاج <bdi>acute chest syndrome</bdi>.",
    "B": "<bdi>hydroxyurea</bdi> دواء وقائي طويل الأمد، لا يعالج نوبة حادة شديدة فورية.",
    "D": "<bdi>methotrexate</bdi> ليس له أي دور بمرض الخلايا المنجلية.",
},
"AS-0349": {
    "A": "<bdi>allopurinol</bdi> يخفض حمض اليوريك فقط، لا علاقة له بعلاج <bdi>acute chest syndrome</bdi>.",
    "B": "<bdi>hydroxyurea</bdi> دواء وقائي طويل الأمد، لا يعالج نوبة حادة شديدة فورية.",
    "D": "<bdi>methotrexate</bdi> ليس له أي دور بمرض الخلايا المنجلية.",
},
"AS-0350": {
    "A": "التدخين هنا خفيف نسبيًا (5 pack-years)، فلا يُعتبر العامل الأقوى بهذا السيناريو.",
    "B": "الجنس الذكري عامل خطر غير قابل للتعديل وأثره أضعف من حالة مؤكدة كارتفاع الضغط.",
    "C": "عمره 40 أقل من عتبة خطر العمر للرجال (45 سنة)، فلا يحتسب كعامل خطر هنا.",
},
"AS-0359": {
    "B": "المراقبة فقط تؤخر العلاج بمريض بلا دفاع مناعي من العدلات، وهذا غير مقبول أبدًا بـ<bdi>febrile neutropenia</bdi>.",
    "C": "مضادات الفيروسات تضاف فقط لسبب محدد (<bdi>herpes</bdi> أو <bdi>influenza</bdi>)، وليست علاجًا أوليًا روتينيًا.",
    "D": "المضاد الفموي يُحفظ لحالات منخفضة الخطر بالعيادات الخارجية، والفطريات تضاف فقط بعد استمرار الحمى أيامًا.",
},
"AS-0367": {
    "A": "<bdi>24-hour urine cortisol</bdi> يفحص <bdi>Cushing syndrome</bdi> الذي يظهر بملامح مختلفة (سمنة مركزية، علامات تمدد) غير موجودة هنا.",
    "C": "<bdi>plasma metanephrines</bdi> يفحص <bdi>pheochromocytoma</bdi> الذي يظهر بصداع نوبي وتعرق وخفقان، وليس بهذه الصورة الكيميائية.",
    "D": "<bdi>renal artery Doppler</bdi> يستخدم لشك بتضيق الشريان الكلوي، وغالبًا يكون الرينين مرتفعًا فيه عكس هذه الحالة.",
},
}

HIGHLIGHT_TERMS = {
"AS-0254": ["mycoplasma pneumonia", "yellowish discolouration of the eyes", "Hb 60", "Reticulocyte 4 (high)", "Haptoglobin 0.4"],
"AS-0254B": ["put on medications", "Hb: 68", "Haptoglobin: low", "LDH: high"],
"AS-0262": ["intracerebral hemorrhage", "hemodynamically stable"],
"AS-0267": ["Reduced platelets count"],
"AS-0275": ["positive family history of type1 diabetes mellitus", "C-peptide 0.09 (low)"],
"AS-0278": ["high dose of atorvastatins", "cholesterol: within normal range", "Triglycerides: significantly elevated (2.8)"],
"AS-0297": ["tumor lysis syndrome (TLS)", "resumption of chemotherapy"],
"AS-0322": ["atorvastatin", "muscle weakness and generalized muscle aches"],
"AS-0323": ["bicuspid aortic stenosis", "normal EF, no LV dilation", "with no symptoms"],
"AS-0333": ["cholangitis intervention", "HR 92", "Temp 38", "WBC low"],
"AS-0336": ["18-year", "red Urine for 5 days", "tonsillitis 3 weeks ago", "elevated blood pressure"],
"AS-0337": ["elderly", "fever, dysuria", "confusion", "leukocytes present", "reverse the CNS symptoms"],
"AS-0339": ["On Warfarin", "Subdural Hematoma", "Already Received Vitamin K", "Requires Urgent Surgical Evacuation"],
"AS-0340": ["mild intermittent asthma", "using her inhaler at least 3 times a week", "wake up in the middle of the night"],
"AS-0343": ["type 1 DM", "symptoms of hypoglycemia"],
"AS-0347": ["sickle cell disease", "acute chest syndrome", "bilateral lung infiltrates"],
"AS-0349": ["sickle cell disease", "acute chest syndrome", "bilateral lung infiltrates"],
"AS-0350": ["5-pack-year smoker", "blood pressure is 150/92"],
"AS-0359": ["chemotherapy", "fever", "low neutrophils"],
"AS-0367": ["persistent HTN despite being on 2 antihypertensive", "hypokalemia and metabolic alkalosis"],
}
