# -*- coding: utf-8 -*-
# Batch r04 — slice abosarah2026/data/slices/r04.json (141 questions)

EXPLANATIONS = {
"AS-0751": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "السؤال عن أشيع <bdi>cause</bdi> لـ<bdi>postpartum hemorrhage (PPH)</bdi> لما يكون عند المريضة عوامل خطورة متعددة لـ<bdi>uterine atony</bdi> مجتمعة بنفس السيناريو.",
    "clues": [
        ("G8 P5126", "<bdi>grand multiparity</bdi>، عامل خطورة لـ<bdi>uterine atony</bdi>"),
        ("oxytocin", "<bdi>prolonged oxytocin exposure</bdi> يتعب العضلة ويضعف تقلصها بعد الولادة"),
        ("chorioamnionitis", "<bdi>infection</bdi> تثبط انقباض العضلة الرحمية"),
    ],
    "why_correct": [
        "<bdi>large continuous bleeding</bdi> بعد الولادة هو <bdi>postpartum hemorrhage (PPH)</bdi>، وأشيع <bdi>cause</bdi> له هو <bdi>uterine atony</bdi>.",
        "هذي المريضة عندها كل عوامل خطورة <bdi>atony</bdi>: <bdi>grand multiparity (G8)</bdi>، و<bdi>prolonged oxytocin</bdi>، و<bdi>chorioamnionitis</bdi>، وكل هذي تضعف انقباض <bdi>myometrium</bdi>.",
        "فالجواب الأقوى والمنطقي هو <bdi>uterine atony</bdi>، مو الأسباب الأخرى اللي تحتاج قرائن خاصة.",
    ],
    "when_changes": [
        "لو قالوا <bdi>uterus is firm</bdi> بعد الولادة، الجواب يصير <bdi>genital tract laceration</bdi> مو <bdi>atony</bdi>.",
        "لو ذكروا <bdi>incomplete placenta</bdi> أو نزيف متأخر بعد أسابيع، الجواب يصير <bdi>retained placental tissue</bdi>.",
    ],
    "rule": "<bdi>oxytocin exposure</bdi> + <bdi>chorioamnionitis</bdi> + <bdi>grand multipara</bdi> = <bdi>uterine atony</bdi>، وهو أشيع <bdi>cause</bdi> لـ<bdi>PPH</bdi> بشكل عام.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0752": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "نزيف بعد الولادة بوقت قريب (<bdi>primary PPH</bdi>) مع <bdi>twin pregnancy</bdi>، والسؤال يبي أشيع <bdi>cause</bdi>.",
    "clues": [
        ("term twin pregnancy", "<bdi>overdistension</bdi> للرحم يضعف الانقباض بعد الولادة"),
    ],
    "why_correct": [
        "نزيف نشط <bdi>2 hours</bdi> بعد الولادة هو <bdi>primary PPH</bdi>، وأشيع <bdi>cause</bdi> له <bdi>uterine atony</bdi>.",
        "<bdi>twin pregnancy</bdi> تعني <bdi>overdistension</bdi> للرحم، وهذا يخلي الانقباض بعد الولادة أضعف، فيزيد احتمال <bdi>atony</bdi>.",
        "ما فيه أي قرينة عن <bdi>trauma</bdi> أو <bdi>coagulopathy</bdi> أو <bdi>retained tissue</bdi>، فالجواب الافتراضي <bdi>atony</bdi>.",
    ],
    "when_changes": [
        "لو قالوا <bdi>uterus firm</bdi> الجواب يتغير لـ<bdi>genital tract trauma</bdi>.",
        "لو كان عندها <bdi>known bleeding disorder</bdi> أو <bdi>abruption</bdi>، الجواب يصير <bdi>coagulopathy</bdi>.",
    ],
    "rule": "<bdi>PPH</bdi> = <bdi>atony</bdi> لحد ما يثبت عكسه، و<bdi>twins</bdi> يعني <bdi>overdistended uterus</bdi> يعني <bdi>atony</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0753": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "<bdi>PPH</bdi> بعد ساعة من ولادة طبيعية، والسؤال يحاول يشتت الذهن بذكر <bdi>low-lying placenta</bdi> بدل ما يركّز على السبب الحقيقي.",
    "clues": [
        ("low-lying placenta", "مش قرينة عن <bdi>accreta</bdi> أو <bdi>trauma</bdi>، بس تزيد فرصة <bdi>atony</bdi> بالقطعة السفلية"),
        ("One hour post-delivery", "توقيت <bdi>primary PPH</bdi>"),
    ],
    "why_correct": [
        "<bdi>PPH</bdi> بعد <bdi>one hour</bdi> من ولادة طبيعية أشيع سبب له <bdi>uterine atony</bdi>.",
        "<bdi>low-lying placenta</bdi> لا تغيّر الجواب، بالعكس القطعة السفلية تنقبض أضعف فتزيد احتمال نزيف من موقع المشيمة بسبب <bdi>atony</bdi>.",
        "ما فيه أي ذكر لـ<bdi>trauma</bdi> أو <bdi>shock مع absent fundus</bdi> أو <bdi>bleeding disorder</bdi>.",
    ],
    "when_changes": [
        "لو ذكروا <bdi>cord traction</bdi> على مشيمة قمة الرحم مع <bdi>shock</bdi> و<bdi>absent fundus</bdi>، الجواب يصير <bdi>uterine inversion</bdi>.",
        "لو ذكروا <bdi>oozing from all sites</bdi> الجواب يصير <bdi>coagulopathy</bdi>.",
    ],
    "rule": "لا تنخدع بـ<bdi>low-lying placenta</bdi>: الجواب يفضل <bdi>atony</bdi> إلا إذا فيه قرينة واضحة لسبب آخر.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0754": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "<bdi>heavy gush of bleeding</bdi> بعد الولادة بدون أي قرائن خاصة بسبب ثاني، فالجواب الافتراضي هو أشيع <bdi>cause</bdi>.",
    "clues": [
        ("not known to have any medical or surgical history", "يستبعد <bdi>bleeding disorder</bdi>"),
        ("heavy gush of bleeding postpartum", "<bdi>postpartum hemorrhage</bdi> بدون قرينة <bdi>trauma</bdi> أو <bdi>retained tissue</bdi>"),
    ],
    "why_correct": [
        "\"<bdi>heavy gush of bleeding postpartum</bdi>\" هو <bdi>PPH</bdi>، وأشيع سبب له بالمطلق هو <bdi>uterine atony</bdi>.",
        "لا تاريخ طبي يدل على <bdi>bleeding disorder</bdi>، ولا ولادة <bdi>instrumental</bdi> تدل على <bdi>trauma</bdi>، ولا مشيمة ناقصة تدل على <bdi>retained tissue</bdi>.",
        "القاعدة: <bdi>PPH</bdi> يُعتبر <bdi>atony</bdi> لحد ما يثبت العكس.",
    ],
    "when_changes": [
        "لو قالوا الرحم <bdi>firm</bdi>، الجواب يصير <bdi>cervical/vaginal injury</bdi>.",
        "لو ذكروا مشيمة ناقصة بالفحص، الجواب يصير <bdi>retained placental fragments</bdi>.",
    ],
    "rule": "<bdi>4 Ts</bdi> لـ<bdi>PPH</bdi> بالترتيب: <bdi>Tone (atony)</bdi> &gt; <bdi>Trauma</bdi> &gt; <bdi>Tissue</bdi> &gt; <bdi>Thrombin</bdi>، وبدون قرينة مميزة الجواب <bdi>Tone</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0755": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "<bdi>PPH</bdi> مع ذكر صريح إن الرحم <bdi>firm</bdi>، وهذا يقلب الجواب من <bdi>atony</bdi> إلى السبب الثاني بالترتيب.",
    "clues": [
        ("uterus noted to be firm", "<bdi>normal tone</bdi>، يستبعد <bdi>atony</bdi> مباشرة"),
    ],
    "why_correct": [
        "<bdi>1000 cc</bdi> نزيف بعد خروج المشيمة هو <bdi>PPH</bdi>.",
        "القرينة الحاسمة إن الرحم <bdi>firm</bdi>، يعني <bdi>tone</bdi> طبيعي، فهذا يستبعد <bdi>atony</bdi>.",
        "مع رحم منقبض كويس، أشيع سبب متبقي هو <bdi>genital tract laceration</bdi> (ثاني أشيع سبب لـ<bdi>PPH</bdi> بشكل عام).",
    ],
    "when_changes": [
        "لو كان الرحم <bdi>soft, boggy</bdi> الجواب يرجع لـ<bdi>uterine atony</bdi>.",
        "لو ذكروا مشيمة غير مكتملة، الجواب يصير <bdi>retained product of conception</bdi>.",
    ],
    "rule": "<bdi>PPH</bdi> + رحم <bdi>firm</bdi> = لازم تبحث عن <bdi>laceration</bdi>؛ رحم <bdi>boggy</bdi> = <bdi>atony</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0756": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "الفحص السريري نفسه كشف السبب بوضوح: <bdi>lacerations</bdi> مرئية بعد ولادة <bdi>forceps</bdi> لجنين كبير.",
    "clues": [
        ("forceps delivery", "عامل خطورة كلاسيكي لـ<bdi>genital tract trauma</bdi>"),
        ("laceration of the cervix, vagina, and the perineal body", "القرينة المباشرة والقاطعة للسبب"),
    ],
    "why_correct": [
        "الفحص وصف مباشرة \"<bdi>laceration of the cervix, vagina, and the perineal body</bdi>\"، وهذا دليل مباشر على مصدر النزيف.",
        "ولادة <bdi>forceps</bdi> لجنين <bdi>3.7 kg</bdi> (كبير نسبيًا) عامل خطورة معروف لـ<bdi>genital tract trauma</bdi>.",
        "إذن النزيف هنا من <bdi>Trauma</bdi> ضمن <bdi>4 Ts</bdi>، مو <bdi>atony</bdi> ولا غيره.",
    ],
    "when_changes": [
        "لو الفحص طبيعي بدون تمزقات، يرجع التفكير لـ<bdi>atony</bdi> كأشيع سبب.",
        "لو ذكروا <bdi>mass in vagina</bdi> مع <bdi>absent fundus</bdi>، الجواب يصير <bdi>uterine inversion</bdi>.",
    ],
    "rule": "<bdi>atony</bdi> أشيع سبب بشكل عام، بس لما الفحص يثبت <bdi>lacerations</bdi> واضحة الجواب يصير <bdi>trauma</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0757": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "التوقيت هو مفتاح السؤال: نزيف بعد <bdi>12 days</bdi> من الولادة هو <bdi>secondary PPH</bdi>، وله سبب مختلف عن <bdi>primary PPH</bdi>.",
    "clues": [
        ("12 days ago", "يضع النزيف ضمن <bdi>secondary PPH</bdi> (24 ساعة إلى 12 أسبوع)"),
    ],
    "why_correct": [
        "نزيف بعد <bdi>12 days</bdi> من الولادة هو <bdi>secondary PPH</bdi>.",
        "أشيع سبب لـ<bdi>secondary PPH</bdi> هو <bdi>retained products of conception</bdi>، وغالبًا مصحوب بـ<bdi>endometritis</bdi> يمنع التقلص الطبيعي لموقع المشيمة.",
        "هذا يختلف تمامًا عن <bdi>primary PPH</bdi> اللي أشيع سببه <bdi>atony</bdi>.",
    ],
    "when_changes": [
        "لو النزيف كان بنفس يوم الولادة أو أول 24 ساعة، الجواب يصير <bdi>uterine atony</bdi>.",
        "لو فيه حمى وألم مع النزيف المتأخر، فكّر بـ<bdi>endometritis</bdi> مصاحب ويحتاج <bdi>antibiotics</bdi> مع تفريغ الرحم.",
    ],
    "rule": "التوقيت يحدد السبب: نزيف مبكر = <bdi>atony</bdi>، نزيف بعد أيام لأسابيع = <bdi>retained products</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0763": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "<bdi>asymptomatic bacteriuria</bdi> عند الحامل لازم تُعالج دايمًا، وزراعة البول هي المرجع مو شريط البول.",
    "clues": [
        ("Asymptomatic Pregnant", "الحمل يغيّر القرار: المعالجة واجبة حتى بدون أعراض"),
        ("urine culture positive for E coli", "<bdi>culture</bdi> هو الفاحص المرجعي، وإيجابيته كافية للعلاج"),
    ],
    "why_correct": [
        "<bdi>positive urine culture</bdi> لـ<bdi>E. coli</bdi> عند حامل بدون أعراض هو <bdi>asymptomatic bacteriuria</bdi>.",
        "بالحمل لازم يُعالج لتجنب تطوره إلى <bdi>pyelonephritis</bdi> ومضاعفاته على الحمل.",
        "<bdi>culture</bdi> هو الفاحص المعياري، و<bdi>negative nitrite</bdi> على شريط البول لا يلغي نتيجة <bdi>culture</bdi> الإيجابية.",
    ],
    "when_changes": [
        "لو كانت غير حامل وما فيه إجراء <bdi>urological</bdi> قادم، الجواب يصير عدم العلاج.",
        "لو كانت بعد الولادة (<bdi>postpartum</bdi>)، لا حاجة للعلاج أيضًا.",
    ],
    "rule": "حامل + <bdi>asymptomatic</bdi> + <bdi>positive culture</bdi> = <bdi>antibiotics</bdi>؛ نتيجة الشريط مجرد مُشتِّت.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0763B": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "نفس موضوع <bdi>asymptomatic bacteriuria</bdi> بس بعد الولادة، وهنا الحمل انتهى فيتغير القرار تمامًا.",
    "clues": [
        ("Postpartum", "خلاص المريضة ما هي حامل، فالاستطباب للعلاج يسقط"),
        ("asymptomatic bacteriuria after delivery", "بدون أعراض عند غير حامل = لا علاج"),
    ],
    "why_correct": [
        "بعد الولادة المريضة <bdi>no longer pregnant</bdi>، وهي <bdi>asymptomatic</bdi>.",
        "<bdi>asymptomatic bacteriuria</bdi> عند غير الحامل وبدون استطباب خاص (زرع كلية، إجراء <bdi>urological</bdi>) لا تحتاج علاج.",
        "إذن الإجراء المناسب هو عدم العلاج (<bdi>no treatment</bdi>).",
    ],
    "when_changes": [
        "لو كانت لسا حامل، الجواب يرجع لـ<bdi>antibiotics</bdi> وجوبًا.",
        "لو ظهرت أعراض مثل حمى وألم بالخاصرة، الجواب يصير علاج <bdi>pyelonephritis</bdi>.",
    ],
    "rule": "نفس نتيجة الزرع تُعالج أثناء الحمل وتُترك بدون علاج بعد الولادة؛ حالة الحمل هي اللي تقلب الجواب.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0772": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طول عنق الرحم <bdi>27 mm</bdi> فوق حد الخطورة <bdi>25 mm</bdi>، فما فيه داعي لأي تدخل.",
    "clues": [
        ("24 weeks", "ضمن فترة فحص طول عنق الرحم (16-24 أسبوع)"),
        ("cervical length of 27 mm", "فوق حد <bdi>25 mm</bdi>، يعني غير قصير"),
    ],
    "why_correct": [
        "الرقم الحاسم هو طول عنق الرحم: <bdi>27 mm</bdi> أعلى من حد <bdi>25 mm</bdi>، يعني العنق ليس قصيرًا.",
        "بدون تاريخ خسارة بالثلث الثاني أو ولادة مبكرة سابقة، طول عنق أكثر من <bdi>25 mm</bdi> يعني متابعة روتينية فقط.",
        "لا تقلصات ولا نزيف ولا تغيّر بالأغشية يستدعي تدخل الآن.",
    ],
    "when_changes": [
        "لو طول العنق كان أقل من <bdi>25 mm</bdi> بدون تاريخ خسارة سابقة، الجواب يصير <bdi>vaginal progesterone</bdi>.",
        "لو عندها تاريخ خسارة بالثلث الثاني، الجواب يصير <bdi>cervical cerclage</bdi>.",
    ],
    "rule": "الرقم السحري هو <bdi>25 mm</bdi>: أعلى منه = متابعة روتينية، أقل منه بدون تاريخ = <bdi>progesterone</bdi>، مع تاريخ خسارة = <bdi>cerclage</bdi>.",
    "comparison": None,
    "labs": [["Cervical length (TVUS)", "27 mm", ">25 mm = reassuring"]],
    "guideline_note": None,
},
"AS-0783": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "دورات غير منتظمة وقليلة التكرار مع نزيف شديد ومديد عند مريضة بدينة سكرية، هذا نموذج <bdi>chronic anovulation (AUB-O)</bdi>.",
    "clues": [
        ("morbidly obese and diabetic", "<bdi>insulin resistance</bdi>، عامل خطورة لـ<bdi>chronic anovulation</bdi>"),
        ("periods are irregular, occurring every 3-4 months", "نموذج <bdi>oligomenorrhea</bdi> الناتج عن <bdi>anovulation</bdi>"),
        ("Pregnancy test is negative", "يستبعد أي سبب متعلق بالحمل"),
    ],
    "why_correct": [
        "\"<bdi>morbidly obese and diabetic</bdi>\" مع دورات \"<bdi>every 3-4 months</bdi>\" توصف <bdi>chronic anovulation</bdi> بنمط <bdi>PCOS</bdi>.",
        "بدون <bdi>ovulation</bdi> ما فيه <bdi>progesterone</bdi>، فيتراكم بطانة الرحم تحت تأثير <bdi>unopposed estrogen</bdi> وينسلخ بشكل شديد ومديد (أسبوعين وجلطات).",
        "هذا هو <bdi>AUB-O</bdi> ضمن تصنيف <bdi>PALM-COEIN</bdi>.",
    ],
    "when_changes": [
        "لو كانت الدورات منتظمة وشديدة فقط، الجواب يصير <bdi>fibroids</bdi> أو <bdi>bleeding disorder</bdi>.",
        "لو كان فحص الحمل إيجابي، الجواب يصير سبب مرتبط بالحمل مثل <bdi>incomplete abortion</bdi>.",
    ],
    "rule": "دورات غير منتظمة وقليلة + نزيف شديد مديد = <bdi>anovulatory AUB</bdi>؛ دورات منتظمة وشديدة = فكر بـ<bdi>fibroids</bdi> أو اضطراب تخثر.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0792": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "السؤال يبي أعلى فعالية بين وسائل منع حمل <bdi>reversible</bdi> مذكورة بالخيارات، والمقارنة بين الهرمونية والحاجزية.",
    "clues": [
        ("effective and reversible", "يبحث عن وسيلة هرمونية فعّالة لكن قابلة للعكس"),
        ("most effective", "المعيار المطلوب هو الفعالية الأعلى بين الخيارات المعطاة"),
    ],
    "why_correct": [
        "<bdi>vaginal ring containing hormones</bdi> يعمل مثل <bdi>combined pill</bdi> بتثبيط <bdi>ovulation</bdi>، بمعدل فشل <bdi>typical-use</bdi> حوالي <bdi>7 per 100 woman-years</bdi>.",
        "كل الخيارات الأخرى وسائل حاجزية أو كيميائية تعتمد على الاستخدام الصحيح كل مرة، فمعدل فشلها أعلى.",
        "إذن <bdi>vaginal ring</bdi> هو الأعلى فعالية بين الخيارات المعطاة.",
    ],
    "when_changes": [
        "لو ظهر <bdi>IUD</bdi> أو <bdi>implant (LARC)</bdi> ضمن الخيارات، هو اللي يتفوق على <bdi>ring</bdi>.",
        "لو السؤال عن منع انتقال <bdi>STI</bdi> لا منع الحمل فقط، الجواب يصير <bdi>condom</bdi>.",
    ],
    "rule": "ترتيب فعالية الاستخدام المعتاد: <bdi>LARC</bdi> &gt; <bdi>vaginal ring</bdi> &gt; <bdi>male condom</bdi> &gt; <bdi>female condom/spermicide</bdi>.",
    "comparison": {
        "headers": ["الوسيلة", "معدل الفشل (Typical use)"],
        "rows": [
            ["Vaginal ring", "~7 /100 woman-years"],
            ["Male condom", "~13 /100 woman-years"],
            ["Female condom", "~21 /100 woman-years"],
            ["Spermicide", "~21 /100 woman-years"],
        ],
    },
    "labs": None,
    "guideline_note": None,
},
"AS-0797": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "<bdi>primary amenorrhea</bdi> مع ألم دوري وكتلة أمام المستقيم تشخّص <bdi>imperforate hymen</bdi>، والسؤال عن أهم تعليمة بعد العملية.",
    "clues": [
        ("1ry amenorrhea and abd pain", "يوجّه لانسداد بمخرج التناسل مع احتباس دم الطمث"),
        ("mature genitalia", "النمو الجنسي الثانوي طبيعي، يستبعد مشاكل هرمونية"),
        ("mass anterior to the rectum", "<bdi>hematocolpos</bdi> خلف غشاء البكارة غير المثقوب"),
        ("cruciate incision", "<bdi>hymenotomy</bdi>، العلاج الجراحي لـ<bdi>imperforate hymen</bdi>"),
    ],
    "why_correct": [
        "<bdi>primary amenorrhea</bdi> مع ألم بطن دوري ونمو جنسي ثانوي طبيعي وكتلة أمام المستقيم هو <bdi>hematocolpos</bdi> من <bdi>imperforate hymen</bdi>، وعلاجه شق صليبي (<bdi>cruciate incision</bdi>).",
        "أهم تعليمة بعد العملية هي <bdi>topical estrogen cream</bdi>: الإستروجين يحسّن التئام حواف الغشاء المقطوعة ويمنع التصاقها وانغلاقها من جديد.",
        "بدونها ممكن تلتصق الحواف وترجع تنسد الفتحة اللي فتحوها.",
    ],
    "when_changes": [
        "لو كانت القضية <bdi>transverse vaginal septum</bdi> بعد استئصاله، التأكيد ينتقل لاستخدام <bdi>vaginal dilators</bdi> لمنع التضيق.",
        "لو ظهرت علامات <bdi>infection</bdi> واضحة بعد العملية، يُضاف <bdi>antibiotics</bdi> كإجراء إضافي.",
    ],
    "rule": "<bdi>imperforate hymen</bdi>: شق صليبي ثم <bdi>topical estrogen</bdi> لمنع إعادة التصاق الحواف.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0807": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "متابعة <bdi>hCG</bdi> بعد <bdi>single-dose methotrexate</bdi> لحمل خارج الرحم، والمقارنة الصحيحة بين يوم 4 ويوم 7 لا يوم 1.",
    "clues": [
        ("methotrexate for an ectopic pregnancy", "علاج طبي لـ<bdi>ectopic pregnancy</bdi> يحتاج متابعة <bdi>hCG</bdi>"),
        ("Day 4: BhCG was1200", "القياس المرجعي للمقارنة"),
        ("Day 7: BhCG was 2100", "ارتفاع واضح مقارنة بيوم 4"),
    ],
    "why_correct": [
        "بعد <bdi>single-dose methotrexate</bdi> يُقيَّم الاستجابة بمقارنة <bdi>day 4 مع day 7</bdi>، لا يوم 1.",
        "هنا <bdi>hCG</bdi> ارتفع من <bdi>1200 على يوم 4</bdi> إلى <bdi>2100 على يوم 7</bdi>، يعني ارتفاع واضح وهذا فشل للعلاج الطبي.",
        "<bdi>hCG</bdi> المرتفع بعد <bdi>methotrexate</bdi> يُدار جراحيًا (<bdi>salpingectomy</bdi> أو <bdi>salpingostomy</bdi>).",
    ],
    "when_changes": [
        "لو كان الانخفاض من يوم 4 إلى يوم 7 أكثر من 15%، الجواب يصير متابعة <bdi>weekly hCG</bdi>.",
        "لو كان هناك ثبات أو انخفاض أقل من 15%، الجواب يصير <bdi>second dose of methotrexate</bdi>.",
    ],
    "rule": "قيّم استجابة <bdi>methotrexate</bdi> بمقارنة يوم 4 بيوم 7 فقط: ارتفاع = جراحة، ثبات/انخفاض &lt;15% = جرعة ثانية، انخفاض &gt;15% = متابعة.",
    "comparison": None,
    "labs": [["Beta-hCG Day 4", "1200 mIU/mL", "—"], ["Beta-hCG Day 7", "2100 mIU/mL", "—"]],
    "guideline_note": None,
},
"AS-0808": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "نفس مبدأ متابعة <bdi>hCG</bdi> بعد <bdi>methotrexate</bdi>، بس هنا الارتفاع من يوم 4 إلى يوم 7 أوضح وأكبر، فيعزز قرار الجراحة الفورية.",
    "clues": [
        ("methotrexate treatment for an ectopic pregnancy", "علاج طبي يحتاج متابعة دقيقة بـ<bdi>hCG</bdi>"),
        ("Day 4: 1200 mIU/mL Day 7: 2100 mIU/mL", "ارتفاع كبير بين يوم 4 ويوم 7"),
    ],
    "why_correct": [
        "<bdi>hCG</bdi> ارتفع من <bdi>1200 على يوم 4</bdi> إلى <bdi>2100 على يوم 7</bdi>، وهذا ارتفاع واضح لا انخفاض.",
        "بحسب خوارزمية هذا المصدر، ارتفاع <bdi>hCG</bdi> بعد <bdi>methotrexate</bdi> يعني فشل العلاج الطبي، والخطوة التالية <bdi>surgical management</bdi> (<bdi>laparoscopy</bdi> مع <bdi>salpingectomy/salpingostomy</bdi>).",
        "الارتفاع الحاد أيضًا يرفع القلق من <bdi>ongoing ectopic</bdi> معرّض لخطر <bdi>rupture</bdi>.",
    ],
    "when_changes": [
        "لو كان الانخفاض من يوم 4 إلى يوم 7 أكثر من 15%، الجواب يصير <bdi>repeat beta-hCG weekly</bdi>.",
        "لو كان ثبات أو انخفاض أقل من 15%، الجواب يصير <bdi>second dose of methotrexate</bdi>.",
    ],
    "rule": "ثبات أو انخفاض طفيف = جرعة ثانية؛ ارتفاع واضح = جراحة. القرار دايمًا بمقارنة يوم 4 بيوم 7.",
    "comparison": None,
    "labs": [["Beta-hCG Day 1", "1000 mIU/mL", "—"], ["Beta-hCG Day 4", "1200 mIU/mL", "—"], ["Beta-hCG Day 7", "2100 mIU/mL", "—"]],
    "guideline_note": None,
},
"AS-0826": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "انقطاع الدورة 9 أشهر مع <bdi>FSH</bdi> و<bdi>LH</bdi> بمستوى ما بعد سن الأمل يشير لـ<bdi>premature ovarian insufficiency</bdi>، والسؤال عن المضاعفة طويلة الأمد.",
    "clues": [
        ("9-month history of amenorrhea", "<bdi>amenorrhea</bdi> لفترة طويلة قبل عمر 40"),
        ("FSH 60", "مستوى <bdi>postmenopausal</bdi>، يدل على فشل مبيضي"),
        ("LH 60", "مستوى <bdi>postmenopausal</bdi>، يؤكد قصور المبيض"),
    ],
    "why_correct": [
        "امرأة بعمر <bdi>32</bdi> سنة مع <bdi>9 months amenorrhea</bdi>، و<bdi>hCG</bdi> سلبي، و<bdi>TSH</bdi> و<bdi>prolactin</bdi> طبيعيين، و<bdi>FSH</bdi> و<bdi>LH</bdi> بمستوى <bdi>postmenopausal</bdi> تشخّص <bdi>premature ovarian insufficiency (POI)</bdi>.",
        "المبيض ما عاد يصنع <bdi>estrogen</bdi>، وأهم مضاعفة طويلة الأمد لحالة <bdi>hypoestrogenism</bdi> هذي هي فقدان كثافة العظم.",
        "فهي معرضة بشكل ملحوظ لـ<bdi>osteoporosis</bdi> (وأيضًا <bdi>cardiovascular disease</bdi>)، ولذا تُعطى <bdi>HRT</bdi> لحد عمر سن الأمل الطبيعي.",
    ],
    "when_changes": [
        "لو كانت الصورة <bdi>PCOS</bdi> بدل <bdi>POI</bdi> (نسبة <bdi>LH:FSH</bdi> مرتفعة مع زيادة أندروجين)، الخطورة تنقلب لـ<bdi>endometrial cancer</bdi> بسبب <bdi>unopposed estrogen</bdi>.",
        "لو كان <bdi>prolactin</bdi> مرتفع، السبب يصير <bdi>hyperprolactinemia</bdi> لا <bdi>POI</bdi>.",
    ],
    "rule": "<bdi>estrogen</bdi> منخفض = خطر على العظم (<bdi>osteoporosis</bdi>)؛ <bdi>unopposed estrogen</bdi> (مثل <bdi>PCOS</bdi>) = خطر على بطانة الرحم.",
    "comparison": None,
    "labs": [
        ["TSH", "3", "0.4-5.0"],
        ["FSH", "60", "5-20 IU/L follicular; 50-100 postmenopausal"],
        ["Testosterone", "1", "0.7-2.8 nmol/L (female)"],
        ["LH", "60", "5-22 U/L follicular; >30 postmenopausal"],
        ["Prolactin", "500", "<870 pmol/L (female)"],
        ["hCG", "4", "<5 mIU/mL"],
    ],
    "guideline_note": None,
},
"AS-0828": {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "السيناريو (مع ركاكة بالصياغة) يصف تمزق أغشية مع سائل خارج وفحص <bdi>sterile speculum test</bdi> إيجابي، والسؤال يبي إجراء وقائي (<bdi>health promotion</bdi>) مو علاج استعجالي.",
    "clues": [
        ("POROM", "يرمز لـ<bdi>PROM / rupture of membranes</bdi>"),
        ("HEALTH PROMOTION AND PREVENT ILLNESS", "يبحث عن إجراء وقائي، مو إنهاء الحمل فورًا"),
    ],
    "why_correct": [
        "تمزق الأغشية المؤكد بـ<bdi>sterile speculum test</bdi> إيجابي يفرض خطة علاج حسب عمر الحمل.",
        "<bdi>steroids</bdi> تنضج رئة الجنين و<bdi>prophylactic antibiotics</bdi> تمنع العدوى الصاعدة (<bdi>chorioamnionitis</bdi>)، وهذا هو الإجراء الوقائي الحقيقي (<bdi>health promotion / illness prevention</bdi>).",
        "هذا السؤال <bdi>self-judged</bdi> لأن المصدر نفسه لم يحدد جواب مؤكد.",
    ],
    "when_changes": [
        "لو كان الحمل <bdi>term (≥37 weeks)</bdi>، الجواب يصير <bdi>induction of labor</bdi> خلال 24 ساعة.",
        "لو كان عمر الحمل أقل من 32 أسبوع، يُضاف <bdi>MgSO4</bdi> لحماية الجهاز العصبي للجنين.",
    ],
    "rule": "<bdi>PPROM</bdi> (مبكر) = <bdi>steroids + latency antibiotics</bdi>؛ <bdi>term PROM</bdi> = <bdi>induction of labor</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر نفسه لم يحدد إجابة مؤكدة لهذا السؤال؛ الجواب هنا باجتهاد سريري بناءً على <bdi>key_concept</bdi> المتوفر.",
},
"AS-0833": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "حامل مدخنة بالثلث الأول متحمسة تترك الدخان، والسؤال عن أفضل خيار إقلاع آمن بالحمل.",
    "clues": [
        ("Pregnant smoking", "التدخين بالحمل يحتاج خطة إقلاع آمنة للجنين"),
    ],
    "why_correct": [
        "بالحمل الأساس هو <bdi>behavioural counselling</bdi>، وإذا احتاجت علاج دوائي فـ<bdi>nicotine replacement therapy (NRT)</bdi> هو الخيار الأول الآمن نسبيًا.",
        "<bdi>NRT</bdi> يعطي <bdi>nicotine</bdi> بدون <bdi>carbon monoxide</bdi> و<bdi>tar</bdi> اللي بالدخان.",
        "<bdi>nicotine gum</bdi> (شكل قصير المفعول) مع <bdi>prenatal counselling</bdi> هو الخيار الأنسب والأكثر أمانًا هنا.",
    ],
    "when_changes": [
        "لو كانت غير حامل، <bdi>varenicline</bdi> يصير الدواء الأكثر فعالية لحاله.",
        "لو عندها <bdi>epilepsy</bdi> أو اضطراب أكل، يُستبعد <bdi>bupropion</bdi> بشكل أوضح.",
    ],
    "rule": "بالحمل: استشارة سلوكية أولًا، وإذا لزم دواء فـ<bdi>NRT</bdi> فقط هو الخط الأول؛ <bdi>varenicline</bdi> و<bdi>bupropion</bdi> يُتجنّبان.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0837": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "تخطيط قلب جنين (<bdi>CTG</bdi>) طبيعي (<bdi>Category 1</bdi>) مع <bdi>early decelerations</bdi> فقط، والمريضة بالطور الكامن الطبيعي، فالإجراء هو المتابعة الروتينية.",
    "clues": [
        ("latent phase of labor", "طور كامن طبيعي، يُدار بالمراقبة"),
        ("baseline of 140", "ضمن المعدل الطبيعي (110-160)"),
        ("moderate variability", "علامة طمأنة على حالة الجنين"),
        ("recurrent early decelerations", "تعكس ضغط الرأس، مو نقص أكسجين"),
    ],
    "why_correct": [
        "<bdi>baseline 140 bpm</bdi> (طبيعي 110-160)، مع <bdi>moderate variability</bdi> وفقط <bdi>early decelerations</bdi> يجعل تخطيط القلب <bdi>Category 1 (reassuring)</bdi>.",
        "<bdi>early decelerations</bdi> تتزامن مع التقلصات وتعكس ضغط رأس الجنين، لا نقص أكسجين.",
        "هي <bdi>primigravida</bdi> بالطور الكامن الطبيعي (<bdi>2 cm</bdi>)، والذي يُدار بالملاحظة، فالإجراء الصحيح متابعة روتينية.",
    ],
    "when_changes": [
        "لو كانت <bdi>late decelerations</bdi> بدل <bdi>early</bdi>، يصير التخطيط غير مطمئن ويحتاج <bdi>intrauterine resuscitation</bdi>.",
        "لو دخلت <bdi>Category 3</bdi> (تخطيط غير طبيعي شديد)، الإجراء يصير إنعاش فوري وتسريع الولادة.",
    ],
    "rule": "<bdi>early decelerations</bdi> = ضغط رأس حميد = <bdi>Category 1</bdi>؛ غيّرها لـ<bdi>late</bdi> ويصير الجواب إنعاش داخل الرحم.",
    "comparison": None,
    "labs": [["FHR baseline", "140 bpm", "110-160 bpm"]],
    "guideline_note": None,
},
"AS-0855": {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "<bdi>CTG type 2 (late) deceleration</bdi> بالطلق مع محطة +2، بدون تأكيد اتساع كامل، فالخطوة المناسبة هي تقييم إضافي قبل أي تدخل نهائي.",
    "clues": [
        ("36 wk ga", "حمل قريب من الاكتمال، يُراعى بقرار نوع الولادة"),
        ("CTG type 2 deceleration", "<bdi>late deceleration</bdi>، علامة غير مطمئنة تحتاج تقييم"),
        ("+2 station", "رأس منخفض نسبيًا، لكن لا يؤكد اتساع كامل لوحده"),
    ],
    "why_correct": [
        "الولادة بالأدوات (<bdi>forceps/ventouse</bdi>) تحتاج <bdi>full dilatation</bdi> + رأس عند أو تحت مستوى الشوكتين؛ محطة <bdi>+2</bdi> لحالها لا تؤكد ذلك.",
        "مع تخطيط <bdi>type 2 (late) deceleration</bdi> غير مؤكد كونه <bdi>Category 3</bdi>، والخطوة المنطقية بالطور الأول هي <bdi>fetal scalp sampling</bdi> لتقييم حالة الجنين بدقة قبل اللجوء لتدخل جراحي.",
        "هذا سؤال <bdi>self-judged</bdi> لعدم وجود جواب مؤكد من المصدر.",
    ],
    "when_changes": [
        "لو كانت المريضة بالطور الثاني (<bdi>fully dilated</bdi>) مع رأس منخفض، الجواب يصير ولادة بالأدوات (<bdi>ventouse/forceps</bdi>).",
        "لو كان التخطيط <bdi>Category 3</bdi> واضح أو فشل الإنعاش داخل الرحم، الجواب يصير <bdi>cesarean section</bdi> فورًا.",
    ],
    "rule": "الولادة بالأدوات تحتاج <bdi>full dilatation</bdi> + محطة منخفضة معًا؛ محطة <bdi>+2</bdi> وحدها بالطور الأول يعني <bdi>scalp sampling</bdi> أو <bdi>cesarean</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر لم يحدد جوابًا مؤكدًا؛ الاختيار هنا اجتهاد سريري بناءً على مبدأ احتياج الاتساع الكامل مع المحطة المنخفضة معًا.",
},
"AS-0857": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "توقيت فحص زراعة البول الروتيني للحامل لكشف <bdi>asymptomatic bacteriuria</bdi>.",
    "clues": [
        ("urine inf for pregnant women", "يسأل عن توقيت الفحص الروتيني لعدوى بولية صامتة"),
    ],
    "why_correct": [
        "الحوامل يُفحصن بزراعة بول لـ<bdi>asymptomatic bacteriuria</bdi> في زيارة الحمل الأولى (<bdi>booking visit</bdi>)، وهذا يقع تقريبًا حول أسبوع <bdi>12</bdi>.",
        "الكشف المبكر مهم لأن <bdi>bacteriuria</bdi> غير المعالج يتطور لـ<bdi>pyelonephritis</bdi> ويرتبط بـ<bdi>preterm labor</bdi> ووزن ولادة منخفض.",
        "فالجواب الصحيح أسبوع <bdi>12</bdi>.",
    ],
    "when_changes": [
        "أسبوع <bdi>20</bdi> يخص فحص التشوهات التفصيلي (<bdi>anomaly scan</bdi>)، لا فحص البول.",
        "أسبوع <bdi>24-28</bdi> يخص فحص السكري الحملي (<bdi>OGTT</bdi>).",
    ],
    "rule": "زراعة البول للحامل تُفحص بزيارة الحمل الأولى، حوالي أسبوع <bdi>12</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0871": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "امرأة على <bdi>warfarin</bdi> تبي منع حمل، والمشكلة تمنع أي وسيلة تحتوي <bdi>estrogen</bdi> بسبب خطر التخثر.",
    "clues": [
        ("on warfarin", "سبب كامن للتخثر يستوجب تجنب <bdi>estrogen</bdi>"),
        ("contraception", "تحتاج وسيلة فعالة وآمنة مع حالتها"),
    ],
    "why_correct": [
        "امرأة \"<bdi>on warfarin</bdi>\" غالبًا عندها استطباب تخثري كامن (مثل صمام قلب أو <bdi>previous VTE</bdi>)، فأي وسيلة تحتوي <bdi>estrogen</bdi> تُتجنب لأنه يرفع خطر التخثر.",
        "وسيلة <bdi>progestogen-only</bdi> تعطي منع حمل فعّال وقابل للعكس مع تأثير ضعيف على التخثر.",
        "منع الحمل الفعّال مهم أيضًا لأن <bdi>warfarin</bdi> مُشوِّه للجنين (<bdi>teratogenic</bdi>).",
    ],
    "when_changes": [
        "لو كانت المريضة صحية بدون خطر تخثري، <bdi>OCP</bdi> يصير خيار مناسب.",
        "لو أنهت تكوين عائلتها وتبي حل نهائي، <bdi>tubal ligation</bdi> يصير مناسب أكثر.",
    ],
    "rule": "مريضة على <bdi>warfarin</bdi> أو معرّضة للتخثر = تجنب <bdi>estrogen</bdi>، واختر وسيلة <bdi>progestogen-only</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0872": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "ثبات <bdi>hCG</bdi> بين يوم 4 ويوم 7 بعد <bdi>single-dose methotrexate</bdi> عند مريضة مستقرة بدون أعراض يعني استجابة غير كافية، فالخطوة التالية جرعة ثانية.",
    "clues": [
        ("b-hcg on day 4 and 7 is plateauing", "استجابة غير كافية (ثبات) تستدعي جرعة ثانية"),
        ("asymptomatic", "لا توجد علامات <bdi>rupture</bdi> أو عدم استقرار تستدعي جراحة"),
    ],
    "why_correct": [
        "بعد <bdi>single-dose methotrexate</bdi> يُقارَن <bdi>hCG</bdi> بين <bdi>day 4 و day 7</bdi>.",
        "<bdi>plateau</bdi> (أو انخفاض أقل من 15%) عند مريضة <bdi>asymptomatic</bdi> ومستقرة يعني استجابة غير كافية، فالخطوة التالية <bdi>second dose of methotrexate</bdi> لا جراحة.",
        "الجراحة محفوظة لحالة <bdi>rising hCG</bdi> أو عدم استقرار أو علامات تمزق.",
    ],
    "when_changes": [
        "لو كان <bdi>hCG</bdi> يرتفع بوضوح بين يوم 4 و7، الجواب يصير <bdi>surgery</bdi>.",
        "لو انخفض أكثر من 15%، الجواب يصير <bdi>weekly hCG follow-up</bdi> فقط.",
    ],
    "rule": "ثبات <bdi>hCG</bdi> = جرعة ثانية من <bdi>methotrexate</bdi>؛ ارتفاع أو عدم استقرار = جراحة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0873": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "نزيف بعد الولادة غير متحكم فيه تطور إلى <bdi>DIC</bdi>، والسؤال عن السبب الكامن الأشيع لـ<bdi>DIC</bdi> بالحمل.",
    "clues": [
        ("postpartum", "توقيت النزيف بعد الولادة"),
        ("DIC", "يحدد السبب الكامن المسؤول عن استهلاك عوامل التخثر"),
    ],
    "why_correct": [
        "<bdi>placental abruption</bdi> هو أشيع سبب ولادي لـ<bdi>DIC</bdi>: الخثرة خلف المشيمة تُفرز <bdi>tissue factor</bdi> بالدورة الدموية للأم وتستهلك عوامل التخثر.",
        "اعتلال التخثر الناتج يجعل النزيف بعد الولادة \"غير متحكم فيه\"، فالمرأة المصابة بنزيف بعد الولادة مع <bdi>DIC</bdi> الأرجح أنها عندها <bdi>abruption</bdi>.",
        "هذا يختلف عن أسباب <bdi>PPH</bdi> الأخرى اللي نادرًا تسبب <bdi>DIC</bdi> مباشرة.",
    ],
    "when_changes": [
        "لو كان النزيف مؤلم مصحوب بخثرة خلف المشيمة فقط بدون <bdi>DIC</bdi>، يبقى التشخيص <bdi>abruption</bdi> لكن بدون مضاعفة.",
        "لو كان النزيف غير مؤلم قبل الولادة، التشخيص الأقرب <bdi>placenta previa</bdi>.",
    ],
    "rule": "<bdi>PPH</bdi> + <bdi>DIC</bdi> = فكّر <bdi>abruption</bdi>، مو <bdi>atony</bdi> ولا <bdi>previa</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0905": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "خسارة حمل واحدة بالثلث الأول عند امرأة صحية هي حدث عرضي شائع، والجواب هو التطمين لا التحقيق.",
    "clues": [
        ("a first-trimester spontaneous abortion", "خسارة واحدة فقط، مو متكررة"),
    ],
    "why_correct": [
        "هي صحية وعندها خسارة واحدة فقط بالثلث الأول.",
        "الإسقاط العرضي بالثلث الأول شائع (أغلبه أخطاء كروموسومية عشوائية)، وخسارة واحدة بالكاد تغيّر التوقعات.",
        "فالخطوة الصحيحة هي تطمينها بالخطر الأساسي حوالي <bdi>10-15%</bdi> لمن هي تحت عمر 35.",
    ],
    "when_changes": [
        "لو كانت هذي خسارتها الثانية أو الثالثة، الجواب يصير بدء تحقيق <bdi>recurrent pregnancy loss</bdi> (كاريوتايب أولًا).",
        "لو كان عمرها أكبر من 35، نسبة الخطر الأساسية تكون أعلى من <bdi>10-15%</bdi>.",
    ],
    "rule": "خسارة واحدة = تطمين؛ خسارة متكررة = تحقيق (كاريوتايب أولًا).",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0908": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "إفرازات \"حليبية رقيقة\" برائحة \"سمكية\" هي العلامة المميزة لـ<bdi>bacterial vaginosis (BV)</bdi>، و<bdi>pH</bdi> المذكور حدّي ولا يغيّر التشخيص.",
    "clues": [
        ("thin milky appearance", "صفة الإفرازات المميزة لـ<bdi>BV</bdi>"),
        ("fish-like odor", "علامة كلاسيكية لـ<bdi>BV</bdi> (<bdi>whiff test</bdi> إيجابي)"),
        ("vaginal pH of 4.5", "حدّي، لكن صفة الإفرازات هي الحاسمة"),
    ],
    "why_correct": [
        "إفرازات \"<bdi>thin milky</bdi>\" برائحة \"<bdi>fish-like</bdi>\" هي التوقيع المميز لـ<bdi>bacterial vaginosis</bdi> (<bdi>Gardnerella</bdi> مع فقدان <bdi>lactobacilli</bdi>).",
        "<bdi>BV</bdi> غالبًا يرفع <bdi>pH</bdi> فوق <bdi>4.5</bdi>؛ الرقم المذكور هنا حدّي بالضبط عند الحد الأعلى، فصفة الإفرازات هي اللي تقرر الجواب لا الرقم.",
        "إذن التشخيص الأقرب <bdi>bacterial vaginosis</bdi>.",
    ],
    "when_changes": [
        "لو كانت الإفرازات رغوية صفراء-خضراء مع عنق رحم \"<bdi>strawberry</bdi>\"، الجواب يصير <bdi>Trichomonas vaginalis</bdi>.",
        "لو كانت سميكة بيضاء شبيهة بالجبن مع حكة وبدون رائحة، الجواب يصير <bdi>Candida</bdi>.",
    ],
    "rule": "رائحة سمكية + إفرازات حليبية رقيقة = <bdi>BV</bdi> حتى لو <bdi>pH</bdi> المذكور حدّي.",
    "comparison": None,
    "labs": [["Vaginal pH", "4.5", "normal <4.5; BV usually >4.5"]],
    "guideline_note": None,
},
"AS-0909": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "نفس صفة الإفرازات المميزة لـ<bdi>BV</bdi>، بس هنا <bdi>pH</bdi> مرتفع بوضوح (<bdi>7.5</bdi>) وهذا يدعم التشخيص بقوة أكبر.",
    "clues": [
        ("thin milky appearance", "صفة الإفرازات المميزة لـ<bdi>BV</bdi>"),
        ("fish-like odor", "علامة كلاسيكية لـ<bdi>BV</bdi>"),
        ("vaginal pH of 7.5", "<bdi>pH</bdi> مرتفع بوضوح فوق <bdi>4.5</bdi>، يدعم <bdi>BV</bdi>"),
    ],
    "why_correct": [
        "إفرازات \"<bdi>thin milky</bdi>\" مع رائحة \"<bdi>fish-like</bdi>\" توقيع <bdi>bacterial vaginosis</bdi> المميز.",
        "هنا <bdi>pH 7.5</bdi> مرتفع بوضوح فوق الحد الطبيعي <bdi>4.5</bdi>، وهذا يتوافق تمامًا مع فقدان <bdi>lactobacilli</bdi> اللي يحدث بـ<bdi>BV</bdi>.",
        "فالتشخيص الأقرب <bdi>bacterial vaginosis</bdi> بثقة أعلى من السؤال السابق.",
    ],
    "when_changes": [
        "لو كانت الإفرازات رغوية صفراء-خضراء مع طفيليات متحركة بالفحص المباشر، الجواب يصير <bdi>Trichomonas</bdi>.",
        "لو كان <bdi>pH</bdi> طبيعي مع إفرازات سميكة بيضاء، الجواب يصير <bdi>Candida</bdi>.",
    ],
    "rule": "رائحة سمكية + إفرازات حليبية رقيقة + <bdi>pH</bdi> مرتفع = <bdi>BV</bdi> بثقة عالية.",
    "comparison": None,
    "labs": [["Vaginal pH", "7.5", "normal <4.5; BV usually >4.5"]],
    "guideline_note": None,
},
"AS-0917": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "امرأة كثيرة الولادة بسادس طفل كبير الحجم، والسؤال عن الدواء المحدد للوقاية من <bdi>PPH</bdi>.",
    "clues": [
        ("6 macrosomic babies", "<bdi>grand multiparity</bdi> + <bdi>macrosomia</bdi>، عاملا خطورة لـ<bdi>atony</bdi>"),
        ("prevent PPH", "يبحث عن إجراء وقائي محدد"),
    ],
    "why_correct": [
        "امرأة كثيرة الولادة تلد \"سادس\" طفل \"<bdi>macrosomic</bdi>\" عندها عاملا خطورة كبار لـ<bdi>uterine atony</bdi>، أشيع سبب لـ<bdi>PPH</bdi>.",
        "أهم إجراء وقائي هو إعطاء <bdi>uterotonic</bdi> وقائي مباشرة بعد الولادة، و<bdi>oxytocin</bdi> هو الدواء الأول (<bdi>first-line</bdi>).",
        "فالجواب المحدد هنا هو الدواء نفسه: <bdi>oxytocin</bdi>.",
    ],
    "when_changes": [
        "لو سأل السؤال عن الاستراتيجية الكاملة لا الدواء، الجواب يصير <bdi>active management of third stage of labor</bdi>.",
        "لو <bdi>oxytocin</bdi> غير متوفر، البديل <bdi>misoprostol</bdi>.",
    ],
    "rule": "إذا سألوا عن الدواء: <bdi>oxytocin</bdi>؛ إذا سألوا عن الاستراتيجية: <bdi>active management of third stage</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0917B": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "<bdi>PPH</bdi> بعد ولادة طبيعية لجنين كبير عند متعددة الولادات، والسؤال عن أفضل علاج دوائي أولي.",
    "clues": [
        ("multipara", "عامل خطورة لـ<bdi>atony</bdi>"),
        ("postpartum hemorrhage", "<bdi>PPH</bdi> فعلي يحتاج علاج"),
        ("macrosomic baby", "عامل خطورة إضافي لـ<bdi>atony</bdi> بسبب <bdi>overdistension</bdi>"),
    ],
    "why_correct": [
        "\"<bdi>multipara</bdi>\" ولدت \"<bdi>macrosomic baby</bdi>\" ثم نزفت، فالتشخيص <bdi>PPH</bdi> بسبب <bdi>uterine atony</bdi> لحد ما يثبت العكس.",
        "بعد تدليك الرحم وطلب المساعدة، <bdi>oxytocin</bdi> هو <bdi>uterotonic</bdi> الخط الأول والمعيار الأساسي للعلاج.",
        "فهو أفضل إدارة بالخيارات المعطاة.",
    ],
    "when_changes": [
        "لو فشل <bdi>oxytocin</bdi> وما عندها <bdi>hypertension</bdi>، الخطوة التالية <bdi>ergonovine (methylergonovine)</bdi>.",
        "لو عندها <bdi>asthma</bdi>، يُتجنب <bdi>carboprost</bdi> ويُستخدم بديل آخر.",
    ],
    "rule": "سلّم علاج <bdi>atonic PPH</bdi>: أولًا <bdi>oxytocin</bdi>، ثانيًا <bdi>methylergonovine</bdi> (تجنبه مع <bdi>hypertension</bdi>)، ثالثًا <bdi>carboprost</bdi> (تجنبه مع <bdi>asthma</bdi>).",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-0918": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "سؤال مباشر عن دواء الوقاية الأول من <bdi>PPH</bdi>.",
    "clues": [
        ("PPH", "موضوع السؤال"),
        ("prevent", "يسأل عن الوقاية، مو العلاج بعد حدوث النزيف"),
    ],
    "why_correct": [
        "السؤال يسأل كيف نقي من <bdi>PPH</bdi>.",
        "أغلب <bdi>PPH</bdi> سببه <bdi>uterine atony</bdi>، وإعطاء <bdi>uterotonic</bdi> وقائي مباشرة بعد ولادة الجنين يقي منه.",
        "<bdi>oxytocin</bdi> هو الخط الأول للوقاية والعلاج معًا.",
    ],
    "when_changes": [
        "لو <bdi>oxytocin</bdi> غير متوفر، البديل المقبول للوقاية هو <bdi>misoprostol</bdi> (مع أعراض جانبية أكثر).",
        "لو السؤال عن علاج نزيف مستمر لا يستجيب، يدخل <bdi>carboprost</bdi> كخيار متأخر (مع تجنبه بـ<bdi>asthma</bdi>).",
    ],
    "rule": "الوقاية أو العلاج الأولي لـ<bdi>atonic PPH</bdi>: <bdi>oxytocin</bdi> بكل الحالتين.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
}

WHY_WRONG = {
"AS-0751": {
    "B": "<bdi>Placenta accreta</bdi> يعطي فشل انفصال المشيمة ونزيف أثناء محاولة إخراجها، وغالبًا مرتبط بـ<bdi>previous cesarean</bdi> مع <bdi>previa</bdi>، وهذا غير مذكور هنا.",
    "C": "<bdi>Cervical laceration</bdi> يتبع ولادة <bdi>instrumental</bdi> أو سريعة جدًا، ويحدث مع رحم <bdi>firm</bdi>؛ ما فيه شي يدل على هذا.",
    "D": "<bdi>Vaginal laceration</bdi> أيضًا يحتاج قرائن <bdi>trauma</bdi> (ولادة <bdi>instrumental</bdi>، جنين كبير، تمزق واضح)؛ ما فيه شي من هذا.",
},
"AS-0752": {
    "B": "<bdi>Coagulopathy</bdi> سبب غير شائع، ولا فيه قرينة (<bdi>abruption</bdi>، <bdi>preeclampsia</bdi>، <bdi>DIC</bdi>، تاريخ نزيف) تدعمه.",
    "C": "<bdi>Genital tract trauma</bdi> ثاني أشيع سبب، بس يحتاج قرائن مثل ولادة <bdi>instrumental</bdi> أو تمزق واضح أو رحم <bdi>firm</bdi>.",
    "D": "<bdi>Retained placental tissue</bdi> أقل شيوعًا وما ذكروا مشيمة ناقصة.",
},
"AS-0753": {
    "A": "<bdi>Coagulopathy</bdi> سبب غير شائع وما فيه قرينة تدل على مشكلة تخثر.",
    "C": "<bdi>Uterine inversion</bdi> نادر، يحدث عند خروج المشيمة (غالبًا مع شد الحبل مع مشيمة بقمة الرحم)، ويعطي <bdi>shock</bdi> وكتلة بالمهبل وغياب قمة الرحم؛ ما ذُكر شي من هذا.",
    "D": "<bdi>Genital tract trauma</bdi> ثاني أشيع سبب، بس ما فيه ذكر ولادة <bdi>instrumental</bdi> أو تمزق أو رحم <bdi>firm</bdi>.",
},
"AS-0754": {
    "B": "<bdi>Cervical injury</bdi> يُشتبه فيه عند استمرار النزيف مع رحم <bdi>firm</bdi> منقبض كويس، أو بعد ولادة <bdi>instrumental</bdi> أو سريعة؛ غير مذكور هنا.",
    "C": "<bdi>Coagulation defects</bdi> تُشتبه مع تاريخ اضطراب تخثر معروف، أو <bdi>abruption</bdi>، أو <bdi>severe preeclampsia/HELLP</bdi>؛ ليس عندها أي تاريخ طبي.",
    "D": "<bdi>Retained placental fragments</bdi> تُشتبه عند مشيمة غير مكتملة بالفحص أو نزيف متأخر/ثانوي؛ ما ذُكر شي من هذا.",
},
"AS-0755": {
    "A": "<bdi>Atony</bdi> هو أشيع سبب بشكل عام، لكنه يعطي رحم <bdi>soft, boggy</bdi>؛ هنا الرحم <bdi>firm</bdi> فيُستبعد.",
    "B": "<bdi>Coagulopathy</bdi> سبب غير شائع ويحتاج محرّض (<bdi>abruption</bdi>، <bdi>preeclampsia</bdi>، <bdi>amniotic fluid embolism</bdi>، اضطراب تخثر معروف)؛ لا شي من ذلك بعد ولادة سهلة.",
    "D": "<bdi>Retained products</bdi> عادة توقف الرحم عن الانقباض الجيد (رحم <bdi>boggy</bdi>) أو تتبع مشيمة ناقصة؛ لا شي من ذلك مذكور.",
},
"AS-0756": {
    "A": "<bdi>Coagulopathy (Thrombin)</bdi> يُشتبه فيه مع نزف من مواقع متعددة أو <bdi>abruption</bdi> أو <bdi>preeclampsia</bdi> أو <bdi>DIC</bdi>؛ هنا فيه مصدر تشريحي واضح بالفحص.",
    "B": "<bdi>Uterine inversion</bdi> يظهر عند خروج المشيمة مع <bdi>shock</bdi> وكتلة بالمهبل وغياب قمة الرحم بالفحص البطني؛ لا شي من ذلك مذكور.",
    "D": "<bdi>Retained placental tissue (Tissue)</bdi> يعطي مشيمة ناقصة ورحم لا يبقى منقبض؛ لا يفسر وجود تمزقات مرئية.",
},
"AS-0757": {
    "A": "<bdi>Uterine atony</bdi> هو أشيع سبب لـ<bdi>primary PPH</bdi> (أول 24 ساعة، رحم <bdi>soft boggy</bdi>)؛ ليس السبب المعتاد لنزيف بعد أسبوعين تقريبًا.",
},
"AS-0763": {
    "B": "تحليل البول أقل حساسية من الزرع (ممكن يكون <bdi>nitrite negative</bdi> إذا كان مكوث البول بالمثانة قصير)؛ تكراره لا يضيف شي بعد ما الزرع إيجابي.",
    "C": "الانتظار لحد ظهور الأعراض هو النهج عند غير الحوامل؛ أما بالحمل فـ<bdi>bacteriuria</bdi> غير المعالج ممكن يتطور لـ<bdi>pyelonephritis</bdi>، فيُعالج فورًا.",
},
"AS-0763B": {
    "A": "<bdi>IV antibiotics</bdi> تُعطى لحالات <bdi>pyelonephritis</bdi> أو <bdi>sepsis</bdi> (حمى، ألم خاصرة، رعشة)؛ بدون أعراض لا توجد عدوى تحتاج علاج، وعلاج <bdi>bacteriuria</bdi> هنا يسبب فقط مقاومة مضادات حيوية.",
},
"AS-0772": {
    "A": "<bdi>Cerclage</bdi> يُعطى لمن لديها تاريخ خسارة بالثلث الثاني وطول عنق أقل من <bdi>25 mm</bdi> قبل 24 أسبوع؛ هنا الطول <bdi>27 mm</bdi> وهي بالفعل عند 24 أسبوع، وبعدها لا يُنصح عادة بـ<bdi>cerclage</bdi>.",
    "B": "<bdi>Vaginal progesterone</bdi> هو جواب مسار الفحص الدوري عندما يكون العنق قصير (أقل من <bdi>25 mm</bdi>) بدون تاريخ خسارة سابقة؛ <bdi>27 mm</bdi> أعلى من هذا الحد.",
    "D": "<bdi>Tocolysis</bdi> تُستخدم لإيقاف التقلصات بـ<bdi>preterm labor</bdi> فعلي لإعطاء فرصة لـ<bdi>steroids</bdi>؛ هي بلا تقلصات، والتوكوليتك لا يعالج طول العنق.",
},
"AS-0783": {
    "A": "<bdi>Fibroids</bdi> تسبب نزيف شديد لكن بدورات منتظمة ومتكررة؛ لا تفسر دورات كل 3-4 أشهر فقط.",
    "B": "اضطراب تخثر (مثل <bdi>von Willebrand</bdi>) عادة يظهر بنزيف منتظم شديد منذ البلوغ مع تاريخ نزيف آخر؛ ما فيه شي يدعم ذلك هنا.",
    "C": "فحص الحمل سلبي، وهذا يستبعد أي نوع من <bdi>abortion</bdi>.",
},
"AS-0792": {
    "B": "<bdi>Female condom</bdi> معدل فشله بالاستخدام المعتاد حوالي <bdi>21 per 100 woman-years</bdi>، أعلى بكثير من الحلقة؛ يُختار عند أولوية الحماية من <bdi>STI</bdi> بتحكم المرأة.",
    "C": "<bdi>Male condom</bdi> معدل فشله حوالي <bdi>13 per 100 woman-years</bdi>؛ هو الجواب الصحيح عندما يسأل السؤال عن الحماية من <bdi>STIs</bdi> لا أقصى منع حمل.",
    "D": "<bdi>Spermicide</bdi> لحاله من أقل الوسائل فعالية (حوالي <bdi>21 per 100</bdi>)؛ يُستخدم أساسًا كإضافة للوسائل الحاجزية.",
},
"AS-0797": {
    "A": "<bdi>Prophylactic antibiotics</bdi> ممكن تُعطى حول وقت العملية، لكنها ليست أهم تعليمة بعد العملية؛ القلق الأساسي بعد <bdi>hymenotomy</bdi> هو الشفاء بدون إعادة انغلاق الفتحة.",
    "C": "<bdi>OCP</bdi> يُثبّط الدورة الشهرية ويُستخدم لمشاكل أخرى (مثل تثبيط الدورة أو اضطراب تخثر)؛ بعد رفع الانسداد المريضة تحتاج تدفق طمث طبيعي لا تثبيطه.",
},
"AS-0807": {
    "C": "تحويل إلى نظام <bdi>multiple-dose regimen</bdi> ليس الخطوة التالية بعد فشل الجرعة الواحدة مع <bdi>hCG</bdi> مرتفع؛ الاستمرار بعلاج طبي يؤخر العلاج الحاسم ويزيد خطر التمزق.",
    "D": "جرعة ثانية من <bdi>methotrexate</bdi> تُعطى عند ثبات أو انخفاض أقل من 15% من يوم 4 إلى يوم 7؛ لا تُستخدم عندما يكون <bdi>hCG</bdi> مرتفع بوضوح.",
},
"AS-0808": {
    "A": "متابعة <bdi>hCG</bdi> أسبوعيًا تناسب فقط استجابة جيدة، أي انخفاض أكثر من 15% بين يوم 4 ويوم 7.",
    "C": "جرعة ثانية من <bdi>methotrexate</bdi> هي الخطوة عند ثبات أو انخفاض أقل من 15%، لا عند ارتفاع واضح كهذا.",
    "D": "ارتفاع <bdi>hCG</bdi> يدل على فشل العلاج الطبي؛ التحويل إلى نظام <bdi>multiple-dose methotrexate</bdi> يؤخر العلاج الحاسم.",
},
"AS-0826": {
    "A": "<bdi>Endometrial cancer</bdi> ينتج من <bdi>unopposed estrogen</bdi> (مثل <bdi>PCOS</bdi>، البدانة، <bdi>HRT</bdi> بإستروجين فقط مع رحم موجود)؛ <bdi>POI</bdi> حالة <bdi>low-estrogen</bdi>.",
    "B": "<bdi>Multiple gestation</bdi> خطر مرتبط بتحريض التبويض أو <bdi>IVF</bdi>؛ مع فشل المبيض خصوبتها منخفضة جدًا لا مرتفعة.",
    "C": "خطر <bdi>ovarian cancer</bdi> يرتفع مع زيادة عدد دورات التبويض (قلة ولادة، بلوغ مبكر، سن أمل متأخر، <bdi>BRCA</bdi>)؛ فشل المبيض لا يرفعه.",
},
"AS-0828": {
    "A": "<bdi>Immediate IOL</bdi> فورًا ليس إجراء وقائيًا عامًا؛ يُعطى فقط عند <bdi>term PROM</bdi> أو عند وجود استطباب واضح (عدوى، تدهور الجنين)، لا كإجراء <bdi>health promotion</bdi> لكل الحالات.",
},
"AS-0833": {
    "A": "<bdi>Bupropion</bdi> ليس خط أول بالحمل لمحدودية بيانات أمان الجنين، ويخفض عتبة التشنج.",
    "B": "<bdi>E-cigarettes</bdi> ليست علاج إقلاع موصى به بالحمل؛ تستمر بإعطاء <bdi>nicotine</bdi> مع مواد أخرى غير مؤكدة الأمان على الجنين وتُبقي سلوك التدخين مستمرًا.",
},
"AS-0837": {
    "A": "<bdi>Maternal oxygen</bdi> جزء من إنعاش داخل الرحم لتخطيط <bdi>Category 2 (non-reassuring)</bdi> بعد تغيير الوضعية والسوائل؛ تخطيط <bdi>Category 1</bdi> لا يحتاج إنعاش.",
    "C": "<bdi>Cesarean section</bdi> يُستخدم لـ<bdi>fetal distress (Category 3)</bdi> أو فشل الإنعاش أو ولادة معسرة؛ لا شي من ذلك موجود هنا.",
},
"AS-0855": {
    "A": "<bdi>Forceps</bdi> يحتاج تأكيد <bdi>full dilatation</bdi> مع محطة مناسبة؛ محطة <bdi>+2</bdi> وحدها لا تكفي بدون تأكيد الاتساع الكامل.",
    "B": "<bdi>Ventouse</bdi> كذلك يحتاج <bdi>full dilatation</bdi> مؤكدة، وغير ذلك قد يسبب أذى بدون فائدة.",
    "C": "<bdi>Cesarean section</bdi> خطوة متقدمة يُنتقل لها بعد فشل التقييم الأقل تدخلًا مثل <bdi>fetal scalp sampling</bdi>، لا كخطوة أولى هنا.",
},
"AS-0857": {
    "B": "أسبوع <bdi>20</bdi> يخص فحص التشوهات التفصيلي (<bdi>anomaly scan</bdi>) لا فحص زراعة البول؛ الانتظار لهذا الوقت يؤخر كشف <bdi>bacteriuria</bdi>.",
},
"AS-0871": {
    "B": "<bdi>OCP</bdi> يحتوي <bdi>estrogen</bdi> ويُتجنب عند مريضة تحتاج علاج تخثر؛ مناسب فقط لامرأة صحية بلا خطورة تخثرية.",
    "C": "<bdi>Combined patch</bdi> يعطي <bdi>estrogen</bdi> تمامًا مثل الحبوب المركبة، فيحمل نفس خطر التخثر.",
    "D": "<bdi>Tubal ligation</bdi> جراحة نهائية تحتاج تخدير وتوقف مؤقت لمضاد التخثر، وهذا مبالغ فيه لعمرها 22 سنة.",
},
"AS-0872": {
    "B": "<bdi>Surgery</bdi> تُحجز لحالة <bdi>rising hCG</bdi> أو عدم استقرار أو علامات تمزق؛ هي <bdi>asymptomatic</bdi> مع ثبات فقط.",
    "C": "تكرار <bdi>hCG</bdi> بعد <bdi>48 hours</bdi> أداة لتقييم حمل مجهول الموقع، لا لتقييم استجابة <bdi>methotrexate</bdi> اللي أصلًا متوفرة بمقارنة يوم 4 بيوم 7.",
    "D": "متابعة <bdi>hCG</bdi> أسبوعيًا لحالها تناسب انخفاض أكثر من 15%؛ الثبات ليس انخفاضًا كافيًا.",
},
"AS-0873": {
    "A": "<bdi>Uterine rupture</bdi> يسبب نزيف مفاجئ وصدمة، كلاسيكيًا بالطلق مع رحم له ندبة، لكنه ليس المحرض المعتاد لـ<bdi>DIC</bdi>.",
    "C": "<bdi>Placenta previa</bdi> يسبب نزيف غير مؤلم قبل الولادة وممكن يسبب <bdi>PPH</bdi> من القطعة السفلية، لكن بدون خثرة خلف المشيمة نادرًا يسبب <bdi>DIC</bdi>.",
    "D": "اضطراب تخثر خلقي حالة مزمنة موجودة من قبل مع تاريخ شخصي أو عائلي، لا اعتلال تخثر مستهلك مستحدث كـ<bdi>DIC</bdi>.",
},
"AS-0905": {
    "A": "تحقيق <bdi>recurrent pregnancy loss</bdi> (كاريوتايب الأبوين، أجسام مضادة فوسفوليبيدية، تقييم تجويف الرحم) يُطلب بعد خسارتين أو ثلاث متتاليات، لا خسارة واحدة عرضية.",
},
"AS-0908": {
    "A": "<bdi>Trichomoniasis</bdi> يعطي إفرازات رغوية صفراء-خضراء كريهة مع عنق رحم \"<bdi>strawberry</bdi>\" وطفيليات متحركة بالفحص المباشر، لا إفرازات حليبية رقيقة.",
    "B": "استعمار <bdi>Group B strep</bdi> حمل صامت يُكتشف بفحص مسحة شرجية مهبلية بالحمل، ولا يسبب رائحة سمكية.",
    "D": "<bdi>Gonorrhea</bdi> يسبب التهاب عنق رحم أو مجرى بول قيحي، غالبًا صامت، ببكتيريا سالبة الغرام ثنائية، بدون رائحة سمكية مميزة.",
},
"AS-0909": {
    "A": "<bdi>Trichomoniasis</bdi> يعطي إفرازات رغوية صفراء-خضراء مع عنق رحم \"<bdi>strawberry</bdi>\" وطفيليات متحركة، لا إفرازات حليبية رقيقة.",
    "B": "استعمار <bdi>Group B strep</bdi> صامت يُكتشف بفحص حمل روتيني، ولا يسبب رائحة سمكية.",
    "D": "<bdi>Gonorrhea</bdi> يسبب التهاب قيحي ببكتيريا سالبة الغرام ثنائية، غالبًا بدون رائحة سمكية مميزة.",
},
"AS-0917": {
    "B": "<bdi>Active management of third stage</bdi> هي الاستراتيجية الكاملة (تشمل <bdi>oxytocin</bdi> مع شد الحبل المتحكم وتدليك الرحم)؛ صحيحة إذا سأل السؤال عن الاستراتيجية لا الدواء المحدد.",
},
"AS-0917B": {
    "B": "<bdi>Ergonovine</bdi> دواء خط ثاني يُستخدم إذا فشل <bdi>oxytocin</bdi>، ويُمنع مع <bdi>hypertension</bdi> أو <bdi>preeclampsia</bdi>.",
    "C": "<bdi>Misoprostol</bdi> بديل يُستخدم عند عدم توفر <bdi>oxytocin</bdi>، لا كخط أول.",
    "D": "<bdi>Carboprost</bdi> دواء متأخر لحالات <bdi>atony</bdi> المعندة، ويُمنع مع <bdi>asthma</bdi>.",
},
"AS-0918": {
    "B": "<bdi>Misoprostol</bdi> بديل مقبول للوقاية فقط عند عدم توفر <bdi>oxytocin</bdi>؛ ليس خط أول وله أعراض جانبية أكثر (حمى، رجفة).",
    "C": "<bdi>Carboprost</bdi> دواء متأخر لعلاج <bdi>atony</bdi> المعندة لا للوقاية الروتينية، ويُمنع مع <bdi>asthma</bdi>.",
},
}

HIGHLIGHT_TERMS = {
"AS-0751": ["G8 P5126", "oxytocin", "chorioamnionitis"],
"AS-0752": ["term twin pregnancy"],
"AS-0753": ["low-lying placenta", "One hour post-delivery"],
"AS-0754": ["not known to have any medical or surgical history", "heavy gush of bleeding postpartum"],
"AS-0755": ["uterus noted to be firm"],
"AS-0756": ["forceps delivery", "laceration of the cervix, vagina, and the perineal body"],
"AS-0757": ["12 days ago"],
"AS-0763": ["Asymptomatic Pregnant", "urine culture positive for E coli"],
"AS-0763B": ["Postpartum", "asymptomatic bacteriuria after delivery"],
"AS-0772": ["24 weeks", "cervical length of 27 mm"],
"AS-0783": ["morbidly obese and diabetic", "periods are irregular, occurring every 3-4 months", "Pregnancy test is negative"],
"AS-0792": ["effective and reversible", "most effective"],
"AS-0797": ["1ry amenorrhea and abd pain", "mature genitalia", "mass anterior to the rectum", "cruciate incision"],
"AS-0807": ["methotrexate for an ectopic pregnancy", "Day 4: BhCG was1200", "Day 7: BhCG was 2100"],
"AS-0808": ["methotrexate treatment for an ectopic pregnancy", "Day 4: 1200 mIU/mL Day 7: 2100 mIU/mL"],
"AS-0826": ["9-month history of amenorrhea", "FSH 60", "LH 60"],
"AS-0828": ["POROM", "HEALTH PROMOTION AND PREVENT ILLNESS"],
"AS-0833": ["Pregnant smoking"],
"AS-0837": ["latent phase of labor", "baseline of 140", "moderate variability", "recurrent early decelerations"],
"AS-0855": ["36 wk ga", "CTG type 2 deceleration", "+2 station"],
"AS-0857": ["urine inf for pregnant women"],
"AS-0871": ["on warfarin", "contraception"],
"AS-0872": ["ectopic pregnancy", "methotrexate", "b-hcg on day 4 and 7 is plateauing", "asymptomatic"],
"AS-0873": ["postpartum", "DIC"],
"AS-0905": ["a first-trimester spontaneous abortion"],
"AS-0908": ["thin milky appearance", "fish-like odor", "vaginal pH of 4.5"],
"AS-0909": ["thin milky appearance", "fish-like odor", "vaginal pH of 7.5"],
"AS-0917": ["6 macrosomic babies", "prevent PPH"],
"AS-0917B": ["multipara", "postpartum hemorrhage", "macrosomic baby"],
"AS-0918": ["PPH", "prevent"],
}
