# -*- coding: utf-8 -*-
# Batch r17 — Pediatrics slice (141 questions), AS-1679..AS-2289.

EXPLANATIONS = {
"AS-1679": {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "هذا سؤال <bdi>dyslipidemia</bdi> عند <bdi>child</bdi> عمره 10 سنين، والمهم تحديد <bdi>stage</bdi>: نتيجة أولى غير مؤكدة، أو <bdi>confirmed</bdi> بسيطة، أو <bdi>very high LDL</bdi>.",
    "clues": [
        ("high LDL", "نتيجة واحدة مرتفعة بدون تأكيد وبدون سبب ثانوي واضح"),
        ("no genetic diseases", "ينفي <bdi>familial hypercholesterolemia</bdi> الواضحة اللي تحتاج تحويل فوري"),
        ("growing normally", "ينفي سبب ثانوي جهازي شديد"),
    ],
    "why_correct": [
        "أول خطوة عند طفل بنتيجة <bdi>lipid profile</bdi> مرتفعة هي <bdi>further investigation</bdi>: نعيد الفحص على معدة فاضية (<bdi>fasting</bdi>) ونأخذ متوسط نتيجتين، ونستبعد أسباب ثانوية (<bdi>hypothyroidism</bdi>، <bdi>nephrotic syndrome</bdi>، مرض كبد، سكري).",
        "السؤال ما يذكر رقم محدد جدًا للـ<bdi>LDL</bdi> ولا تأكيد بنتيجتين، فمو منطقي نقفز لـ<bdi>diet</bdi> أو <bdi>referral</bdi> من أول نتيجة.",
        "التحويل لعيادة <bdi>cardiology prevention</bdi> يكون لما تتأكد النتيجة وتكون عالية جدًا أو فيه <bdi>familial hypercholesterolemia</bdi>، وهذا غير متوفر هنا.",
    ],
    "when_changes": [
        "لو السؤال حدد <bdi>LDL</bdi> 5 <bdi>mmol/L</bdi> ومؤكدة، الجواب يصير <bdi>further investigation</bdi> أيضًا (استبعاد أسباب ثانوية) قبل أي قرار نهائي - وهذا نفس منطق سؤال مكرر بنفس البيانات تقريبًا.",
        "لو كانت النتيجة مؤكدة بدون سبب ثانوي وطفيفة الارتفاع، الجواب يصير تعليم الأم عن <bdi>feeding habits</bdi> (<bdi>diet</bdi> أول خط علاج).",
        "لو تأكد <bdi>LDL</bdi> ≥4.9 <bdi>mmol/L</bdi> مع فشل <bdi>diet</bdi> أو <bdi>family history</bdi> قوي لـ<bdi>FH</bdi>، الجواب يصير تحويل لعيادة متخصصة.",
    ],
    "rule": "ترتيب التعامل مع <bdi>dyslipidemia</bdi> عند <bdi>child</bdi>: تأكيد النتيجة أولًا (<bdi>further investigation</bdi>)، بعدين استبعاد سبب ثانوي، بعدين <bdi>diet</bdi>، وأخيرًا <bdi>referral</bdi>/أدوية.",
    "comparison": None,
    "labs": None,
    "guideline_note": "هذا السؤال بلا جواب مؤكد من المصدر؛ اعتمدت على نفس منطق <bdi>exam_pearl</bdi> اللي يقول نتيجة أولى غير مؤكدة = <bdi>further investigation</bdi>.",
},
"AS-1680": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "هذا سيناريو <bdi>dyslipidemia</bdi> عند <bdi>child</bdi> بـ<bdi>LDL</bdi> عالي جدًا (5 <bdi>mmol/L</bdi>)، والسؤال يبي الخطوة الصحيحة قبل الالتزام بـ<bdi>diet</bdi> أو <bdi>referral</bdi>.",
    "clues": [
        ("LDL 5 mmol", "ارتفاع واضح يرفع الشك بـ<bdi>familial hypercholesterolemia</bdi>"),
        ("low HDL", "جزء من الصورة لكن ما يغيّر الخطوة الأولى"),
        ("growing normally", "ينفي سبب ثانوي جهازي شديد يحتاج تدخل فوري"),
    ],
    "why_correct": [
        "<bdi>LDL</bdi> 5 <bdi>mmol/L</bdi> (حوالي 193 <bdi>mg/dL</bdi>) عند طفل عمره 10 سنين وصحته طيبة هو ارتفاع واضح يرفع الشك بـ<bdi>familial hypercholesterolemia</bdi>.",
        "الخطوة الجاية هي <bdi>further investigation</bdi>: نعيد فحص <bdi>fasting lipid profile</bdi>، نستبعد أسباب ثانوية (<bdi>hypothyroidism</bdi>، <bdi>nephrotic syndrome</bdi>، مرض كبد، سكري) ونأخذ <bdi>family history</bdi>، قبل الالتزام بـ<bdi>diet</bdi> أو دواء متخصص.",
        "يعني نتيجة واحدة ولو عالية ما تكفي عشان نقرر <bdi>management</bdi> نهائي بدون تأكيد.",
    ],
    "when_changes": [
        "لو تأكدت النتيجة بفحصين واستبعدنا الأسباب الثانوية وكانت الزيادة بسيطة، الجواب يصير تعليم الأم عن <bdi>feeding habits</bdi>.",
        "لو تأكد <bdi>LDL</bdi> ≥4.9 <bdi>mmol/L</bdi> بعد <bdi>diet</bdi> فاشل أو فيه <bdi>FH</bdi> مؤكدة، الجواب يصير تحويل لعيادة <bdi>cardiology prevention</bdi>.",
    ],
    "rule": "نتيجة <bdi>LDL</bdi> عالية عند طفل لازم تتأكد وتُستبعد أسبابها الثانوية قبل أي قرار <bdi>diet</bdi> أو <bdi>referral</bdi>، حتى لو الرقم عالي جدًا.",
    "comparison": None,
    "labs": [["LDL", "5 mmol/L", "أقل من 2.85 mmol/L يُفضّل عند الأطفال"]],
    "guideline_note": None,
},
"AS-1682": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل مشخّص بـ<bdi>pyloric stenosis</bdi>، والسؤال يبي الخطوة الجاية بعد التشخيص، يعني تثبيت الحالة قبل الجراحة مو تصوير إضافي.",
    "clues": [
        ("diagnosed with pyloric stenosis", "التشخيص خلص، فالتصوير مو الخطوة الجاية"),
        ("next step", "يبي خطوة الاستقرار (<bdi>stabilization</bdi>) قبل العملية"),
    ],
    "why_correct": [
        "بعد تأكيد <bdi>pyloric stenosis</bdi>، الحالة ما تعتبر طارئة جراحية؛ الأولوية هي إيقاف الرضعات (<bdi>NPO</bdi>) وتصحيح الجفاف وخلل الإلكترولايتات (<bdi>hypochloremic hypokalemic metabolic alkalosis</bdi>) قبل عملية <bdi>pyloromyotomy</bdi>.",
        "كلمة <bdi>next step</bdi> بعد ما التشخيص تأكد تعني تثبيت الحالة، مو مزيد من <bdi>imaging</bdi>.",
    ],
    "when_changes": [
        "لو السؤال يبي أول فحص يأكد التشخيص قبل ما يصير التشخيص معروف، الجواب يصير <bdi>abdominal ultrasound</bdi>.",
        "لو السؤال يبي السائل الوريدي المستخدم للتصحيح، الجواب يصير <bdi>0.9% saline</bdi> مع بوتاسيوم بعد تأكد إدرار البول، مو <bdi>bicarbonate</bdi>.",
    ],
    "rule": "في <bdi>pyloric stenosis</bdi> المؤكدة: ثبّت الطفل أولًا (<bdi>NPO</bdi> + <bdi>IV fluids</bdi>) وصحح الإلكترولايتات، وبعدها العملية؛ التصوير يكون قبل التشخيص مو بعده.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1704": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بحمى طويلة مع مجموعة علامات تشخيصية تدل على <bdi>Kawasaki disease</bdi>، والسؤال يبي التشخيص نفسه.",
    "clues": [
        ("high fever", "حمى شديدة مستمرة"),
        ("6 days", "حمى ≥5 أيام شرط أساسي لـ<bdi>Kawasaki disease</bdi>"),
        ("cracked red lips", "من علامات <bdi>CRASH</bdi>"),
        ("cervical lymphadenopathy", "من علامات <bdi>CRASH</bdi>"),
        ("red eyes", "<bdi>non-purulent conjunctivitis</bdi>"),
    ],
    "why_correct": [
        "حمى لمدة <bdi>6 days</bdi> مع <bdi>cracked red lips</bdi> و<bdi>rash</bdi> و<bdi>cervical lymphadenopathy</bdi> و<bdi>red eyes</bdi> (<bdi>non-purulent conjunctivitis</bdi>) تعطي حمى ≥5 أيام مع 4 من 5 علامات أساسية، وهذا معيار تشخيص <bdi>Kawasaki disease</bdi>.",
        "التشخيص مهم لأن <bdi>Kawasaki</bdi> غير المعالج يرفع خطر <bdi>coronary artery aneurysms</bdi>.",
    ],
    "when_changes": [
        "لو العين فيها إفرازات (<bdi>purulent</bdi>)، الصورة تميل لعدوى وما تدعم <bdi>Kawasaki</bdi>.",
        "لو الحمى أقل من 5 أيام بدون العلامات الكافية، التشخيص يصير <bdi>incomplete Kawasaki</bdi> ويحتاج فحوصات إضافية.",
    ],
    "rule": "حمى مستمرة ≥5 أيام لا تستجيب لخافض الحرارة مع <bdi>non-purulent conjunctivitis</bdi> تعني <bdi>Kawasaki</bdi> لحد ما يثبت العكس.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1705": {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "طفل بـ<bdi>red urine</bdi> وحمى وألم بطني، والسؤال يفرّق بين عدوى الجهاز البولي العلوي و<bdi>glomerulonephritis</bdi>.",
    "clues": [
        ("red urine", "يحتاج تفريق بين سبب كلوي أو عدوى"),
        ("fever", "مع ألم بطني يدعم عدوى الجهاز العلوي"),
        ("abdominal discomfort", "يشبه ألم الخاصرة في <bdi>pyelonephritis</bdi>"),
    ],
    "why_correct": [
        "الجمع بين <bdi>fever</bdi> وألم بطني/خاصرة مع <bdi>red urine</bdi> (<bdi>hematuria</bdi> أو بول غامق من <bdi>pyuria</bdi>) يدعم أكثر <bdi>acute pyelonephritis</bdi> (عدوى الجهاز البولي العلوي).",
        "ما فيه ذكر لـ<bdi>edema</bdi> أو <bdi>hypertension</bdi> أو عدوى <bdi>strep</bdi> سابقة اللي تدعم <bdi>glomerulonephritis</bdi>، فالصورة الأقرب هي عدوى.",
    ],
    "when_changes": [
        "لو فيه <bdi>edema</bdi> و<bdi>hypertension</bdi> وتاريخ عدوى <bdi>strep throat</bdi> أو جلدية قبل 1-2 أسبوع، الجواب يصير <bdi>glomerulonephritis</bdi> (<bdi>PSGN</bdi>).",
        "لو الأعراض محصورة بـ<bdi>dysuria</bdi> و<bdi>frequency</bdi> بدون حمى عالية، الجواب يصير <bdi>UTI</bdi> سفلي بسيط.",
    ],
    "rule": "حمى + ألم بطني/خاصرة + بول غير طبيعي عند طفل يوجّه لعدوى الجهاز العلوي (<bdi>pyelonephritis</bdi>)؛ <bdi>edema</bdi> و<bdi>hypertension</bdi> و<bdi>RBC casts</bdi> توجّه لـ<bdi>glomerulonephritis</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "هذا السؤال بلا جواب مؤكد من المصدر؛ اخترت <bdi>acute pyelonephritis</bdi> لأن الحمى مع الألم البطني أقوى من مجرد <bdi>red urine</bdi> بدون علامات نفريتية.",
},
"AS-1711": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "هذا سؤال <bdi>toxidrome</bdi> كلاسيكي، والصورة كلها تدل على التسمم الكولينرجي الناتج عن <bdi>organophosphate</bdi>.",
    "clues": [
        ("miosis", "تضيّق الحدقة، من علامات <bdi>cholinergic toxidrome</bdi>"),
        ("excessive salivation", "من مجموعة <bdi>DUMBBELSS</bdi>"),
        ("garlic odour", "علامة مميزة لتسمم <bdi>organophosphate</bdi>"),
    ],
    "why_correct": [
        "<bdi>diarrhoea</bdi>، <bdi>vomiting</bdi>، <bdi>miosis</bdi>، <bdi>bronchoconstriction</bdi>، <bdi>sweating</bdi> و<bdi>excessive salivation</bdi> كلها تشكّل <bdi>cholinergic toxidrome</bdi> الناتج عن تثبيط <bdi>acetylcholinesterase</bdi>، وهذا تسمم <bdi>organophosphate</bdi>.",
        "رائحة <bdi>garlic odour</bdi> على النفس علامة مساعدة كلاسيكية تدعم التشخيص.",
    ],
    "when_changes": [
        "لو كانت الحدقة متوسعة (<bdi>mydriasis</bdi>) مع <bdi>tachycardia</bdi> و<bdi>hypertension</bdi>، الجواب يصير تسمم <bdi>sympathomimetic</bdi> مثل <bdi>cocaine</bdi>.",
        "لو النفس رائحته <bdi>acetone</bdi> مع <bdi>Kussmaul breathing</bdi> وسكر عالي، الجواب يصير <bdi>DKA</bdi>.",
    ],
    "rule": "حدقة ضيقة (<bdi>miosis</bdi>) مع إفرازات زائدة = تسمم كولينرجي (<bdi>organophosphate</bdi>)؛ حدقة ضيقة مع تنفس هادئ جاف = تسمم <bdi>opioid</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1713": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفل بدون أعراض عنده نفخة قلبية (<bdi>murmur</bdi>) توصيفها كلاسيكي للنفخة البريئة (<bdi>venous hum</bdi>)، والسؤال يبي الإجراء الصحيح قبل جراحة فم اختيارية.",
    "clues": [
        ("asymptomatic", "من علامات النفخة البريئة"),
        ("continuous murmur", "نوع <bdi>venous hum</bdi> الاستثنائي بين النفخات البريئة"),
        ("murmur disappears when the child is supine", "العلامة المميزة لـ<bdi>venous hum</bdi>"),
    ],
    "why_correct": [
        "طفل <bdi>asymptomatic</bdi> بنفخة خفيفة <bdi>grade 2/6 continuous</bdi> عند الحافة العظمية العلوية اليمنى، تُسمع جالسًا وتختفي مستلقيًا (<bdi>supine</bdi>)، هذه صورة <bdi>venous hum</bdi> الكلاسيكية وهي نفخة بريئة.",
        "تغيّر النفخة مع وضعية الجسم هو العلامة الأساسية للنفخة البريئة، فنطمئن الأسرة ونكمل الجراحة بدون تأخير.",
    ],
    "when_changes": [
        "لو كانت النفخة من درجة ≥3 أو فيها <bdi>thrill</bdi> أو مكون <bdi>diastolic</bdi> أو ما تتغير بالوضعية، الجواب يصير تحويل لـ<bdi>cardiology</bdi>.",
        "لو الطفل عنده عيب قلبي عالي الخطورة (صمام مصنّع أو مرض قلب سياني)، الجواب يصير <bdi>antibiotic prophylaxis</bdi> قبل جراحة الفم.",
    ],
    "rule": "نفخة مستمرة (<bdi>continuous</bdi>) غالبًا مرضية (<bdi>PDA</bdi>) إلا لو اختفت مستلقيًا، فتكون <bdi>venous hum</bdi> بريئة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1716": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "كسر بذراع طفل مع تأخر واضح في طلب الرعاية الطبية، والسؤال يبي العلامة الأهم على <bdi>child abuse</bdi>.",
    "clues": [
        ("2 days ago", "تأخر يومين في طلب الرعاية بعد إصابة واضحة"),
    ],
    "why_correct": [
        "الوالدين لاحظوا إن الطفل ما يقدر يحرك ذراعه لكنهم جاوا للمستشفى بعد يومين فقط؛ التأخر غير المفسَّر (<bdi>delayed presentation</bdi>) في طلب الرعاية لإصابة واضحة هو علامة معروفة لـ<bdi>non-accidental injury</bdi>، حتى لو الأسرة تبدو حنونة.",
    ],
    "when_changes": [
        "لو كان الكسر من نوع <bdi>metaphyseal corner fracture</bdi> أو <bdi>posterior rib fracture</bdi> أو كسور بأعمار مختلفة، يصير نوع الكسر نفسه هو العلامة الأقوى.",
        "لو القصة تتغيّر أو غير منطقية مع عمر الطفل، تصير القصة غير المتسقة هي العلامة.",
    ],
    "rule": "الظهور النظيف والأسرة المتعاونة لا تستبعد <bdi>abuse</bdi>؛ توقيت طلب الرعاية هو اللي يفضح الحالة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1726": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفلة بثالوث جلدي وعضلي كلاسيكي، والسؤال يبي تشخيص <bdi>juvenile dermatomyositis</bdi>.",
    "clues": [
        ("heliotrope rash", "طفح الجفون المميز لـ<bdi>dermatomyositis</bdi>"),
        ("thickening of skin over metacarpophalangeal joints", "<bdi>Gottron papules</bdi>"),
        ("proximal muscle weakness", "ضعف عضلي قريب من الجذع"),
    ],
    "why_correct": [
        "<bdi>heliotrope rash</bdi> بالجفون مع تثخّن جلد فوق مفاصل <bdi>MCP</bdi> (<bdi>Gottron papules</bdi>) مع <bdi>proximal muscle weakness</bdi> عند طفلة 7 سنين هو الثالوث المميز (<bdi>pathognomonic</bdi>) لـ<bdi>juvenile dermatomyositis</bdi>.",
        "الجمع بين علامات الجلد والضعف العضلي (<bdi>myopathy</bdi>) يفرّقها عن أمراض النسيج الضام الأخرى.",
    ],
    "when_changes": [
        "لو كان الطفح مركّز بالوجنتين مع تجنّب الثنايا الأنفية الشفوية ومعه قرحات فمية و<bdi>cytopenia</bdi>، الجواب يصير <bdi>SLE</bdi>.",
        "لو فيه تاريخ عدوى <bdi>streptococcal</bdi> سابقة مع التهاب قلب وحركات لا إرادية، الجواب يصير <bdi>rheumatic fever</bdi>.",
    ],
    "rule": "<bdi>heliotrope rash</bdi> + <bdi>Gottron papules</bdi> + ضعف عضلي قريب = <bdi>juvenile dermatomyositis</bdi>؛ خلافًا عن البالغين، ما له ارتباط بالسرطان.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1728": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل غير ملقّح بصورة مرض معدي خطير بالحلق، والسؤال يبي اللقاح اللي يمنع هذي الحالة، يعني <bdi>diphtheria</bdi> مو <bdi>Hib epiglottitis</bdi>.",
    "clues": [
        ("URTI", "بداية تدريجية بأعراض تنفسية علوية"),
        ("drooling of saliva", "يحدث في الحالتين لكنه أكثر دعم لـ<bdi>diphtheria</bdi> مع بقية الصورة"),
        ("did not receive any vaccine", "يفتح الباب لمرض يمنعه اللقاح"),
    ],
    "why_correct": [
        "طفل <bdi>unvaccinated</bdi> عنده <bdi>URTI</bdi> سابق مع <bdi>drooling</bdi> و<bdi>multiple enlarged lymph nodes</bdi> (<bdi>bull neck</bdi>) تناسب <bdi>respiratory diphtheria</bdi>، حيث الغشاء الكاذب الحلقي (<bdi>pseudomembrane</bdi>) يسبب صعوبة بلع وانسداد مجرى هوائي.",
        "لقاح <bdi>DTaP</bdi> كان يمنع هذي الحالة، وهذا اللي يجاوب على سؤال اللقاح الوقائي.",
    ],
    "when_changes": [
        "لو كانت البداية مفاجئة بحمى عالية وطفل متعب (<bdi>toxic</bdi>) بوضعية <bdi>tripod</bdi> وصفير (<bdi>stridor</bdi>) بدون <bdi>URTI</bdi> سابق، الجواب يصير <bdi>Hib epiglottitis</bdi> واللقاح يصير <bdi>Hemophilus</bdi>.",
        "لو شفنا غشاء رمادي ينزف عند إزالته (<bdi>pseudomembrane</bdi>)، هذا يأكد <bdi>diphtheria</bdi> بشكل مباشر.",
    ],
    "rule": "غشاء أبيض/رمادي أو <bdi>bull neck</bdi> = <bdi>diphtheria</bdi>؛ طفل متعب مفاجئ يميل للأمام يلعّب = <bdi>Hib epiglottitis</bdi>.",
    "comparison": {
        "headers": ["الصفة", "Diphtheria", "Hib epiglottitis"],
        "rows": [
            ["البداية", "تدريجية، أيام", "مفاجئة، ساعات"],
            ["الحمى", "منخفضة الدرجة", "عالية"],
            ["العلامة المميزة", "pseudomembrane / bull neck", "tripod / stridor"],
        ],
    },
    "labs": None,
    "guideline_note": "المصدر نفسه يذكر جدل بين الممتحنين؛ الجواب المعتمد هنا <bdi>diphtheria</bdi> حسب ملاحظة المُجمِّع وتفصيل بداية الأعراض.",
},
"AS-1734": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بعلامات عظمية كلاسيكية لـ<bdi>rickets</bdi>، والسؤال يبي العلاج/المكمّل الأنسب.",
    "clues": [
        ("bowed legs", "تقوّس الساقين من علامات <bdi>rickets</bdi>"),
        ("Harrison sulcus", "انخماص عظمي بالصدر مميز لـ<bdi>rickets</bdi>"),
        ("rickets", "التشخيص مذكور مباشرة"),
    ],
    "why_correct": [
        "<bdi>bowed legs</bdi> و<bdi>Harrison sulcus</bdi> علامات عظمية كلاسيكية لـ<bdi>rickets</bdi>، وعند الأطفال أشهر سبب هو نقص <bdi>vitamin D</bdi> الغذائي.",
        "السؤال يبي العلاج/المكمّل، فالجواب هو شكل <bdi>vitamin D</bdi> المستخدم للعلاج: <bdi>vitamin D3 (cholecalciferol)</bdi> يوميًا مع كالسيوم كافٍ.",
    ],
    "when_changes": [
        "لو التحاليل أظهرت <bdi>phosphate</bdi> منخفض مع كالسيوم طبيعي، الجواب يتغيّر لتشخيص <bdi>hypophosphatemic rickets</bdi> اللي لا يستجيب لـ<bdi>vitamin D</bdi> العادي.",
        "لو الطفل عنده أعراض عينية (<bdi>night blindness</bdi>، <bdi>Bitot spots</bdi>) بدل العظمية، الجواب يصير <bdi>vitamin A</bdi>.",
    ],
    "rule": "لما يسألوا نوع <bdi>vitamin D</bdi> المعطى لعلاج <bdi>rickets</bdi>، الجواب الدائم هو <bdi>D3 (cholecalciferol)</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1743": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفل بأعراض سكري وتحاليل تحدد النوع، والعلامة الحاسمة هي <bdi>C-peptide</bdi> المنخفض اللي يدل على نقص إنتاج الأنسولين.",
    "clues": [
        ("C-peptide 0.09 (low)", "يدل على نقص إنتاج الأنسولين من خلايا البيتا، علامة <bdi>type 1 DM</bdi>"),
    ],
    "why_correct": [
        "طفل عمره 10 سنين بـ<bdi>polyuria/polydipsia</bdi> و<bdi>HbA1c</bdi> 6.8% (بمستوى السكري، ≥6.5%) عنده سكري مؤكد.",
        "العلامة الحاسمة هي <bdi>low C-peptide</bdi>: يعني خلايا البيتا لا تصنع أنسولين، وهذا هو الصفة الأساسية لـ<bdi>type 1 diabetes</bdi> (نقص أنسولين مناعي ذاتي)، أشهر سكري الأطفال.",
    ],
    "when_changes": [
        "لو <bdi>C-peptide</bdi> طبيعي أو مرتفع مع سمنة و<bdi>acanthosis nigricans</bdi>، الجواب يصير <bdi>type 2 DM</bdi>.",
        "لو فيه تاريخ عائلي قوي بأجيال متتالية مع <bdi>C-peptide</bdi> محفوظ وأجسام مضادة سلبية، الجواب يصير <bdi>MODY</bdi>.",
        "لو <bdi>HbA1c</bdi> كان طبيعي رغم سكر مرتفع وقت مرض حاد، الجواب يصير <bdi>stress-induced hyperglycemia</bdi>.",
    ],
    "rule": "<bdi>C-peptide</bdi> يفصل بين نقص الأنسولين ومقاومة الأنسولين: منخفض + طفل + أعراض عطش وتبول = <bdi>type 1 DM</bdi>.",
    "comparison": None,
    "labs": [["HbA1c", "6.8%", "أقل من 5.7% طبيعي، 6.5% فأعلى سكري"], ["C-peptide", "0.09", "منخفض (يدل على نقص إنتاج الأنسولين)"]],
    "guideline_note": None,
},
"AS-1755": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "أخ وأخت لمريض <bdi>meningococcal meningitis</bdi>، والسؤال يبي نظام الوقاية الدوائية الصحيح لـ<bdi>close contacts</bdi>.",
    "clues": [
        ("meningococcal meningitis", "عدوى تحتاج <bdi>chemoprophylaxis</bdi> للمقربين"),
        ("chemoprophylaxis", "المطلوب هو الوقاية الدوائية الصحيحة"),
        ("close contacts", "جهات اتصال منزلية، بأعراض أو بدونها"),
    ],
    "why_correct": [
        "<bdi>household contacts</bdi> لمرض <bdi>meningococcal</bdi> يحتاجون وقاية دوائية سواء عندهم أعراض أو لا.",
        "من بين الأنظمة المذكورة، <bdi>ciprofloxacin single dose</bdi> هو النظام المعياري الصحيح الوحيد وهو الدواء المناسب لـ<bdi>Neisseria meningitidis</bdi>.",
    ],
    "when_changes": [
        "لو المريض طفل صغير، النظام البديل الكلاسيكي يصير <bdi>rifampicin</bdi> لمدة يومين فقط (مو أسبوع).",
        "لو المريضة حامل، النظام الأنسب يصير <bdi>ceftriaxone</bdi> جرعة واحدة بالعضل.",
    ],
    "rule": "العدد يفرق: <bdi>ciprofloxacin</bdi> و<bdi>ceftriaxone</bdi> جرعة واحدة، و<bdi>rifampicin</bdi> يومين فقط؛ أي خيار يذكر أسبوع أو جرعات متعددة من <bdi>ceftriaxone</bdi> غلط.",
    "comparison": {
        "headers": ["الدواء", "النظام الصحيح"],
        "rows": [
            ["Ciprofloxacin", "جرعة واحدة فموية"],
            ["Rifampicin", "يومين"],
            ["Ceftriaxone", "جرعة واحدة بالعضل (مفضّل بالحمل)"],
            ["Penicillin", "لا يُستخدم للوقاية (لا يزيل الحمل بالأنف)"],
        ],
    },
    "labs": None,
    "guideline_note": None,
},
"AS-1756": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل ذكر بصفات شبيهة بـ<bdi>Turner</bdi> لكن الجنس ذكر، والسؤال يبي التشخيص الصحيح وهو <bdi>Noonan syndrome</bdi>.",
    "clues": [
        ("short stature", "قصر قامة"),
        ("Webbed neck", "رقبة بها زوائد جلدية جانبية"),
        ("ejection murmurs", "يوجّه لعيب قلبي يمين القلب مثل <bdi>pulmonary stenosis</bdi>"),
    ],
    "why_correct": [
        "الكلمات المفتاحية: <bdi>4-year-old boy</bdi> بـ<bdi>short stature</bdi> و<bdi>webbed neck</bdi> وصفات غير طبيعية ونفخة قلبية انقباضية (<bdi>ejection murmur</bdi>).",
        "<bdi>Noonan syndrome</bdi> هو المظهر الشبيه بـ<bdi>Turner</bdi> اللي يصيب الذكور (والإناث) بـ<bdi>karyotype</bdi> طبيعي، وعيبه القلبي المعتاد هو <bdi>pulmonary valve stenosis</bdi> المسبب للنفخة الانقباضية.",
    ],
    "when_changes": [
        "لو كانت المريضة بنت بـ<bdi>45,X karyotype</bdi> مع <bdi>coarctation of aorta</bdi>، الجواب يصير <bdi>Turner syndrome</bdi>.",
        "لو الطفل طويل القامة مع <bdi>arachnodactyly</bdi> وخلع عدسة العين، الجواب يصير <bdi>Marfan syndrome</bdi>.",
    ],
    "rule": "رقبة بزوائد جلدية (<bdi>webbed neck</bdi>) عند ذكر = <bdi>Noonan</bdi> دايمًا، أبدًا مو <bdi>Turner</bdi>؛ عيب يمين القلب (<bdi>pulmonary stenosis</bdi>) لـ<bdi>Noonan</bdi>، وعيب يسار القلب (<bdi>coarctation</bdi>) لـ<bdi>Turner</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1757": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفلة بكدمات وبقع نزفية بعد عدوى فيروسية مع نقص صفائح معزول، والسؤال يبي الفحص الأكثر تشخيصًا لـ<bdi>ITP</bdi>.",
    "clues": [
        ("after history of runny nose and flu symptoms", "عدوى فيروسية سابقة، نمط <bdi>ITP</bdi> الكلاسيكي"),
        ("Isolated thrombocytopenia", "باقي خطوط الدم طبيعية"),
        ("Platelet 22", "نقص صفائح شديد"),
    ],
    "why_correct": [
        "كدمات وبقع نزفية بعد مرض فيروسي (<bdi>flu-like</bdi>) مع نقص صفائح معزول (صفائح 22، <bdi>WBC</bdi> 8، <bdi>Hb</bdi> 125 طبيعيين) هي صورة <bdi>immune thrombocytopenia</bdi> الكلاسيكية.",
        "<bdi>ITP</bdi> تشخيص استبعاد، والفحص المفتاحي هو <bdi>blood film</bdi>: يأكد نقص الصفائح الحقيقي (يستبعد التجمع الكاذب)، يُظهر صفائح كبيرة، ويستبعد <bdi>blasts</bdi> أو خلايا دم حمراء مجزّأة (<bdi>HUS/TTP</bdi>) أو تشوهات صفائح تدل على سبب آخر.",
    ],
    "when_changes": [
        "لو ظهرت أعراض بخلايا دم أخرى (<bdi>blasts</bdi>، تضخم أعضاء، ألم عظمي)، الخطوة الجاية تصير <bdi>bone marrow aspiration</bdi>.",
        "لو فيه نزيف داخل المفاصل أو العضلات، نفكر بـ<bdi>coagulation disorder</bdi> ونطلب <bdi>coagulation profile</bdi>.",
    ],
    "rule": "نقص صفائح معزول = <bdi>blood film</bdi>؛ لو زاد عليه فقر دم أو خلل <bdi>WBC</bdi> أو <bdi>blasts</bdi>، يصير <bdi>bone marrow aspiration</bdi>.",
    "comparison": None,
    "labs": [["Platelet", "22", "150-450 x10^9/L"], ["WBC", "8", "4-11 x10^9/L"], ["Hb", "125 g/L", "طبيعي لعمر الطفل"]],
    "guideline_note": None,
},
"AS-1758": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "نفس صورة <bdi>ITP</bdi> بالطفلة السابقة، لكن هنا السؤال يحدد: ما هو الفحص <bdi>CONFIRMATORY</bdi> (المؤكِّد).",
    "clues": [
        ("after history of runny nose and flu symptoms", "عدوى فيروسية سابقة، نمط <bdi>ITP</bdi>"),
        ("Isolated thrombocytopenia", "باقي خطوط الدم طبيعية"),
        ("CONFIRMATORY", "يبي فحص يأكد التشخيص ويستبعد غيره"),
    ],
    "why_correct": [
        "<bdi>ITP</bdi> تشخيص استبعاد، والفحص المؤكِّد هو <bdi>blood film</bdi>: يأكد نقص الصفائح الحقيقي، يُظهر صفائح كبيرة، ويستبعد <bdi>blasts</bdi> أو خلايا مجزأة تدل على سبب آخر.",
        "صفائح 22 مع <bdi>WBC</bdi> و<bdi>Hb</bdi> طبيعيين مع قصة فيروسية سابقة تدعم <bdi>ITP</bdi> بقوة.",
    ],
    "when_changes": [
        "لو ظهرت خلايا <bdi>blasts</bdi> أو تضخم أعضاء، يصير الفحص المؤكِّد <bdi>bone marrow aspiration</bdi>.",
    ],
    "rule": "نقص صفائح معزول = <bdi>blood film</bdi> هو الفحص المؤكِّد/التشخيصي الأول.",
    "comparison": None,
    "labs": [["Platelet", "22", "150-450 x10^9/L"], ["WBC", "8", "4-11 x10^9/L"], ["Hb", "125 g/L", "طبيعي لعمر الطفل"]],
    "guideline_note": None,
},
"AS-1759": {
    "correct_letter": "A",
    "self_judged": True,
    "idea": "يرقان عند رضيع عمره 5 أيام بدون أي علامة غير طبيعية أخرى، والسؤال يبي التشخيص الأقرب.",
    "clues": [
        ("Isolated jaundice", "بدون أعراض عصبية أو جهازية أخرى"),
        ("5 days old", "ضمن نافذة <bdi>breastfeeding/breast milk jaundice</bdi>"),
        ("all other exam normal", "ينفي <bdi>kernicterus</bdi> اللي يحتاج علامات عصبية"),
    ],
    "why_correct": [
        "يرقان معزول بعمر 5 أيام مع فحص طبيعي تمامًا بدون علامات عصبية يناسب <bdi>breast milk jaundice</bdi> (أو <bdi>breastfeeding jaundice</bdi> المبكر).",
        "الفحص العصبي الطبيعي يستبعد <bdi>kernicterus</bdi> اللي يحتاج ترسب بيليروبين عالي جدًا مع علامات عصبية واضحة.",
    ],
    "when_changes": [
        "لو ظهرت علامات عصبية (خمول شديد، ارتخاء، تشنج) مع بيليروبين مرتفع جدًا، الجواب يصير <bdi>kernicterus</bdi>.",
        "لو استمر اليرقان أكثر من أسبوعين أو فيه بيليروبين مباشر مرتفع وبراز باهت، لازم نفكر بـ<bdi>biliary atresia</bdi> ونحقق.",
    ],
    "rule": "فحص عصبي طبيعي يستبعد <bdi>kernicterus</bdi>؛ يرقان أسبوع ١ لرضيع يرضع طبيعيًا وينمو جيد = <bdi>breast milk jaundice</bdi> يحتاج ملاحظة فقط.",
    "comparison": None,
    "labs": None,
    "guideline_note": "السؤال بلا جواب مؤكد من المصدر؛ اخترت <bdi>breast milk jaundice</bdi> لأن الفحص طبيعي تمامًا وهذا يستبعد <bdi>kernicterus</bdi> مباشرة.",
},
"AS-1776": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "رضيع بكسر عظمي وتأخر بطلب الرعاية، والسؤال يبي الإجراء الصحيح وهو علاج الطفل مع إبلاغ الجهات المختصة.",
    "clues": [
        ("11-month-old", "رضيع صغير، كسر بهذا العمر يرفع الشك"),
        ("right ulnar and radial fracture", "كسر عظم طويل برضيع"),
        ("2 days", "تأخر بطلب الرعاية"),
    ],
    "why_correct": [
        "رضيع عمره 11 شهر بكسر <bdi>radius</bdi> و<bdi>ulna</bdi>، أُحضر متأخر يومين، بتفسير لا يتطابق تمامًا، يرفع الشك بـ<bdi>non-accidental injury</bdi> حتى لو الطفل نظيف ومتابع بزياراته الدورية.",
        "دور الطبيب هو علاج الإصابة والإبلاغ عن القلق لجهات حماية الطفل، اللي تتولى التحقيق؛ الطبيب لا يحتاج دليل قاطع، فقط شك معقول.",
    ],
    "when_changes": [
        "لو كانت القصة والعمر والآلية متطابقة تمامًا بدون تأخير، نصدق الوالدين ونعالج فقط.",
        "لو فيه علامات عصبية أو الطفل رضيع جدًا، يصير التصوير الدماغي (<bdi>head CT</bdi>) جزء من التقييم.",
    ],
    "rule": "الشك كافٍ: نبلّغ جهات حماية الطفل مو الشرطة مباشرة، وأبدًا لا نصدّق الوالدين فقط بدون تقييم.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1780": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل بسعال مزمن منتج وتكرار دخول بالمستشفى، مع أخ بنفس الحالة ويرقان خلال فترة الولادة، والسؤال يبي الفحص التشخيصي لـ<bdi>cystic fibrosis</bdi>.",
    "clues": [
        ("chronic productive cough", "سعال منتج مزمن"),
        ("neonatal admission for jaundice", "يرقان مديد بالولادة، علامة مبكرة مرافقة لـ<bdi>CF</bdi>"),
        ("Brother has same condition", "وراثة <bdi>autosomal recessive</bdi>"),
    ],
    "why_correct": [
        "طفل بسعال منتج مزمن ودخول متكرر بصفير يحتاج مضادات حيوية، مع أخ بنفس الحالة (<bdi>autosomal recessive</bdi>) وتاريخ يرقان وليدي مديد (علامة <bdi>CF</bdi> مبكرة معروفة) يوجّه لـ<bdi>cystic fibrosis</bdi>.",
        "الفحص التشخيصي هو <bdi>sweat chloride test</bdi>.",
    ],
    "when_changes": [
        "لو السؤال يبي تقييم فشل تنفسي حاد، يصير الفحص <bdi>ABG</bdi>.",
        "لو يبي استبعاد عدوى أو فقر دم فقط، يصير الفحص <bdi>CBC</bdi>.",
    ],
    "rule": "سعال منتج مزمن + عدوى صدرية متكررة + أخ مصاب = فكّر <bdi>cystic fibrosis</bdi> والفحص هو <bdi>sweat chloride test</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1784": {
    "correct_letter": "C",
    "self_judged": True,
    "idea": "توقف نمو الطفل (<bdi>plateauing</bdi>) بعد البدء بالأكل الصلب عند 6 شهور، والسؤال يبي الطعام الممنوع.",
    "clues": [
        ("Weight chart", "يوضح توقف الزيادة بالوزن"),
        ("plateauing after six month", "توقف يترافق مع بدء الأكل الصلب، نافذة إدخال الحبوب"),
    ],
    "why_correct": [
        "توقف الزيادة بالوزن بعد إدخال الأكل الصلب (عادة الحبوب) بعمر 6 شهور هو نمط كلاسيكي لـ<bdi>celiac disease</bdi>، فالطعام الممنوع هو <bdi>gluten</bdi> (قمح، شعير، شيلم).",
    ],
    "when_changes": [
        "لو كان توقف النمو مرتبط ببدء الحليب الصناعي أو منتجات الألبان مع دم بالبراز أو إكزيما، الجواب يصير <bdi>cow's milk protein allergy</bdi> ونمنع بروتين الحليب.",
        "لو الوزن فقط ينخفض والطول محفوظ، الصورة تميل لـ<bdi>malabsorptive failure to thrive</bdi> عام.",
    ],
    "rule": "توقف النمو بعد إدخال الحبوب = فكّر <bdi>celiac disease</bdi> وامنع <bdi>gluten</bdi>؛ لا نوقف <bdi>gluten</bdi> قبل الفحص لأنه يعطي نتيجة سلبية كاذبة.",
    "comparison": None,
    "labs": None,
    "guideline_note": "السؤال بلا جواب مؤكد من المصدر؛ اخترت <bdi>gluten</bdi> لأن توقيت التوقف بعد إدخال الأكل الصلب يطابق نمط <bdi>celiac disease</bdi> الكلاسيكي.",
},
"AS-1786": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "مولود بعد عملية قيصرية بضيق تنفس خفيف وصورة أشعة توضح سائل بالشق الرئوي، وهذا <bdi>TTN</bdi>، والسؤال يبي الخطوة الجاية.",
    "clues": [
        ("after CS", "ولادة قيصرية ترفع خطر <bdi>TTN</bdi>"),
        ("without desaturating", "الحالة خفيفة وليست خطيرة"),
        ("fluid in the lung fissure", "علامة أشعة كلاسيكية لـ<bdi>TTN</bdi>"),
    ],
    "why_correct": [
        "مولود بعد عملية قيصرية بضيق تنفس و\"سائل بالشق الرئوي\" بالأشعة هو <bdi>transient tachypnea of the newborn (TTN)</bdi>، الناتج من تأخر تصريف سائل الرئة الجنيني.",
        "<bdi>TTN</bdi> يُشفى تلقائيًا، فالعلاج داعم: أكسجين بتركيز منخفض (30-40%) مع المراقبة لحين يتصرّف السائل خلال الأيام الأولى.",
    ],
    "when_changes": [
        "لو كان المولود خدّيج بصورة أشعة <bdi>ground glass</bdi> منتشرة، الجواب يصير <bdi>RDS</bdi> ويحتاج <bdi>surfactant</bdi>.",
        "لو ازدادت الحالة سوءًا أو طالت، لازم نعيد النظر بتشخيصات أخرى مثل <bdi>pneumonia</bdi> أو <bdi>PPHN</bdi>.",
    ],
    "rule": "خدّيج بأشعة <bdi>ground glass</bdi> = <bdi>RDS</bdi> (<bdi>surfactant</bdi>)؛ مولود مكتمل بعد قيصرية بسائل بالشق = <bdi>TTN</bdi> (أكسجين داعم فقط).",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1789": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "السؤال يبي الفحص الأكثر تشخيصًا لـ<bdi>renal scarring</bdi> عند الأطفال.",
    "clues": [
        ("renal scarring", "يحدد نوع الفحص المطلوب (تصوير وظيفي لونسيج الكلى)"),
    ],
    "why_correct": [
        "<bdi>DMSA</bdi> فحص تصوير ثابت (<bdi>static cortical scan</bdi>): المادة المشعة ترتبط بخلايا الأنابيب القريبة الوظيفية، فتظهر الندبات كعيوب بالقشرة.",
        "هو الفحص الأكثر حساسية وتشخيصًا لـ<bdi>renal scarring</bdi> (مثلًا بعد <bdi>pyelonephritis</bdi> مع <bdi>VUR</bdi>).",
    ],
    "when_changes": [
        "لو السؤال يبي الفحص الأولي بعد عدوى بولية حموية، الجواب يصير <bdi>ultrasound</bdi>.",
        "لو السؤال يبي فحص التصريف أو الانسداد، الجواب يصير <bdi>MAG3 scan</bdi>.",
        "لو السؤال يبي فحص الارتجاع (<bdi>VUR</bdi>)، الجواب يصير <bdi>MCUG/VCUG</bdi>.",
    ],
    "rule": "ندبة = <bdi>DMSA</bdi> (ثابت)؛ تصريف أو انسداد = <bdi>MAG3</bdi> (ديناميكي)؛ ارتجاع = <bdi>MCUG</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1792": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بيرقان حاد مع ارتفاع إنزيمات الكبد جدًا، والسؤال يبي تشخيص الالتهاب الكبدي الحاد.",
    "clues": [
        ("yellow discoloration of the sclera", "يرقان عيني"),
        ("anorexia and abdominal pain", "أعراض التهاب كبدي حاد"),
        ("Alanine aminotransferase 878", "ارتفاع شديد بإنزيمات خلايا الكبد"),
        ("Aspartate aminotransferase 1005", "ارتفاع شديد بإنزيمات خلايا الكبد"),
    ],
    "why_correct": [
        "طفل عمره 10 سنين بـ3 أيام من يرقان عيني وفقدان شهية وألم بطني، مع إنزيمات كبد قريبة أو أعلى من 1000 (<bdi>ALT</bdi> 878، <bdi>AST</bdi> 1005)، هذا تلف خلايا كبدية حاد (<bdi>hepatocellular injury</bdi>)، وعند الأطفال أشهر سبب هو التهاب كبد فيروسي حاد، كلاسيكيًا <bdi>hepatitis A</bdi>.",
        "ارتفاع البيليروبين بجزء مباشر وغير مباشر مع <bdi>albumin</bdi> و<bdi>total protein</bdi> طبيعيين يناسب حالة حادة مو مزمنة.",
    ],
    "when_changes": [
        "لو كانت إنزيمات الكبد طبيعية مع بيليروبين غير مباشر معزول فقط، الجواب يصير <bdi>Gilbert syndrome</bdi>.",
        "لو كان <bdi>ALP</bdi> و<bdi>GGT</bdi> مرتفعين مع بيليروبين مباشر بشكل أساسي وبراز باهت، الجواب يصير <bdi>obstructive jaundice</bdi>.",
    ],
    "rule": "إنزيمات كبد قريبة من 1000 تعني التهاب كبدي (<bdi>hepatitis</bdi>)، مو انسداد ولا <bdi>Gilbert</bdi>، بغض النظر عن نسبة البيليروبين.",
    "comparison": None,
    "labs": [
        ["Indirect bilirubin", "140 mol/L", "أقل من 19"],
        ["Total bilirubin", "260 mol/L", "أقل من 20.5"],
        ["Albumin", "40 g/L", "36-52"],
        ["Total Proteins", "76 g/L", "56-80"],
        ["ALT", "878 U/L", "10-35"],
        ["AST", "1005 IU/L", "12-40"],
    ],
    "guideline_note": None,
},
"AS-1795": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل عنده رد فعل خطير على لقاح الإنفلونزا سابقًا، والسؤال يبي الخطة المستقبلية الصحيحة.",
    "clues": [
        ("Influenza vaccine", "اللقاح المسبب لرد الفعل"),
        ("flushing, SYNCOPE", "صورة رد فعل خطير شبيه بالتحسس (<bdi>anaphylactic type</bdi>)"),
    ],
    "why_correct": [
        "الاحمرار (<bdi>flushing</bdi>) مع فقدان الوعي (<bdi>syncope</bdi>) بعد لقاح الإنفلونزا يُقرأ كرد فعل خطير (شبيه بالتحسس) لذاك اللقاح.",
        "رد فعل تحسسي خطير لجرعة سابقة من لقاح يُعتبر منع مطلق (<bdi>absolute contraindication</bdi>) لجرعات مستقبلية من نفس اللقاح، فلا يُعطى لقاح الإنفلونزا مرة ثانية، بينما باقي الجدول يستمر طبيعي.",
    ],
    "when_changes": [
        "لو كان مجرد إغماء بسيط لحظي بعد الحقن (<bdi>vasovagal</bdi>) بدون احمرار أو رد فعل تحسسي، هذا مو منع، ونعطي اللقاح بشكل طبيعي.",
        "لو كان تحسس بيض خفيف فقط، اللقاح غير الحي يُعطى بدون أي تحضير مسبق.",
    ],
    "rule": "رد فعل تحسسي خطير لجرعة سابقة = منع مطلق لنفس اللقاح فقط، لا نوقف كل اللقاحات ولا نجرب تحضير مسبق.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1799": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل بـ<bdi>dilated cardiomyopathy</bdi> معروف يجي بأعراض احتقان رئوي، والسؤال يبي العلاج الأول وهو مدر بول.",
    "clues": [
        ("dilated CMP", "قلب ضعيف معروف"),
        ("pulmonary edema", "احتقان رئوي، يحتاج تفريغ سوائل"),
    ],
    "why_correct": [
        "طفل بـ<bdi>dilated cardiomyopathy</bdi> معروف يجي بضيق تنفس وألم صدري و(حسب السؤال) احتقان رئوي بالأشعة، هذا <bdi>acute decompensated heart failure</bdi> مع زيادة سوائل، وقد يكون محفَّز بالحمى.",
        "العلاج الأول للاحتقان هو مدر بول من نوع <bdi>loop diuretic</bdi> وهو <bdi>furosemide</bdi>، مع الأكسجين، لتخفيف السوائل عن الرئتين وتحسين ضيق التنفس.",
    ],
    "when_changes": [
        "لو كان الطفل بصدمة قلبية (<bdi>cold and wet</bdi>، ضغط منخفض وسوء تروية)، يُضاف مقوي للقلب مثل <bdi>dobutamine</bdi> أو <bdi>milrinone</bdi>.",
        "لو كان توقف قلب أو صدمة تحسسية، يصير العلاج <bdi>epinephrine</bdi>.",
    ],
    "rule": "محتقن ومتروّى بشكل جيد = <bdi>furosemide</bdi> + أكسجين؛ محتقن وصادم (سوء تروية) = نضيف مقوي قلب.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1802": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "رضيع بكيتونات موجبة ورائحة مميزة وسكر منخفض وتشنج، والسؤال يبي تشخيص خلل استقلابي، وهو <bdi>maple syrup urine disease</bdi>.",
    "clues": [
        ("Ketone positive", "جزء من صورة <bdi>MSUD</bdi>"),
        ("Characteristic odor", "رائحة شراب القيقب المميزة"),
        ("Hypoglycemia", "تستبعد <bdi>DKA</bdi>"),
    ],
    "why_correct": [
        "\"Marble urine syndrome\" هي تسمية الاستدعاء لمرض <bdi>maple syrup urine disease (MSUD)</bdi>، خلل باستقلاب الأحماض الأمينية المتفرعة (<bdi>leucine</bdi>، <bdi>isoleucine</bdi>، <bdi>valine</bdi>).",
        "التركيبة المفتاحية هي كيتونات موجبة + رائحة مميزة (حلوة، شبيه بشراب القيقب) + سكر منخفض + تشنج، عادة برضيع بعد بدء الرضعات مع ضعف تغذية وتقيؤ واعتلال وعي.",
    ],
    "when_changes": [
        "لو كان السكر مرتفعًا مع عطش وتبول زائد وحمض، الجواب يصير <bdi>DKA</bdi> مو <bdi>MSUD</bdi>.",
        "لو جاءت الأعراض بعد الرضعات الحليبية مع يرقان وتضخم كبد وعتامة عدسة العين، الجواب يصير <bdi>galactosemia</bdi>.",
    ],
    "rule": "كيتونات مع سكر منخفض ورائحة بول حلوة = <bdi>MSUD</bdi>، مو <bdi>DKA</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1814": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بعمر 4 سنين يبلل بالليل، وهذا ضمن المعدل الطبيعي، والسؤال يبي الخطوة الصحيحة.",
    "clues": [
        ("4yo", "عمر أصغر من حد <bdi>enuresis</bdi> السريري (6 سنين)"),
        ("nocturia", "يعني تبليل ليلي عند الأطفال"),
    ],
    "why_correct": [
        "طفل عمره 4 سنين يبلل ليلًا ضمن المعدل الطبيعي: الجفاف الليلي آخر مهارة تحكم تُكتسب، والتبليل الليلي لا يُعتبر <bdi>enuresis</bdi> سريري قبل عمر 6 سنين تقريبًا.",
        "الخطوة الصحيحة هي التطمين مع تعزيز عادات دخول الحمام (تبول نهاري منتظم، تبول قبل النوم، تقليل السوائل مساءً، تشجيع إيجابي بدون عقاب).",
    ],
    "when_changes": [
        "لو كان الطفل عمره 6 سنين فأكثر، يصير التبليل الليلي <bdi>nocturnal enuresis</bdi> ونبدأ بتحليل بول ثم جهاز منبّه (<bdi>alarm</bdi>) كخط أول.",
        "لو فيه علامات خطر مثل تبليل نهاري، عدوى بولية متكررة، أو تبول زائد، يصير التحويل لـ<bdi>urology</bdi>.",
    ],
    "rule": "العمر يحدد القرار: طفل عمره 4 سنين = تطمين وعادات؛ طفل أكبر من 6 سنين = منبّه التبول (<bdi>alarm</bdi>) كخط أول.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1816": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "سؤال معالم تطور (<bdi>developmental milestones</bdi>)، والمطلوب تحديد العمر الأقرب حسب المهارات المذكورة.",
    "clues": [
        ("walk backwards", "مهارة حركية مبكرة بعد المشي"),
        ("Follow simple commands", "مهارة لغوية تظهر حوالي 15 شهر"),
        ("using a spoon", "بداية استخدام الملعقة"),
        ("Pointing to things", "إشارة للاهتمام، مهارة 15 شهر"),
    ],
    "why_correct": [
        "\"يتبع أوامر بسيطة\" و\"يشير للأشياء اللي تهمه\" مهارات عمر 15 شهر، والمشي المبكر مع المشي للخلف وبداية استخدام الملعقة (بداية فقط مو احترافي) تناسب نفس المرحلة.",
        "لا توجد علامة عمر 18 شهر (جري، سكب حبيبات، 6-10 كلمات)، فالعمر المتوقع هو 15 شهر.",
    ],
    "when_changes": [
        "لو أُضيف الجري أو سكب الحبيبات أو 6-10 كلمات، الجواب يقفز لـ18 شهر.",
        "لو السؤال أضاف صعود السلم وكلام بجملتين، الجواب يصير 24 شهر.",
    ],
    "rule": "نجاوب بأعلى معلم تطوري واضح أن الطفل حققه؛ أمر بسيط + إشارة اهتمام = 15 شهر.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1821": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "رضيع بنزيف نشط بعد الختان مع <bdi>PTT</bdi> مرتفع، والسؤال يبي الخطوة الأولى: السيطرة الموضعية على النزيف.",
    "clues": [
        ("after circumcision", "موقع النزيف معروف وموضعي"),
        ("5-hours of bleeding", "نزيف فعّال ومستمر"),
        ("high PTT", "يرمز لخلل تخثر كامن (<bdi>hemophilia</bdi> مثلًا)"),
    ],
    "why_correct": [
        "رضيع عمره 10 أيام بنزيف مستمر 5 ساعات بعد الختان يحتاج سيطرة موضعية فورية على النزيف: ضغط مباشر وثابت على موقع العملية.",
        "<bdi>high PTT</bdi> يرمز لخلل تخثر كامن (<bdi>hemophilia</bdi>، أو نقص <bdi>vitamin K</bdi> لو لم يُعطَ)، يُشخَّص ويُصحَّح بعد السيطرة على النزيف، لكن الضغط يجي أولًا.",
    ],
    "when_changes": [
        "لو استمر النزيف رغم الضغط مع تحليل تخثر طبيعي، الجواب يصير استكشاف جراحي (مصدر وعائي جراحي).",
        "لو تأكد نقص عامل تخثر محدد، نعطي العامل المناسب كتصحيح نهائي.",
    ],
    "rule": "نزيف موضعي حاد = ضغط مباشر أولًا دائمًا، قبل أي تدخل جراحي أو تصحيح دوائي.",
    "comparison": None,
    "labs": [["PTT", "مرتفع", "طبيعي حسب المختبر"]],
    "guideline_note": None,
},
"AS-1838": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفل بكتلة رقبية كبيرة فيها سائل لمفاوي صافٍ، وهذا <bdi>cystic hygroma</bdi>، والسؤال يبي العلاج الأنسب لكتلة كبيرة.",
    "clues": [
        ("large neck swelling", "كتلة كبيرة بالرقبة"),
        ("clear lymphatic fluid", "علامة <bdi>cystic hygroma</bdi> الحميدة"),
    ],
    "why_correct": [
        "كتلة رقبية جانبية كبيرة (10 سم) بسائل لمفاوي صافٍ عند الشفط هي <bdi>cystic hygroma</bdi> (تشوه لمفاوي <bdi>macrocystic</bdi>)، وهو حميد.",
        "الهدف إزالة أو استئصال التشوه؛ ومن بين الخيارات المذكورة الجراحة فقط تعالجه، والاستئصال خيار نهائي لكتلة بهذا الحجم.",
    ],
    "when_changes": [
        "لو كانت الكتلة صغيرة أو <bdi>macrocystic</bdi> بدون أعراض ضغط، قد نبدأ بـ<bdi>sclerotherapy</bdi> قبل الجراحة.",
        "لو كانت الكتلة صلبة وثابتة مع أعراض جهازية، نفكر بورم خبيث ونطلب خزعة.",
    ],
    "rule": "سائل لمفاوي صافٍ بكتلة رقبية جانبية = <bdi>cystic hygroma</bdi>؛ كتلة كبيرة = استئصال جراحي نهائي.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
}

WHY_WRONG = {
"AS-1679": {
    "A": "تعليم الأم عن العادات الغذائية جزء من الإدارة لكنه يجي بعد تأكيد النتيجة واستبعاد الأسباب الثانوية، مو من أول نتيجة.",
    "C": "التحويل لعيادة القلب يكون بعد تأكيد <bdi>LDL</bdi> عالي جدًا أو <bdi>familial hypercholesterolemia</bdi>، وهذا سابق لأوانه هنا.",
},
"AS-1680": {
    "A": "تعليم العادات الغذائية جزء من إدارة كل طفل بخلل شحوم، لكنه يجي بعد تأكيد النتيجة واستبعاد الأسباب الثانوية، و<bdi>diet</bdi> وحده غير كافٍ لـ<bdi>LDL</bdi> عالي بهذا القدر.",
    "C": "التحويل لعيادة القلب يكون صحيحًا بعد تأكيد <bdi>familial hypercholesterolemia</bdi> أو استمرار <bdi>LDL</bdi> عالي جدًا بعد <bdi>diet</bdi>؛ سابق لأوانه هنا على نتيجة واحدة غير مؤكدة.",
},
"AS-1682": {
    "A": "<bdi>NGT</bdi> يُستخدم لتفريغ المعدة لكنه غير مطلوب بشكل روتيني وليس الخطوة الأولى المعرّفة؛ يُحفظ للتقيؤ المستمر أو انتفاخ المعدة.",
    "C": "<bdi>Bicarbonate</bdi> يزيد <bdi>metabolic alkalosis</bdi> الموجود أصلًا؛ السائل الصحيح هو <bdi>0.9% saline</bdi>.",
    "D": "<bdi>Ultrasound</bdi> هو أول فحص لتأكيد التشخيص، لكن السؤال يقول التشخيص تأكد مسبقًا، فالتصوير مو الخطوة الجاية.",
},
"AS-1704": {
    "A": "<bdi>Scarlet fever</bdi> تعطي طفح كصنفرة مع لسان توتي بعد التهاب حلق <bdi>streptococcal</bdi>، لكن بدون التهاب ملتحمة أو شفاه متشققة، والحمى تخف سريعًا مع البنسلين.",
    "C": "<bdi>Rocky Mountain spotted fever</bdi> تجي بعد لدغة قرادة وتعطي طفح نقطي من الرسغين والكاحلين منتشر للداخل؛ مو شائع هنا وما يشمل الشفاه والعقد بهذا الشكل.",
},
"AS-1705": {
    "A": "<bdi>UTI</bdi> سفلي عادةً يعطي <bdi>dysuria</bdi> و<bdi>frequency</bdi> بدون الحمى العالية والألم البطني بهذا الوضوح.",
    "B": "<bdi>glomerulonephritis</bdi> يحتاج علامات نفريتية مثل <bdi>edema</bdi> و<bdi>hypertension</bdi> و<bdi>RBC casts</bdi> وتاريخ عدوى <bdi>strep</bdi> سابقة، وغير مذكورة هنا.",
},
"AS-1711": {
    "B": "<bdi>DKA</bdi> تعطي نفس رائحة <bdi>acetone</bdi> و<bdi>Kussmaul breathing</bdi> وبول وعطش زائد مع سكر وكيتونات عالية؛ لا تسبب <bdi>miosis</bdi> أو سيلان لعاب أو تشنج قصبي.",
    "C": "<bdi>cyanide</bdi> يسبب رائحة لوز مرير وانهيار مفاجئ وتشنجات مع حمض لبني شديد وجلد وردي؛ لا توجد صورة كولينرجية.",
    "D": "<bdi>cocaine</bdi> دواء <bdi>sympathomimetic</bdi>: توسع حدقة وتسرع قلب وارتفاع ضغط وحرارة وهياج؛ العرق موجود لكن الحدقة متوسعة مو متضيّقة.",
},
"AS-1713": {
    "B": "تحويل القلب يكون لعلامات مرضية: درجة ≥3 أو <bdi>thrill</bdi> أو مكون انبساطي أو أعراض أو نفخة لا تتغير بالوضعية.",
    "C": "الوقاية بالمضادات قبل أسنان تكون فقط لعيوب قلبية عالية الخطورة؛ نفخة بريئة لا تحتاج أي وقاية.",
    "D": "تأجيل الجراحة يكون صحيحًا لنفخة مرضية جديدة أو مرض حموي حاد؛ نفخة وضعية بطفل سليم لا تستدعي تأخير.",
},
"AS-1716": {
    "A": "كسر الرسغ البعيد شائع عرضيًا؛ كسور <bdi>abuse</bdi> المحددة هي <bdi>metaphyseal corner</bdi> وكسور الضلع الخلفية وكسور متعددة الأعمار أو كسور بطفل لا يمشي.",
    "C": "قصة متسقة من الوالدين تقلل الشك بـ<bdi>abuse</bdi>؛ القصة المتغيرة أو غير المنطقية هي اللي ترفع الشك.",
    "D": "طفل نظيف وملابسه جيدة يقلل الشك بالإهمال لكنه لا يستبعد الإيذاء الجسدي؛ المظهر وحده ليس علامة هنا.",
},
"AS-1726": {
    "A": "<bdi>Scleroderma</bdi> تسبب تصلب الجلد (<bdi>sclerodactyly</bdi>) و<bdi>Raynaud</bdi> وبقع <bdi>morphea</bdi>؛ لا تعطي <bdi>heliotrope rash</bdi> أو <bdi>Gottron papules</bdi> مع اعتلال عضلي قريب.",
    "B": "<bdi>SLE</bdi> تعطي طفح وجنتين يتجنب الثنايا الأنفية الشفوية وقرحات فمية وألم مفاصل ونقص خلايا دم أو التهاب كلوي؛ الاعتلال العضلي قد يحدث لكن <bdi>heliotrope</bdi> و<bdi>Gottron</bdi> توجّه لـ<bdi>dermatomyositis</bdi>.",
    "D": "<bdi>Rheumatic fever</bdi> تجي بعد التهاب حلق <bdi>streptococcal</bdi> مع التهاب قلب وألم مفاصل متنقل وحركات لا إرادية وعقد تحت الجلد؛ لا يوجد اعتلال عضلي أو طفح جفني.",
},
"AS-1728": {
    "A": "لقاح <bdi>Hemophilus</bdi> يمنع <bdi>epiglottitis</bdi>: بداية مفاجئة بساعات، حمى عالية، طفل متعب، سيلان لعاب، وضعية <bdi>tripod</bdi> وصفير، بدون <bdi>URTI</bdi> سابق أو تضخم عقد واضح.",
    "B": "لا يوجد لقاح ضد <bdi>group A streptococcus</bdi>، ولقاح <bdi>pneumococcal</bdi> لا يمنع هذي الصورة؛ التهاب الحلق أو العقد الـ<bdi>streptococcal</bdi> مو الجواب هنا.",
    "D": "<bdi>Polio</bdi> يعطي حمى ثم شلل رخو غير متماثل؛ لا يسبب انسداد بلعومي مع سيلان لعاب وتضخم عقد.",
},
"AS-1734": {
    "A": "نقص <bdi>vitamin A</bdi> يسبب عمى ليلي و<bdi>xerophthalmia</bdi> وبقع <bdi>Bitot</bdi>، مو تشوه عظمي؛ يكون الجواب الصحيح عند وجود أعراض عينية أو حصبة تحتاج مكمّل، مو تقوّس الساقين وانخماص الصدر.",
},
"AS-1743": {
    "B": "<bdi>Type 2 DM</bdi>: مقاومة أنسولين مع <bdi>C-peptide</bdi> طبيعي أو مرتفع، عادة بمراهق سمين مع <bdi>acanthosis nigricans</bdi>؛ <bdi>C-peptide</bdi> المنخفض هنا يعاكس هذا التشخيص.",
    "C": "<bdi>MODY</bdi>: وراثة سائدة مع سكري بأجيال متتالية، ارتفاع سكر خفيف و<bdi>C-peptide</bdi> محفوظ بدون أجسام مضادة؛ يصح عند تاريخ عائلي قوي متعدد الأجيال و<bdi>C-peptide</bdi> موجود.",
    "D": "ارتفاع السكر الناتج عن الضغط النفسي/المرضي: سكر عالي مؤقت وقت مرض حاد مع <bdi>HbA1c</bdi> طبيعي لأنه لا يعكس 3 شهور من ارتفاع السكر؛ هنا <bdi>HbA1c</bdi> مرتفع أصلًا مع أعراض عطش وتبول واضحة.",
},
"AS-1755": {
    "A": "بنسلين مع ريفامبين أسبوع: البنسلين لا يزيل الحمل بالأنف، وريفامبين مدته يومان فقط مو أسبوع؛ يصح لو ذُكر ريفامبين يومين فقط كخيار منفرد.",
    "C": "بنسلين أسبوع: البنسلين يعالج المرض الغازي لكنه لا يزيل الحمل، فهو ليس صحيحًا أبدًا كوقاية لمقربين.",
    "D": "<bdi>ceftriaxone</bdi> 4 جرعات بالعضل: <bdi>ceftriaxone</bdi> فعلًا دواء وقائي صحيح (مفضّل بالحمل) لكن كجرعة واحدة فقط؛ جرعات متعددة نظام علاج مو وقاية.",
},
"AS-1756": {
    "A": "<bdi>Sotos syndrome</bdi>: متلازمة فرط نمو بقامة طويلة ورأس كبير ونضج عظمي متقدم؛ يصح لو كان الطفل طويلًا وبرأس كبير، مو قصير برقبة بها زوائد.",
    "B": "<bdi>Turner syndrome</bdi>: 45,X تصيب البنات فقط مع رقبة بزوائد وقصر قامة وتأخر بلوغ و<bdi>coarctation</bdi> أو صمام أبهري ثنائي؛ يصح لو كانت المريضة بنت؛ الذكورة هنا تستبعدها.",
    "C": "<bdi>Marfan syndrome</bdi>: طويل، نحيف، أطراف طويلة، <bdi>arachnodactyly</bdi>، خلع عدسة وتوسع جذر الأبهر؛ يصح مع قامة طويلة وخلع عدسة، عكس هذا الطفل القصير.",
},
"AS-1757": {
    "A": "تحليل التخثر (<bdi>PT/aPTT</bdi>) طبيعي في <bdi>ITP</bdi> لأن الخلل بعدد الصفائح مو بعوامل التخثر؛ يصح عند نزيف بالمفاصل أو العضلات (<bdi>hemophilia</bdi>) أو اشتباه <bdi>DIC</bdi>.",
    "B": "<bdi>BM aspiration</bdi> غير مطلوب إذا كانت الصفائح فقط منخفضة والمسحة طبيعية؛ يصح عند خلل بخلايا دم أخرى أو <bdi>blasts</bdi> أو ألم عظمي أو تضخم أعضاء (اشتباه لوكيميا أو فشل نقي).",
    "D": "الأجسام المضادة للصفائح غير حساسة ولا نوعية، فلا تؤكد أو تستبعد <bdi>ITP</bdi> وليست جزءًا من الفحص الروتيني.",
},
"AS-1758": {
    "A": "تحليل التخثر طبيعي في <bdi>ITP</bdi> لأن الخلل بعدد الصفائح مو عوامل التخثر؛ يصح عند نزيف بالمفاصل أو اشتباه <bdi>DIC</bdi>.",
    "B": "<bdi>BM aspiration</bdi> غير مطلوب إذا كانت الصفائح فقط منخفضة والمسحة طبيعية؛ يصح عند خلل خلايا أخرى أو <bdi>blasts</bdi>.",
    "D": "الأجسام المضادة للصفائح غير حساسة ولا نوعية، فلا تؤكد <bdi>ITP</bdi> كفحص مؤكِّد.",
},
"AS-1776": {
    "B": "تصديق الوالدين وعلاج الطفل يتجاهل علامات الخطر (تأخر العرض، كسر عظم طويل برضيع) وقد يرجع الطفل لبيئة خطرة؛ يصح فقط لو الآلية والعمر والتوقيت متطابقين تمامًا.",
    "C": "التصوير الدماغي يكون عند اشتباه إيذاء مع علامات عصبية أو برضيع صغير جدًا؛ هذا الطفل بلا علامات دماغية، والخطوة المطلوبة قانونيًا وأخلاقيًا هي الإبلاغ.",
    "D": "الاتصال بالشرطة مباشرة يتجاوز فريق حماية الطفل بالمستشفى اللي يتولى الإبلاغ ويحوّل للشرطة لو احتاج الأمر؛ يصح فقط لو الطفل بخطر فوري بموقع العنف.",
},
"AS-1780": {
    "A": "<bdi>CBC</bdi> قد يظهر عدوى لكنه غير نوعي ولا يشخّص سبب العدوى الصدرية المتكررة الأساسي.",
    "B": "<bdi>ABG</bdi> يقيّم فشل تنفسي حاد أو توازن حمضي قاعدي، مو سبب المرض الرئوي المزمن.",
},
"AS-1784": {
    "A": "البروتين ليس الطعام المرتبط بتوقف النمو بعد إدخال الحبوب؛ لا يوجد نمط سريري يربطه بهذا التوقيت.",
    "B": "الدهون ليست المحرك المعتاد لتوقف النمو بعد إدخال الأكل الصلب بهذا التوقيت المرتبط بالحبوب.",
},
"AS-1786": {
    "A": "السائل الوريدي لا يعالج سائل الرئة المحتجز؛ يُستخدم فقط لو كان الرضيع متسرع تنفس بشدة لدرجة تمنعه من الرضاعة الآمنة، وزيادة السوائل قد تزيد الحالة سوءًا.",
    "C": "الأشعة سُويت مسبقًا وأظهرت العلامة الكلاسيكية لـ<bdi>TTN</bdi>؛ تكرارها لا يضيف شيء إلا لو تدهورت الحالة.",
},
"AS-1789": {
    "A": "<bdi>Ultrasound</bdi> فحص أولي غير جراحي (الحجم، التوسع، التركيب) لكنه يفوّت كثير من الندبات القشرية؛ يصح كتصوير أولي بعد عدوى بولية حموية، مو كأكثر فحص تشخيصي للندبة.",
    "B": "<bdi>MAG3</bdi> فحص ديناميكي (<bdi>renogram</bdi>) للتصريف والانسداد والوظيفة النسبية؛ يصح باشتباه انسداد مثل <bdi>PUJ obstruction</bdi>، مو لندبات القشرة.",
},
"AS-1792": {
    "A": "<bdi>Gilbert syndrome</bdi> يعطي ارتفاع بيليروبين غير مباشر معزول خفيف مع إنزيمات كبد طبيعية، غالبًا يُحرَّض بالصيام أو المرض؛ إنزيمات بالآلاف تستبعده.",
    "C": "<bdi>obstructive jaundice</bdi> يعطي بيليروبين مباشر غالبًا مع <bdi>ALP</bdi> و<bdi>GGT</bdi> مرتفعين وارتفاع متواضع بإنزيمات الكبد، غالبًا مع براز باهت وبول غامق؛ إنزيمات بالآلاف توجّه لخلايا الكبد مباشرة.",
    "D": "<bdi>acute pancreatitis</bdi> يعطي ألم شرسوفي ينتشر للظهر مع ارتفاع <bdi>lipase</bdi> أو <bdi>amylase</bdi>؛ يرقان مع إنزيمات كبد قريبة من 1000 ليس صورته.",
},
"AS-1795": {
    "A": "منع كل اللقاحات مستقبلًا غلط: رد فعل لقاح واحد يمنع فقط ذاك اللقاح (أو مكوّن مشترك)، مو كل الجدول.",
    "B": "اللقاح داخل الأنف لا يزال لقاح إنفلونزا بمكونات متشابهة، فرد الفعل الخطير يمنعه هو كذلك.",
    "C": "التحضير المسبق بمضاد هيستامين وستيرويد لا يجعل إعادة إعطاء لقاح تسبب برد فعل خطير أمرًا آمنًا؛ التحضير المسبق غير مطلوب أصلًا لرد فعل خفيف أو تحسس بيض خفيف.",
},
"AS-1799": {
    "A": "<bdi>Epinephrine</bdi> لصدمة تحسسية أو توقف قلب أو صدمة مقاومة؛ يرفع احتياج عضلة القلب للأكسجين ولا يعالج احتقان رئوي بطفل متروّى جيد.",
    "B": "<bdi>Dobutamine</bdi> مقوي قلب لحالات انخفاض النتاج القلبي أو الصدمة القلبية (ضغط منخفض وسوء تروية)؛ السيناريو يصف احتقان مو صدمة.",
    "C": "<bdi>Milrinone</bdi> كذلك مخصص لحالات انخفاض النتاج، غالبًا بالعناية المركزة؛ ليس الخطوة الأولى لاحتقان رئوي مع تروية جيدة.",
},
"AS-1802": {
    "A": "<bdi>DKA</bdi> يعطي كيتونات ورائحة فاكهية أيضًا لكن مع سكر مرتفع وعطش وتبول زائد وحمض؛ نقص السكر هنا يستبعده.",
    "C": "<bdi>galactosemia</bdi> يظهر بعد الرضعات الحليبية بيرقان وتضخم كبد وتقيؤ وعتامة عدسة وعدوى <bdi>E. coli</bdi>، مع نقص سكر ومواد مختزلة بالبول؛ لا توجد رائحة مميزة.",
    "D": "عدم تحمل الفركتوز الوراثي يظهر عند إدخال الفركتوز أو السكروز (فاكهة، عصير) بالفطام، بتقيؤ ونقص سكر وتضخم كبد؛ بلا رائحة مميزة وغير مناسب لرضيع يرضع حليب فقط.",
},
"AS-1814": {
    "A": "تأجيل تدريب التبول حتى عمر 6 خطأ؛ يجب استمرار عادات التبول الطبيعية، وعمر 6 هو فقط حد تسمية التبليل الليلي <bdi>enuresis</bdi>، مو بدء التدريب.",
    "C": "التحويل لـ<bdi>urology</bdi> يكون لعلامات خطر: تبليل نهاري، تبليل ثانوي بعد فترة جفاف، عدوى بولية متكررة، ضعف تيار البول أو تبول زائد؛ لا شيء من هذا مذكور.",
    "D": "جهاز المنبّه علاج لـ<bdi>enuresis</bdi> المؤسس بطفل بعمر المدرسة متحمس للتعاون (بعد عمر 6)، مو لطفل طبيعي عمره 4 سنين.",
},
"AS-1816": {
    "A": "عمر 18 شهر يحتاج علامات مثل الجري أو سكب حبيبات من زجاجة أو مفردات 6-10 كلمات، وهذا غير مذكور.",
    "C": "عمر 24 شهر يُظهر صعود السلم ورفص كرة وجمل من كلمتين؛ هذا الطفل يُظهر فقط مهارات مرحلة مبكرة.",
    "D": "عمر 48 شهر أبعد بكثير: طفل عمره 4 سنين يقفز ويحكي قصص ويتكلم بجمل كاملة.",
},
"AS-1821": {
    "B": "استكشاف جراحي للنزيف المستمر رغم الضغط ومع تحليل تخثر طبيعي (وعاء جراحي)؛ مع <bdi>PTT</bdi> مرتفع، الجراحة قبل تصحيح خلل التخثر تزيد النزيف.",
    "D": "تطمين الوالدين غير أمن: نزيف مستمر 5 ساعات برضيع مع <bdi>PTT</bdi> مرتفع هو اضطراب تخثر حقيقي لحد ما يثبت العكس.",
},
"AS-1838": {
    "B": "الملاحظة غير مناسبة لكتلة كبيرة 10 سم تحمل خطر ضغط مجرى الهواء والعدوى والنزيف داخل الكيس؛ التراجع التلقائي نادر.",
    "C": "العلاج الكيميائي يُستخدم لأورام خبيثة (<bdi>lymphoma</bdi>، <bdi>rhabdomyosarcoma</bdi>)؛ سائل لمفاوي صافٍ يدل على تشوه حميد.",
    "D": "العلاج الإشعاعي ليس له دور بتشوه لمفاوي حميد عند طفل ويحمل خطر على النمو والسرطان لاحقًا.",
},
}

HIGHLIGHT_TERMS = {
"AS-1679": ["high LDL"],
"AS-1680": ["LDL 5 mmol", "low HDL", "growing normally"],
"AS-1682": ["projectile vomiting", "pyloric stenosis", "next step"],
"AS-1704": ["high fever", "6 days", "cracked red lips", "cervical lymphadenopathy", "red eyes"],
"AS-1705": ["red urine", "fever", "abdominal discomfort"],
"AS-1711": ["miosis", "excessive salivation", "garlic odour"],
"AS-1713": ["asymptomatic", "continuous murmur", "murmur disappears when the child is supine"],
"AS-1716": ["2 days ago"],
"AS-1726": ["heliotrope rash", "thickening of skin over metacarpophalangeal joints", "proximal muscle weakness"],
"AS-1728": ["URTI", "drooling of saliva", "did not receive any vaccine"],
"AS-1734": ["bowed legs", "Harrison sulcus", "rickets"],
"AS-1743": ["C-peptide 0.09 (low)"],
"AS-1755": ["meningococcal meningitis", "chemoprophylaxis", "close contacts"],
"AS-1756": ["short stature", "Webbed neck", "ejection murmurs"],
"AS-1757": ["after history of runny nose and flu symptoms", "Isolated thrombocytopenia", "Platelet 22"],
"AS-1758": ["after history of runny nose and flu symptoms", "Isolated thrombocytopenia", "Platelet 22", "CONFIRMATORY"],
"AS-1759": ["Isolated jaundice", "5 days old", "all other exam normal"],
"AS-1776": ["11-month-old", "right ulnar and radial fracture", "2 days"],
"AS-1780": ["chronic productive cough", "neonatal admission for jaundice", "Brother has same condition"],
"AS-1784": ["Weight chart", "plateauing after six month"],
"AS-1786": ["after CS", "without desaturating", "fluid in the lung fissure"],
"AS-1789": ["renal scarring"],
"AS-1792": ["yellow discoloration of the sclera", "anorexia and abdominal pain", "Alanine aminotransferase 878", "Aspartate aminotransferase 1005"],
"AS-1795": ["Influenza vaccine", "flushing, SYNCOPE"],
"AS-1799": ["dilated CMP", "pulmonary edema"],
"AS-1802": ["Ketone positive", "Characteristic odor", "Hypoglycemia"],
"AS-1814": ["4yo", "nocturia"],
"AS-1816": ["walk backwards", "Follow simple commands", "using a spoon", "Pointing to things"],
"AS-1821": ["after circumcision", "5-hours of bleeding", "high PTT"],
"AS-1838": ["large neck swelling", "clear lymphatic fluid"],
}
