# -*- coding: utf-8 -*-
# Batch r16: AS-1021 .. (141 questions from data/slices/r16.json)

EXPLANATIONS = {
"AS-1021": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "السؤال عن أشهر <bdi>complication</bdi> لـ<bdi>meconium aspiration syndrome (MAS)</bdi> بالمولود.",
    "clues": [
        ("meconium aspiration syndrome (MAS)", "<bdi>hypoxia</bdi> و<bdi>acidosis</bdi> و<bdi>lung inflammation</bdi> تخلي <bdi>pulmonary vascular resistance</bdi> عالية بعد الولادة"),
    ],
    "why_correct": [
        "<bdi>meconium aspiration</bdi> يسبب <bdi>hypoxia</bdi> و<bdi>acidosis</bdi> و<bdi>lung inflammation</bdi>، وهذا يخلي <bdi>pulmonary vascular resistance</bdi> عالية بعد <bdi>birth</bdi>.",
        "النتيجة <bdi>persistent pulmonary hypertension of the newborn (PPHN)</bdi> مع <bdi>right-to-left shunt</bdi> عبر <bdi>foramen ovale</bdi> و<bdi>ductus</bdi>، و<bdi>hypoxemia</bdi> لا يتحسن بالأكسجين.",
        "هذا هو <bdi>complication</bdi> الكلاسيكي المسؤول عنه بالأسئلة لـ<bdi>MAS</bdi>.",
    ],
    "when_changes": [
        "لو السؤال يبي <bdi>complication</bdi> مرتبط بـ<bdi>prematurity</bdi> نفسها (مو <bdi>MAS</bdi>)، الجواب يصير <bdi>PDA</bdi>.",
        "لو فيه <bdi>congenital</bdi> موجود قبل الولادة، الجواب يصير <bdi>diaphragmatic hernia</bdi> اللي هي سبب لـ<bdi>PPHN</bdi> مو نتيجة لـ<bdi>MAS</bdi>.",
    ],
    "rule": "مولود <bdi>term</bdi> أو بعد الموعد مع <bdi>meconium</bdi> و<bdi>hypoxemia</bdi> ما تتحسن بالأكسجين = <bdi>PPHN</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1022": {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "مولود <bdi>preterm</bdi> لأم عندها <bdi>gestational diabetes</bdi> جاء بـ<bdi>grunting</bdi> و<bdi>respiratory distress</bdi>، والسؤال عن الخطوة الأولية (<bdi>bedside</bdi>) الأسرع.",
    "clues": [
        ("preterm", "<bdi>surfactant deficiency</bdi> ممكن تسبب <bdi>RDS</bdi>"),
        ("gestational diabetes", "طفل أم <bdi>diabetic</bdi> معرض لـ<bdi>hypoglycemia</bdi> المبكر"),
        ("grunting and respiratory distress", "عرض عام يحتاج نفي الأسباب الخطيرة والقابلة للعلاج السريع أول"),
    ],
    "why_correct": [
        "ما فيه جواب مصدري مؤكد بهذا السؤال، فأعتمد على <bdi>clinical judgment</bdi>: مولود لأم <bdi>diabetic</bdi> معرض لـ<bdi>hypoglycemia</bdi> بالساعات الأولى، وهذا يسبب أو يفاقم <bdi>respiratory distress</bdi>.",
        "فحص <bdi>blood glucose</bdi> فحص <bdi>bedside</bdi> سريع (ثواني) وقابل للتصحيح فورًا، فهو الخطوة الأولى الأسرع قبل أي تصوير.",
        "<bdi>chest x-ray</bdi> مهم لتحديد سبب <bdi>respiratory distress</bdi> (<bdi>RDS</bdi> أو <bdi>TTN</bdi> أو <bdi>sepsis</bdi>) بس هو خطوة تالية مو أول خطوة <bdi>bedside</bdi>.",
    ],
    "when_changes": [
        "لو السؤال يبي السبب أو أفضل تصوير لتفسير <bdi>distress</bdi>، الجواب يصير <bdi>chest x-ray</bdi>.",
        "لو فيه عوامل خطورة لـ<bdi>sepsis</bdi> (<bdi>prolonged rupture of membranes</bdi> أو <bdi>maternal fever</bdi>)، الجواب يصير <bdi>blood culture</bdi> مع <bdi>antibiotics</bdi>.",
    ],
    "rule": "بمولود أم <bdi>diabetic</bdi>، الخطوة الأولى <bdi>bedside</bdi> دايمًا <bdi>blood glucose</bdi>؛ وأفضل فحص لسبب <bdi>distress</bdi> هو <bdi>chest x-ray</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر نفسه ما حدد جواب (علّم '??' على A و B)، فهذا <bdi>self-judged</bdi> باجتهاد <bdi>clinical</bdi>.",
},
"AS-1024": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل عمره 5 سنوات بـ<bdi>asthma</bdi> تحت <bdi>control</bdi> جيد، والأم تسأل عن <bdi>prognosis</bdi> المستقبلي.",
    "clues": [
        ("bronchial asthma under control", "<bdi>mild</bdi> و<bdi>controlled</bdi> = <bdi>prognosis</bdi> أحسن"),
        ("adulthood", "السؤال عن مصير <bdi>asthma</bdi> بالمستقبل"),
    ],
    "why_correct": [
        "الطفل صغير (5 سنوات) و<bdi>asthma</bdi>ه <bdi>controlled</bdi> بـ<bdi>inhalers</bdi>، وهذا ينبئ بـ<bdi>prognosis</bdi> حسن.",
        "أغلب الأطفال خصوصًا بـ<bdi>mild</bdi> أو <bdi>viral-triggered wheeze</bdi> يصيرون بلا <bdi>symptoms</bdi> مع البلوغ، فالجواب الصحيح للتوعية إن <bdi>most children grow out of it</bdi>.",
    ],
    "when_changes": [
        "لو الطفل عنده <bdi>atopy</bdi> (<bdi>eczema</bdi>، <bdi>allergic rhinitis</bdi>) أو تاريخ عائلي، نسبة الاستمرار بالبلوغ تزيد.",
        "لو <bdi>asthma</bdi> شديد وغير <bdi>controlled</bdi>، الخطر يصير <bdi>chronic lung disease</bdi> مو زوال <bdi>symptoms</bdi>.",
    ],
    "rule": "<bdi>mild</bdi> و<bdi>controlled asthma</bdi> بطفولة صغيرة = طمّن الأم إن أغلبهم يتجاوزونه؛ <bdi>severity</bdi> و<bdi>atopy</bdi> يغيرون هذا.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1026": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "القيم المختبرية تصور <bdi>salt-wasting crisis</bdi> بمولود، والسؤال عن طريقة <bdi>inheritance</bdi> للمرض.",
    "clues": [
        ("Sodium 127", "<bdi>hyponatremia</bdi>"),
        ("Potassium 6.8", "<bdi>hyperkalemia</bdi>"),
        ("Glucose 2.5", "<bdi>hypoglycemia</bdi>"),
    ],
    "why_correct": [
        "القيم: <bdi>hyponatremia</bdi>، <bdi>hyperkalemia</bdi>، <bdi>acidosis</bdi> (<bdi>bicarbonate</bdi> منخفض)، و<bdi>hypoglycemia</bdi> بمولود = صورة <bdi>salt-wasting congenital adrenal hyperplasia (CAH)</bdi> بنقص <bdi>21-hydroxylase</bdi>.",
        "كل أنواع <bdi>CAH</bdi> هي نقص <bdi>enzyme</bdi> واحد بـ<bdi>gene</bdi> واحد، فالوراثة <bdi>autosomal recessive</bdi>.",
    ],
    "when_changes": [
        "لو السؤال عن مرض <bdi>multifactorial</bdi> مثل <bdi>cleft lip</bdi> أو <bdi>pyloric stenosis</bdi>، الجواب يصير <bdi>multifactorial</bdi>.",
        "لو السؤال عن <bdi>hypophosphatemic rickets</bdi>، الجواب يصير <bdi>X-linked dominant</bdi>.",
    ],
    "rule": "<bdi>neonatal hyponatremia + hyperkalemia + acidosis + hypoglycemia</bdi> = <bdi>salt-wasting CAH</bdi>، وراثته <bdi>autosomal recessive</bdi>.",
    "comparison": None,
    "labs": [
        ["Sodium", "127 mmol/L", "134-146 mmol/L"],
        ["Potassium", "6.8 mmol/L", "3.5-5.1 mmol/L"],
        ["Bicarbonate", "15 mmol/L", "21-28 mmol/L"],
        ["Glucose", "2.5 mmol/L", "2.8-5 mmol/L (newborn) / 3.3-5.5 mmol/L (child)"],
    ],
    "guideline_note": None,
},
"AS-1028": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفلة غير مُطعّمة جرحت بجسم ملوّث وظهرت عندها <bdi>spasms</bdi> و<bdi>convulsions</bdi>، وهذا <bdi>tetanus</bdi>.",
    "clues": [
        ("never received any vaccinations", "لا يوجد <bdi>immunity</bdi> سابق"),
        ("contaminated metal rod", "جرح معرض لـ<bdi>tetanus</bdi>"),
        ("muscle spasms and convulsions", "صورة <bdi>tetanus</bdi> الكلاسيكية"),
    ],
    "why_correct": [
        "طفلة غير مُطعّمة بجرح من \"contaminated metal rod\" ثم \"muscle spasms and convulsions\" = <bdi>tetanus</bdi>.",
        "<bdi>vaccine</bdi> اللي يغطي <bdi>tetanus</bdi> هو <bdi>toxoid</bdi> اللي بـ<bdi>DTaP</bdi> (العمر المناسب تحت 7 سنوات).",
        "الإصابة بـ<bdi>tetanus disease</bdi> نفسها لا تعطي <bdi>immunity</bdi>، فلازم <bdi>active immunization</bdi> مع <bdi>tetanus immunoglobulin</bdi> وتنظيف الجرح.",
    ],
    "when_changes": [
        "لو الطفل عمره 7 سنوات أو أكبر، الـ<bdi>vaccine</bdi> يصير <bdi>Tdap</bdi> أو <bdi>Td</bdi> مو <bdi>DTaP</bdi>.",
        "لو السؤال عن سبب <bdi>flaccid paralysis</bdi> بدل <bdi>spasms</bdi>، نفكر بـ<bdi>polio</bdi> ويصير الجواب <bdi>OPV</bdi> أو <bdi>IPV</bdi>.",
    ],
    "rule": "<bdi>spasms and convulsions</bdi> بعد جرح متسخ = <bdi>tetanus</bdi>؛ <bdi>flaccid paralysis</bdi> يوجه لـ<bdi>polio</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1030": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل صغير بـ<bdi>SOB</bdi> و<bdi>palpitation</bdi> مع الجهد بعد <bdi>URTI</bdi>، والسؤال عن العلامة اللي تدل بالتحديد على القلب.",
    "clues": [
        ("URTI 3 days ago", "<bdi>viral illness</bdi> سابق يسبق <bdi>myocarditis</bdi>"),
        ("gallop rythum", "<bdi>S3</bdi> علامة <bdi>ventricular dysfunction</bdi>"),
    ],
    "why_correct": [
        "<bdi>breathlessness</bdi> و<bdi>palpitation</bdi> مع الجهد بعد <bdi>URTI</bdi> يوجه لـ<bdi>viral myocarditis</bdi> مع <bdi>heart failure</bdi>.",
        "العلامة اللي تخص القلب بالتحديد هي <bdi>gallop rhythm</bdi> (<bdi>S3</bdi>)، علامة <bdi>ventricular dysfunction</bdi> و<bdi>volume overload</bdi>.",
        "هذا ينقل <bdi>diagnosis</bdi> من مرض تنفسي إلى مرض قلبي.",
    ],
    "when_changes": [
        "لو السؤال يبي العلامة الأكثر <bdi>sensitivity</bdi> بس أقل <bdi>specificity</bdi>، نرجع لـ<bdi>tachycardia</bdi> أو <bdi>tachypnea</bdi>.",
        "لو فيه <bdi>hepatomegaly</bdi> و<bdi>cardiomegaly</bdi> بالـ<bdi>CXR</bdi>، هذا يدعم <bdi>heart failure</bdi> أكثر بعد <bdi>gallop rhythm</bdi>.",
    ],
    "rule": "العلامة الأكثر تخصيصًا (<bdi>gallop rhythm</bdi>) تتغلب على العلامات الحساسة لكن غير المحددة (<bdi>tachycardia</bdi>، <bdi>tachypnea</bdi>).",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1034": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل <bdi>asthmatic</bdi> يستخدم <bdi>MDI</bdi> مع <bdi>spacer</bdi>، والسؤال عن أهم نصيحة تعليمية.",
    "clues": [
        ("asthma", "<bdi>chronic disease</bdi> يحتاج <bdi>adherence</bdi>"),
        ("metered-dose inhaler with a spacer", "التقنية الصحيحة أهم شي"),
        ("educational advice", "السؤال عن تعليم الأم"),
    ],
    "why_correct": [
        "الطفل <bdi>asthmatic</bdi> وعنده <bdi>mild wheeze</bdi> مع <bdi>viral URTI</bdi>، وهذا <bdi>trigger</bdi> شائع.",
        "أهم نصيحة هي <bdi>ensure proper inhaler technique</bdi> لأن ضعف التقنية أو إيقاف العلاج هو السبب الأشهر لفقدان <bdi>control</bdi>.",
    ],
    "when_changes": [
        "لو الطفل يحتاج تصعيد علاج، الخطوة الأولى دايمًا نتحقق من التقنية والـ<bdi>adherence</bdi> قبل تغيير الأدوية.",
        "لو العرض بسبب <bdi>exercise</bdi>، النصيحة تشجيع النشاط البدني الطبيعي مو تقييده.",
    ],
    "rule": "<bdi>asthma</bdi> غير مضبوط بطفل = تحقق من <bdi>inhaler technique</bdi> قبل أي تعديل بالدواء.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1035": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "<bdi>wheezing</bdi> يزيد بـ<bdi>feeding</bdi> و<bdi>crying</bdi> مع <bdi>monophasic bilateral expiratory wheezing</bdi> يوجه لـ<bdi>tracheomalacia</bdi>.",
    "clues": [
        ("worsens during feeding and crying", "زيادة <bdi>intrathoracic pressure</bdi> تضغط مجرى هوائي لين"),
        ("monophasic bilateral expiratory wheezing", "صوت واحد من مكان واحد = مجرى رئيسي لين، مو <bdi>bronchospasm</bdi>"),
    ],
    "why_correct": [
        "<bdi>monophasic bilateral expiratory wheezing</bdi> يزيد مع \"feeding and crying\" (حالات ترفع الضغط داخل الصدر وتضغط مجرى هوائي لين) يوجه لـ<bdi>tracheomalacia</bdi>.",
        "بدون <bdi>distress</bdi> أو مشكلة بالنمو، الحالة <bdi>self-limiting</bdi> مع نضوج الـ<bdi>cartilage</bdi>، فالنصيحة <bdi>reassurance</bdi> بالشفاء التلقائي.",
    ],
    "when_changes": [
        "لو الصوت <bdi>inspiratory stridor</bdi> ويتحسن بوضع الانبطاح، الجواب يصير <bdi>laryngomalacia</bdi>.",
        "لو فيه <bdi>apnea</bdi> أو <bdi>cyanosis</bdi> أو <bdi>failure to thrive</bdi>، نحتاج تحويل وتقييم أعمق، لا نطمّن فقط.",
    ],
    "rule": "<bdi>monophasic expiratory wheeze</bdi> يزيد بـ<bdi>crying</bdi> و<bdi>feeding</bdi> = <bdi>tracheomalacia</bdi>، <bdi>reassure</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1036": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفل بأعراض <bdi>hyperthyroidism</bdi> مع <bdi>high free T4</bdi> و<bdi>suppressed TSH</bdi>، والسؤال عن العلاج الابتدائي.",
    "clues": [
        ("elevated free T4", "<bdi>hyperthyroidism</bdi>"),
        ("suppressed TSH", "<bdi>primary hyperthyroidism</bdi> (<bdi>Graves disease</bdi> بالأطفال)"),
    ],
    "why_correct": [
        "<bdi>weight loss</bdi> مع زيادة الشهية، <bdi>heat intolerance</bdi>، <bdi>palpitations</bdi>، <bdi>tremor</bdi> مع <bdi>high free T4</bdi> و<bdi>suppressed TSH</bdi> = <bdi>Graves disease</bdi>.",
        "السؤال يبي العلاج الابتدائي: <bdi>antithyroid drug</bdi>، و<bdi>methimazole</bdi> هو الدواء المختار بالأطفال.",
    ],
    "when_changes": [
        "لو المريضة حامل بالـ<bdi>trimester</bdi> الأول، الجواب يصير <bdi>PTU</bdi> بدل <bdi>methimazole</bdi>.",
        "لو فيه فشل بـ<bdi>antithyroid drugs</bdi> أو <bdi>goiter</bdi> كبير ضاغط، الجواب يصير <bdi>surgery</bdi> أو <bdi>radioactive iodine</bdi> كعلاج نهائي.",
    ],
    "rule": "<bdi>methimazole</bdi> هو الخط الأول بـ<bdi>hyperthyroidism</bdi> عند الأطفال وبالحمل بعد <bdi>trimester</bdi> الأول.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1046": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل بـ<bdi>end-stage cancer</bdi> وعنده <bdi>DNR</bdi>، والسؤال عن أفضل <bdi>management</bdi> بهذه المرحلة.",
    "clues": [
        ("end-stage cancer", "مرحلة <bdi>palliative</bdi>، الهدف راحة المريض"),
        ("do-not-resuscitate (DNR)", "<bdi>DNR</bdi> يمنع <bdi>resuscitation</bdi> فقط، ما يمنع <bdi>comfort care</bdi>"),
    ],
    "why_correct": [
        "طفل بـ<bdi>end-stage cancer</bdi> و<bdi>bone metastases</bdi> بـ<bdi>DNR</bdi> مؤكد بمرحلة <bdi>palliative</bdi>، والهدف راحة لا تمديد الحياة.",
        "<bdi>bone metastases</bdi> تسبب ألم شديد، و<bdi>opioids</bdi> مثل <bdi>morphine</bdi> هي الأساس لضبط الألم و<bdi>dyspnea</bdi> بنهاية الحياة.",
        "<bdi>DNR</bdi> يحدد فقط عدم <bdi>resuscitation</bdi>، أبدًا لا يعني إيقاف <bdi>symptom relief</bdi>.",
    ],
    "when_changes": [
        "لو هدف الرعاية \"full treatment\" بدون <bdi>DNR</bdi>، <bdi>inotropes</bdi> و<bdi>mechanical ventilation</bdi> تصير مناسبة بحالة <bdi>reversible</bdi>.",
        "لو فيه ألم غير مضبوط بـ<bdi>morphine</bdi> وحده، نحتاج تصعيد <bdi>palliative</bdi> متعدد التخصصات.",
    ],
    "rule": "<bdi>DNR</bdi> لا تعني \"nothing to do\"؛ <bdi>palliative care</bdi> و<bdi>analgesia</bdi> مستمرة دايمًا.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1050": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "رضيع 6 أسابيع بـ<bdi>forceful vomiting</bdi> بعد كل وجبة مع ضعف نمو وجفاف، صورة <bdi>pyloric stenosis</bdi> الكلاسيكية.",
    "clues": [
        ("6 weeks", "عمر مطابق لـ<bdi>pyloric stenosis</bdi> (2-8 أسابيع)"),
        ("forceful vomiting after each meal", "<bdi>projectile vomiting</bdi> نموذجي"),
    ],
    "why_correct": [
        "رضيع 6 أسابيع بـ<bdi>forceful vomiting</bdi> بعد كل وجبة مع ضعف نمو و<bdi>dehydration</bdi> = صورة <bdi>infantile hypertrophic pyloric stenosis</bdi> الكلاسيكية.",
        "<bdi>abdominal ultrasound</bdi> هو أفضل وأول <bdi>imaging</bdi>: يبين <bdi>pylorus</bdi> المتضخم والمستطيل، <bdi>diagnostic</bdi> وبدون <bdi>radiation</bdi>.",
    ],
    "when_changes": [
        "لو <bdi>ultrasound</bdi> غير واضح أو غير متوفر، أو الشك بـ<bdi>malrotation</bdi> أو <bdi>reflux</bdi>، نستخدم <bdi>barium study</bdi>.",
        "لو الرضيع عنده <bdi>dehydration</bdi> و<bdi>electrolyte</bdi> غير متزن، تصحيح السوائل يسبق أي <bdi>imaging</bdi> أو <bdi>surgery</bdi>.",
    ],
    "rule": "<bdi>projectile vomiting</bdi> برضيع صغير = <bdi>abdominal ultrasound</bdi> أول وأفضل فحص لـ<bdi>pyloric stenosis</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1053": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل 11 سنة بـ<bdi>sudden</bdi> ألم بالربع السفلي الأيمن مع <bdi>high WBC</bdi>، والسؤال عن أفضل فحص <bdi>diagnostic</bdi>.",
    "clues": [
        ("11 y o boy", "عمر طفل، <bdi>ultrasound</bdi> مفضل على <bdi>CT</bdi>"),
        ("lower right quadrant", "موقع نموذجي لـ<bdi>appendicitis</bdi>"),
        ("high WBC", "التهاب حاد يدعم <bdi>appendicitis</bdi>"),
    ],
    "why_correct": [
        "طفل بـ<bdi>sudden RLQ pain</bdi> مع <bdi>high WBC</bdi> و<bdi>urine dipstick</bdi> سليم (يستبعد <bdi>UTI</bdi> أو <bdi>stone</bdi>) يحتاج تقييم لـ<bdi>acute appendicitis</bdi>.",
        "بالأطفال، <bdi>abdominal ultrasound</bdi> هو <bdi>imaging</bdi> المفضل لأنه دقيق وبدون <bdi>radiation</bdi>.",
    ],
    "when_changes": [
        "لو المريض بالغ غير حامل، الأفضل يصير <bdi>CT scan</bdi>.",
        "لو فيه <bdi>complicated appendicitis</bdi> (كتلة بالربع السفلي الأيمن، ألم مستمر لأيام)، نستخدم <bdi>CT</bdi> حتى بالأطفال.",
    ],
    "rule": "<bdi>appendicitis</bdi> بالأطفال والحوامل = <bdi>ultrasound</bdi> أول؛ بالبالغين غير الحوامل = <bdi>CT</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1067": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفل بـ<bdi>pneumonia</bdi> ساءت حالته مع <bdi>O2 85%</bdi> و<bdi>drowsy</bdi>، والسؤال عن الخطوة التالية.",
    "clues": [
        ("O2% 85", "<bdi>hypoxemia</bdi> شديد"),
        ("drowsy", "<bdi>altered consciousness</bdi> يعني <bdi>airway</bdi> غير محمي"),
    ],
    "why_correct": [
        "الطفل ساءت حالته رغم <bdi>oral antibiotics</bdi>، مع <bdi>SpO2 85%</bdi> و<bdi>moderate-severe distress</bdi>، والأهم إنه <bdi>drowsy</bdi>.",
        "<bdi>altered consciousness</bdi> يعني <bdi>impending respiratory failure</bdi> و<bdi>airway</bdi> غير محمي، وهذا يستبعد أي دعم غير <bdi>invasive</bdi>.",
        "الخطوة التالية <bdi>intubation</bdi> و<bdi>invasive ventilation</bdi>.",
    ],
    "when_changes": [
        "لو الطفل <bdi>alert</bdi> ومتعاون رغم <bdi>distress</bdi>، نجرب <bdi>noninvasive ventilation</bdi> أول.",
        "لو الطفل <bdi>alert</bdi> و<bdi>hypoxic</bdi> بس بدون <bdi>distress</bdi> شديد، يكفي <bdi>oxygen</bdi> بقناع أو <bdi>high-flow</bdi>.",
    ],
    "rule": "<bdi>drowsiness</bdi> بفشل تنفسي ينقل الجواب من <bdi>NIV</bdi> إلى <bdi>intubation</bdi> مباشرة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1073": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل 3 سنوات على حمية <bdi>biscuits and milk</bdi> مع <bdi>pale</bdi> و<bdi>lethargic</bdi> و<bdi>Hb</bdi> منخفض جدًا، صورة <bdi>iron deficiency anemia</bdi> غذائي.",
    "clues": [
        ("3 yo on diet of biscuits and milk", "<bdi>excess cow's milk</bdi> يسبب <bdi>iron deficiency</bdi>"),
        ("hb 67 g", "<bdi>anemia</bdi> شديد لكن <bdi>chronic</bdi>"),
    ],
    "why_correct": [
        "طفل على حمية <bdi>milk</bdi> زائد مع <bdi>biscuits</bdi> قليلة <bdi>iron</bdi>، و<bdi>pale</bdi> و<bdi>lethargic</bdi> مع <bdi>Hb</bdi> منخفض = <bdi>nutritional iron deficiency anemia</bdi>.",
        "لأن <bdi>anemia</bdi> مزمن والطفل غير <bdi>hemodynamically unstable</bdi> بالوصف، العلاج <bdi>oral iron</bdi> مع تعديل الحمية ومتابعة.",
    ],
    "when_changes": [
        "لو فيه <bdi>hemodynamic instability</bdi> أو <bdi>heart failure</bdi> أو نزيف فعّال، الجواب يصير <bdi>blood transfusion</bdi>.",
        "لو <bdi>anemia</bdi> لا يستجيب لـ<bdi>oral iron</bdi>، نفكر بـ<bdi>malabsorption</bdi> أو <bdi>poor compliance</bdi> ونحول لـ<bdi>parenteral iron</bdi>.",
    ],
    "rule": "<bdi>Hb</bdi> منخفض وحده لا يعني <bdi>transfusion</bdi> بـ<bdi>chronic IDA</bdi>؛ نبحث عن عدم استقرار أول.",
    "comparison": None,
    "labs": [["Hemoglobin", "67 g/L", "111-117 g/L"]],
    "guideline_note": None,
},
"AS-1074": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "السؤال عن العلامة اللي تدعم <bdi>diagnosis</bdi> الـ<bdi>asthma</bdi> بالذات، بعد وصف <bdi>asthma</bdi> يسوء مع <bdi>URTI</bdi> و<bdi>CXR</bdi> طبيعي.",
    "clues": [
        ("Indicates Diagnosis Of Asthma", "يبحث عن علامة محددة لـ<bdi>asthma</bdi> مو عرض عام"),
    ],
    "why_correct": [
        "<bdi>asthma</bdi> تشخيص <bdi>clinical</bdi> يعتمد على أعراض متكررة ومتغيرة مع <bdi>triggers</bdi> نموذجية.",
        "<bdi>polyphonic wheeze</bdi> (منتشر، وقت الزفير) يحدث مع الجهد، وهذا يعكس انسداد مجرى هوائي متغير، وهو علامة مميزة تدعم <bdi>asthma</bdi>.",
    ],
    "when_changes": [
        "لو الصوت <bdi>monophasic</bdi> من مكان واحد، نفكر بسبب تشريحي مثل <bdi>tracheomalacia</bdi> مو <bdi>asthma</bdi>.",
        "لو الصوت <bdi>inspiratory</bdi> ولا يتحسن بـ<bdi>bronchodilator</bdi>، نفكر بـ<bdi>vocal cord dysfunction</bdi> أو سبب بمجرى الهواء العلوي.",
    ],
    "rule": "<bdi>polyphonic expiratory wheeze</bdi> مع الجهد والعدوى الفيروسية يدعم <bdi>asthma</bdi>؛ <bdi>CXR</bdi> طبيعي بين النوبات غير محدد.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1075": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "<bdi>PKU</bdi> نقص <bdi>phenylalanine hydroxylase</bdi>، والحمية تمنع تراكم <bdi>phenylalanine</bdi>.",
    "clues": [
        ("phenylketonuria (PKU)", "نقص <bdi>enzyme</bdi> واحد يحدد الحمية المناسبة"),
    ],
    "why_correct": [
        "<bdi>PKU</bdi> نقص <bdi>phenylalanine hydroxylase</bdi>، فـ<bdi>phenylalanine</bdi> لا يتحول إلى <bdi>tyrosine</bdi> ويتراكم ويضر الدماغ النامي.",
        "العلاج تقييد <bdi>phenylalanine</bdi> مدى الحياة بـ<bdi>formula</bdi> خاص بدون <bdi>phenylalanine</bdi>، مع تزويد <bdi>tyrosine</bdi> لأنه يصير أساسي.",
    ],
    "when_changes": [
        "لو السؤال عن <bdi>galactosemia</bdi>، الحمية تصير إزالة <bdi>galactose</bdi> و<bdi>lactose</bdi>.",
        "لو السؤال عن <bdi>hereditary fructose intolerance</bdi>، الحمية تصير إزالة <bdi>fructose</bdi> و<bdi>sucrose</bdi> و<bdi>sorbitol</bdi>.",
    ],
    "rule": "كل مرض <bdi>metabolic</bdi> له <bdi>nutrient</bdi> محدد يُزال؛ بـ<bdi>PKU</bdi> هو <bdi>phenylalanine</bdi> فقط، مو كل <bdi>protein</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1076": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بـ<bdi>cirrhosis</bdi> من <bdi>autoimmune hepatitis</bdi> مع <bdi>hepatic encephalopathy</bdi>، والسؤال عن ما يُتجنب بالحمية حسب التعليم الكلاسيكي.",
    "clues": [
        ("pediatric with cirrhosis", "<bdi>liver</bdi> لا يقدر يصفّي <bdi>ammonia</bdi>"),
        ("hepatic encephalopathy", "<bdi>ammonia</bdi> من <bdi>protein</bdi> هو المحرك الكلاسيكي"),
    ],
    "why_correct": [
        "التعليم الكلاسيكي: <bdi>dietary protein</bdi> يتحول إلى <bdi>ammonia</bdi> بالأمعاء، و<bdi>ammonia</bdi> يحرك <bdi>hepatic encephalopathy</bdi> بـ<bdi>cirrhosis</bdi> اللي ما تقدر تصفّيه.",
        "بهذا المنطق، <bdi>protein</bdi> هو العنصر المحدود، والدهون والكاربوهيدرات مصادر طاقة لا ترفع <bdi>ammonia</bdi>.",
    ],
    "when_changes": [
        "لو السؤال عن <bdi>ascites</bdi> بـ<bdi>cirrhosis</bdi>، العنصر المحدود يصير <bdi>sodium</bdi> مو <bdi>protein</bdi>.",
        "بالممارسة الحديثة، تقييد <bdi>protein</bdi> الشديد غير مفضل لأنه يزيد هدم العضلات؛ المهم علاج السبب المحرك (<bdi>infection</bdi>، نزيف، إمساك).",
    ],
    "rule": "<bdi>hepatic encephalopathy</bdi> الكلاسيكي = حد من <bdi>protein</bdi>؛ <bdi>ascites</bdi> = حد من <bdi>sodium</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "التعليم الحديث يميل لعدم تقييد <bdi>protein</bdi> الشديد والتركيز على علاج السبب المحرك، بس المصدر يعتمد الجواب الكلاسيكي B.",
},
"AS-1142": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "مولود بـ<bdi>TSH 60</bdi> (طبيعي أقل من 10) بدون أعراض، والسؤال عن الخطوة الصحيحة فورًا.",
    "clues": [
        ("Neonate", "فحص <bdi>screening</bdi> روتيني"),
        ("TSH 60", "ارتفاع كبير يدل على <bdi>congenital hypothyroidism</bdi>"),
        ("no symptoms normal appearance", "المظهر الطبيعي لا يستبعد المرض بسبب <bdi>maternal T4</bdi>"),
    ],
    "why_correct": [
        "مولود بـ<bdi>TSH 60</bdi> له <bdi>screening</bdi> موجب بشدة لـ<bdi>congenital hypothyroidism</bdi>.",
        "الأطفال عادة بلا أعراض ومظهر طبيعي بالولادة بسبب عبور <bdi>maternal T4</bdi> للمشيمة، فـ\"no symptoms\" لا يطمّن.",
        "هرمون الدرقية أساسي لنمو الدماغ بالأسابيع الأولى، فنبدأ <bdi>levothyroxine</bdi> فورًا بعد سحب <bdi>confirmatory TSH</bdi> و<bdi>free T4</bdi>، بدون انتظار النتائج أو التصوير.",
    ],
    "when_changes": [
        "لو <bdi>TSH</bdi> مرتفع بشكل طفيف أو على الحد (<bdi>borderline</bdi>)، نعيد الفحص قبل البدء بالعلاج.",
        "<bdi>thyroid ultrasound</bdi> أو <bdi>scintigraphy</bdi> ممكن تحدد السبب، بس اختياري وما يأخر العلاج أبدًا.",
    ],
    "rule": "مظهر طبيعي لا يعني غدة طبيعية؛ <bdi>TSH</bdi> مرتفع بوضوح بمولود = علاج فوري بـ<bdi>levothyroxine</bdi>.",
    "comparison": None,
    "labs": [["TSH", "60", "&lt;10 (normal)"]],
    "guideline_note": None,
},
"AS-1143": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل 2 سنوات برفض المشي و<bdi>bowing</bdi> بالساقين، صورة <bdi>rickets</bdi>، والسؤال عن نتائج <bdi>labs</bdi> المتوقعة.",
    "clues": [
        ("2-year-old", "عمر مناسب لـ<bdi>nutritional vitamin D deficiency</bdi>"),
        ("refuses to walk", "ضعف وألم بالعظام"),
        ("bowing of both legs", "صورة <bdi>rickets</bdi> الكلاسيكية"),
    ],
    "why_correct": [
        "طفل 2 سنوات برفض المشي و<bdi>bowing of both legs</bdi> له <bdi>rickets</bdi>، وبهذا العمر السبب الشائع <bdi>nutritional vitamin D deficiency</bdi>.",
        "<bdi>low vitamin D</bdi> يقلل امتصاص <bdi>calcium</bdi> بالأمعاء (<bdi>calcium</bdi> منخفض)، و<bdi>secondary hyperparathyroidism</bdi> يهدر <bdi>phosphate</bdi> بالبول (<bdi>phosphate</bdi> منخفض)، وضعف تمعدن صفائح النمو يرفع <bdi>ALP</bdi>.",
    ],
    "when_changes": [
        "لو النتائج <bdi>calcium</bdi> و<bdi>phosphate</bdi> مرتفعين مع <bdi>ALP</bdi> منخفض، الجواب يصير <bdi>hypophosphatasia</bdi>.",
        "لو <bdi>calcium</bdi> طبيعي و<bdi>phosphate</bdi> منخفض و<bdi>PTH</bdi> طبيعي و<bdi>vitamin D</bdi> طبيعي، نفكر بـ<bdi>X-linked hypophosphatemic rickets</bdi>.",
    ],
    "rule": "<bdi>ALP</bdi> مرتفع بكل أنواع <bdi>rickets</bdi> إلا <bdi>hypophosphatasia</bdi> اللي يكون منخفض فيها.",
    "comparison": {
        "headers": ["النوع", "Calcium", "Phosphate", "ALP", "Vitamin D"],
        "rows": [
            ["Nutritional deficiency", "طبيعي/منخفض", "منخفض", "مرتفع", "منخفض"],
            ["Hypophosphatasia", "مرتفع", "مرتفع", "منخفض", "طبيعي"],
            ["X-linked hypophosphatemic", "طبيعي", "منخفض", "مرتفع", "طبيعي"],
        ],
    },
    "labs": None,
    "guideline_note": None,
},
"AS-1145": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "رضيع بـ<bdi>bronchiolitis</bdi> مع <bdi>O2 89%</bdi> و<bdi>alert</bdi>، والسؤال عن <bdi>initial management</bdi>.",
    "clues": [
        ("nasal congestion cough and poor feeding", "صورة <bdi>bronchiolitis</bdi> الفيروسية"),
        ("alert", "لا يحتاج تصعيد فوري بدعم تنفسي"),
        ("Oxygen saturation is 89%", "<bdi>hypoxemia</bdi> يحتاج <bdi>oxygen</bdi>"),
        ("bilateral crackles and wheezing", "صورة <bdi>bronchiolitis</bdi> بالفحص"),
    ],
    "why_correct": [
        "احتقان وسعال 3 أيام ثم <bdi>tachypnea</bdi> و<bdi>nasal flaring</bdi> مع <bdi>bilateral crackles and wheezing</bdi> برضيع = <bdi>bronchiolitis</bdi>.",
        "العلاج <bdi>supportive</bdi>: <bdi>SpO2 89%</bdi> يحتاج <bdi>low-flow oxygen</bdi>، و\"poor feeding\" يحتاج دعم سوائل (<bdi>IV</bdi> أو <bdi>NG</bdi>)، و<bdi>nasal suctioning</bdi> ينظف الأنف المسدود.",
        "الرضيع <bdi>alert</bdi>، فلا حاجة لتصعيد الدعم التنفسي كخطوة أولى.",
    ],
    "when_changes": [
        "لو <bdi>low-flow oxygen</bdi> فشل بتصحيح <bdi>hypoxia</bdi> أو ازداد العمل التنفسي، نصعّد لـ<bdi>high-flow oxygen</bdi>.",
        "لو فيه <bdi>focal findings</bdi> أو شك بعدوى بكتيرية، نفكر بـ<bdi>chest X-ray</bdi> و<bdi>antibiotics</bdi> خارج الصورة النموذجية.",
    ],
    "rule": "<bdi>wheeze</bdi> برضيع مع <bdi>coryza</bdi> = <bdi>bronchiolitis</bdi>، العلاج <bdi>oxygen</bdi> و<bdi>hydration</bdi> و<bdi>suction</bdi>، لا <bdi>antibiotics</bdi> ولا <bdi>bronchodilators</bdi> روتينيًا.",
    "comparison": None,
    "labs": [["SpO2", "89%", "≥94-95%"]],
    "guideline_note": None,
},
"AS-1145B": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "مولود <bdi>term</bdi> بـ<bdi>cesarean section</bdi> بـ<bdi>tachypnea</bdi> خفيف مع <bdi>fluid</bdi> بالـ<bdi>fissure</bdi>، صورة <bdi>TTN</bdi> الكلاسيكية.",
    "clues": [
        ("cesarean section", "<bdi>TTN</bdi> أكثر شيوعًا بدون <bdi>labour</bdi>"),
        ("fluid in the horizontal fissure", "علامة <bdi>TTN</bdi> بالـ<bdi>X-ray</bdi>"),
    ],
    "why_correct": [
        "مولود \"term\" بـ\"cesarean section\" مع <bdi>tachypnea</bdi> و<bdi>nasal flaring</bdi> و<bdi>grunting</bdi> خفيف ونقص أكسجين طفيف (<bdi>SpO2 92%</bdi>) و\"fluid in the horizontal fissure\" بـ<bdi>CXR</bdi> = <bdi>transient tachypnea of the newborn (TTN)</bdi>.",
        "السبب تأخر تصريف سوائل الرئة الجنينية، وأكثر شيوعًا بعد <bdi>cesarean</bdi> بدون <bdi>labour</bdi>، وهو <bdi>self-limiting</bdi> بأيام مع رعاية <bdi>supportive</bdi>.",
    ],
    "when_changes": [
        "لو المولود <bdi>preterm</bdi> مع نقص أكسجين شديد و<bdi>ground-glass pattern</bdi>، الجواب يصير <bdi>RDS</bdi>.",
        "لو فيه <bdi>maternal fever</bdi> أو <bdi>prolonged rupture of membranes</bdi> مع <bdi>consolidation</bdi>، الجواب يصير <bdi>pneumonia</bdi>.",
    ],
    "rule": "<bdi>term</bdi> + <bdi>cesarean</bdi> + <bdi>fluid in fissure</bdi> = <bdi>TTN</bdi>؛ نفس الصورة بـ<bdi>preterm</bdi> مع نقص أكسجين شديد تصير <bdi>RDS</bdi>.",
    "comparison": None,
    "labs": [
        ["Blood pressure", "60/35 mmHg", "normal neonatal range"],
        ["Heart rate", "140 /min", "normal neonatal range"],
        ["Respiratory rate", "65 /min", "30-60 /min"],
        ["Temperature", "36.6 °C", "36.5-37.5 °C"],
        ["Oxygen saturation", "92%", "≥94-95%"],
    ],
    "guideline_note": None,
},
"AS-1148": {
    "correct_letter": "A",
    "self_judged": False,
    "idea": "طفل بـ<bdi>cystic fibrosis</bdi> مع ضعف نمو و<bdi>foul smelling stool</bdi>، صورة <bdi>exocrine pancreatic insufficiency</bdi>.",
    "clues": [
        ("Cystic fibrosis", "مرض <bdi>multisystem</bdi> يصيب البنكرياس والرئة"),
        ("weight 3rd centile", "ضعف نمو من سوء الامتصاص"),
        ("Foul smelling stool", "<bdi>steatorrhea</bdi>"),
    ],
    "why_correct": [
        "بـ<bdi>cystic fibrosis</bdi>، الوزن بالـ3rd centile مع \"inability to gain weight\" و\"foul smelling stool\" تعني <bdi>steatorrhea</bdi> من <bdi>exocrine pancreatic insufficiency</bdi>.",
        "الإفرازات السميكة تسد قنوات البنكرياس فلا يُهضم الدهن والبروتين، و<bdi>pancreatic enzyme replacement</bdi> مع الوجبات يعالج السبب ويُرجع الوزن.",
    ],
    "when_changes": [
        "لو السؤال عن الحمية نفسها، الجواب يكون حمية عالية السعرات والدهون مع <bdi>enzymes</bdi>، لا تقييد الدهون.",
        "لو السؤال عن نقص الفيتامينات الذائبة بالدهن، نضيف <bdi>vitamins A, D, E, K</bdi> بجانب <bdi>enzymes</bdi>.",
    ],
    "rule": "<bdi>CF</bdi> مع <bdi>steatorrhea</bdi> وضعف نمو = <bdi>pancreatic enzyme replacement</bdi> مع كل وجبة.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1149": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل 10 سنوات بـ<bdi>ptosis</bdi> و<bdi>dysarthria</bdi> تزيد مساءً وتتحسن صباحًا، صورة <bdi>myasthenia gravis</bdi>.",
    "clues": [
        ("ptosis", "ضعف عضلي <bdi>fatigable</bdi>"),
        ("at evening only, he is normal in the morning", "تذبذب يومي نموذجي لـ<bdi>myasthenia gravis</bdi>"),
        ("exuasting ptosis", "<bdi>fatigable weakness</bdi> بالفحص"),
    ],
    "why_correct": [
        "<bdi>ptosis</bdi> و<bdi>drooling</bdi> و<bdi>dysarthria</bdi> تظهر \"at evening only\" وتكون \"normal in the morning\"، مع <bdi>fatigable ptosis</bdi> بالفحص، تعني ضعف <bdi>bulbar</bdi> و<bdi>ocular</bdi> متذبذب = <bdi>myasthenia gravis</bdi>.",
        "المرض سببه <bdi>antibodies</bdi> ضد <bdi>acetylcholine receptor</bdi>، فـ<bdi>serum AChR antibody test</bdi> هو الفحص التأكيدي.",
    ],
    "when_changes": [
        "لو الفحص سلبي، نفكر بـ<bdi>anti-MuSK antibody</bdi> أو <bdi>repetitive nerve stimulation</bdi> أو <bdi>single-fiber EMG</bdi>.",
        "لو الضعف يتحسن مع التكرار (مو يسوء)، نفكر بـ<bdi>Lambert-Eaton syndrome</bdi> بدل <bdi>MG</bdi>.",
    ],
    "rule": "ضعف يسوء مساءً ويتحسن بالراحة = <bdi>myasthenia gravis</bdi>، أكّده بـ<bdi>AChR antibody</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
"AS-1159": {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "طفل بـ<bdi>seizures</bdi> و<bdi>Anti-dsDNA</bdi> مرتفع ضمن صورة <bdi>SLE</bdi> نشط بالجهاز العصبي، والسؤال عن العلاج.",
    "clues": [
        ("seizures", "<bdi>neuropsychiatric lupus</bdi>، حالة خطيرة تهدد الحياة"),
        ("Anti ds DNA high", "نشاط <bdi>SLE</bdi>"),
    ],
    "why_correct": [
        "ما فيه جواب مصدري مؤكد، فأعتمد على القاعدة العامة: <bdi>seizures</bdi> ضمن <bdi>SLE</bdi> تعتبر <bdi>life-threatening manifestation</bdi> (<bdi>neuropsychiatric lupus</bdi>).",
        "العلاج الأولي الأهم لأي <bdi>life-threatening lupus flare</bdi> هو <bdi>high-dose corticosteroids</bdi>، ويُضاف <bdi>cyclophosphamide</bdi> بعدها للحالات العصبية الشديدة.",
        "بما إن السؤال يسأل \"what to give\" بشكل عام بدون تحديد \"add to steroids\"، الخطوة الأولى الأهم هي <bdi>corticosteroids</bdi>.",
    ],
    "when_changes": [
        "لو السؤال يحدد \"بعد إعطاء الـ<bdi>steroids</bdi>، شنو نضيف للسيطرة على <bdi>CNS lupus</bdi>؟\"، الجواب يصير <bdi>cyclophosphamide</bdi>.",
        "لو السؤال عن <bdi>lupus nephritis</bdi> بدل <bdi>CNS</bdi>، الجواب يصير <bdi>mycophenolate mofetil</bdi>.",
    ],
    "rule": "بأي <bdi>life-threatening SLE flare</bdi> (شامل <bdi>seizures</bdi>) العلاج الأولي <bdi>corticosteroids</bdi>؛ <bdi>cyclophosphamide</bdi> يُضاف لـ<bdi>CNS lupus</bdi> الشديد.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر ما حدد جواب لهذا السؤال؛ الاختيار هنا باجتهاد <bdi>clinical</bdi> حسب قاعدة علاج <bdi>SLE</bdi> الشديد.",
},
"AS-1167": {
    "correct_letter": "B",
    "self_judged": True,
    "idea": "إسهال <bdi>foul smelling</bdi> مائي أخضر، والسؤال عن الكائن المسبب.",
    "clues": [
        ("Foul smelling watery diarrhea, green in color", "وصف كلاسيكي لـ<bdi>Salmonella</bdi>"),
    ],
    "why_correct": [
        "ما فيه جواب مصدري مؤكد، فأعتمد على الوصف الكلاسيكي: إسهال \"green, foul\" (يشبه \"pea soup\") هو الوصف المرتبط بـ<bdi>Salmonella</bdi>.",
        "هذا يختلف عن <bdi>Shigella</bdi> (دم ومخاط مع <bdi>seizure</bdi>) و<bdi>Rotavirus</bdi> (إسهال مائي غزير مع قيء بالرضع).",
    ],
    "when_changes": [
        "لو الإسهال دموي مخاطي مع <bdi>seizure</bdi>، الجواب يصير <bdi>Shigella</bdi>.",
        "لو الإسهال مائي غزير مع قيء برضيع، الجواب يصير <bdi>Rotavirus</bdi>.",
    ],
    "rule": "إسهال \"green, foul\" = وصف <bdi>Salmonella</bdi> الكلاسيكي؛ \"blood and mucus\" ينقل لـ<bdi>Shigella</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر ما حدد جواب؛ الاختيار باجتهاد حسب الوصف الكلاسيكي بالمادة التعليمية.",
},
"AS-1170": {
    "correct_letter": "D",
    "self_judged": True,
    "idea": "رضيع 9 أشهر لم يُطعّم أبدًا، والسؤال عن اللقاحات المناسبة بزيارة <bdi>catch-up</bdi> واحدة.",
    "clues": [
        ("9 month never been vaccinated", "يحتاج تعويض جرعات الولادة والجرعات الأولى والجرعات المستحقة بعمره بزيارة واحدة"),
    ],
    "why_correct": [
        "ما فيه جواب مصدري مؤكد، فأعتمد على قاعدة <bdi>catch-up</bdi>: نعطي كل اللقاحات المناسبة للعمر بزيارة واحدة، بدون إعادة بدء السلسلة.",
        "الخيار D (<bdi>BCG</bdi>، <bdi>Hep B</bdi>، <bdi>OPV-1</bdi>، <bdi>DTaP-1</bdi>، <bdi>Measles</bdi>) يجمع جرعات الولادة المفقودة (<bdi>BCG</bdi>، <bdi>Hep B</bdi>) مع أول جرعة بالسلسلة الأساسية (<bdi>OPV-1</bdi>، <bdi>DTaP-1</bdi>) مع اللقاح المستحق بعمر 9 أشهر (<bdi>Measles</bdi>).",
    ],
    "when_changes": [
        "لو الرضيع عمره أقل من 9 أشهر، لقاح <bdi>Measles</bdi> ما يُعطى قبل هذا العمر.",
        "لو الرضيع أكمل جرعات الولادة والسلسلة الأساسية، نضيف فقط اللقاح المستحق بعمره الحالي.",
    ],
    "rule": "بـ<bdi>catch-up vaccination</bdi>، نختار الخيار اللي يجمع جرعات الولادة المفقودة مع أول جرعات السلسلة الأساسية مع اللقاح المستحق بالعمر الحالي.",
    "comparison": None,
    "labs": None,
    "guideline_note": "المصدر ما حدد جواب؛ الاختيار باجتهاد حسب قاعدة <bdi>catch-up</bdi> بالمادة التعليمية.",
},
"AS-1174": {
    "correct_letter": "D",
    "self_judged": False,
    "idea": "طفل 5 سنوات بحمى 6 أسابيع مع <bdi>salmon rash</bdi> و<bdi>hepatomegaly</bdi> و<bdi>arthritis</bdi>، صورة <bdi>systemic JIA</bdi>.",
    "clues": [
        ("fever 37.9 for 6 weeks", "حمى مزمنة تتجاوز 6 أسابيع تدعم <bdi>systemic JIA</bdi>"),
        ("salmon color rash", "الطفح المميز لـ<bdi>systemic JIA</bdi>"),
    ],
    "why_correct": [
        "حمى \"6 weeks\" مع <bdi>arthritis</bdi> (\"bilateral wrist swelling\" لمدة 6 أسابيع أو أكثر) و\"salmon color rash\" و<bdi>hepatomegaly</bdi> بطفل 5 سنوات = <bdi>systemic JIA (Still disease)</bdi>.",
        "الطفح الوردي العابر مع نوبات الحمى و<bdi>hepatosplenomegaly</bdi> هي الصفات الجهازية اللي تميزه عن أنواع <bdi>JIA</bdi> الأخرى، وهو تشخيص استبعادي يحتاج نفي العدوى والأورام أول.",
    ],
    "when_changes": [
        "لو الحمى لمدة 5 أيام فقط مع <bdi>conjunctivitis</bdi> وتشققات شفايف وطفح <bdi>polymorphous</bdi>، الجواب يصير <bdi>Kawasaki disease</bdi>.",
        "لو فيه ألم عظمي ليلي مع <bdi>cytopenias</bdi>، نفكر بـ<bdi>leukemia</bdi> كتشخيص استبعادي أول.",
    ],
    "rule": "طفح <bdi>salmon</bdi> يظهر مع نوبات الحمى ويختفي معها = <bdi>systemic JIA</bdi>؛ حمى قصيرة مع علامات جلدية مخاطية = <bdi>Kawasaki</bdi>.",
    "comparison": None,
    "labs": [["Temperature", "37.9 °C for 6 weeks", "36.5-37.5 °C"]],
    "guideline_note": None,
},
"AS-1175": {
    "correct_letter": "C",
    "self_judged": False,
    "idea": "طفل 10 سنوات بإسهال دموي مع ألم بالتبرز وفقدان وزن وألم مفاصل، صورة <bdi>IBD</bdi> تميل لـ<bdi>ulcerative colitis</bdi>.",
    "clues": [
        ("bloody", "إسهال دموي يدعم <bdi>UC</bdi> أكثر من <bdi>Crohn's</bdi>"),
        ("lost weight", "مرض مزمن <bdi>inflammatory</bdi>"),
    ],
    "why_correct": [
        "إسهال \"sometimes bloody\" مع ألم مصاحب للتبرز (التهاب <bdi>rectal</bdi> و<bdi>colonic</bdi> يسبب <bdi>urgency</bdi> و<bdi>tenesmus</bdi>) هو العلامة الفاصلة.",
        "\"aches and pains of his joints\" من مظاهر <bdi>IBD</bdi> خارج الأمعاء، والحمى و<bdi>anemia</bdi> (<bdi>Hb 82</bdi>) ونقص <bdi>albumin</bdi> وارتفاع <bdi>CRP</bdi> وفقدان الوزن تؤكد التهاب مزمن نشط.",
        "الإسهال الدموي مع صفات <bdi>IBD</bdi> يوجه لـ<bdi>ulcerative colitis</bdi>.",
    ],
    "when_changes": [
        "لو الإسهال غير دموي مع ألم بالربع السفلي الأيمن وتقرحات فموية ومرض حول الشرج، الجواب يصير <bdi>Crohn's disease</bdi>.",
        "لو الإسهال غير دموي مع سوء امتصاص وانتفاخ بدون حمى، الجواب يصير <bdi>celiac disease</bdi>.",
    ],
    "rule": "الدم بالبراز يوجه <bdi>IBD</bdi> نحو <bdi>UC</bdi>؛ مرض حول الشرج أو تقرحات فموية أو كتلة بالربع السفلي الأيمن توجه نحو <bdi>Crohn's disease</bdi>.",
    "comparison": None,
    "labs": [
        ["Sodium", "132 mmol/L", "134-146 mmol/L"],
        ["Potassium", "3.2 mmol/L", "3.5-5.1 mmol/L"],
        ["Creatinine", "31", "27-62"],
        ["BUN", "5.6 mmol/L", "1.8-6.4 mmol/L"],
        ["Hemoglobin", "82 g/L", "112-165 g/L"],
        ["CRP", "1.1 mg/dl", "0-0.5 mg/dl"],
        ["Albumin", "32 g/L", "36-52 g/L"],
        ["Temperature", "38.6 °C", "36.5-37.5 °C"],
    ],
    "guideline_note": None,
},
"AS-1178": {
    "correct_letter": "B",
    "self_judged": False,
    "idea": "طفل بأسنان ضعيفة و<bdi>enamel hypoplasia</bdi> مع صورة مختبرية لـ<bdi>nutritional rickets</bdi>، والسؤال عن العلاج المناسب.",
    "clues": [
        ("enamel hypoplasia", "ضعف تمعدن يصيب الأسنان بـ<bdi>rickets</bdi>"),
        ("low calcium, low phosphate, high alkaline phosphatase", "الصورة المختبرية لـ<bdi>nutritional vitamin D deficiency rickets</bdi>"),
    ],
    "why_correct": [
        "<bdi>calcium</bdi> منخفض و<bdi>phosphate</bdi> منخفض و<bdi>ALP</bdi> مرتفع مع \"poor dentition, enamel hypoplasia\" هي الصورة المختبرية لـ<bdi>nutritional (vitamin D deficiency) rickets</bdi>.",
        "بدون <bdi>tetany</bdi> أو <bdi>seizures</bdi> مذكورة، العلاج المناسب هو <bdi>vitamin D3</bdi> عن طريق الفم مع <bdi>calcium supplementation</bdi> لمعالجة السبب وتحسين العظم والأسنان.",
    ],
    "when_changes": [
        "لو فيه <bdi>tetany</bdi> أو <bdi>laryngospasm</bdi> أو <bdi>seizures</bdi> من <bdi>hypocalcemia</bdi> الحاد، الجواب يصير <bdi>IV calcium gluconate</bdi> فورًا.",
        "لو <bdi>calcium</bdi> طبيعي و<bdi>vitamin D</bdi> طبيعي مع <bdi>phosphate</bdi> منخفض فقط، نفكر بـ<bdi>X-linked hypophosphatemic rickets</bdi> ونعالج بـ<bdi>phosphate</bdi> و<bdi>calcitriol</bdi>.",
    ],
    "rule": "<bdi>IV calcium</bdi> فقط لـ<bdi>hypocalcemia</bdi> العرضي الحاد؛ غير ذلك نعالج السبب بـ<bdi>oral vitamin D</bdi> مع <bdi>calcium</bdi>.",
    "comparison": None,
    "labs": None,
    "guideline_note": None,
},
}

WHY_WRONG = {
"AS-1021": {
    "A": "<bdi>neonatal sepsis</bdi> ممكن ترتبط بـ<bdi>pneumonitis</bdi> بعد <bdi>meconium</bdi>، بس هي ليست <bdi>complication</bdi> المميز لـ<bdi>MAS</bdi>؛ فكر بها مع <bdi>GBS</bdi> أو <bdi>prolonged rupture of membranes</bdi>.",
    "C": "<bdi>PDA</bdi> المعزول هو <bdi>complication</bdi> لـ<bdi>prematurity</bdi> مو لـ<bdi>MAS</bdi> اللي تصيب مواليد <bdi>term</bdi> أو بعد الموعد.",
    "D": "<bdi>diaphragmatic hernia</bdi> عيب <bdi>congenital</bdi> موجود قبل الولادة، وهو سبب لـ<bdi>PPHN</bdi> مو نتيجة لـ<bdi>aspiration</bdi>.",
},
"AS-1022": {
    "A": "<bdi>chest x-ray</bdi> مفيد لتحديد سبب <bdi>distress</bdi> بس أبطأ من فحص <bdi>bedside</bdi> سريع كـ<bdi>glucose</bdi>.",
    "C": "<bdi>blood culture</bdi> مناسب لو فيه عوامل خطورة لـ<bdi>sepsis</bdi> واضحة، وما هو الخطوة الأسرع هنا بغياب هذي العوامل.",
},
"AS-1024": {
    "A": "<bdi>chronic lung disease</bdi> خطر مرتبط بمرض شديد غير مضبوط، لا بـ<bdi>asthma</bdi> خفيف مضبوط.",
    "C": "فقط نسبة قليلة من الأطفال تستمر <bdi>asthmatic</bdi> للبلوغ، وغالبًا مرتبطين بمرض شديد أو <bdi>atopy</bdi>.",
    "D": "فيه ارتباط واضح: <bdi>severe</bdi> أو <bdi>atopic asthma</bdi> بالطفولة يرفع احتمال الاستمرار أو الرجوع بالبلوغ.",
},
"AS-1026": {
    "A": "<bdi>CAH</bdi> نتيجة نقص <bdi>enzyme</bdi> واحد بـ<bdi>gene</bdi> واحد، مو صفة <bdi>multifactorial</bdi> متأثرة بجينات متعددة وبيئة.",
    "B": "جينات <bdi>CAH</bdi> على <bdi>autosomes</bdi> وتصيب الذكور والإناث بالتساوي؛ <bdi>X-linked dominant</bdi> يناسب <bdi>hypophosphatemic rickets</bdi>.",
    "C": "بـ<bdi>autosomal dominant</bdi> الوالدين الحاملين يكونوا مصابين، وهذا يخالف صورة <bdi>CAH</bdi> اللي الوالدين فيها حاملين سليمين.",
},
"AS-1028": {
    "B": "<bdi>OPV</bdi> يحمي من <bdi>poliomyelitis</bdi> اللي تسبب <bdi>flaccid paralysis</bdi>، لا علاقة له بـ<bdi>tetanus</bdi>.",
    "C": "<bdi>IPV</bdi> أيضًا <bdi>vaccine</bdi> لـ<bdi>polio</bdi>، ما يغطي <bdi>tetanus</bdi>.",
    "D": "<bdi>Hib vaccine</bdi> يحمي من <bdi>Haemophilus influenzae type b</bdi>، لا علاقة له بـ<bdi>tetanus</bdi>.",
},
"AS-1030": {
    "A": "<bdi>history</bdi> الفيروسي السابق مفيد بس غير محدد، يحدث قبل أمراض تنفسية كثيرة.",
    "B": "<bdi>tachypnea</bdi> تحدث بأي مرض تنفسي أو قلبي أو حتى الحمى، فلا تحدد المصدر بالقلب.",
    "C": "<bdi>tachycardia</bdi> غير محدد (حمى، قلق، جفاف، <bdi>sepsis</bdi>)، وإن كانت زيادتها عن الحمى تثير الشك بـ<bdi>myocarditis</bdi>.",
},
"AS-1034": {
    "A": "إيقاف الـ<bdi>inhaler</bdi> وقت البرد عكس الصحيح؛ العدوى الفيروسية تزيد خطر <bdi>exacerbation</bdi>، فالعلاج المستمر ضروري.",
    "B": "تقييد النشاط البدني غير صحيح؛ الطفل <bdi>asthmatic</bdi> يشجَّع على النشاط الطبيعي، وأعراض الجهد تعني نحتاج تحسين <bdi>control</bdi>.",
    "D": "<bdi>vitamin C</bdi> ما له دليل بالوقاية من <bdi>URTIs</bdi> أو <bdi>exacerbations</bdi>.",
},
"AS-1035": {
    "A": "الصوت ناتج عن انضغاط مجرى هوائي لا <bdi>bronchospasm</bdi>، فـ<bdi>bronchodilator</bdi> لا يفيد؛ يصلح لـ<bdi>asthma</bdi> بصوت <bdi>polyphonic</bdi>.",
    "B": "لا يوجد التهاب يحتاج علاج؛ <bdi>steroids</bdi> تصلح لـ<bdi>croup</bdi> أو نوبة <bdi>asthma</bdi> حادة.",
    "D": "<bdi>tracheostomy</bdi> فقط بحالات <bdi>severe malacia</bdi> مع <bdi>apnea</bdi> متكرر أو فشل بالنمو، وما ذُكر هنا شي من هذا.",
},
"AS-1036": {
    "B": "<bdi>levothyroxine</bdi> يعوض هرمون الدرقية فيزيد <bdi>thyrotoxicosis</bdi>؛ يصلح لـ<bdi>hypothyroidism</bdi> بـ<bdi>TSH</bdi> مرتفع.",
    "C": "<bdi>surgery</bdi> خيار نهائي مو خطوة أولى؛ يصلح عند فشل الدواء أو <bdi>goiter</bdi> كبير ضاغط بعد تثبيت <bdi>euthyroid</bdi>.",
    "D": "<bdi>radioactive iodine</bdi> يُتجنب بالأطفال الصغار وليس خط أول؛ يصلح للانتكاس أو فشل الدواء عند الأكبر سنًا.",
},
"AS-1046": {
    "A": "<bdi>inotropic support</bdi> إجراء <bdi>resuscitative</bdi> لتمديد الحياة، يتعارض مع هدف الراحة بـ<bdi>DNR</bdi>.",
    "B": "<bdi>mechanical ventilation</bdi> دعم <bdi>invasive</bdi> يتعارض مع خطة <bdi>DNR</bdi> و<bdi>comfort care</bdi>.",
    "D": "\"nothing to do\" خطأ؛ <bdi>DNR</bdi> لا تعني إيقاف العلاج، بل تستمر <bdi>palliative care</bdi> ودعم الأسرة.",
},
"AS-1050": {
    "A": "<bdi>barium study</bdi> يحتاج <bdi>radiation</bdi> وهو خط ثاني يصلح لو <bdi>ultrasound</bdi> غير واضح أو غير متوفر.",
},
"AS-1053": {
    "A": "<bdi>MRI</bdi> بدون <bdi>radiation</bdi> بس أبطأ وأقل توفرًا وقد يحتاج تخدير بالأطفال؛ خط ثاني لو <bdi>ultrasound</bdi> غير واضح.",
    "B": "<bdi>abdominal X-ray</bdi> حساسيته ضعيفة لـ<bdi>appendicitis</bdi> ويُستخدم بالشك بانسداد أو <bdi>perforation</bdi>.",
    "D": "<bdi>laparotomy</bdi> علاج لا <bdi>diagnostic test</bdi>؛ يأتي بعد تأكيد التشخيص أو مباشرة بحالة <bdi>peritonitis</bdi> غير مستقرة.",
},
"AS-1067": {
    "B": "<bdi>high-flow oxygen</bdi> يناسب طفل <bdi>alert</bdi> بـ<bdi>hypoxia</bdi> و<bdi>distress</bdi> متوسط، لا يحمي <bdi>airway</bdi> ولا يناسب طفل <bdi>drowsy</bdi>.",
    "C": "<bdi>noninvasive ventilation</bdi> يحتاج مريض <bdi>alert</bdi> ومتعاون يحمي <bdi>airway</bdi>؛ <bdi>drowsiness</bdi> مانع لاستخدامه.",
    "D": "<bdi>oxygen via non-rebreather mask</bdi> خطوة أولى مناسبة لطفل <bdi>alert hypoxic</bdi>، بس غير كافية مع تراجع الوعي وفشل العلاج الأولي.",
},
"AS-1073": {
    "A": "<bdi>blood transfusion</bdi> يحمل مخاطر وغير ضروري بـ<bdi>chronic anemia</bdi> متكيف؛ يُحفظ لعدم الاستقرار أو <bdi>heart failure</bdi> أو نزيف فعّال.",
},
"AS-1074": {
    "A": "العلاقة بالعكس: <bdi>viral URTIs</bdi> تحرّض نوبات <bdi>asthma</bdi>، <bdi>asthma</bdi> نفسه لا يزيد قابلية الإصابة بـ<bdi>URTIs</bdi>.",
    "C": "<bdi>CXR</bdi> طبيعي بين النوبات صحيح بس غير محدد؛ يُستخدم لاستبعاد أسباب أخرى لا لتشخيص <bdi>asthma</bdi>.",
},
"AS-1075": {
    "B": "تمثيل الدهون طبيعي بـ<bdi>PKU</bdi>؛ تقييد الدهون يخص أمراض أخرى مثل عيوب أكسدة <bdi>fatty acids</bdi> الطويلة.",
    "C": "هذا يخلط أمراض متعددة؛ <bdi>lactose</bdi> يُزال بـ<bdi>galactosemia</bdi> و<bdi>fructose</bdi> بـ<bdi>hereditary fructose intolerance</bdi>، ولا علاقة لهما بـ<bdi>PKU</bdi>.",
},
"AS-1076": {
    "A": "الدهون لا ترتبط بـ<bdi>ammonia</bdi> أو <bdi>encephalopathy</bdi>؛ بالأطفال مع <bdi>cholestasis</bdi> حتى تُعطى دهون متوسطة السلسلة لتحسين الامتصاص.",
    "C": "الكاربوهيدرات المصدر الأساسي للطاقة بـ<bdi>cirrhosis</bdi>؛ تقييدها يسبب هدم عضلي و<bdi>hypoglycemia</bdi> قد تزيد <bdi>encephalopathy</bdi>.",
},
"AS-1142": {
    "B": "الانتظار شهر يضيع وقت نمو دماغي لا يُستعاد؛ إعادة الفحص قبل العلاج تناسب <bdi>TSH</bdi> مرتفع بشكل طفيف أو <bdi>borderline</bdi> فقط.",
    "C": "<bdi>thyroid ultrasound</bdi> أو <bdi>scintigraphy</bdi> ممكن تحدد السبب بس اختياري وما يجوز يأخر البدء بـ<bdi>levothyroxine</bdi>.",
},
"AS-1143": {
    "A": "هذا نمط <bdi>hypophosphatasia</bdi> (خلل بـ<bdi>ALP</bdi> نفسه)، عكس صورة <bdi>nutritional rickets</bdi>.",
    "C": "نقص <bdi>vitamin D</bdi> لا يرفع <bdi>calcium</bdi> و<bdi>phosphate</bdi>؛ هذا التوليف لا يطابق أي نوع <bdi>rickets</bdi> معروف.",
    "D": "<bdi>ALP</bdi> طبيعي يستبعد <bdi>rickets</bdi> النشط، و<bdi>phosphate</bdi> يكون منخفض بـ<bdi>calcipenic rickets</bdi> بسبب فقدانه الكلوي بتأثير <bdi>PTH</bdi>.",
},
"AS-1145": {
    "A": "<bdi>bronchiolitis</bdi> مرض فيروسي يُشخص <bdi>clinically</bdi>؛ <bdi>CXR</bdi> و<bdi>antibiotics</bdi> الروتينية غير مطلوبة إلا بشك عدوى بكتيرية أو تدهور غير نموذجي.",
    "B": "<bdi>high-flow oxygen</bdi> خطوة تصعيد لو فشل <bdi>low-flow</bdi> بتصحيح <bdi>hypoxia</bdi> أو العمل التنفسي ازداد، ليست الخطوة الأولى برضيع <bdi>alert</bdi>.",
},
"AS-1145B": {
    "A": "<bdi>pneumonia</bdi> تحتاج عوامل خطورة لعدوى (<bdi>maternal fever</bdi>، <bdi>prolonged rupture of membranes</bdi>) و<bdi>consolidation</bdi> بالـ<bdi>X-ray</bdi>، وهذا المولود بلا حمى وبلا عوامل خطورة.",
    "B": "<bdi>meconium aspiration</bdi> تحتاج <bdi>meconium-stained liquor</bdi> بمولود بعد الموعد غالبًا، مع <bdi>patchy infiltrates</bdi> و<bdi>hyperinflation</bdi>، وهذا غير موصوف هنا.",
    "C": "<bdi>RDS</bdi> مرض مواليد <bdi>preterm</bdi> بنقص <bdi>surfactant</bdi> مع نمط <bdi>ground-glass</bdi> منتشر، وهذا مولود <bdi>term</bdi> بـ<bdi>fissural fluid</bdi>.",
},
"AS-1148": {
    "B": "<bdi>high-fiber diet</bdi> يضيف حجمًا بلا سعرات ولا يصحح سوء امتصاص الدهن.",
    "C": "أطفال <bdi>CF</bdi> يحتاجون حمية عالية السعرات والدهون؛ تقييد الدهون لا يناسب <bdi>CF</bdi> أبدًا.",
    "D": "الفيتامينات الذائبة بالدهن جزء من رعاية <bdi>CF</bdi>، بس تُعطى بجانب <bdi>enzymes</bdi> ولا تصحح <bdi>steatorrhea</bdi> أو ضعف الوزن وحدها.",
},
"AS-1149": {
    "A": "<bdi>muscle biopsy</bdi> يصلح لـ<bdi>myopathies</bdi> و<bdi>dystrophies</bdi> بضعف ثابت، والعضلة نفسها طبيعية بـ<bdi>myasthenia</bdi>.",
    "B": "<bdi>routine nerve conduction</bdi> طبيعي بـ<bdi>myasthenia</bdi>؛ يؤكد <bdi>neuropathies</bdi> مثل <bdi>GBS</bdi>.",
    "C": "<bdi>CK</bdi> طبيعي بـ<bdi>myasthenia</bdi>؛ يرتفع بـ<bdi>muscular dystrophy</bdi> و<bdi>myositis</bdi> الالتهابي.",
},
"AS-1159": {
    "A": "<bdi>hydroxychloroquine</bdi> علاج أساسي مستمر بكل مرضى <bdi>SLE</bdi> بس ليس العلاج العاجل لحالة <bdi>life-threatening</bdi> مثل <bdi>seizures</bdi>.",
    "B": "<bdi>cyclophosphamide</bdi> يُضاف لعلاج <bdi>CNS lupus</bdi> الشديد بس بعد أو مع <bdi>steroids</bdi>، لا بديل عنها بالخطوة الأولى.",
    "C": "<bdi>mycophenolate mofetil</bdi> يستخدم أساسًا لـ<bdi>lupus nephritis</bdi>، مو العرض العصبي بهذا السؤال.",
},
"AS-1167": {
    "A": "<bdi>Shigella</bdi> يرتبط بإسهال دموي مخاطي مع <bdi>seizure</bdi>، مو الوصف الأخضر \"foul\" بهذا السؤال.",
    "C": "<bdi>Rotavirus</bdi> يسبب إسهال مائي غزير مع قيء بالرضع، مو الوصف الأخضر \"foul\" بهذا السؤال.",
    "D": "<bdi>Adenovirus</bdi> سبب أقل شيوعًا للإسهال، ووصفه غير مطابق للصورة \"green, foul\" بهذا السؤال.",
},
"AS-1170": {
    "A": "خيار ناقص: يعطي فقط جرعات الولادة المفقودة بدون أول جرعات السلسلة الأساسية ولا اللقاح المستحق بعمر 9 أشهر.",
    "B": "خيار ناقص السلسلة الأساسية (<bdi>DTaP</bdi>، <bdi>OPV</bdi>) رغم إنه يذكر <bdi>PCV</bdi> و<bdi>Measles</bdi> و<bdi>Hep B</bdi>.",
    "C": "خيار يهمل جرعات الولادة المفقودة (<bdi>BCG</bdi>، <bdi>Hep B</bdi>) ويضيف <bdi>MCV4</bdi> اللي ليس مستحق بهذا العمر.",
},
"AS-1174": {
    "A": "<bdi>Kawasaki disease</bdi> حمى 5 أيام أو أكثر مع <bdi>conjunctivitis</bdi> وتشققات شفايف وتغيرات بالأطراف وطفح <bdi>polymorphous</bdi>، لا تسبب <bdi>arthritis</bdi> 6 أسابيع أو طفح <bdi>salmon</bdi>.",
    "B": "<bdi>acute leukemia</bdi> يتميز بألم عظمي ليلي مع <bdi>cytopenias</bdi>؛ و<bdi>acute rheumatic fever</bdi> يعطي <bdi>migratory</bdi> بمفاصل كبيرة بعد عدوى <bdi>strep</bdi>؛ كلاهما يُستبعد من هذه الصورة.",
    "C": "<bdi>SLE</bdi> بالأطفال يعطي طفح <bdi>malar</bdi> وتقرحات فموية و<bdi>cytopenias</bdi> وإصابة كلوية، لا طفح <bdi>salmon</bdi> مع نوبات الحمى.",
},
"AS-1175": {
    "A": "<bdi>celiac disease</bdi> يعطي إسهال غير دموي بسوء امتصاص مع انتفاخ، بلا حمى أو ارتفاع <bdi>CRP</bdi> أو دم بالبراز.",
    "B": "<bdi>Crohn's disease</bdi> غالبًا إسهال غير دموي مع ألم بالربع السفلي الأيمن وتقرحات فموية ومرض حول الشرج؛ وجود الدم مع ألم بالتبرز هنا يفضل <bdi>UC</bdi>.",
    "D": "<bdi>chronic dysentery</bdi> يحتاج تاريخ تعرض أو سفر وفحص براز موجب، ولا يفسر ألم المفاصل ضمن هذه الصورة الالتهابية.",
},
"AS-1178": {
    "A": "<bdi>IV calcium gluconate</bdi> لحالات <bdi>hypocalcemia</bdi> العرضي الحاد (<bdi>tetany</bdi>، <bdi>seizures</bdi>)، وهذا غير موصوف هنا؛ يصحح المستوى مؤقتًا بدون علاج السبب.",
},
}

HIGHLIGHT_TERMS = {
"AS-1021": ["meconium aspiration syndrome (MAS)"],
"AS-1022": ["preterm", "gestational diabetes", "grunting and respiratory distress"],
"AS-1024": ["bronchial asthma under control", "adulthood"],
"AS-1026": ["Sodium 127", "Potassium 6.8", "Glucose 2.5"],
"AS-1028": ["never received any vaccinations", "contaminated metal rod", "muscle spasms and convulsions"],
"AS-1030": ["URTI 3 days ago", "gallop rythum"],
"AS-1034": ["asthma", "metered-dose inhaler with a spacer", "educational advice"],
"AS-1035": ["worsens during feeding and crying", "monophasic bilateral expiratory wheezing"],
"AS-1036": ["elevated free T4", "suppressed TSH"],
"AS-1046": ["end-stage cancer", "do-not-resuscitate (DNR)"],
"AS-1050": ["6 weeks", "forceful vomiting after each meal"],
"AS-1053": ["11 y o boy", "lower right quadrant", "high WBC"],
"AS-1067": ["O2% 85", "drowsy"],
"AS-1073": ["3 yo on diet of biscuits and milk", "hb 67 g"],
"AS-1074": ["Indicates Diagnosis Of Asthma"],
"AS-1075": ["phenylketonuria (PKU)"],
"AS-1076": ["pediatric with cirrhosis", "hepatic encephalopathy"],
"AS-1142": ["Neonate", "TSH 60", "no symptoms normal appearance"],
"AS-1143": ["2-year-old", "refuses to walk", "bowing of both legs"],
"AS-1145": ["nasal congestion cough and poor feeding", "alert", "Oxygen saturation is 89%", "bilateral crackles and wheezing"],
"AS-1145B": ["cesarean section", "fluid in the horizontal fissure"],
"AS-1148": ["Cystic fibrosis", "weight 3rd centile", "Foul smelling stool"],
"AS-1149": ["ptosis", "at evening only, he is normal in the morning", "exuasting ptosis"],
"AS-1159": ["seizures", "Anti ds DNA high"],
"AS-1167": ["Foul smelling watery diarrhea, green in color"],
"AS-1170": ["9 month never been vaccinated"],
"AS-1174": ["fever 37.9 for 6 weeks", "salmon color rash"],
"AS-1175": ["bloody", "lost weight"],
"AS-1178": ["enamel hypoplasia", "low calcium, low phosphate, high alkaline phosphatase"],
}
